/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 1b35d61b-eac8-48c2-96e2-2a4636791a7c

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>

Aristotle's budget for this request has been reached.
If there is partial progress, it will appear in this file.
If you would like to continue working off of this partial progress,
please submit the same prompt, and add this .lean file in "Optional: Attach a Lean file as context" field.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

/-
For 0 < ρ < 1, any p ∈ ℕ, and any α > 0, lim_{n→∞} (n+1)^p · ρ^n · (n+1)^α = 0.
-/
theorem exponential_beats_polynomial (ρ : ℝ) (hρ_pos : 0 < ρ) (hρ_lt_one : ρ < 1) (p : ℕ) (α : ℝ) (hα : 0 < α) :
  Filter.Tendsto (fun n : ℕ => ((n + 1 : ℝ) ^ p) * (ρ ^ n) * ((n + 1 : ℝ) ^ α)) Filter.atTop (nhds 0) := by
    -- The function $f(n) = (n+1)^{p+α} \cdot \rho^n$ converges to 0 as $n \to \infty$ because the exponential decay $\rho^n$ dominates any polynomial growth.
    have h_lim : Filter.Tendsto (fun n : ℕ => (n + 1 : ℝ) ^ (p + α) * ρ ^ n) Filter.atTop (nhds 0) := by
      -- We can use the fact that $(n+1)^{p+\alpha}$ grows polynomially, while $\rho^n$ decays exponentially.
      have h_poly_exp : Filter.Tendsto (fun n : ℕ => ((n : ℝ) ^ (p + α)) * ρ ^ n) Filter.atTop (nhds 0) := by
        -- We can use the fact that $(n+1)^{p+\alpha}$ grows polynomially, while $\rho^n$ decays exponentially. Specifically, we can use the fact that $\lim_{n \to \infty} n^{p+\alpha} e^{-bn} = 0$ for any $b > 0$.
        have h_poly_exp : ∀ b > 0, Filter.Tendsto (fun n : ℕ => ((n : ℝ) ^ (p + α)) * Real.exp (-b * n)) Filter.atTop (nhds 0) := by
          intro b hb_pos
          have h_poly_exp : Filter.Tendsto (fun n : ℝ => (n : ℝ) ^ (p + α) * Real.exp (-b * n)) Filter.atTop (nhds 0) := by
            exact?
          exact h_poly_exp.comp tendsto_natCast_atTop_atTop |> fun h => h.congr (by intros; simp) ;
        convert h_poly_exp ( -Real.log ρ ) ( neg_pos.mpr ( Real.log_neg hρ_pos hρ_lt_one ) ) using 2 ; norm_num [ Real.exp_neg, Real.exp_nat_mul, Real.exp_log hρ_pos ];
        exact Or.inl ( by rw [ Real.exp_mul, Real.exp_log hρ_pos ] ; norm_cast );
      -- We can convert this limit into our desired form by noting that $(n+1)^{p+\alpha} = n^{p+\alpha} \cdot (1 + 1/n)^{p+\alpha}$.
      have h_convert : Filter.Tendsto (fun n : ℕ => ((n : ℝ) ^ (p + α)) * (1 + 1 / (n : ℝ)) ^ (p + α) * ρ ^ n) Filter.atTop (nhds 0) := by
        simpa [ mul_right_comm ] using h_poly_exp.mul ( Filter.Tendsto.rpow ( tendsto_const_nhds.add <| tendsto_inverse_atTop_nhds_zero_nat ) tendsto_const_nhds <| Or.inl <| by positivity );
      refine h_convert.congr' ( by filter_upwards [ Filter.eventually_gt_atTop 0 ] with n hn; rw [ ← Real.mul_rpow ( by positivity ) ( by positivity ), mul_add, mul_one_div_cancel ( by positivity ), mul_one ] );
    convert h_lim using 2 ; rw [ Real.rpow_add ( by positivity ) ] ; norm_cast ; ring

/-
For x ∈ ℝᵈ with ‖x‖ ≠ 0, let S = xxᵀ and γ = 1/‖x‖². Then A = I - γS satisfies A² = A and Aᵀ = A (i.e., A is an orthogonal projection).
-/
theorem gradient_step_is_projection {d : ℕ} (x : Fin d → ℝ) (hx : x ≠ 0) :
  let γ := (x ⬝ᵥ x)⁻¹
  let S := Matrix.vecMulVec x x
  let A := (1 : Matrix (Fin d) (Fin d) ℝ) - γ • S
  A ^ 2 = A ∧ A.transpose = A := by
    refine' ⟨ _, _ ⟩ <;> ext i j <;> norm_num [ Matrix.vecMulVec, Matrix.mul_apply, pow_two ] <;> ring;
    · simp +decide [ Matrix.one_apply, Finset.sum_add_distrib, Finset.mul_sum _ _ _, Finset.sum_mul, sq, mul_assoc, mul_comm, mul_left_comm, dotProduct ] ; ring;
      norm_num [ ← Finset.mul_sum _ _ _, ← Finset.sum_mul ] ; ring; by_cases h : ∑ i : Fin d, x i ^ 2 = 0 <;> simp_all +decide [ sq, mul_assoc ] ; ring;
    · by_cases hij : i = j <;> simp +decide [ hij ] ; ring;
      · grind;
      · exact if_neg ( Ne.symm hij )

/-
For 0 < ρ < 1 and α > 0, there exists N ∈ ℕ such that for all n ≥ N, (n+1)² · ρ^{2n} < 1/(n+1)^α.
-/
theorem separation_theorem (ρ : ℝ) (hρ_pos : 0 < ρ) (hρ_lt_one : ρ < 1) (α : ℝ) (hα : 0 < α) :
  ∃ N : ℕ, ∀ n ≥ N, ((n + 1 : ℝ) ^ 2) * (ρ ^ (2 * n)) < 1 / ((n + 1 : ℝ) ^ α) := by
    -- Let's simplify the expression by defining ρ' = ρ^2.
    set ρ' : ℝ := ρ^2
    have hρ'_lt_one : ρ' < 1 := by
      exact pow_lt_one₀ hρ_pos.le hρ_lt_one ( by norm_num )
    have hρ'_pos : 0 < ρ' := by
      positivity
    have h_eq : ∀ n : ℕ, ((n + 1 : ℝ) ^ 2) * ρ ^ (2 * n) = ((n + 1 : ℝ) ^ 2) * (ρ') ^ n := by
      exact fun n => by rw [ pow_mul ] ;
    -- We'll use the fact that $(n+1)^{2+\alpha} \rho^{2n}$ tends to $0$ as $n$ tends to infinity.
    have h_lim : Filter.Tendsto (fun n : ℕ => ((n + 1 : ℝ) ^ 2) * ρ' ^ n * ((n + 1 : ℝ) ^ α)) Filter.atTop (nhds 0) := by
      exact?;
    have h_lim : ∃ N : ℕ, ∀ n ≥ N, ((n + 1 : ℝ) ^ 2) * ρ' ^ n * ((n + 1 : ℝ) ^ α) < 1 := by
      simpa using h_lim.eventually ( gt_mem_nhds zero_lt_one );
    exact ⟨ h_lim.choose, fun n hn => by rw [ lt_div_iff₀ ( by positivity ) ] ; simpa only [ h_eq ] using h_lim.choose_spec n hn ⟩

#check (Matrix.instL2OpNormedRing : NormedRing (Matrix (Fin 3) (Fin 3) ℝ))
#check (inferInstance : Norm (EuclideanSpace ℝ (Fin 3)))
#check (inferInstance : InnerProductSpace ℝ (EuclideanSpace ℝ (Fin 3)))

/-
For positive definite S_total, matrix M, and vector θ₀, (M^n θ₀)ᵀ S_total (M^n θ₀) ≤ ‖M^n‖² · ‖S_total‖ · ‖θ₀‖².
-/
open scoped Matrix.Norms.L2Operator

theorem spectral_radius_controls_forgetting {d : ℕ} (M : Matrix (Fin d) (Fin d) ℝ) (S_total : Matrix (Fin d) (Fin d) ℝ) (hS : S_total.PosDef) (θ₀ : Fin d → ℝ) (n : ℕ) :
  let to_euc := (EuclideanSpace.equiv (Fin d) ℝ).symm
  let v := (M ^ n).mulVec θ₀
  inner ℝ (to_euc v) (to_euc (S_total.mulVec v)) ≤ ‖M ^ n‖ ^ 2 * ‖S_total‖ * ‖to_euc θ₀‖ ^ 2 := by
    intro to_euc v
    have h_inner : inner ℝ (to_euc v) (to_euc (S_total.mulVec v)) ≤ ‖S_total‖ * ‖to_euc v‖^2 := by
      -- By the properties of the operator norm and the Cauchy-Schwarz inequality, we have:
      have h_norm : ‖(to_euc (S_total.mulVec v))‖ ≤ ‖S_total‖ * ‖(to_euc v)‖ := by
        exact?
      have h_cauchy_schwarz : inner ℝ (to_euc v) (to_euc (S_total.mulVec v)) ≤ ‖(to_euc v)‖ * ‖(to_euc (S_total.mulVec v))‖ := by
        exact real_inner_le_norm _ _
      exact le_trans h_cauchy_schwarz (by
      convert mul_le_mul_of_nonneg_left h_norm ( norm_nonneg ( to_euc v ) ) using 1 ; ring!;)
    have h_norm : ‖to_euc v‖ ≤ ‖M^n‖ * ‖to_euc θ₀‖ := by
      exact?
    have h_subst : ‖S_total‖ * ‖to_euc v‖^2 ≤ ‖S_total‖ * (‖M^n‖ * ‖to_euc θ₀‖)^2 := by
      gcongr
    norm_cast at *; (
    linarith);

/-
For a 2×2 real matrix M with (M - rI)² = 0 and 0 < r < 1, there exists C > 0 such that ‖M^n‖ ≤ C · (n+1) · r^n for all n.
-/
open scoped Matrix.Norms.L2Operator

theorem jordan_block_2x2_iterate_bound (M : Matrix (Fin 2) (Fin 2) ℝ) (r : ℝ) (hr_pos : 0 < r) (hr_lt_one : r < 1) (h_nilpotent : (M - r • (1 : Matrix (Fin 2) (Fin 2) ℝ)) ^ 2 = 0) :
  ∃ C > 0, ∀ n : ℕ, ‖M ^ n‖ ≤ C * (n + 1) * r ^ n := by
    -- Since $(M - rI)^2 = 0$, we can write $M = rI + N$ where $N^2 = 0$.
    obtain ⟨N, hN⟩ : ∃ N : Matrix (Fin 2) (Fin 2) ℝ, M = r • 1 + N ∧ N ^ 2 = 0 := by
      exact ⟨ M - r • 1, by norm_num, h_nilpotent ⟩;
    -- By the properties of the norm, we have ‖M^n‖ ≤ ‖r^n I‖ + ‖n r^{n-1} N‖.
    have h_norm : ∀ n : ℕ, ‖M ^ n‖ ≤ r ^ n + (n : ℝ) * r ^ (n - 1) * ‖N‖ := by
      -- By the properties of the norm, we have ‖M^n‖ ≤ ‖r^n I‖ + ‖n r^{n-1} N‖ for all n.
      intros n
      have h_expansion : M ^ n = r ^ n • 1 + (n : ℝ) • r ^ (n - 1) • N := by
        induction n <;> simp_all +decide [ pow_succ, add_mul, mul_add ];
        cases ‹ℕ› <;> simp_all +decide [ pow_succ, mul_assoc, mul_comm, mul_left_comm, add_smul ] ; ext i j ; norm_num ; ring;
      simp_all [h_expansion];
      refine' le_trans ( norm_add_le _ _ ) _ ; norm_num [ norm_smul, abs_of_pos hr_pos ] ; ring_nf ; aesop;
    use 1 + ‖N‖ / r, by positivity, fun n => le_trans ( h_norm n ) ?_ ; rcases n with ( _ | n ) <;> norm_num [ pow_succ' ] at * ; ring_nf at * ; aesop;
    field_simp [mul_comm, mul_assoc, mul_left_comm] at *; (
    nlinarith [ norm_nonneg N ]);

/-
Given a 2×2 cycle operator M with (M - r*I)² = 0, 0 < r < 1, and positive definite S_total, for any θ₀ there exists C > 0 such that (M^n θ₀)ᵀ S_total (M^n θ₀) ≤ C · (n+1)² · r^{2n} · ‖θ₀‖² for all n ∈ ℕ.
-/
open scoped Matrix.Norms.L2Operator

theorem exponential_forgetting_decay (M : Matrix (Fin 2) (Fin 2) ℝ) (r : ℝ) (hr_pos : 0 < r) (hr_lt_one : r < 1) (h_nilpotent : (M - r • (1 : Matrix (Fin 2) (Fin 2) ℝ)) ^ 2 = 0) (S_total : Matrix (Fin 2) (Fin 2) ℝ) (hS : S_total.PosDef) (θ₀ : Fin 2 → ℝ) :
  ∃ C > 0, ∀ n : ℕ,
    let to_euc := (EuclideanSpace.equiv (Fin 2) ℝ).symm
    let v := (M ^ n).mulVec θ₀
    inner ℝ (to_euc v) (to_euc (S_total.mulVec v)) ≤ C * ((n + 1 : ℝ) ^ 2) * (r ^ (2 * n)) * ‖to_euc θ₀‖ ^ 2 := by
      obtain ⟨ C₁, hC₁_pos, hC₁ ⟩ := jordan_block_2x2_iterate_bound M r hr_pos hr_lt_one h_nilpotent;
      -- From D1.2: (M^n θ₀)ᵀ S_total (M^n θ₀) ≤ ‖M^n‖² · ‖S_total‖ · ‖θ₀‖².
      have h_bound : ∀ n : ℕ, let to_euc : (Fin 2 → ℝ) ≃L[ℝ] EuclideanSpace ℝ (Fin 2) := (EuclideanSpace.equiv (Fin 2) ℝ).symm;
        let v : Fin 2 → ℝ := (M ^ n).mulVec θ₀;
        (inner ℝ (to_euc v) (to_euc (S_total.mulVec v))) ≤ ‖M ^ n‖ ^ 2 * ‖S_total‖ * ‖to_euc θ₀‖ ^ 2 := by
          exact?;
      refine' ⟨ C₁ ^ 2 * ‖S_total‖, _, fun n => le_trans ( h_bound n ) _ ⟩ <;> norm_num [ pow_mul' ];
      · refine' mul_pos ( sq_pos_of_pos hC₁_pos ) ( norm_pos_iff.mpr _ );
        exact fun h => by simpa [ h ] using hS.2 ( Pi.single 0 1 ) ;
      · exact mul_le_mul_of_nonneg_right ( by convert mul_le_mul_of_nonneg_right ( pow_le_pow_left₀ ( by positivity ) ( hC₁ n ) 2 ) ( norm_nonneg S_total ) using 1 ; ring ) ( sq_nonneg _ )

/-
For K=2, with fixed stepsizes γ₁, γ₂ > 0, ‖(I - γ₂S₂)(I - γ₁S₁) - (I - γ₂S₂')(I - γ₁S₁')‖ ≤ γ₁‖I - γ₂S₂‖ · ‖S₁ - S₁'‖ + γ₂‖I - γ₁S₁'‖ · ‖S₂ - S₂'‖ + γ₁γ₂‖S₁ - S₁'‖ · ‖S₂ - S₂'‖.
-/
open scoped Matrix.Norms.L2Operator

theorem cycle_operator_lipschitz_continuity {d : ℕ} (S1 S2 S1' S2' : Matrix (Fin d) (Fin d) ℝ) (γ1 γ2 : ℝ) (hγ1 : 0 < γ1) (hγ2 : 0 < γ2) :
  let I := (1 : Matrix (Fin d) (Fin d) ℝ)
  ‖(I - γ2 • S2) * (I - γ1 • S1) - (I - γ2 • S2') * (I - γ1 • S1')‖ ≤
    γ1 * ‖I - γ2 • S2‖ * ‖S1 - S1'‖ + γ2 * ‖I - γ1 • S1'‖ * ‖S2 - S2'‖ + γ1 * γ2 * ‖S1 - S1'‖ * ‖S2 - S2'‖ := by
      -- Apply the triangle inequality to the difference and bound each term by the product of the norms.
      have h_triangle : ‖(1 - γ2 • S2) * (1 - γ1 • S1) - (1 - γ2 • S2') * (1 - γ1 • S1')‖ ≤ ‖(1 - γ2 • S2) * (1 - γ1 • S1) - (1 - γ2 • S2) * (1 - γ1 • S1')‖ + ‖(1 - γ2 • S2) * (1 - γ1 • S1') - (1 - γ2 • S2') * (1 - γ1 • S1')‖ := by
        exact?;
      -- Apply the norm property to each term in the triangle inequality.
      have h_norm1 : ‖(1 - γ2 • S2) * (1 - γ1 • S1) - (1 - γ2 • S2) * (1 - γ1 • S1')‖ ≤ γ1 * ‖1 - γ2 • S2‖ * ‖S1 - S1'‖ := by
        have h_triangle_part1 : ‖(1 - γ2 • S2) * (1 - γ1 • S1) - (1 - γ2 • S2) * (1 - γ1 • S1')‖ ≤ ‖1 - γ2 • S2‖ * ‖(1 - γ1 • S1) - (1 - γ1 • S1')‖ := by
          convert norm_mul_le ( 1 - γ2 • S2 ) ( ( 1 - γ1 • S1 ) - ( 1 - γ1 • S1' ) ) using 1 ; simp +decide [ mul_sub ];
        convert h_triangle_part1 using 1 ; norm_num [ mul_assoc, mul_comm, mul_left_comm, norm_smul, abs_of_pos hγ1 ];
        rw [ ← smul_sub, norm_smul, Real.norm_of_nonneg hγ1.le ] ; ring;
        rw [ norm_sub_rev S1' S1 ] ; ring
      have h_norm2 : ‖(1 - γ2 • S2) * (1 - γ1 • S1') - (1 - γ2 • S2') * (1 - γ1 • S1')‖ ≤ γ2 * ‖S2 - S2'‖ * ‖1 - γ1 • S1'‖ := by
        -- Factor out common terms and apply the norm property.
        have h_factor : (1 - γ2 • S2) * (1 - γ1 • S1') - (1 - γ2 • S2') * (1 - γ1 • S1') = γ2 • (S2' - S2) * (1 - γ1 • S1') := by
          simp +decide [ sub_mul, mul_sub, smul_sub ] ; abel_nf;
        -- Apply the norm property to the product.
        have h_norm_prod : ‖γ2 • (S2' - S2) * (1 - γ1 • S1')‖ ≤ ‖γ2 • (S2' - S2)‖ * ‖1 - γ1 • S1'‖ := by
          exact?;
        simp_all +decide [ norm_smul, abs_of_pos ];
        simpa only [ norm_sub_rev ] using h_norm_prod;
      exact le_add_of_le_of_nonneg ( h_triangle.trans ( add_le_add h_norm1 h_norm2 ) |> le_trans <| by ring_nf; norm_num ) <| by positivity;

/-
For a d×d complex matrix N with N^k = 0 and non-zero scalar c, there exists C > 0 such that ‖(cI + N)^n‖ ≤ C · (n+1)^{k-1} · |c|^n.
-/
open scoped Matrix.Norms.L2Operator

theorem norm_pow_scalar_add_nilpotent_bound {d : ℕ} (N : Matrix (Fin d) (Fin d) ℂ) (c : ℂ) (k : ℕ) (hk : N ^ k = 0) (hc : c ≠ 0) :
  ∃ C > 0, ∀ n : ℕ, ‖(c • (1 : Matrix (Fin d) (Fin d) ℂ) + N) ^ n‖ ≤ C * (n + 1) ^ (k - 1) * ‖c‖ ^ n := by
    -- Let $M = cI + N$. Since $I$ and $N$ commute, we can use the binomial theorem: $M^n = \sum_{j=0}^n \binom{n}{j} c^{n-j} N^j$.
    set M : Matrix (Fin d) (Fin d) ℂ := c • (1 : Matrix (Fin d) (Fin d) ℂ) + N
    have hM : ∀ n : ℕ, M ^ n = ∑ j ∈ Finset.range (min (n + 1) k), Nat.choose n j • c ^ (n - j) • N ^ j := by
      -- By the binomial theorem for matrices, we have $(cI + N)^n = \sum_{j=0}^n \binom{n}{j} c^{n-j} N^j$.
      have h_binom : ∀ n : ℕ, M ^ n = ∑ j ∈ Finset.range (n + 1), Nat.choose n j • c ^ (n - j) • N ^ j := by
        intro n
        have h_comm : Commute (c • (1 : Matrix (Fin d) (Fin d) ℂ)) N := by
          simp +decide [ Commute, mul_comm ];
          simp +decide [ SemiconjBy ]
        rw [ h_comm.add_pow ];
        rw [ ← Finset.sum_flip ];
        refine' Finset.sum_congr rfl fun x hx => _ ; rw [ Nat.choose_symm ( Finset.mem_range_succ_iff.mp hx ), tsub_tsub_cancel_of_le ( Finset.mem_range_succ_iff.mp hx ) ] ; simp +decide [ smul_pow, mul_assoc, mul_comm, mul_left_comm, smul_smul ] ; ring;
        exact congr_arg _ ( by exact? );
      intro n; rw [ min_def ] ; split_ifs <;> simp_all +decide [ Finset.sum_range_succ ] ;
      rw [ ← Finset.sum_range_add_sum_Ico _ ( by linarith : k ≤ n ) ];
      simp_all +decide [ Finset.sum_Ico_eq_sum_range, pow_add ];
      exact pow_eq_zero_of_le ( Nat.le_of_lt_succ ‹_› ) hk;
    -- Taking norms:
    -- $\|M^n\| \le \sum_{j=0}^{\min(n, k-1)} \binom{n}{j} |c|^{n-j} \|N^j\|$.
    have h_norm : ∀ n : ℕ, ‖M ^ n‖ ≤ ∑ j ∈ Finset.range (min (n + 1) k), Nat.choose n j * ‖c‖ ^ (n - j) * ‖N ^ j‖ := by
      intro n
      rw [hM n];
      refine' le_trans ( norm_sum_le _ _ ) _;
      norm_num [ norm_smul, mul_assoc ];
      -- Since ‖(Nat.choose n x : Matrix (Fin d) (Fin d) ℂ) * N ^ x‖ = Nat.choose n x * ‖N ^ x‖, we can simplify the expression.
      have h_norm_scalar : ∀ x : ℕ, ‖(Nat.choose n x : Matrix (Fin d) (Fin d) ℂ) * N ^ x‖ = Nat.choose n x * ‖N ^ x‖ := by
        intro x; erw [ show ( Nat.choose n x : Matrix ( Fin d ) ( Fin d ) ℂ ) = ( Nat.choose n x : ℂ ) • 1 by simp +decide [ Algebra.smul_def ] ] ; simp +decide [ norm_smul ] ;
      exact Finset.sum_le_sum fun _ _ => by rw [ h_norm_scalar ] ; ring_nf; norm_num;
    -- We know $\binom{n}{j} \le \frac{n^j}{j!} \le (n+1)^{k-1}$ for $j < k$.
    have h_binom : ∀ n : ℕ, ∑ j ∈ Finset.range (min (n + 1) k), Nat.choose n j * ‖c‖ ^ (n - j) * ‖N ^ j‖ ≤ (n + 1) ^ (k - 1) * ‖c‖ ^ n * ∑ j ∈ Finset.range (min (n + 1) k), ‖N ^ j‖ / ‖c‖ ^ j := by
      intro n
      have h_binom_le : ∀ j ∈ Finset.range (min (n + 1) k), Nat.choose n j * ‖c‖ ^ (n - j) ≤ (n + 1) ^ (k - 1) * ‖c‖ ^ n / ‖c‖ ^ j := by
        intro j hj
        have h_binom_le : Nat.choose n j ≤ (n + 1) ^ (k - 1) := by
          refine' le_trans _ ( pow_le_pow_right₀ ( by linarith ) ( Nat.le_sub_one_of_lt ( Finset.mem_range.mp hj |> lt_of_lt_of_le <| min_le_right _ _ ) ) );
          exact le_trans ( Nat.choose_le_pow _ _ ) ( by gcongr ; linarith );
        rw [ le_div_iff₀ ( pow_pos ( norm_pos_iff.mpr hc ) _ ) ];
        rw [ mul_assoc, ← pow_add, Nat.sub_add_cancel ( show j ≤ n from by linarith [ Finset.mem_range.mp hj, min_le_left ( n + 1 ) k ] ) ] ; exact mul_le_mul_of_nonneg_right ( mod_cast h_binom_le ) ( by positivity ) ;
      simpa only [ Finset.mul_sum _ _ _, mul_div_assoc ] using Finset.sum_le_sum fun j hj => by convert mul_le_mul_of_nonneg_right ( h_binom_le j hj ) ( norm_nonneg ( N ^ j ) ) using 1 ; ring;
    -- Let $C = \sum_{j=0}^{k-1} \|N^j\| / \|c\|^j$.
    obtain ⟨C, hC⟩ : ∃ C > 0, ∀ n : ℕ, ∑ j ∈ Finset.range (min (n + 1) k), ‖N ^ j‖ / ‖c‖ ^ j ≤ C := by
      use ∑ j ∈ Finset.range k, ‖N ^ j‖ / ‖c‖ ^ j + 1;
      exact ⟨ add_pos_of_nonneg_of_pos ( Finset.sum_nonneg fun _ _ => div_nonneg ( norm_nonneg _ ) ( pow_nonneg ( norm_nonneg _ ) _ ) ) zero_lt_one, fun n => le_add_of_le_of_nonneg ( Finset.sum_le_sum_of_subset_of_nonneg ( Finset.range_mono ( min_le_right _ _ ) ) fun _ _ _ => div_nonneg ( norm_nonneg _ ) ( pow_nonneg ( norm_nonneg _ ) _ ) ) zero_le_one ⟩;
    exact ⟨ C, hC.1, fun n => le_trans ( h_norm n ) ( le_trans ( h_binom n ) ( by nlinarith [ show 0 ≤ ( n + 1 : ℝ ) ^ ( k - 1 ) * ‖c‖ ^ n by positivity, hC.2 n ] ) ) ⟩

/-
Checking Norm instance and Matrix.reindex
-/
open scoped Matrix.Norms.L2Operator
variable (n : ℕ)
#synth Norm (Matrix (Fin n) (Fin n) ℂ)
#check Matrix.reindex

/-
Checking equality of toLin' and toLinAlgEquiv'
-/
open scoped Matrix.Norms.L2Operator
variable {d : ℕ} (M : Matrix (Fin d) (Fin d) ℂ)
#check Matrix.toLinAlgEquiv' M
#check Matrix.toLin' M
example : (Matrix.toLinAlgEquiv' M : (Fin d → ℂ) →ₗ[ℂ] (Fin d → ℂ)) = Matrix.toLin' M := rfl

/-
If M = S + N with S, N commuting, S diagonalizable, N nilpotent, and ρ(S) > 0, then ‖M^n‖ is bounded by C * n^(k-1) * ρ(S)^n.
-/
open scoped Matrix.Norms.L2Operator

theorem bound_of_commuting_semisimple_nilpotent {d : ℕ} (S N : Matrix (Fin d) (Fin d) ℂ) (k : ℕ) (hk : 0 < k)
  (h_comm : Commute S N) (h_nil : N ^ k = 0)
  (h_diag : ∃ P : Matrix (Fin d) (Fin d) ℂ, IsUnit P ∧ (P * S * P⁻¹).IsDiag)
  (h_rho_pos : 0 < (spectralRadius ℂ S).toReal) :
  ∃ C > 0, ∀ n : ℕ, ‖(S + N) ^ n‖ ≤ C * (n + 1) ^ (k - 1) * ((spectralRadius ℂ S).toReal) ^ n := by
    -- Let $P$ be a matrix such that $PSP^{-1}$ is diagonal.
    obtain ⟨P, hP_unit, hP_diag⟩ := h_diag
    set D := P * S * P⁻¹
    have hD_diag : D.IsDiag := by
      exact hP_diag
    have hD_eigenvalues : ∀ i, ‖D i i‖ ≤ (spectralRadius ℂ S).toReal := by
      intro i
      have h_eigenvalue : ∀ (μ : ℂ), μ ∈ spectrum ℂ (P * S * P⁻¹) → ‖μ‖ ≤ (spectralRadius ℂ S).toReal := by
        intro μ hμ
        have h_eigenvalue : μ ∈ spectrum ℂ S := by
          simp_all +decide [ spectrum.mem_iff, Matrix.isUnit_iff_isUnit_det ];
          rw [ show ( algebraMap ℂ ( Matrix ( Fin d ) ( Fin d ) ℂ ) ) μ - P * S * P⁻¹ = P * ( ( algebraMap ℂ ( Matrix ( Fin d ) ( Fin d ) ℂ ) ) μ - S ) * P⁻¹ from ?_, Matrix.det_mul, Matrix.det_mul ] at hμ ; aesop
          generalize_proofs at *; (
          simp +decide [ mul_sub, sub_mul, mul_assoc, hP_unit, isUnit_iff_ne_zero ];
          simp +decide [ Algebra.algebraMap_eq_smul_one, mul_assoc, hP_unit, isUnit_iff_ne_zero ])
        generalize_proofs at *;
        refine' le_trans _ ( ENNReal.toReal_mono _ <| le_ciSup _ μ ) <;> norm_num [ h_eigenvalue ];
        contrapose! h_rho_pos; aesop;
      generalize_proofs at *;
      apply h_eigenvalue
      generalize_proofs at *; (
      rw [ spectrum.mem_iff ];
      simp_all +decide [ Matrix.isUnit_iff_isUnit_det ];
      rw [ ← Matrix.exists_mulVec_eq_zero_iff ];
      refine' ⟨ Pi.single i 1, _, _ ⟩ <;> simp_all +decide [ funext_iff, Matrix.mulVec ];
      · exact ⟨ i, by simp +decide ⟩;
      · intro x; by_cases hx : x = i <;> simp_all +decide [ Algebra.algebraMap_eq_smul_one ] ;
        · exact sub_self _;
        · exact hP_diag hx)
    have hD_pow : ∀ n, ‖D ^ n‖ ≤ (spectralRadius ℂ S).toReal ^ n := by
      intro n
      have hD_pow_diag : D ^ n = Matrix.diagonal (fun i => (D i i) ^ n) := by
        induction n <;> simp_all +decide [ pow_succ, Matrix.mul_assoc ];
        ext i j; by_cases hi : i = j <;> aesop;
      have hD_pow_norm : ‖D ^ n‖ ≤ (spectralRadius ℂ S).toReal ^ n := by
        rw [ hD_pow_diag ];
        refine' csInf_le _ _ <;> norm_num [ hD_eigenvalues ];
        · exact ⟨ 0, fun c hc => hc.1 ⟩;
        · intro x; rw [ EuclideanSpace.norm_eq ] ; simp +decide [ Matrix.toEuclideanLin, Matrix.mulVec ] ; (
          rw [ Real.sqrt_le_iff ] ; norm_num [ EuclideanSpace.norm_eq ] ; ring_nf ; (
          exact ⟨ by positivity, by rw [ Real.sq_sqrt <| Finset.sum_nonneg fun _ _ => sq_nonneg _ ] ; exact le_trans ( Finset.sum_le_sum fun _ _ => mul_le_mul_of_nonneg_right ( pow_le_pow_left₀ ( by positivity ) ( hD_eigenvalues _ ) _ ) <| sq_nonneg _ ) <| by simp +decide [ pow_mul', mul_assoc, mul_comm, mul_left_comm, Finset.mul_sum _ _ _ ] ⟩ ;););
      exact hD_pow_norm
      skip
    have hS_pow : ∀ n, ‖S ^ n‖ ≤ ‖P‖ * ‖P⁻¹‖ * (spectralRadius ℂ S).toReal ^ n := by
      intro n
      have hS_pow_step : ‖S ^ n‖ ≤ ‖P⁻¹‖ * ‖D ^ n‖ * ‖P‖ := by
        have hS_pow_step : S ^ n = P⁻¹ * D ^ n * P := by
          induction n <;> simp_all +decide [ pow_succ, mul_assoc ];
          · cases hP_unit.nonempty_invertible ; aesop;
          · cases hP_unit.nonempty_invertible ; aesop
        generalize_proofs at *; (
        rw [hS_pow_step];
        exact le_trans ( norm_mul_le _ _ ) ( mul_le_mul_of_nonneg_right ( norm_mul_le _ _ ) ( norm_nonneg _ ) ) |> le_trans <| by norm_num [ mul_assoc ] ;)
      generalize_proofs at *; (
      exact hS_pow_step.trans ( by nlinarith [ hD_pow n, show 0 ≤ ‖P‖ * ‖P⁻¹‖ by positivity ] ))
    generalize_proofs at *; (
    -- Expand $(S+N)^n$ using the binomial theorem (valid since $S, N$ commute).
    have h_binom : ∀ n, (S + N) ^ n = ∑ j ∈ Finset.range (k), Nat.choose n j • S ^ (n - j) * N ^ j := by
      intro n
      have h_binom : (S + N) ^ n = ∑ j ∈ Finset.range (n + 1), Nat.choose n j • S ^ (n - j) * N ^ j := by
        have := h_comm.add_pow n
        generalize_proofs at *; (
        rw [ this, ← Finset.sum_flip ];
        refine' Finset.sum_congr rfl fun x hx => _ ; rw [ Nat.choose_symm ( Finset.mem_range_succ_iff.mp hx ), tsub_tsub_cancel_of_le ( Finset.mem_range_succ_iff.mp hx ) ] ; simp +decide [ mul_assoc, mul_comm, mul_left_comm, Algebra.smul_def ] ;
        simp +decide [ ← mul_assoc, ← Nat.cast_comm ])
      generalize_proofs at *; (
      by_cases hn : n < k <;> simp_all +decide [ Finset.sum_range_add_sum_Ico ];
      · rw [ Finset.sum_subset ( Finset.range_mono ( Nat.succ_le_of_lt hn ) ) fun x hx₁ hx₂ => by rw [ Nat.choose_eq_zero_of_lt ] <;> aesop ];
      · rw [ ← Finset.sum_range_add_sum_Ico _ ( by linarith : k ≤ n + 1 ) ] ; simp_all +decide [ pow_add, pow_mul, mul_assoc ] ;
        exact Finset.sum_eq_zero fun x hx => by rw [ pow_eq_zero_of_le ( Finset.mem_Ico.mp hx |>.1 ) h_nil ] ; norm_num;)
    generalize_proofs at *; (
    -- Bound the norm of each term in the sum.
    have h_term_bound : ∀ n j, j < k → ‖Nat.choose n j • S ^ (n - j) * N ^ j‖ ≤ Nat.choose n j * ‖P‖ * ‖P⁻¹‖ * (spectralRadius ℂ S).toReal ^ (n - j) * ‖N ^ j‖ := by
      intros n j hj_lt_k
      have h_term_bound : ‖Nat.choose n j • S ^ (n - j) * N ^ j‖ ≤ Nat.choose n j * ‖S ^ (n - j)‖ * ‖N ^ j‖ := by
        refine' le_trans ( norm_mul_le _ _ ) _;
        gcongr;
        convert norm_smul_le ( n.choose j : ℂ ) ( S ^ ( n - j ) ) using 1 ; norm_num [ Algebra.smul_def ];
        norm_num [ Norm.norm ]
      generalize_proofs at *; (
      exact h_term_bound.trans ( by simpa only [ mul_assoc ] using mul_le_mul_of_nonneg_right ( mul_le_mul_of_nonneg_left ( hS_pow _ ) ( Nat.cast_nonneg _ ) ) ( norm_nonneg _ ) ) ;)
    generalize_proofs at *; (
    -- Using the bound on the binomial coefficients, we get:
    have h_binom_bound : ∀ n, ∑ j ∈ Finset.range k, Nat.choose n j * ‖P‖ * ‖P⁻¹‖ * (spectralRadius ℂ S).toReal ^ (n - j) * ‖N ^ j‖ ≤ (‖P‖ * ‖P⁻¹‖ * (∑ j ∈ Finset.range k, ‖N ^ j‖ / (spectralRadius ℂ S).toReal ^ j)) * (n + 1) ^ (k - 1) * (spectralRadius ℂ S).toReal ^ n := by
      intro n
      have h_binom_bound : ∀ j < k, Nat.choose n j ≤ (n + 1) ^ (k - 1) := by
        intro j hj
        have h_binom_bound : Nat.choose n j ≤ (n + 1) ^ j := by
          exact le_trans ( Nat.choose_le_pow _ _ ) ( by gcongr ; linarith )
        generalize_proofs at *; (
        exact le_trans h_binom_bound ( pow_le_pow_right₀ ( by linarith ) ( Nat.le_pred_of_lt hj ) ))
      generalize_proofs at *; (
      have h_binom_bound : ∀ j < k, Nat.choose n j * ‖P‖ * ‖P⁻¹‖ * (spectralRadius ℂ S).toReal ^ (n - j) * ‖N ^ j‖ ≤ ‖P‖ * ‖P⁻¹‖ * ‖N ^ j‖ / (spectralRadius ℂ S).toReal ^ j * (n + 1) ^ (k - 1) * (spectralRadius ℂ S).toReal ^ n := by
        intro j hj
        have h_binom_bound : Nat.choose n j * (spectralRadius ℂ S).toReal ^ (n - j) ≤ (n + 1) ^ (k - 1) * (spectralRadius ℂ S).toReal ^ n / (spectralRadius ℂ S).toReal ^ j := by
          rw [ le_div_iff₀ ( pow_pos h_rho_pos _ ) ];
          convert mul_le_mul_of_nonneg_right ( Nat.cast_le.mpr ( h_binom_bound j hj ) ) ( pow_nonneg h_rho_pos.le n ) using 1 ; ring;
          · by_cases h : j ≤ n <;> simp_all +decide [ mul_assoc, ← pow_add ];
            exact Or.inr <| Nat.choose_eq_zero_of_lt h;
          · norm_cast
        generalize_proofs at *; (
        convert mul_le_mul_of_nonneg_right h_binom_bound ( show 0 ≤ ‖P‖ * ‖P⁻¹‖ * ‖N ^ j‖ by positivity ) using 1 <;> ring;)
      generalize_proofs at *; (
      convert Finset.sum_le_sum fun j hj => h_binom_bound j ( Finset.mem_range.mp hj ) using 1 ; norm_num [ Finset.mul_sum _ _ _, Finset.sum_mul ] ; ring;
      ac_rfl))
    generalize_proofs at *; (
    refine' ⟨ ‖P‖ * ‖P⁻¹‖ * ∑ j ∈ Finset.range k, ‖N ^ j‖ / ( spectralRadius ℂ S |> ENNReal.toReal ) ^ j + 1, _, _ ⟩ <;> norm_num [ h_binom ] at *;
    · exact add_pos_of_nonneg_of_pos ( mul_nonneg ( mul_nonneg ( norm_nonneg _ ) ( norm_nonneg _ ) ) ( Finset.sum_nonneg fun _ _ => div_nonneg ( norm_nonneg _ ) ( pow_nonneg h_rho_pos.le _ ) ) ) zero_lt_one;
    · intro n; refine' le_trans ( norm_sum_le _ _ ) _ ; refine' le_trans ( Finset.sum_le_sum fun j hj => h_term_bound n j ( Finset.mem_range.mp hj ) ) _ ; refine' le_trans ( h_binom_bound n ) _ ; ring_nf; norm_num;
      field_simp;
      exact le_add_of_nonneg_right zero_le_one))))

/-
If S is diagonalizable, then ‖S^n‖ is bounded by C * ρ(S)^n.
-/
open scoped Matrix.Norms.L2Operator

theorem norm_pow_diagonalizable_bound {d : ℕ} (S : Matrix (Fin d) (Fin d) ℂ)
  (h_diag : ∃ P : Matrix (Fin d) (Fin d) ℂ, IsUnit P ∧ (P * S * P⁻¹).IsDiag) :
  ∃ C > 0, ∀ n : ℕ, ‖S ^ n‖ ≤ C * ((spectralRadius ℂ S).toReal) ^ n := by
    by_cases hS : S = 0 <;> simp_all +decide [ Matrix.nonsing_inv_apply_not_isUnit ];
    · refine' ⟨ 1, by norm_num, fun n => _ ⟩ ; cases n <;> norm_num [ Norm.norm ];
      refine' csInf_le _ _ <;> norm_num [ Norm.norm ];
      · exact ⟨ 0, fun c hc => hc.1 ⟩;
      · simp +decide [ Matrix.toEuclideanLin ];
    · obtain ⟨ P, hP_unit, hP_diag ⟩ := h_diag
      have hP_inv : IsUnit P := by
        exact hP_unit
      have hP_inv_norm : 0 < ‖P‖ ∧ 0 < ‖P⁻¹‖ := by
        cases d <;> simp_all +decide [ Matrix.isUnit_iff_isUnit_det ];
        · exact hS ( Subsingleton.elim _ _ );
        · exact ⟨ by aesop_cat, by intro h; simpa [ h, hP_inv ] using congr_arg Matrix.det ( Matrix.nonsing_inv_mul _ <| show IsUnit P.det from isUnit_iff_ne_zero.mpr hP_inv ) ⟩
      have hP_diag_norm : ∀ n : ℕ, ‖(P * S * P⁻¹) ^ n‖ ≤ (spectralRadius ℂ S).toReal ^ n := by
        intro n
        have hP_diag_norm : ∀ i : Fin d, ‖(P * S * P⁻¹) i i‖ ≤ (spectralRadius ℂ S).toReal := by
          intro i
          have h_eigenvalue : (P * S * P⁻¹) i i ∈ spectrum ℂ S := by
            simp_all +decide [ spectrum.mem_iff, Matrix.isUnit_iff_isUnit_det ];
            have h_eigenvalue : Matrix.det (P * (S - (P * S * P⁻¹) i i • 1) * P⁻¹) = 0 := by
              simp_all +decide [ mul_sub, sub_mul, mul_assoc ];
              rw [ ← Matrix.exists_mulVec_eq_zero_iff ];
              refine' ⟨ Pi.single i 1, _, _ ⟩ <;> simp_all +decide [ funext_iff, Matrix.mulVec, dotProduct ];
              · exact ⟨ i, by simp +decide ⟩;
              · intro x; by_cases hx : x = i <;> simp_all +decide [ Matrix.one_apply ] ;
                exact hP_diag hx
            generalize_proofs at *;
            simp_all +decide [ Matrix.det_mul, Algebra.algebraMap_eq_smul_one ];
            rw [ ← neg_sub, Matrix.det_neg ] ; aesop
          generalize_proofs at *;
          refine' le_trans _ ( ENNReal.toReal_mono _ <| le_ciSup _ <| ( P * S * P⁻¹ ) i i ) <;> norm_num [ h_eigenvalue ];
          simp +decide [ spectralRadius ];
          -- Since the spectrum of S is finite, the supremum of the norms of its elements is finite.
          have h_spectrum_finite : Set.Finite (spectrum ℂ S) := by
            exact?
          generalize_proofs at *; (
          rw [ iSup_eq_top ];
          simp +zetaDelta at *;
          exact ⟨ ∑ x ∈ h_spectrum_finite.toFinset, ‖x‖₊, ENNReal.sum_lt_top.mpr fun x hx => ENNReal.coe_lt_top, fun x hx => by simpa using Finset.single_le_sum ( fun x _ => zero_le ( ‖x‖₊ : ENNReal ) ) ( h_spectrum_finite.mem_toFinset.mpr hx ) ⟩)
        generalize_proofs at *;
        have hP_diag_pow : (P * S * P⁻¹) ^ n = Matrix.diagonal (fun i => ((P * S * P⁻¹) i i) ^ n) := by
          induction n <;> simp_all +decide [ pow_succ, Matrix.diagonal_pow ];
          ext i j; by_cases hi : i = j <;> aesop;
        generalize_proofs at *;
        simp_all +decide [ Matrix.norm_def ];
        refine' csInf_le _ _ <;> norm_num [ hP_diag_norm ];
        · exact ⟨ 0, fun c hc => hc.1 ⟩;
        · intro x; rw [ EuclideanSpace.norm_eq ] ; simp +decide [ Matrix.toEuclideanLin, Matrix.mulVec ] ; (
          rw [ Real.sqrt_le_left ] <;> norm_num [ mul_pow, Finset.mul_sum _ _ _, EuclideanSpace.norm_eq ];
          · rw [ Real.sq_sqrt <| Finset.sum_nonneg fun _ _ => sq_nonneg _ ] ; exact le_trans ( Finset.sum_le_sum fun _ _ => mul_le_mul_of_nonneg_right ( pow_le_pow_left₀ ( by positivity ) ( pow_le_pow_left₀ ( by positivity ) ( hP_diag_norm _ ) _ ) _ ) <| sq_nonneg _ ) <| by simp +decide [ Finset.mul_sum _ _ _, mul_assoc, mul_comm, mul_left_comm ] ;
          · exact mul_nonneg ( pow_nonneg ( ENNReal.toReal_nonneg ) _ ) ( Real.sqrt_nonneg _ ));
      generalize_proofs at *;
      -- Using the fact that $S^n = P^{-1} (P S P^{-1})^n P$, we can bound $\|S^n\|$.
      have hS_pow : ∀ n : ℕ, S ^ n = P⁻¹ * (P * S * P⁻¹) ^ n * P := by
        intro n; induction n <;> simp_all +decide [ pow_succ, mul_assoc ] ;
        · cases hP_unit.nonempty_invertible ; aesop;
        · cases hP_unit.nonempty_invertible ; aesop
      generalize_proofs at *; (
      refine' ⟨ ‖P⁻¹‖ * ‖P‖, mul_pos hP_inv_norm.2 hP_inv_norm.1, fun n => _ ⟩ ; rw [ hS_pow ] ; (
      refine' le_trans _ ( mul_le_mul_of_nonneg_left ( hP_diag_norm n ) ( mul_nonneg hP_inv_norm.2.le hP_inv_norm.1.le ) ) ; ring_nf ; (
      exact le_trans ( norm_mul_le _ _ ) ( by rw [ mul_right_comm ] ; exact mul_le_mul_of_nonneg_right ( norm_mul_le _ _ ) ( norm_nonneg _ ) ) ;));)