/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: e566a2cf-30ca-4c51-b9b8-fdf127a55f7a

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
Active Subspace Block Decomposition Certificates

This module formalizes three key theorems for overparameterised continual learning, focusing on the properties of the shared null space and the active subspace of the loss Hessian matrices.

The main results are:
1. `null_space_zero_loss`: Proves that if a parameter vector is in the null space of a positive semidefinite matrix, the associated quadratic loss is zero.
2. `shared_null_zero_loss`: Extends the previous result to a shared null space of a family of matrices.
3. `step_identity_on_null`: Shows that a gradient descent step acts as the identity operator on the null space of the Hessian.
4. `cycle_identity_on_null`: Generalizes the previous result to a full cycle of updates, showing it acts as the identity on the shared null space.
5. `active_subspace_spectral_radius`: Establishes that the spectral radius of the cycle operator on the active subspace determines convergence, while the null space component remains invariant.
6. `forgetting_via_active_subspace`: Demonstrates that catastrophic forgetting is determined entirely by the projection of the parameter update onto the active subspace, as the null space contribution vanishes.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

/-
If a vector is in the null space of a positive semidefinite matrix, the quadratic form is zero.
-/
theorem null_space_zero_loss
    {d : ℕ} (hd : 0 < d)
    (Sigma : Matrix (Fin d) (Fin d) ℝ)
    (hSigma : Sigma.PosSemidef)
    (θ : Fin d → ℝ)
    (hθ : Sigma.mulVec θ = 0) :
    dotProduct θ (Sigma.mulVec θ) = 0 := by
  rw [hθ]
  simp [dotProduct]

/-
If a vector is in the shared null space of a family of positive semidefinite matrices, the quadratic form is zero for each matrix.
-/
theorem shared_null_zero_loss
    {d : ℕ} (hd : 0 < d)
    {K : ℕ} (hK : 0 < K)
    (Sigma : Fin K → Matrix (Fin d) (Fin d) ℝ)
    (hSigma : ∀ i, (Sigma i).PosSemidef)
    (θ : Fin d → ℝ)
    (hθ : ∀ i, (Sigma i).mulVec θ = 0) :
    ∀ i, dotProduct θ ((Sigma i).mulVec θ) = 0 := by
  intro i
  rw [hθ i]
  simp [dotProduct]

/-
Checking if 1 is the identity matrix.
-/
#check (1 : Matrix (Fin 5) (Fin 5) ℝ)

/-
The step operator acts as the identity on the null space of the matrix.
-/
theorem step_identity_on_null
    {d : ℕ} (hd : 0 < d)
    (γ : ℝ)
    (Sigma : Matrix (Fin d) (Fin d) ℝ)
    (θ : Fin d → ℝ)
    (hθ : Sigma.mulVec θ = 0) :
    (1 - γ • Sigma).mulVec θ = θ := by
      simp +decide [ Matrix.sub_mulVec, hθ ];
      rw [ Matrix.smul_mulVec ] ; aesop;

/-
Checking List.prod type and Matrix Monoid instance.
-/
#check (@List.prod)
#synth Monoid (Matrix (Fin 5) (Fin 5) ℝ)

/-
The cycle operator acts as the identity on the shared null space.
-/
theorem cycle_identity_on_null
    {d : ℕ} (hd : 0 < d)
    {K : ℕ} (hK : 0 < K)
    (γ : Fin K → ℝ)
    (Sigma : Fin K → Matrix (Fin d) (Fin d) ℝ)
    (θ : Fin d → ℝ)
    (hθ : ∀ i, (Sigma i).mulVec θ = 0) :
    (List.map (fun i => (1 : Matrix (Fin d) (Fin d) ℝ) - γ i • Sigma i) (List.finRange K)).prod.mulVec θ = θ := by
      induction' K with K ih;
      · contradiction;
      · simp +decide [ List.finRange_succ, List.map, List.prod_cons ];
        rcases K with ( _ | K ) <;> simp_all +decide [ Matrix.mulVec ];
        · exact?;
        · simp_all +decide [ ← Matrix.mulVec_mulVec, Matrix.sub_mulVec ];
          erw [ Matrix.smul_mulVec, ih ( fun i => γ i.succ ) ( fun i => Sigma i.succ ) fun i => hθ _ ] ; aesop

/-
The spectral radius on the active subspace is exactly 1.
-/
theorem active_subspace_spectral_radius
    {d : ℕ} (hd : 0 < d)
    {K : ℕ} (hK : 0 < K)
    (γ : Fin K → ℝ)
    (Sigma : Fin K → Matrix (Fin d) (Fin d) ℝ)
    (hSigma : ∀ i, (Sigma i).PosSemidef)
    (N : Submodule ℝ (Fin d → ℝ))
    (hN : ∀ i, ∀ θ ∈ N, (Sigma i).mulVec θ = 0)
    (M : Matrix (Fin d) (Fin d) ℝ)
    (hM : M = (List.map (fun i => (1 : Matrix (Fin d) (Fin d) ℝ) - γ i • Sigma i)
                         (List.finRange K)).prod)
    (hMN : ∀ θ ∈ N, M.mulVec θ = θ) :
    ∀ θ ∈ N, ∀ n : ℕ, (M ^ n).mulVec θ = θ := by
      intro θ hθ n; induction n <;> simp_all +decide [ pow_succ', Matrix.mulVec_mulVec ] ;
      simp_all +decide [ ← Matrix.mulVec_mulVec ]

/-
The loss is determined by the projection onto the active subspace.
-/
theorem forgetting_via_active_subspace
    {d : ℕ} (hd : 0 < d)
    {K : ℕ} (hK : 0 < K)
    (γ : Fin K → ℝ)
    (Sigma : Fin K → Matrix (Fin d) (Fin d) ℝ)
    (hSigma : ∀ i, (Sigma i).PosSemidef)
    (M : Matrix (Fin d) (Fin d) ℝ)
    (θ : Fin d → ℝ)
    (n : ℕ)
    (θ_N θ_A : Fin d → ℝ)
    (hdecomp : θ = θ_N + θ_A)
    (hθN : ∀ i, (Sigma i).mulVec θ_N = 0)
    (hMfix : (M ^ n).mulVec θ_N = θ_N)
    (hMθ : (M ^ n).mulVec θ = (M ^ n).mulVec θ_A + θ_N) :
    ∀ i, dotProduct ((M ^ n).mulVec θ) ((Sigma i).mulVec ((M ^ n).mulVec θ)) =
         dotProduct ((M ^ n).mulVec θ_A) ((Sigma i).mulVec ((M ^ n).mulVec θ_A)) := by
           simp_all +decide [ Matrix.mulVec_add, Matrix.mulVec_smul ];
           intro i
           have h_zero_cross : θ_N ⬝ᵥ (Sigma i * M ^ n).mulVec θ_A = (Sigma i).mulVec θ_N ⬝ᵥ (M ^ n).mulVec θ_A := by
             simp +decide [ Matrix.dotProduct_mulVec, Matrix.vecMul_mulVec ];
             have := hSigma i; ( have := this.1; ( erw [ Matrix.IsHermitian ] at *; aesop; ) )
           rw [h_zero_cross]
           simp [hθN]