/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 0141d423-aebc-4544-8080-b0bd5b0b439c

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
We define the cyclic and i.i.d. learning efficiencies `cyclic_le` and `iid_le`. We prove that the i.i.d. learning efficiency with a uniform distribution is less than or equal to the cyclic learning efficiency (`cyclic_le_ge_iid_le_uniform`), which implies that there exists a task distribution (specifically the uniform one) that improves upon or matches the cyclic performance (`optimal_task_distribution_improves`). We also show that they are equal when the terms are non-zero (`commutative_cyclic_eq_iid_le_of_ne_zero`).
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

noncomputable def cyclic_le
  (K d : ℕ) [NeZero K] [NeZero d] (Λ : Fin K → Fin d → ℝ) (γ : Fin K → ℝ) : ℝ :=
  (1 / (K : ℝ)) * Finset.univ.sup' (by
  -- Since $d$ is a positive integer, the universal set $\text{Fin } d$ is nonempty.
  apply Finset.univ_nonempty_iff.mpr; exact ⟨0, NeZero.pos d⟩)
    (fun j => Real.log (|∏ i : Fin K, (1 - γ i * Λ i j)|))

noncomputable def iid_le
  (K d : ℕ) [NeZero K] [NeZero d] (Λ : Fin K → Fin d → ℝ) (γ : Fin K → ℝ) (P : Fin K → ℝ) : ℝ :=
  Finset.univ.sup' (by
  -- Since $K$ is a positive integer, the universal set of `Fin K` is nonempty.
  simp [Finset.Nonempty])
    (fun j => ∑ i : Fin K, P i * Real.log |1 - γ i * Λ i j|)

lemma log_abs_prod {α : Type*} (s : Finset α) (f : α → ℝ) (hf : ∀ x ∈ s, f x ≠ 0) :
  Real.log (|∏ x ∈ s, f x|) = ∑ x ∈ s, Real.log (|f x|) := by
  rw [Finset.abs_prod]
  apply Real.log_prod
  intro x hx
  apply abs_ne_zero.mpr (hf x hx)

lemma sup'_mul_const {ι : Type*} (s : Finset ι) (hs : s.Nonempty) (f : ι → ℝ) (c : ℝ) (hc : 0 < c) :
  s.sup' hs f * c = s.sup' hs (fun i => f i * c) := by
  apply Finset.sup'_mul₀ hc

theorem commutative_cyclic_eq_iid_le_of_ne_zero
  (K d : ℕ) [NeZero K] [NeZero d]
  (γ : Fin K → ℝ)
  (Λ : Fin K → Fin d → ℝ)
  (hΛ_pos : ∀ i j, 0 < Λ i j)
  (hNF : ∀ i j, |1 - γ i * Λ i j| < 1)
  (h_ne_zero : ∀ i j, 1 - γ i * Λ i j ≠ 0) :
  cyclic_le K d Λ γ = iid_le K d Λ γ (fun _ => (1 : ℝ) / K) := by
    -- By definition of cyclic_le, we can rewrite the left-hand side as (1/K) * max_j (sum_i log |1 - γ_i Λ_ij|).
    have h_cyclic : cyclic_le K d Λ γ = (1 / K : ℝ) * Finset.univ.sup' (by
    exact ⟨ ⟨ 0, NeZero.pos d ⟩, Finset.mem_univ _ ⟩) (fun j => ∑ i, Real.log |1 - γ i * Λ i j|) := by
      unfold cyclic_le
      generalize_proofs at *;
      simp +decide only [Real.log_abs, Real.log_prod _ _ fun i _ => h_ne_zero i _]
    generalize_proofs at *;
    convert h_cyclic using 1;
    unfold iid_le; norm_num [ mul_comm, Finset.mul_sum _ _ _ ] ;
    refine' le_antisymm _ _ <;> simp +decide [ Finset.mul_sum _ _ _, Finset.sum_mul ];
    · intro j; rw [ ← Finset.mul_sum _ _ _ ] ; exact mul_le_mul_of_nonneg_left ( Finset.le_sup' ( fun x => ∑ i, Real.log ( 1 - γ i * Λ i x ) ) ( Finset.mem_univ j ) ) ( inv_nonneg.mpr ( Nat.cast_nonneg _ ) ) ;
    · obtain ⟨ b, hb ⟩ := Finset.exists_max_image Finset.univ ( fun x => ∑ i : Fin K, Real.log ( 1 - γ i * Λ i x ) ) ⟨ ⟨ 0, NeZero.pos d ⟩, Finset.mem_univ _ ⟩ ; use b; simp_all +decide [ ← Finset.mul_sum _ _ _ ] ;
      exact mul_le_mul_of_nonneg_left ( Finset.sup'_le _ _ fun x _ => hb x ) ( inv_nonneg.2 ( Nat.cast_nonneg _ ) )

lemma cyclic_le_ge_iid_le_uniform
  (K d : ℕ) [NeZero K] [NeZero d]
  (γ : Fin K → ℝ)
  (Λ : Fin K → Fin d → ℝ)
  (hΛ_pos : ∀ i j, 0 < Λ i j)
  (hNF : ∀ i j, |1 - γ i * Λ i j| < 1) :
  iid_le K d Λ γ (fun _ => (1 : ℝ) / K) ≤ cyclic_le K d Λ γ := by
    -- By the properties of the supremum and the fact that the logarithm is a monotonically increasing function, we can bring the supremum inside the sum.
    have h_sup_sum : ∀ j, ∑ i, (1 / (K : ℝ)) * Real.log (abs (1 - γ i * Λ i j)) ≤ (1 / (K : ℝ)) * Real.log (abs (∏ i, (1 - γ i * Λ i j))) := by
      intro j
      have h_sum_le : ∑ i, Real.log (abs (1 - γ i * Λ i j)) ≤ Real.log (abs (∏ i, (1 - γ i * Λ i j))) := by
        by_cases h : ∏ i, ( 1 - γ i * Λ i j ) = 0 <;> simp_all +decide [ Real.log_prod ];
        · exact Finset.sum_nonpos fun x hx => Real.log_nonpos ( abs_nonneg _ ) ( le_of_lt ( hNF x j ) ) |> le_trans ( by aesop ) ;
        · rw [ Real.log_prod _ _ fun i _ => by intro H; exact h <| Finset.prod_eq_zero ( Finset.mem_univ i ) H ];
      simpa only [ Finset.mul_sum _ _ _ ] using mul_le_mul_of_nonneg_left h_sum_le <| by positivity;
    convert Finset.sup'_le _ _ _;
    exact fun j _ => le_trans ( h_sup_sum j ) ( mul_le_mul_of_nonneg_left ( Finset.le_sup' ( fun j => Real.log |∏ i, ( 1 - γ i * Λ i j )| ) ( Finset.mem_univ j ) ) ( by positivity ) )

theorem optimal_task_distribution_improves
  (K d : ℕ) [NeZero K] [NeZero d]
  (γ : Fin K → ℝ) (Λ : Fin K → Fin d → ℝ)
  (hΛ_pos : ∀ i j, 0 < Λ i j)
  (hNF : ∀ i j, |1 - γ i * Λ i j| < 1) :
  ∃ P : Fin K → ℝ,
    (∀ i, 0 < P i) ∧ (∑ i, P i = 1) ∧
    iid_le K d Λ γ P ≤ cyclic_le K d Λ γ := by
  -- Consider the uniform distribution where each $P_i = \frac{1}{K}$.
  use fun _ => 1 / K;
  -- Since the uniform distribution gives each element equal weight, the supremum of the sum of the logarithms should be less than or equal to the supremum of the logarithm of the product.
  apply And.intro;
  · -- Since $K$ is a positive integer, $1/K$ is positive.
    intro i
    exact one_div_pos.mpr (Nat.cast_pos.mpr (NeZero.pos K));
  · -- Apply the lemma that states the cyclic LE is greater than or equal to the IID LE with uniform weights.
    apply And.intro; simp [Finset.sum_const, nsmul_one] ; exact cyclic_le_ge_iid_le_uniform K d γ Λ hΛ_pos hNF;