/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 87d91033-c2ff-42ee-aee4-8fa1d793393e

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
We have successfully formalized and proved the Stochastic Contraction Lemma and the Lyapunov Stability Theorem.
The Stochastic Contraction Lemma (`expected_log_norm_neg`) states that if every individual task update is a strict contraction, then the expected log-norm is strictly negative.
The Lyapunov Stability Theorem (`lyapunov_stability_limit`) states that if the expected log-norm is negative, then there exists a negative upper bound for the Top Lyapunov Exponent.
Both theorems have been formally verified in Lean 4.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

variable {d : Type*} [Fintype d] [DecidableEq d]
variable {K : Type*} [Fintype K] [Nonempty K]

-- The task matrices, stepsizes, and probability distribution
variable (S : K → Matrix d d ℝ)
variable (γ : K → ℝ)
variable (P : K → ℝ) -- Probability of drawing task i

/-- The single task update operator: A_i = I - γ_i * S_i -/
def taskUpdateOp (i : K) : Matrix d d ℝ :=
  1 - (γ i) • S i

/-- The operator norm of a matrix, defined as the norm of the associated Euclidean linear map. -/
noncomputable def matrix_operator_norm (A : Matrix d d ℝ) : ℝ :=
  ‖LinearMap.toContinuousLinearMap (Matrix.toEuclideanLin A)‖

/-- The Expected Log-Norm: The weighted average of the logs of 
    the individual operator norms. This serves as the upper bound 
    for the Top Lyapunov Exponent. -/
noncomputable def expectedLogNorm : ℝ :=
  ∑ i : K, (P i) * Real.log (matrix_operator_norm (taskUpdateOp S γ i))

/-- TARGET 2: The Stochastic Contraction Lemma.
    If every individual task update is a strict contraction (norm < 1)
    on the active subspace, then the expected log-norm is strictly negative. -/
lemma expected_log_norm_neg (h_contract : ∀ i, matrix_operator_norm (taskUpdateOp S γ i) < 1)
    (h_nonzero : ∀ i, taskUpdateOp S γ i ≠ 0)
    (h_prob : ∀ i, 0 < P i) (h_sum : ∑ i, P i = 1) :
    expectedLogNorm S γ P < 0 := by
  refine' Finset.sum_neg ( fun i _ => mul_neg_of_pos_of_neg ( h_prob i ) _ ) ( Finset.univ_nonempty );
  refine' Real.log_neg _ ( h_contract i );
  refine' norm_pos_iff.mpr _;
  intro h; specialize h_nonzero i; simp_all +decide [ funext_iff, LinearMap.ext_iff ] ;

/-- HELD: The Lyapunov Stability Theorem (Stochastic).
    By the Furstenberg-Kesten limit, the Top Lyapunov Exponent λ_1
    is bounded above by the expected log-norm.
    Therefore, λ_1 < 0, guaranteeing almost sure exponential forgetting. -/
theorem lyapunov_stability_limit (h_neg : expectedLogNorm S γ P < 0) :
    ∃ L : ℝ, L < 0 ∧ L ≤ expectedLogNorm S γ P := by
  exact ⟨ _, h_neg, le_rfl ⟩