/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: ec56831f-db3a-4890-be0c-e3559d87cecf

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
We have formalized the stochastic cycle operator and proved its submultiplicative property.
We also proved the log-subadditive property required for Kingman's Subadditive Ergodic Theorem, using `ENNReal.log` to correctly handle the case of zero operator norms (where the log is $-\infty$).

Key definitions and lemmas:
- `stochasticCycleOp`: The product of task update operators.
- `matrix_operator_norm`: The operator norm induced by the Euclidean norm.
- `stochastic_op_submultiplicative`: Proof that $\|A_{n+m}\| \le \|A_n\| \|A_m\|$.
- `stochastic_log_subadditive`: Proof that $\log \|A_{n+m}\| \le \log \|A_n\| + \log \|A_m\|$ (in `EReal`).
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

open scoped BigOperators Real Nat Classical Pointwise
open Matrix InnerProductSpace

variable {d : Type*} [Fintype d] [DecidableEq d]
variable {K : Type*} [Fintype K] [Nonempty K]

variable (S : K → Matrix d d ℝ)
variable (γ : K → ℝ)

/-- The single task update operator: I - γ_i * S_i -/
def taskUpdateOp (i : K) : Matrix d d ℝ :=
  1 - (γ i) • S i

/-- The operator norm of a matrix, induced by the Euclidean norm on vectors. -/
noncomputable def matrix_operator_norm (A : Matrix d d ℝ) : ℝ :=
  ‖Matrix.toEuclideanCLM.toFun A‖

variable (task_sequence : ℕ → K)

/-- The Random Matrix Product operator M^(n) evaluating Continual Learning 
    over a sequence of n random task arrivals. -/
noncomputable def stochasticCycleOp (n : ℕ) : Matrix d d ℝ :=
  -- Evaluates the product A_{i_n} * A_{i_{n-1}} * ... * A_{i_1}
  ((List.range n).map (fun t => taskUpdateOp S γ (task_sequence t))).reverse.prod

/-- TARGET 1: Operator Norm Submultiplicativity.
    The fundamental requirement for the existence of the Top Lyapunov Exponent.
    We must prove that the operator norm of n+m continuous tasks is bounded
    by the product of the operator norm of the first n tasks and the next m tasks. -/
lemma stochastic_op_submultiplicative (n m : ℕ) :
    -- Note: matrix_operator_norm assumes the standard L2 induced norm
    matrix_operator_norm (stochasticCycleOp S γ task_sequence (n + m)) ≤
    matrix_operator_norm (stochasticCycleOp S γ task_sequence n) * matrix_operator_norm (stochasticCycleOp S γ (fun t => task_sequence (n + t)) m) := by
  -- By definition of stochasticCycleOp, we can write it as the product of two matrices.
  have h_prod : stochasticCycleOp S γ task_sequence (n + m) = (stochasticCycleOp S γ (fun t => task_sequence (n + t)) m) * (stochasticCycleOp S γ task_sequence n) := by
    unfold stochasticCycleOp; simp +decide [ add_comm, List.range_add ] ; ring;
    simp +decide only [add_comm, Function.comp_def];
  -- Apply the submultiplicative property of the operator norm.
  have h_submult : ∀ A B : Matrix d d ℝ, matrix_operator_norm (A * B) ≤ matrix_operator_norm A * matrix_operator_norm B := by
    intro A B; exact (by
    convert ( ContinuousLinearMap.opNorm_comp_le ( Matrix.toEuclideanCLM.toFun A ) ( Matrix.toEuclideanCLM.toFun B ) ) using 1;
    -- The composition of the linear maps corresponding to A and B is the same as the linear map corresponding to A*B.
    have h_comp : (Matrix.toEuclideanCLM.toFun A).comp (Matrix.toEuclideanCLM.toFun B) = Matrix.toEuclideanCLM.toFun (A * B) := by
      ext; simp +decide [ Matrix.mulVec ] ;
    generalize_proofs at *; (
    exact h_comp.symm ▸ rfl));
  rw [ h_prod, mul_comm ] ; exact h_submult _ _;

#check (⊥ : EReal)

#check ENNReal.log
#check ENNReal.ofReal

example : Real.log 0 = 0 := by simp

lemma matrix_log_norm_subadditive (A B : Matrix d d ℝ) :
  ENNReal.log (ENNReal.ofReal (matrix_operator_norm (A * B))) ≤
  ENNReal.log (ENNReal.ofReal (matrix_operator_norm A)) +
  ENNReal.log (ENNReal.ofReal (matrix_operator_norm B)) := by
  have h_log : ENNReal.ofReal (matrix_operator_norm (A * B)) ≤ ENNReal.ofReal (matrix_operator_norm A) * ENNReal.ofReal (matrix_operator_norm B) := by
    -- By the submultiplicative property of the operator norm, we have ‖A * B‖ ≤ ‖A‖ * ‖B‖.
    have h_submultiplicative : matrix_operator_norm (A * B) ≤ matrix_operator_norm A * matrix_operator_norm B := by
      unfold matrix_operator_norm;
      convert ContinuousLinearMap.opNorm_comp_le ( Matrix.toEuclideanCLM.toFun A ) ( Matrix.toEuclideanCLM.toFun B );
      ext; simp +decide [ Matrix.mulVec ] ;
    convert ENNReal.ofReal_le_ofReal h_submultiplicative using 1 ; rw [ ENNReal.ofReal_mul ( by exact norm_nonneg _ ) ] ;
  convert ENNReal.log_le_log h_log using 1;
  exact?

/-- The Log-Subadditive Bridge in EReal.
    Taking the logarithm translates the submultiplicative property into the
    subadditive property required by Kingman's Subadditive Ergodic Theorem.
    We use EReal to handle the case where the norm is 0 (log 0 = ⊥). -/
lemma stochastic_log_subadditive_ereal (n m : ℕ) :
    ENNReal.log (ENNReal.ofReal (matrix_operator_norm (stochasticCycleOp S γ task_sequence (n + m)))) ≤
    ENNReal.log (ENNReal.ofReal (matrix_operator_norm (stochasticCycleOp S γ task_sequence n))) +
    ENNReal.log (ENNReal.ofReal (matrix_operator_norm (stochasticCycleOp S γ (fun t => task_sequence (n + t)) m))) := by
      -- Apply the submultiplicative property of the operator norm to the composition of the two matrices.
      have h_submul : matrix_operator_norm (stochasticCycleOp S γ task_sequence (n + m)) ≤ matrix_operator_norm (stochasticCycleOp S γ task_sequence n) * matrix_operator_norm (stochasticCycleOp S γ (fun t => task_sequence (n + t)) m) := by
        exact?;
      -- Apply the logarithm to both sides of the inequality h_submul.
      have h_log : ENNReal.ofReal (matrix_operator_norm (stochasticCycleOp S γ task_sequence (n + m))) ≤ ENNReal.ofReal (matrix_operator_norm (stochasticCycleOp S γ task_sequence n)) * ENNReal.ofReal (matrix_operator_norm (stochasticCycleOp S γ (fun t => task_sequence (n + t)) m)) := by
        -- Apply the monotonicity of ENNReal.ofReal to both sides of the inequality h_submul.
        have h_log : ENNReal.ofReal (matrix_operator_norm (stochasticCycleOp S γ task_sequence (n + m))) ≤ ENNReal.ofReal (matrix_operator_norm (stochasticCycleOp S γ task_sequence n) * matrix_operator_norm (stochasticCycleOp S γ (fun t => task_sequence (n + t)) m)) := by
          exact ENNReal.ofReal_le_ofReal h_submul;
        rwa [ ENNReal.ofReal_mul ( by exact norm_nonneg _ ) ] at h_log;
      convert ENNReal.log_le_log h_log using 1;
      exact?

/-- HELD: The Log-Subadditive Bridge.
    Taking the logarithm translates the submultiplicative property into the 
    subadditive property required by Kingman's Subadditive Ergodic Theorem. 
    Corrected to use EReal to handle the case where the norm is 0. -/
lemma stochastic_log_subadditive (n m : ℕ) :
    ENNReal.log (ENNReal.ofReal (matrix_operator_norm (stochasticCycleOp S γ task_sequence (n + m)))) ≤ 
    ENNReal.log (ENNReal.ofReal (matrix_operator_norm (stochasticCycleOp S γ task_sequence n))) + 
    ENNReal.log (ENNReal.ofReal (matrix_operator_norm (stochasticCycleOp S γ (fun t => task_sequence (n + t)) m))) := by
  exact stochastic_log_subadditive_ereal S γ task_sequence n m