/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 1100f846-1b06-4d57-b230-2f52830c33ab

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
Verified Conjecture E Global Optimality.
Renamed variable `λ` to `lam` to avoid conflict with Lean's lambda abstraction keyword.
All theorems from the user's input have been formally proven.

Theorems proved:
1. `conj_e_annihilation`: ρ̃(γ₃*) = 0
2. `conj_e_strict_pos`: ρ̃(γ₃) > 0 for γ₃ ≠ γ₃*, γ₃ > 0
3. `conj_e_decreasing`: ρ̃ strictly decreasing on (0, 1/λ)
4. `conj_e_increasing`: ρ̃ strictly increasing on (1/λ, ∞)
5. `conj_e_global_min`: ρ̃(γ₃*) ≤ ρ̃(γ₃) for all γ₃ > 0
6. `conj_e_unique`: γ₃* is the unique minimiser
7. `conj_e_in_NF`: γ₃* ∈ NF (0 < γ₃* ≤ 2/λ)
8. `conj_e_global_optimality`: Omnibus certificate combining all properties.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

private lemma inv_mul_self {lam : ℝ} (hlam : 0 < lam) : (1 : ℝ) / lam * lam = 1 :=
  div_mul_cancel₀ 1 (ne_of_gt hlam)

private lemma one_sub_ne_zero {lam γ₃ : ℝ} (hlam : 0 < lam) (hne : γ₃ ≠ 1/lam) :
    1 - γ₃ * lam ≠ 0 := by
  intro h
  have h1 : γ₃ * lam = 1 := by linarith [sub_eq_zero.mp h]
  have h2 : γ₃ = 1 / lam := by
    have hlamne : lam ≠ 0 := ne_of_gt hlam
    field_simp; linarith
  exact hne h2

theorem conj_e_annihilation (lam ρ₂ : ℝ) (hlam : 0 < lam) :
    |1 - (1/lam) * lam| * ρ₂ = 0 := by
  rw [inv_mul_self hlam]; simp

theorem conj_e_strict_pos (lam ρ₂ : ℝ) (hlam : 0 < lam) (hρ₂ : 0 < ρ₂)
    (γ₃ : ℝ) (hγ : 0 < γ₃) (hne : γ₃ ≠ 1/lam) :
    0 < |1 - γ₃ * lam| * ρ₂ :=
  mul_pos (abs_pos.mpr (one_sub_ne_zero hlam hne)) hρ₂

private lemma pos_on_left {lam γ₃ : ℝ} (hlam : 0 < lam) (hγ : γ₃ < 1/lam) :
    0 < 1 - γ₃ * lam := by
  have : γ₃ * lam < 1 := by
    calc γ₃ * lam < (1/lam) * lam := by
          apply mul_lt_mul_of_pos_right hγ hlam
      _ = 1 := inv_mul_self hlam
  linarith

private lemma neg_on_right {lam γ₃ : ℝ} (hlam : 0 < lam) (hγ : 1/lam < γ₃) :
    1 - γ₃ * lam < 0 := by
  have : 1 < γ₃ * lam := by
    calc 1 = (1/lam) * lam := (inv_mul_self hlam).symm
      _ < γ₃ * lam := by apply mul_lt_mul_of_pos_right hγ hlam
  linarith

theorem conj_e_decreasing (lam ρ₂ : ℝ) (hlam : 0 < lam) (hρ₂ : 0 < ρ₂)
    (a b : ℝ) (ha : 0 < a) (hb : a < b) (hb' : b < 1/lam) :
    |1 - b * lam| * ρ₂ < |1 - a * lam| * ρ₂ := by
  have ha' : a < 1/lam := lt_trans hb hb'
  have hap : 0 < 1 - a * lam := pos_on_left hlam ha'
  have hbp : 0 < 1 - b * lam := pos_on_left hlam hb'
  rw [abs_of_pos hap, abs_of_pos hbp]
  apply mul_lt_mul_of_pos_right _ hρ₂
  nlinarith [mul_pos hlam (show 0 < b - a by linarith)]

theorem conj_e_increasing (lam ρ₂ : ℝ) (hlam : 0 < lam) (hρ₂ : 0 < ρ₂)
    (a b : ℝ) (ha : 1/lam < a) (hab : a < b) :
    |1 - a * lam| * ρ₂ < |1 - b * lam| * ρ₂ := by
  have han : 1 - a * lam < 0 := neg_on_right hlam ha
  have hbn : 1 - b * lam < 0 := neg_on_right hlam (lt_trans ha hab)
  rw [abs_of_neg han, abs_of_neg hbn]
  apply mul_lt_mul_of_pos_right _ hρ₂
  nlinarith [mul_pos hlam (show 0 < b - a by linarith)]

theorem conj_e_global_min (lam ρ₂ : ℝ) (hlam : 0 < lam) (hρ₂ : 0 < ρ₂)
    (γ₃ : ℝ) (hγ : 0 < γ₃) :
    |1 - (1/lam) * lam| * ρ₂ ≤ |1 - γ₃ * lam| * ρ₂ := by
  rw [inv_mul_self hlam]; simp
  exact mul_nonneg (abs_nonneg _) (le_of_lt hρ₂)

theorem conj_e_unique (lam ρ₂ : ℝ) (hlam : 0 < lam) (hρ₂ : 0 < ρ₂)
    (γ₃ : ℝ) (hγ : 0 < γ₃) (hmin : |1 - γ₃ * lam| * ρ₂ = 0) :
    γ₃ = 1/lam := by
  -- From hmin and ρ₂ > 0, deduce |1 - γ₃ * lam| = 0
  have h_abs : |1 - γ₃ * lam| = 0 := by
    rcases mul_eq_zero.mp hmin with h | h
    · exact h
    · exact absurd (h ▸ hρ₂) (lt_irrefl 0)
  -- Hence 1 - γ₃ * lam = 0, so γ₃ * lam = 1
  have h_eq : γ₃ * lam = 1 := by
    have := abs_eq_zero.mp h_abs
    linarith [sub_eq_zero.mp this]
  -- Conclude γ₃ = 1/lam
  have hlamne : lam ≠ 0 := ne_of_gt hlam
  field_simp
  linarith

def scalar_NF (γ lam : ℝ) : Prop := 0 < γ ∧ γ ≤ 2 / lam

theorem conj_e_in_NF (lam : ℝ) (hlam : 0 < lam) : scalar_NF (1/lam) lam := by
  -- By definition of scalar_NF, we need to show that 0 < 1 / lam and 1 / lam ≤ 2 / lam.
  apply And.intro (by
  -- Since $lam > 0$, we have $1 / lam > 0$.
  apply one_div_pos.mpr hlam) (by
  -- Since $lam > 0$, dividing both sides of $1 \leq 2$ by $lam$ preserves the inequality.
  apply div_le_div_of_nonneg_right; norm_num; exact hlam.le)

theorem conj_e_global_optimality
    (lam ρ₂ : ℝ) (hlam : 0 < lam) (hρ₂ : 0 < ρ₂) :
    -- (1) minimum value zero
    |1 - (1/lam) * lam| * ρ₂ = 0  ∧
    -- (2) strictly positive away from optimum
    (∀ γ₃ : ℝ, 0 < γ₃ → γ₃ ≠ 1/lam → 0 < |1 - γ₃ * lam| * ρ₂)  ∧
    -- (3) bimonotonicity
    (∀ a b : ℝ, 0 < a → a < b → b < 1/lam →
        |1 - b * lam| * ρ₂ < |1 - a * lam| * ρ₂)  ∧
    (∀ a b : ℝ, 1/lam < a → a < b →
        |1 - a * lam| * ρ₂ < |1 - b * lam| * ρ₂)  ∧
    -- (4) global bound
    (∀ γ₃ : ℝ, 0 < γ₃ → |1 - (1/lam) * lam| * ρ₂ ≤ |1 - γ₃ * lam| * ρ₂) :=
  ⟨conj_e_annihilation lam ρ₂ hlam,
   fun γ₃ hγ hne => conj_e_strict_pos lam ρ₂ hlam hρ₂ γ₃ hγ hne,
   fun a b ha hab hb' => conj_e_decreasing lam ρ₂ hlam hρ₂ a b ha hab hb',
   fun a b ha hab => conj_e_increasing lam ρ₂ hlam hρ₂ a b ha hab,
   fun γ₃ hγ => conj_e_global_min lam ρ₂ hlam hρ₂ γ₃ hγ⟩