/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 14470f51-6cc6-421d-a3f2-31c7246cc0a5

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
Formalized the effective covariance definitions and proved the identity I - Σ_R = M12. Note that the user's definition of Σ_R was inconsistent with the hint and the target identity; a corrected definition `Sigma_R_corrected` was used to prove the theorem `effective_covariance_identity`. The correction involves using the structure `S + Q3(1-S)` instead of `S + Q3 - Q3(1-S)`.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

/-
Definition of A_i = I - gamma_i Sigma_i
-/
open Matrix

noncomputable def A {d : Type*} [Fintype d] [DecidableEq d] (Sigma : Fin 12 → Matrix d d ℝ) (gamma : Fin 12 → ℝ) (i : Fin 12) : Matrix d d ℝ :=
  (1 : Matrix d d ℝ) - gamma i • Sigma i

/-
Definition of M12 = A_12 ... A_1
-/
noncomputable def M12 {d : Type*} [Fintype d] [DecidableEq d] (Sigma : Fin 12 → Matrix d d ℝ) (gamma : Fin 12 → ℝ) : Matrix d d ℝ :=
  (List.ofFn (fun i => A Sigma gamma i)).reverse.prod

/-
Definition of Level 1 effective covariance Sigma_P
-/
noncomputable def Sigma_P {d : Type*} [Fintype d] [DecidableEq d] (Sigma : Fin 12 → Matrix d d ℝ) (gamma : Fin 12 → ℝ) (i : Fin 6) : Matrix d d ℝ :=
  let i1 : Fin 12 := ⟨2 * i.val, by have := i.isLt; omega⟩
  let i2 : Fin 12 := ⟨2 * i.val + 1, by have := i.isLt; omega⟩
  gamma i1 • Sigma i1 + gamma i2 • Sigma i2 - (gamma i1 * gamma i2) • (Sigma i2 * Sigma i1)

/-
Definition of Level 2 effective covariance Sigma_Q
-/
noncomputable def Sigma_Q {d : Type*} [Fintype d] [DecidableEq d] (Sigma : Fin 12 → Matrix d d ℝ) (gamma : Fin 12 → ℝ) (i : Fin 3) : Matrix d d ℝ :=
  let P1 := Sigma_P Sigma gamma ⟨2 * i.val, by have := i.isLt; omega⟩
  let P2 := Sigma_P Sigma gamma ⟨2 * i.val + 1, by have := i.isLt; omega⟩
  P1 + P2 - P2 * P1

/-
Definition of Level 3 effective covariance Sigma_R
-/
noncomputable def Sigma_R {d : Type*} [Fintype d] [DecidableEq d] (Sigma : Fin 12 → Matrix d d ℝ) (gamma : Fin 12 → ℝ) : Matrix d d ℝ :=
  let Q1 := Sigma_Q Sigma gamma 0
  let Q2 := Sigma_Q Sigma gamma 1
  let Q3 := Sigma_Q Sigma gamma 2
  Q1 + Q2 + Q3 - Q2 * Q1 - Q3 * (1 - Q2) * (1 - Q1)

/-
Lemma: I - Sigma_P_i = A_{2i+1} A_{2i}
-/
theorem one_sub_Sigma_P {d : Type*} [Fintype d] [DecidableEq d] (Sigma : Fin 12 → Matrix d d ℝ) (gamma : Fin 12 → ℝ) (i : Fin 6) :
    (1 : Matrix d d ℝ) - Sigma_P Sigma gamma i =
    A Sigma gamma ⟨2 * i.val + 1, by have := i.isLt; omega⟩ * A Sigma gamma ⟨2 * i.val, by have := i.isLt; omega⟩ := by
      unfold Sigma_P A
      simp [mul_add, add_mul, sub_mul, mul_sub];
      ext; norm_num; ring;

/-
Lemma: I - Sigma_Q_i = (I - Sigma_P_{2i+1}) (I - Sigma_P_{2i})
-/
theorem one_sub_Sigma_Q {d : Type*} [Fintype d] [DecidableEq d] (Sigma : Fin 12 → Matrix d d ℝ) (gamma : Fin 12 → ℝ) (i : Fin 3) :
    (1 : Matrix d d ℝ) - Sigma_Q Sigma gamma i =
    ((1 : Matrix d d ℝ) - Sigma_P Sigma gamma ⟨2 * i.val + 1, by have := i.isLt; omega⟩) *
    ((1 : Matrix d d ℝ) - Sigma_P Sigma gamma ⟨2 * i.val, by have := i.isLt; omega⟩) := by
      unfold Sigma_Q Sigma_P; ring;
      grind

/-
Definition of Corrected Level 3 effective covariance Sigma_R_corrected
-/
noncomputable def Sigma_R_corrected {d : Type*} [Fintype d] [DecidableEq d] (Sigma : Fin 12 → Matrix d d ℝ) (gamma : Fin 12 → ℝ) : Matrix d d ℝ :=
  let Q1 := Sigma_Q Sigma gamma 0
  let Q2 := Sigma_Q Sigma gamma 1
  let Q3 := Sigma_Q Sigma gamma 2
  Q1 + Q2 - Q2 * Q1 + Q3 * ((1 : Matrix d d ℝ) - Q2) * ((1 : Matrix d d ℝ) - Q1)

/-
Lemma: I - Sigma_R_corrected = (I - Q3)(I - Q2)(I - Q1)
-/
theorem one_sub_Sigma_R_corrected {d : Type*} [Fintype d] [DecidableEq d] (Sigma : Fin 12 → Matrix d d ℝ) (gamma : Fin 12 → ℝ) :
    (1 : Matrix d d ℝ) - Sigma_R_corrected Sigma gamma =
    ((1 : Matrix d d ℝ) - Sigma_Q Sigma gamma 2) *
    ((1 : Matrix d d ℝ) - Sigma_Q Sigma gamma 1) *
    ((1 : Matrix d d ℝ) - Sigma_Q Sigma gamma 0) := by
      unfold Sigma_R_corrected Sigma_Q;
      simp +decide [ sub_mul, mul_sub, add_mul, mul_add ] ; abel_nf;

/-
Lemma: I - Sigma_Q_i = A_{4i+3} A_{4i+2} A_{4i+1} A_{4i}
-/
theorem one_sub_Sigma_Q_expansion {d : Type*} [Fintype d] [DecidableEq d] (Sigma : Fin 12 → Matrix d d ℝ) (gamma : Fin 12 → ℝ) (i : Fin 3) :
    (1 : Matrix d d ℝ) - Sigma_Q Sigma gamma i =
    A Sigma gamma ⟨4 * i.val + 3, by have := i.isLt; omega⟩ *
    A Sigma gamma ⟨4 * i.val + 2, by have := i.isLt; omega⟩ *
    A Sigma gamma ⟨4 * i.val + 1, by have := i.isLt; omega⟩ *
    A Sigma gamma ⟨4 * i.val, by have := i.isLt; omega⟩ := by
      convert one_sub_Sigma_Q Sigma gamma i using 1
      generalize_proofs at *;
      rw [ one_sub_Sigma_P, one_sub_Sigma_P ] ; ring!;
      rw [ mul_assoc ]

/-
Lemma: M12 = (I - Q3)(I - Q2)(I - Q1)
-/
theorem M12_decomposition {d : Type*} [Fintype d] [DecidableEq d] (Sigma : Fin 12 → Matrix d d ℝ) (gamma : Fin 12 → ℝ) :
    M12 Sigma gamma =
    ((1 : Matrix d d ℝ) - Sigma_Q Sigma gamma 2) *
    ((1 : Matrix d d ℝ) - Sigma_Q Sigma gamma 1) *
    ((1 : Matrix d d ℝ) - Sigma_Q Sigma gamma 0) := by
      -- By definition of $M12$, we can write it as a product of the matrices $A_i$.
      have hM12 : M12 Sigma gamma = (A Sigma gamma 11 * A Sigma gamma 10 * A Sigma gamma 9 * A Sigma gamma 8) * (A Sigma gamma 7 * A Sigma gamma 6 * A Sigma gamma 5 * A Sigma gamma 4) * (A Sigma gamma 3 * A Sigma gamma 2 * A Sigma gamma 1 * A Sigma gamma 0) := by
        unfold M12; simp +decide [ mul_assoc ] ;
      convert hM12 using 1 ; simp +decide [ ← mul_assoc, one_sub_Sigma_Q_expansion ] ;

/-
Main Theorem: I - Sigma_R_corrected = M12
-/
theorem effective_covariance_identity {d : Type*} [Fintype d] [DecidableEq d] (Sigma : Fin 12 → Matrix d d ℝ) (gamma : Fin 12 → ℝ) :
    (1 : Matrix d d ℝ) - Sigma_R_corrected Sigma gamma = M12 Sigma gamma := by
      rw [ one_sub_Sigma_R_corrected, M12_decomposition ]