/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 16894d9f-d1e3-4af6-b4af-d0867f1027ca

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
This module formalizes the "d=2 miracle" and related properties for the interleaved quartic invariant of matrices. It proves that for 2x2 matrices, the trace of S₁S₂S₁S₂ reduces to degree-2 invariants (trace and determinant), specifically tr(S₁S₂S₁S₂) = tr(S₁S₂)² - 2·det(S₁)·det(S₂). It also verifies the commutative reduction, provides explicit 3x3 counterexamples showing this reduction fails at d=3, and establishes the stratification of invariants at d=2.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

open scoped BigOperators Classical

open Matrix BigOperators Finset

theorem cayley_hamilton_2x2 {R : Type*} [CommRing R] (M : Matrix (Fin 2) (Fin 2) R) :
    M ^ 2 = M.trace • M - M.det • 1 := by
      -- By expanding the right-hand side, we can verify that it matches the left-hand side.
      ext i j; simp [Matrix.mul_apply, Matrix.trace, Matrix.det_fin_two];
      -- By expanding both sides using the definitions of matrix multiplication and the determinant, we can verify that they are equal.
      fin_cases i <;> fin_cases j <;> simp [Matrix.mul_apply, pow_two] <;> ring!;

theorem trace_sq_d2 {R : Type*} [CommRing R] (M : Matrix (Fin 2) (Fin 2) R) :
    (M ^ 2).trace = M.trace ^ 2 - 2 * M.det := by
      -- By definition of matrix multiplication and the properties of the trace and determinant, we can expand both sides.
      simp [Matrix.trace, Matrix.det_fin_two, pow_two];
      -- By expanding both sides, we can see that they are equal.
      simp [Matrix.mul_apply, Matrix.trace]
      ring

theorem d2_miracle {R : Type*} [CommRing R] (S₁ S₂ : Matrix (Fin 2) (Fin 2) R) :
    (S₁ * S₂ * S₁ * S₂).trace =
    (S₁ * S₂).trace ^ 2 - 2 * (S₁.det * S₂.det) := by
      -- By the properties of the trace and determinant, we can expand the left-hand side.
      have h_expand : Matrix.trace ((S₁ * S₂) ^ 2) = (Matrix.trace (S₁ * S₂)) ^ 2 - 2 * Matrix.det (S₁ * S₂) := by
        -- Apply the formula for the trace of the square of a 2x2 matrix.
        apply trace_sq_d2;
      -- By the properties of the trace and determinant, we can expand the left-hand side and simplify.
      simp_all +decide [ pow_two, mul_assoc, Matrix.trace_mul_comm S₁ ]

theorem d2_commutator_correction {R : Type*} [CommRing R] (S₁ S₂ : Matrix (Fin 2) (Fin 2) R) :
    (S₁ * (S₂ * S₁ - S₁ * S₂) * S₂).trace =
    (S₁ * S₂).trace ^ 2 - 2 * (S₁.det * S₂.det) - (S₁ ^ 2 * S₂ ^ 2).trace := by
      -- By expanding the left-hand side and using the properties of traces and determinants for 2x2 matrices, we can show that the equation holds.
      have h_expand : Matrix.trace (S₁ * S₂ * S₁ * S₂) = (Matrix.trace (S₁ * S₂))^2 - 2 * (S₁.det * S₂.det) := by
        -- Apply the theorem d2_miracle to the matrix S₁ * S₂.
        apply d2_miracle;
      simp +decide [ sub_mul, mul_sub, ← mul_assoc, pow_two, h_expand ]

theorem p12_commutative {R : Type*} [CommRing R] (S₁ S₂ : Matrix (Fin 2) (Fin 2) R)
    (hcomm : S₁ * S₂ = S₂ * S₁) :
    (S₁ * S₂ * S₁ * S₂).trace = (S₁ ^ 2 * S₂ ^ 2).trace := by
      -- Since $S₁$ and $S₂$ commute, we can rearrange the terms in the product.
      simp [hcomm, pow_two, mul_assoc];
      grind

theorem p12_commutative_general {R : Type*} [CommRing R] {n : Type*} [DecidableEq n] [Fintype n]
    (S₁ S₂ : Matrix n n R)
    (hcomm : S₁ * S₂ = S₂ * S₁) :
    (S₁ * S₂ * S₁ * S₂).trace = (S₁ ^ 2 * S₂ ^ 2).trace := by
      -- By associativity of matrix multiplication and the commutativity condition, we can rearrange the terms in the product.
      simp [hcomm, mul_assoc, pow_two];
      grind

theorem d2_miracle_fails_d3 : ∃ (S₁ S₂ : Matrix (Fin 3) (Fin 3) ℤ),
    (S₁ * S₂ * S₁ * S₂).trace ≠
    (S₁ * S₂).trace ^ 2 - 2 * (S₁.det * S₂.det) := by
      -- Consider the matrices
      use !![1, 0, 0; 0, 1, 0; 0, 0, 1], !![0, 1, 0; 0, 0, 1; 1, 0, 0];
      -- Calculate the trace of $S₁ * S₂ * S₁ * S₂$.
      simp +decide [Matrix.trace]

theorem d2_interleaved_determined {R : Type*} [CommRing R] (S₁ S₂ : Matrix (Fin 2) (Fin 2) R) :
    ∃ (f : R → R → R → R),
    (S₁ * S₂ * S₁ * S₂).trace = f (S₁ * S₂).trace S₁.det S₂.det := by
  exact ⟨fun c d₁ d₂ => c ^ 2 - 2 * (d₁ * d₂), d2_miracle S₁ S₂⟩

theorem d3_p12_independent_of_scalar_invariants :
    let A₁ : Matrix (Fin 3) (Fin 3) ℤ := !![0,0,1; -1,-2,2; 1,0,-2]
    let B₁ : Matrix (Fin 3) (Fin 3) ℤ := !![0,2,0; -2,2,-1; 1,2,0]
    let A₂ : Matrix (Fin 3) (Fin 3) ℤ := !![0,2,1; 1,0,-2; 0,-2,-2]
    let B₂ : Matrix (Fin 3) (Fin 3) ℤ := !![-2,-2,1; 0,0,1; 1,0,-1]
    -- Same tr(AB) = -1, det(A) = 2, det(B) = -2
    (A₁ * B₁).trace = (A₂ * B₂).trace ∧
    A₁.det = A₂.det ∧ B₁.det = B₂.det ∧
    -- But p₁₂ differs: 21 ≠ 1
    (A₁ * B₁ * A₁ * B₁).trace ≠ (A₂ * B₂ * A₂ * B₂).trace := by
  native_decide