/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 1d60ff74-0d00-4c03-9cdc-e918bb568bd6

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
I have formalized the Boundary Lemma for general K at d=2.
I defined the 2x2 skew-symmetric basis matrix `J2`, the symmetric part `sym_part`, and the skew scalar `skew_scalar`.
I proved the decomposition `matrix2x2_skew_decomp` (corrected to use subtraction) and the determinant identity `det_decomp_2x2`.
I defined `spectral_radius_2x2` to correctly handle both real and complex regimes, as the user's original formula was only valid in the complex regime.
I proved `boundary_lemma_generalK` and `boundary_lemma_generalK_achieved`.
Finally, I proved the summary theorem `boundary_lemma_all_K_summary` using the corrected spectral radius definition, showing that the minimum spectral radius is T/2 and is achieved at the boundary of the real/complex regimes.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

open Real

def J2 : Matrix (Fin 2) (Fin 2) ℝ :=
  !![0, 1; -1, 0]

def sym_part (M : Matrix (Fin 2) (Fin 2) ℝ) : Matrix (Fin 2) (Fin 2) ℝ :=
  (M + Matrix.transpose M) / 2

def skew_scalar (M : Matrix (Fin 2) (Fin 2) ℝ) : ℝ :=
  (M 1 0 - M 0 1) / 2

theorem matrix2x2_skew_decomp (M : Matrix (Fin 2) (Fin 2) ℝ) :
    M = sym_part M - skew_scalar M • J2 := by
      -- Let's expand the right-hand side to verify the equality.
      ext i j; simp [sym_part, skew_scalar, J2];
      norm_num [ div_eq_mul_inv ];
      fin_cases i <;> fin_cases j <;> norm_num [ Matrix.mul_apply, Matrix.inv_def ] <;> ring!;
      · erw [ Matrix.det_diagonal, Matrix.adjugate_diagonal ] ; norm_num ; ring!;
      · erw [ Matrix.det_diagonal, Matrix.adjugate_diagonal ] ; norm_num ; ring;
      · erw [ Matrix.det_diagonal, Matrix.adjugate_diagonal ] ; norm_num ; ring;
      · erw [ Matrix.det_diagonal, Matrix.adjugate_diagonal ] ; norm_num ; ring!;

theorem det_decomp_2x2 (a b c_off d_diag c : ℝ) :
    let M : Matrix (Fin 2) (Fin 2) ℝ := !![a, b + c; -c + b, d_diag]
    Matrix.det M = a * d_diag - b^2 + c^2 := by
  simp [Matrix.det_fin_two]
  ring

theorem boundary_lemma_sym_generalK (a b : ℝ) (ha : a ≥ 0) (hb : b ≥ 0) :
    (a + b)^2 ≥ 4 * a * b := by nlinarith [sq_nonneg (a - b)]

theorem rho_lb_from_T (T D : ℝ) (hT : T > 0) (hD : D > 0) :
    Real.sqrt D ≥ T / 2 ∨ (T^2 ≥ 4 * D ∧ (T + Real.sqrt (T^2 - 4*D)) / 2 ≥ T / 2) := by
  by_cases h : T^2 < 4 * D
  · left
    rw [ge_iff_le, ← Real.sqrt_sq (by linarith : T/2 ≥ 0)]
    apply Real.sqrt_le_sqrt
    nlinarith
  · right
    push_neg at h
    constructor
    · exact h
    · apply div_le_div_of_nonneg_right _ (by norm_num)
      linarith [Real.sqrt_nonneg (T^2 - 4*D)]

theorem boundary_lemma_generalK
    (T D_sym : ℝ) (hT : T > 0) (hD_sym : D_sym > 0) :
    -- For any skew parameter c:
    ∀ c : ℝ,
    -- The determinant is D_sym + c²
    let D_c := D_sym + c^2
    -- ρ_c ≥ T/2 (in the relevant regime)
    (T^2 ≥ 4 * D_c → (T + Real.sqrt (T^2 - 4*D_c)) / 2 ≥ T / 2) ∧
    (T^2 < 4 * D_c → Real.sqrt D_c ≥ T / 2) := by
  intro c
  constructor
  · intro _
    apply div_le_div_of_nonneg_right _ (by norm_num)
    linarith [Real.sqrt_nonneg (T^2 - 4*(D_sym + c^2))]
  · intro h
    rw [ge_iff_le, ← Real.sqrt_sq (by linarith : T/2 ≥ 0)]
    apply Real.sqrt_le_sqrt
    nlinarith

theorem boundary_lemma_generalK_achieved
    (T D_sym : ℝ) (hT : T > 0) (hD_sym : D_sym > 0)
    (h_feasible : T^2 / 4 ≥ D_sym) :
    ∃ c₀ : ℝ, D_sym + c₀^2 = T^2 / 4 := by
  use Real.sqrt (T^2 / 4 - D_sym)
  have h : T^2 / 4 - D_sym ≥ 0 := by linarith
  rw [Real.sq_sqrt h]
  ring

theorem boundary_lemma_generalK_corollary
    (T D_sym : ℝ) (hT : T > 0) (hD_sym : D_sym > 0)
    (h_feasible : T^2 / 4 ≥ D_sym) :
    -- Minimum ρ = T/2
    ∃ c₀ : ℝ, D_sym + c₀^2 = T^2 / 4 ∧
    -- And at this c₀: ρ = T/2 (boundary of real/complex regime)
    Real.sqrt (D_sym + c₀^2) = T / 2 := by
      -- By solving $D_sym + c₀^2 = T^2 / 4$ for $c₀$, we get $c₀ = \sqrt{T^2 / 4 - D_sym}$.
      use Real.sqrt (T^2 / 4 - D_sym);
      -- By definition of $c₀$, we have $D_sym + c₀^2 = T^2 / 4$.
      simp [h_feasible];
      -- Since $T > 0$, we have $\sqrt{T^2} = T$.
      norm_num [Real.sqrt_sq hT.le]

def spectral_radius_2x2 (T D : ℝ) : ℝ :=
  if T^2 < 4 * D then Real.sqrt D
  else (T + Real.sqrt (T^2 - 4 * D)) / 2

theorem boundary_lemma_all_K_summary_corrected :
    -- For any 2×2 matrix with trace T>0 and symmetric-part determinant D_sym>0:
    ∀ (T D_sym : ℝ), T > 0 → D_sym > 0 → T^2 / 4 ≥ D_sym →
    -- 1. ρ ≥ T/2 for all skew parameters
    (∀ c : ℝ, spectral_radius_2x2 T (D_sym + c^2) ≥ T / 2) ∧
    -- 2. ρ = T/2 is achieved at c₀² = T²/4 - D_sym
    (∃ c₀ : ℝ, spectral_radius_2x2 T (D_sym + c₀^2) = T / 2) := by
      intros T D_sym hT hD_sym h_feasible
      apply And.intro;
      · unfold spectral_radius_2x2
        intro c
        by_cases h_case : T^2 < 4 * (D_sym + c^2);
        · rw [ if_pos h_case ] ; exact Real.le_sqrt_of_sq_le ( by linarith );
        · split_ifs ; linarith [ Real.sqrt_nonneg ( T ^ 2 - 4 * ( D_sym + c ^ 2 ) ) ];
          linarith [ Real.sqrt_nonneg ( T ^ 2 - 4 * ( D_sym + c ^ 2 ) ) ];
      · -- By the boundary_lemma_generalK_corollary, there exists a c₀ such that D_sym + c₀^2 = T^2/4 and sqrt(D_sym + c₀^2) = T/2.
        obtain ⟨c₀, hc₀⟩ : ∃ c₀ : ℝ, D_sym + c₀^2 = T^2 / 4 ∧ Real.sqrt (D_sym + c₀^2) = T / 2 := by
          exact ⟨ Real.sqrt ( T ^ 2 / 4 - D_sym ), by linarith [ Real.mul_self_sqrt ( show 0 ≤ T ^ 2 / 4 - D_sym by linarith ) ], by rw [ Real.sqrt_eq_iff_mul_self_eq ] <;> nlinarith [ Real.mul_self_sqrt ( show 0 ≤ T ^ 2 / 4 - D_sym by linarith ) ] ⟩;
        -- Substitute $c₀$ into the spectral radius formula and simplify.
        use c₀
        simp [hc₀, spectral_radius_2x2];
        ring_nf; norm_num [ hT.le ] ;

theorem boundary_lemma_all_K_summary :
    -- For any 2×2 matrix with trace T>0 and symmetric-part determinant D_sym>0:
    ∀ (T D_sym : ℝ), T > 0 → D_sym > 0 → T^2 / 4 ≥ D_sym →
    -- 1. ρ ≥ T/2 for all skew parameters
    (∀ c : ℝ, spectral_radius_2x2 T (D_sym + c^2) ≥ T / 2) ∧
    -- 2. ρ = T/2 is achieved at c₀² = T²/4 - D_sym
    (∃ c₀ : ℝ, spectral_radius_2x2 T (D_sym + c₀^2) = T / 2) := by
  exact boundary_lemma_all_K_summary_corrected