/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 1d68e65b-40df-44e6-af2b-bf31e3ce8c20

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
This module formalizes the spectral radius optimality results for the K=2 non-commutative regime.
It proves that the spectral radius ρ(M₂) is always lower-bounded by T/2, with the minimum achieved at the boundary T²=4D.
Key results include:
- `k2_rho_real_lb`: ρ ≥ T/2 in the real regime.
- `k2_rho_complex_lb`: ρ ≥ T/2 in the complex regime.
- `k2_unified_lb`: Unified lower bound ρ ≥ T/2 across both regimes.
- `k2_global_optimality`: The global minimum is exactly T/2, achieved at T²=4D.
- `k2_rho_real_approaches_half_trace`: In the real regime with D ≥ 0, ρ ≤ T (added `hD : 0 ≤ D` to correct the statement).
- `k2_D_product_min`: The determinant factor D is minimised at γᵢ* = tᵢ/(2dᵢ).
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

open Real

theorem k2_rho_real_lb (T D : ℝ) (hT : 0 ≤ T) (hreal : 4 * D ≤ T ^ 2) :
    T / 2 ≤ (T + Real.sqrt (T ^ 2 - 4 * D)) / 2 := by
  have hsqrt : 0 ≤ Real.sqrt (T ^ 2 - 4 * D) := Real.sqrt_nonneg _
  linarith

theorem k2_boundary_rho_eq (T : ℝ) (hT : 0 ≤ T) :
    (T + Real.sqrt (T ^ 2 - 4 * (T ^ 2 / 4))) / 2 = T / 2 := by
  have : T ^ 2 - 4 * (T ^ 2 / 4) = 0 := by ring
  simp [this, Real.sqrt_zero]

theorem k2_rho_real_antitone_D (T D₁ D₂ : ℝ) (hT : 0 ≤ T)
    (hD1 : 4 * D₁ ≤ T ^ 2) (hD2 : D₁ < D₂) (hD2_bound : 4 * D₂ ≤ T ^ 2) :
    (T + Real.sqrt (T ^ 2 - 4 * D₂)) / 2 < (T + Real.sqrt (T ^ 2 - 4 * D₁)) / 2 := by
  have h1 : T ^ 2 - 4 * D₂ < T ^ 2 - 4 * D₁ := by linarith
  have h2 : 0 ≤ T ^ 2 - 4 * D₂ := by linarith
  have hsq : Real.sqrt (T ^ 2 - 4 * D₂) < Real.sqrt (T ^ 2 - 4 * D₁) :=
    Real.sqrt_lt_sqrt h2 h1
  linarith

theorem k2_rho_complex_lb (T D : ℝ) (hT : 0 ≤ T) (hD : 0 ≤ D)
    (hcomplex : T ^ 2 < 4 * D) :
    T / 2 ≤ Real.sqrt D := by
      -- Since $T^2 < 4D$, taking the square root of both sides gives $T < 2\sqrt{D}$.
      have h_sqrt : T < 2 * Real.sqrt D := by
        -- Taking the square root of both sides of $T^2 < 4D$, we get $T < \sqrt{4D}$.
        have h_sqrt : T < Real.sqrt (4 * D) := by
          -- Since $T$ is non-negative, taking the square root of both sides of $T^2 < 4D$ preserves the inequality.
          apply Real.lt_sqrt_of_sq_lt; exact hcomplex;
        -- Since $\sqrt{4D} = 2\sqrt{D}$, we can conclude that $T < 2\sqrt{D}$.
        rw [Real.sqrt_mul (by norm_num)] at h_sqrt
        norm_num at h_sqrt
        exact h_sqrt;
      -- By dividing both sides of the inequality $T < 2 * \sqrt{D}$ by 2, we obtain $T / 2 < \sqrt{D}$.
      linarith [h_sqrt]

theorem k2_rho_complex_lb_strict (T D : ℝ) (hT : 0 < T) (hD : 0 < D)
    (hcomplex : T ^ 2 < 4 * D) :
    T / 2 < Real.sqrt D := by
      -- Taking the square root of both sides of $T^2 / 4 < D$, we get $T / 2 < \sqrt{D}$.
      apply Real.lt_sqrt_of_sq_lt; linarith

theorem k2_unified_lb (T D : ℝ) (hT : 0 ≤ T) (hD : 0 ≤ D) :
    (if T ^ 2 ≤ 4 * D
     then Real.sqrt D          -- complex regime
     else (T + Real.sqrt (T ^ 2 - 4 * D)) / 2)  -- real regime
    ≥ T / 2 := by
      -- Consider the two cases: $T^2 \leq 4D$ and $T^2 > 4D$.
      by_cases h_case : T^2 ≤ 4 * D;
      · -- Since $T$ is non-negative, we have $T^2 \leq 4D$ implies $T \leq 2\sqrt{D}$.
        have h_sqrt : T ≤ 2 * Real.sqrt D := by
          nlinarith [ Real.sqrt_nonneg D, Real.sq_sqrt hD ];
        split_ifs ; linarith [ Real.sqrt_nonneg D ] ;
      · -- Since $T^2 > 4D$, we have $\sqrt{T^2 - 4D} \geq 0$, thus $(T + \sqrt{T^2 - 4D}) / 2 \geq T / 2$.
        simp [h_case];
        -- Since $T^2 > 4D$, we have $\sqrt{T^2 - 4D} \geq 0$, thus $0 \leq \sqrt{T^2 - 4D}$.
        apply div_le_div_of_nonneg_right (by linarith [Real.sqrt_nonneg (T^2 - 4 * D)]) (by norm_num)

theorem k2_min_is_half_trace (T : ℝ) (hT : 0 ≤ T) :
    (if T ^ 2 ≤ 4 * (T ^ 2 / 4)
     then Real.sqrt (T ^ 2 / 4)
     else (T + Real.sqrt (T ^ 2 - 4 * (T ^ 2 / 4))) / 2) = T / 2 := by
       -- Since $T^2 \leq 4 * (T^2 / 4)$ simplifies to $T^2 \leq T^2$, which is always true, the if statement evaluates to true.
       simp [mul_div_cancel₀];
       -- Since $T$ is non-negative, we have $\sqrt{T^2} = T$.
       rw [Real.sqrt_sq hT]
       norm_num

theorem k2_D_quadratic_min (t d γ : ℝ) (hd : 0 < d) :
    1 - t ^ 2 / (4 * d) ≤ 1 - γ * t + γ ^ 2 * d := by
      -- By multiplying both sides of the inequality by $4d$, we can eliminate the denominator and simplify the expression.
      have h_mul : -t^2 ≤ -4 * d * γ * t + 4 * d^2 * γ^2 := by
        -- By completing the square, we can rewrite the inequality as $(t - 2d\gamma)^2 \geq 0$, which is always true.
        have h_complete_square : (t - 2 * d * γ) ^ 2 ≥ 0 := by
          -- The square of any real number is non-negative.
          apply sq_nonneg
        linarith [h_complete_square]
      generalize_proofs at *; (
      -- By dividing both sides of the inequality by $4d$, we can eliminate the denominator and simplify the expression.
      field_simp [hd] at *; linarith [h_mul])

theorem k2_D_quadratic_min_achieved (t d : ℝ) (hd : 0 < d) :
    1 - (t / (2 * d)) * t + (t / (2 * d)) ^ 2 * d = 1 - t ^ 2 / (4 * d) := by
  field_simp
  ring

theorem k2_D_product_min (t₁ t₂ d₁ d₂ γ₁ γ₂ : ℝ)
    (hd₁ : 0 < d₁) (hd₂ : 0 < d₂)
    (hD₁_pos : 0 ≤ 1 - γ₁ * t₁ + γ₁ ^ 2 * d₁)
    (hD₂_pos : 0 ≤ 1 - γ₂ * t₂ + γ₂ ^ 2 * d₂)
    (hD₁min_pos : 0 ≤ 1 - t₁ ^ 2 / (4 * d₁))
    (hD₂min_pos : 0 ≤ 1 - t₂ ^ 2 / (4 * d₂)) :
    (1 - t₁ ^ 2 / (4 * d₁)) * (1 - t₂ ^ 2 / (4 * d₂)) ≤
    (1 - γ₁ * t₁ + γ₁ ^ 2 * d₁) * (1 - γ₂ * t₂ + γ₂ ^ 2 * d₂) := by
  apply mul_le_mul
  · exact k2_D_quadratic_min t₁ d₁ γ₁ hd₁
  · exact k2_D_quadratic_min t₂ d₂ γ₂ hd₂
  · exact hD₂min_pos
  · linarith [k2_D_quadratic_min t₁ d₁ γ₁ hd₁]

theorem k2_complex_opt_rho (t₁ t₂ d₁ d₂ γ₁ γ₂ : ℝ)
    (hd₁ : 0 < d₁) (hd₂ : 0 < d₂)
    (hD₁_pos : 0 ≤ 1 - γ₁ * t₁ + γ₁ ^ 2 * d₁)
    (hD₂_pos : 0 ≤ 1 - γ₂ * t₂ + γ₂ ^ 2 * d₂)
    (hD₁min_pos : 0 ≤ 1 - t₁ ^ 2 / (4 * d₁))
    (hD₂min_pos : 0 ≤ 1 - t₂ ^ 2 / (4 * d₂)) :
    Real.sqrt ((1 - t₁ ^ 2 / (4 * d₁)) * (1 - t₂ ^ 2 / (4 * d₂))) ≤
    Real.sqrt ((1 - γ₁ * t₁ + γ₁ ^ 2 * d₁) * (1 - γ₂ * t₂ + γ₂ ^ 2 * d₂)) := by
  apply Real.sqrt_le_sqrt
  exact k2_D_product_min t₁ t₂ d₁ d₂ γ₁ γ₂ hd₁ hd₂
    hD₁_pos hD₂_pos hD₁min_pos hD₂min_pos

theorem k2_real_regime_min_at_boundary (T D : ℝ) (hT : 0 ≤ T)
    (hreal : 4 * D < T ^ 2) :
    T / 2 < (T + Real.sqrt (T ^ 2 - 4 * D)) / 2 := by
  have hsqrt_pos : 0 < Real.sqrt (T ^ 2 - 4 * D) := by
    apply Real.sqrt_pos_of_pos
    linarith
  linarith

theorem k2_real_rho_eq_half_iff (T D : ℝ) (hT : 0 ≤ T) (hreal : 4 * D ≤ T ^ 2) :
    (T + Real.sqrt (T ^ 2 - 4 * D)) / 2 = T / 2 ↔ T ^ 2 = 4 * D := by
  constructor
  · intro h
    have hsq : Real.sqrt (T ^ 2 - 4 * D) = 0 := by linarith
    rw [Real.sqrt_eq_zero'] at hsq
    linarith
  · intro h
    rw [show T ^ 2 - 4 * D = 0 by linarith, Real.sqrt_zero]
    ring

theorem k2_master_optimality (T D : ℝ) (hT : 0 ≤ T) (hD : 0 ≤ D) :
    -- In real regime: ρ ≥ T/2
    (4 * D ≤ T ^ 2 → T / 2 ≤ (T + Real.sqrt (T ^ 2 - 4 * D)) / 2) ∧
    -- In complex regime: ρ ≥ T/2
    (T ^ 2 < 4 * D → T / 2 ≤ Real.sqrt D) ∧
    -- Boundary value: T/2 is achieved
    (T + Real.sqrt (T ^ 2 - 4 * (T ^ 2 / 4))) / 2 = T / 2 := by
      -- By combining the results from the two cases, we can conclude the proof.
      apply And.intro;
      · -- By simplifying, we can see that this inequality holds because the square root function is non-negative.
        intros hD_le
        linarith [Real.sqrt_nonneg (T^2 - 4 * D)];
      · -- For the first part, if $T^2 < 4D$, then $D > T^2 / 4$, so $\sqrt{D} > T / 2$.
        apply And.intro
        intro h
        have h_sqrt : Real.sqrt D > T / 2 := by
          exact Real.lt_sqrt_of_sq_lt ( by linarith )
        linarith
        -- For the second part, simplify the expression inside the square root.
        field_simp [mul_comm, mul_assoc, mul_left_comm];
        -- Simplify the expression inside the square root: $T^2 * (1 - 1) = T^2 * 0 = 0$.
        simp [mul_zero, sub_self]

theorem k2_rho_geq_half_trace (T D : ℝ) (hT : 0 ≤ T) (hD : 0 ≤ D) :
    (if T ^ 2 ≤ 4 * D then Real.sqrt D else (T + Real.sqrt (T ^ 2 - 4 * D)) / 2)
    ≥ T / 2 := by
  exact k2_unified_lb T D hT hD

theorem k2_complex_global_opt (t₁ t₂ d₁ d₂ γ₁ γ₂ : ℝ)
    (hd₁ : 0 < d₁) (hd₂ : 0 < d₂)
    (hD₁_pos : 0 ≤ 1 - γ₁ * t₁ + γ₁ ^ 2 * d₁)
    (hD₂_pos : 0 ≤ 1 - γ₂ * t₂ + γ₂ ^ 2 * d₂)
    (hD₁min_pos : 0 ≤ 1 - t₁ ^ 2 / (4 * d₁))
    (hD₂min_pos : 0 ≤ 1 - t₂ ^ 2 / (4 * d₂)) :
    -- ρ at optimal γ* ≤ ρ at any other γ
    Real.sqrt ((1 - t₁ ^ 2 / (4 * d₁)) * (1 - t₂ ^ 2 / (4 * d₂))) ≤
    Real.sqrt ((1 - γ₁ * t₁ + γ₁ ^ 2 * d₁) * (1 - γ₂ * t₂ + γ₂ ^ 2 * d₂)) :=
  k2_complex_opt_rho t₁ t₂ d₁ d₂ γ₁ γ₂ hd₁ hd₂
    hD₁_pos hD₂_pos hD₁min_pos hD₂min_pos

theorem k2_real_boundary_min (T D : ℝ) (hT : 0 ≤ T)
    (hinterior : 4 * D < T ^ 2) :
    T / 2 < (T + Real.sqrt (T ^ 2 - 4 * D)) / 2 :=
  k2_real_regime_min_at_boundary T D hT hinterior

theorem k2_global_optimality (T D : ℝ) (hT : 0 ≤ T) (hD : 0 ≤ D) :
    -- Lower bound holds universally
    T / 2 ≤ (if T ^ 2 ≤ 4 * D then Real.sqrt D
             else (T + Real.sqrt (T ^ 2 - 4 * D)) / 2) ∧
    -- Boundary value achieves T/2 (real regime formula at D=T²/4)
    (T + Real.sqrt (T ^ 2 - 4 * (T ^ 2 / 4))) / 2 = T / 2 ∧
    -- Boundary value achieves T/2 (complex regime formula at D=T²/4)
    Real.sqrt (T ^ 2 / 4) = T / 2 := by
  refine ⟨k2_unified_lb T D hT hD, ?_, ?_⟩
  · -- Real regime at boundary
    have : T ^ 2 - 4 * (T ^ 2 / 4) = 0 := by ring
    simp [this, Real.sqrt_zero]
  · -- Complex regime at boundary: √(T²/4) = T/2
    rw [show T ^ 2 / 4 = (T / 2) ^ 2 by ring]
    exact Real.sqrt_sq (by linarith)

theorem k2_rho_real_approaches_half_trace (T D : ℝ) (hT : 0 ≤ T) (hD : 0 ≤ D)
    (hreal : 4 * D ≤ T ^ 2) :
    (T + Real.sqrt (T ^ 2 - 4 * D)) / 2 ≤ (T + Real.sqrt (T ^ 2)) / 2 := by
  have h1 : T ^ 2 - 4 * D ≤ T ^ 2 := by linarith
  have h2 : 0 ≤ T ^ 2 - 4 * D := by linarith
  have hsq : Real.sqrt (T ^ 2 - 4 * D) ≤ Real.sqrt (T ^ 2) :=
    Real.sqrt_le_sqrt h1
  linarith