/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 21509db5-2b5c-4836-8eee-87dfae2800db

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>

Aristotle's budget for this request has been reached.
If there is partial progress, it will appear in this file.
If you would like to continue working off of this partial progress,
please submit the same prompt, and add this .lean file in "Optional: Attach a Lean file as context" field.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

/-
Definitions of Finset.argmax and Matrix.eigenvalues.
-/
variable {d : Type} [Fintype d] [DecidableEq d] [Nonempty d]

def Finset.argmax {α β : Type*} [LinearOrder β] [DecidableEq α] (f : α → β) (s : Finset α) : Option α := s.toList.argmax f

noncomputable def Matrix.eigenvalues {n : Type*} [Fintype n] [DecidableEq n] (A : Matrix n n ℝ) : n → ℝ :=
  if h : A.IsHermitian then h.eigenvalues else 0

/-
Definition of SimultDiag as an existential proposition.
-/
variable {d : Type} [Fintype d] [DecidableEq d] [Nonempty d]

def SimultDiag (K : ℕ) (S : Fin K → Matrix d d ℝ) : Prop :=
  ∃ U : Matrix d d ℝ, U * U.transpose = 1 ∧ ∀ k, U.transpose * S k * U = Matrix.diagonal ((S k).eigenvalues)

/-
Definition of greedyStepsize.
-/
variable {d : Type} [Fintype d] [DecidableEq d] [Nonempty d]

noncomputable def greedyStepsize {K : ℕ} (lam : Fin K → d → ℝ) (g : Fin K → ℝ) (k : Fin K) : ℝ :=
  let obj (j : d) := ∏ i ∈ Finset.univ.filter (· < k), |1 - g i * lam i j|
  let j_opt := Finset.argmax (fun j => obj j * |lam k j|) Finset.univ
  match j_opt with
  | some j => 1 / lam k j
  | none => 0

#check measure
#check WellFounded.fix

/-
Definitions of g_opt_fn, A, M_cyc, and inNF.
-/
noncomputable def g_opt_fn (K : ℕ) (S : Fin K → Matrix d d ℝ) : Fin K → ℝ :=
  WellFounded.fix (measure Fin.val).wf fun k ih =>
    greedyStepsize (fun i j => (S i).eigenvalues j) (fun i => if h : i.val < k.val then ih i h else 0) k

def A {K : ℕ} (S : Fin K → Matrix d d ℝ) (g : Fin K → ℝ) (k : Fin K) : Matrix d d ℝ :=
  1 - g k • S k

def M_cyc {K : ℕ} (S : Fin K → Matrix d d ℝ) (g : Fin K → ℝ) : Matrix d d ℝ :=
  (List.finRange K).foldr (fun k M => (A S g k) * M) 1

def inNF {K : ℕ} (S : Fin K → Matrix d d ℝ) (g : Fin K → ℝ) : Prop :=
  ∀ i j : Fin K, i < j → Commute (A S g i) (A S g j)

/-
Definition of Matrix.spectralRadius as the maximum absolute eigenvalue (assuming symmetric matrices).
-/
variable {d : Type} [Fintype d] [DecidableEq d] [Nonempty d]

noncomputable def Matrix.spectralRadius (A : Matrix d d ℝ) : ℝ :=
  Finset.univ.sup' Finset.univ_nonempty (fun i => |Matrix.eigenvalues A i|)

/-
Lemma: Product of commuting Hermitian matrices is Hermitian.
-/
lemma Matrix.IsHermitian.mul_of_commute {n} [Fintype n] [DecidableEq n] {A B : Matrix n n ℝ}
    (hA : A.IsHermitian) (hB : B.IsHermitian) (hComm : Commute A B) :
    (A * B).IsHermitian := by
      exact?

/-
Definition of SimultDiagOne.
-/
variable {n : Type*} [Fintype n] [DecidableEq n] [Nonempty n]

def SimultDiagOne (U : Matrix n n ℝ) (A : Matrix n n ℝ) : Prop :=
  U * U.transpose = 1 ∧ ∃ d : n → ℝ, U.transpose * A * U = Matrix.diagonal d

#check Finset.univ_nonempty

#check Finset.sup'
#check Finset.univ_nonempty

/-
Test lemma to check if Finset.sup' works with Finset.univ_nonempty.
-/
lemma test_sup_univ {n : Type} [Fintype n] [Nonempty n] (f : n → ℝ) :
  Finset.univ.sup' Finset.univ_nonempty f = Finset.univ.sup' Finset.univ_nonempty f := rfl

/-
Lemma: If A is simultaneously diagonalizable with the identity (i.e. by a unitary matrix), then A is Hermitian.
-/
lemma isHermitian_of_SimultDiagOne {n : Type} [Fintype n] [DecidableEq n]
    {U A : Matrix n n ℝ} (h : SimultDiagOne U A) :
    A.IsHermitian := by
      obtain ⟨ h₁, d, h₂ ⟩ := h;
      -- Since $U$ is unitary, we have $A = U * (U.transpose * A * U) * U.transpose$.
      have hA : A = U * (U.transpose * A * U) * U.transpose := by
        simp +decide [ ← mul_assoc, h₁ ];
        rw [ mul_assoc, h₁, mul_one ];
      rw [ hA, h₂ ];
      simp +decide [ Matrix.IsHermitian, Matrix.mul_assoc ]

/-
Test definition to check if Finset.sup' works.
-/
def my_sup (n : Type*) [Fintype n] [Nonempty n] (f : n → ℝ) : ℝ :=
  Finset.univ.sup' Finset.univ_nonempty f

/-
Test lemma for Finset.sup' with explicit types.
-/
lemma test_sup_univ_explicit {n : Type} [Fintype n] [Nonempty n] (f : n → ℝ) :
  Finset.sup' (Finset.univ : Finset n) Finset.univ_nonempty f = Finset.sup' Finset.univ Finset.univ_nonempty f := rfl

/-
Lemma: The range of eigenvalues of a diagonal matrix is the range of its diagonal entries.
-/
lemma range_eigenvalues_diagonal {n : Type*} [Fintype n] [DecidableEq n] (d : n → ℝ) :
    Set.range (Matrix.eigenvalues (Matrix.diagonal d)) = Set.range d := by
      unfold Matrix.eigenvalues;
      split_ifs with h <;> simp_all +decide [ Matrix.IsHermitian, Set.range_eq_iff ];
      have := Matrix.IsHermitian.spectral_theorem h;
      -- By multiplying both sides of the equation by the inverse of the eigenvector unitary matrix, we can isolate the diagonal matrix of eigenvalues.
      have h_isolate : Matrix.diagonal (RCLike.ofReal ∘ h.eigenvalues) = (h.eigenvectorUnitary : Matrix n n ℝ)⁻¹ * Matrix.diagonal d * (h.eigenvectorUnitary : Matrix n n ℝ) := by
        rw [ Matrix.inv_eq_left_inv ];
        any_goals exact star ( h.eigenvectorUnitary : Matrix n n ℝ );
        · replace this := congr_arg ( fun m => Star.star ( h.eigenvectorUnitary : Matrix n n ℝ ) * m * ( h.eigenvectorUnitary : Matrix n n ℝ ) ) this ; simp +decide [ Matrix.mul_assoc ] at this ⊢;
          simp_all +decide [ ← Matrix.mul_assoc, Matrix.mul_eq_one_comm ];
        · simp +decide [ Matrix.mul_eq_one_comm ];
      -- Since the diagonal matrix of eigenvalues is similar to the diagonal matrix of d, their eigenvalues must be the same.
      have h_similar : Matrix.charpoly (Matrix.diagonal (RCLike.ofReal ∘ h.eigenvalues)) = Matrix.charpoly (Matrix.diagonal d) := by
        have h_similar : ∀ (A B : Matrix n n ℝ), Invertible A → Matrix.charpoly (A⁻¹ * B * A) = Matrix.charpoly B := by
          intro A B hA
          simp [Matrix.charpoly];
          simp +decide [ Matrix.charmatrix, mul_assoc ];
          -- Since $A$ is invertible, we can simplify the expression for the determinant.
          have h_det_simplify : Matrix.det (Matrix.diagonal (fun _ => Polynomial.X) - A⁻¹.map (⇑Polynomial.C) * (B.map (⇑Polynomial.C) * A.map (⇑Polynomial.C))) = Matrix.det (A⁻¹.map (⇑Polynomial.C) * (Matrix.diagonal (fun _ => Polynomial.X) - B.map (⇑Polynomial.C)) * A.map (⇑Polynomial.C)) := by
            simp +decide [ mul_sub, sub_mul, mul_assoc ];
            simp +decide [ ← mul_assoc, ← Matrix.smul_eq_diagonal_mul ];
            simp +decide [ ← Matrix.map_mul, hA.2 ];
            exact congr_arg Matrix.det ( by ext i j; by_cases hi : i = j <;> simp +decide [ hi ] );
          rw [ h_det_simplify, Matrix.det_mul, Matrix.det_mul ];
          rw [ mul_right_comm, ← Matrix.det_mul ];
          simp +decide [ ← Matrix.map_mul, hA.2 ];
        rw [ h_isolate, h_similar ];
        refine' ⟨ _, _, _ ⟩;
        exact star ( h.eigenvectorUnitary : Matrix n n ℝ );
        · simp +decide [ Matrix.mul_eq_one_comm ];
        · simp +decide [ Matrix.mul_eq_one_comm ];
      simp +decide [ Matrix.charpoly, Matrix.det_diagonal ] at h_similar;
      have h_roots : Multiset.map (fun i => h.eigenvalues i) (Multiset.ofList (Finset.toList Finset.univ)) = Multiset.map (fun i => d i) (Multiset.ofList (Finset.toList Finset.univ)) := by
        apply_fun Polynomial.roots at h_similar;
        rw [ Polynomial.roots_prod, Polynomial.roots_prod ] at h_similar <;> norm_num at *;
        · exact h_similar;
        · exact Finset.prod_ne_zero_iff.mpr fun i _ => Polynomial.X_sub_C_ne_zero _;
        · exact Finset.prod_ne_zero_iff.mpr fun i _ => Polynomial.X_sub_C_ne_zero _;
      constructor <;> intro a <;> replace h_roots := congr_arg Multiset.toFinset h_roots <;> rw [ Finset.ext_iff ] at h_roots <;> specialize h_roots ( h.eigenvalues a ) <;> simp +decide at h_roots ⊢;
      · exact h_roots;
      · replace h_similar := congr_arg ( Polynomial.eval ( d a ) ) h_similar ; simp +decide [ Finset.prod_eq_prod_diff_singleton_mul ( Finset.mem_univ a ) ] at h_similar;
        simp +decide [ Polynomial.eval_prod, Finset.prod_eq_zero_iff, sub_eq_zero ] at h_similar;
        exact h_similar.elim ( fun ⟨ b, hb, hb' ⟩ => ⟨ b, hb'.symm ⟩ ) fun hb => ⟨ a, hb.symm ⟩

/-
Check if Finset.univ_nonempty works.
-/
lemma check_univ_nonempty {n : Type*} [Fintype n] [Nonempty n] : (Finset.univ : Finset n).Nonempty :=
  Finset.univ_nonempty

#check @Matrix.spectralRadius

/-
Lemma: If two functions have the same range, their supremums over the universe are equal.
-/
lemma sup'_eq_of_range_eq {ι1 ι2 : Type*} [Fintype ι1] [Fintype ι2] [Nonempty ι1] [Nonempty ι2]
    (f : ι1 → ℝ) (g : ι2 → ℝ) (h : Set.range f = Set.range g) :
    Finset.univ.sup' Finset.univ_nonempty f = Finset.univ.sup' Finset.univ_nonempty g := by
  rw [Finset.sup'_eq_csSup_image, Finset.sup'_eq_csSup_image]
  congr
  simp only [Finset.coe_univ, Set.image_univ]
  exact h

/-
Lemma: The spectral radius of a diagonal matrix is the maximum absolute value of its diagonal entries (fixed universe levels).
-/
lemma spectralRadius_diagonal {n : Type} [Fintype n] [DecidableEq n] [hn : Nonempty n] (d : n → ℝ) :
    @Matrix.spectralRadius n _ _ hn (Matrix.diagonal d) = Finset.sup' Finset.univ (@Finset.univ_nonempty n _ hn) (fun i => |d i|) := by
      convert sup'_eq_of_range_eq _ _ _;
      · exact hn;
      · exact hn;
      · convert Set.ext _;
        convert range_eigenvalues_diagonal d using 1;
        constructor <;> intro h <;> simp_all +decide [ Set.ext_iff ];
        · convert range_eigenvalues_diagonal d using 1;
          simp +decide [ Set.ext_iff ];
        · intro x; exact ⟨fun ⟨y, hy⟩ => by obtain ⟨z, hz⟩ := h (Matrix.diagonal d |> Matrix.eigenvalues |> fun f => f y) |>.1 ⟨y, rfl⟩; exact ⟨z, by aesop⟩, fun ⟨y, hy⟩ => by obtain ⟨z, hz⟩ := h (d y) |>.2 ⟨y, rfl⟩; exact ⟨z, by aesop⟩⟩

/-
Lemma: Spectral radius is invariant under unitary similarity.
-/
lemma spectralRadius_eq_of_unitary_similarity {n : Type} [Fintype n] [DecidableEq n] [Nonempty n]
    (A : Matrix n n ℝ) (U : Matrix n n ℝ) (hU : U * U.transpose = 1) :
    Matrix.spectralRadius (U.transpose * A * U) = Matrix.spectralRadius A := by
      have h_eigenvalues : ∀ (M : Matrix n n ℝ), M.IsHermitian → Matrix.IsHermitian (U.transpose * M * U) := by
        simp +contextual [ Matrix.IsHermitian, Matrix.mul_assoc ];
      have h_eigenvalues : ∀ (M : Matrix n n ℝ), M.IsHermitian → Set.range (Matrix.eigenvalues (U.transpose * M * U)) = Set.range (Matrix.eigenvalues M) := by
        intro M hM
        have h_eigenvalues : Matrix.IsHermitian (U.transpose * M * U) := h_eigenvalues M hM
        have h_eigenvalues_eq : Matrix.charpoly (U.transpose * M * U) = Matrix.charpoly M := by
          rw [ Matrix.charpoly, Matrix.charpoly ];
          simp +decide [ Matrix.charmatrix, Matrix.det_mul, hU ];
          -- Since $U$ is unitary, we have $U^T U = I$, and thus $(U^T M U)^T = U^T M^T U = U^T M U$.
          have h_unitary : (U.transpose.map (⇑Polynomial.C)) * (U.map (⇑Polynomial.C)) = 1 := by
            simp_all +decide [ ← Matrix.map_mul ];
            rw [ Matrix.mul_eq_one_comm.mp hU ] ; aesop;
          have h_det : Matrix.det (Matrix.diagonal (fun _ => Polynomial.X) - U.transpose.map (⇑Polynomial.C) * M.map (⇑Polynomial.C) * U.map (⇑Polynomial.C)) = Matrix.det (U.transpose.map (⇑Polynomial.C) * (Matrix.diagonal (fun _ => Polynomial.X) - M.map (⇑Polynomial.C)) * U.map (⇑Polynomial.C)) := by
            simp +decide [ mul_sub, sub_mul, mul_assoc, h_unitary ];
            simp +decide [ ← mul_assoc, ← Matrix.smul_eq_diagonal_mul ];
            rw [ h_unitary, Matrix.smul_one_eq_diagonal ];
          rw [ h_det, Matrix.det_mul, Matrix.det_mul ];
          rw [ mul_right_comm, ← Matrix.det_mul, h_unitary, Matrix.det_one, one_mul ]
        have h_eigenvalues_eq : Matrix.eigenvalues (U.transpose * M * U) = Matrix.eigenvalues M := by
          rw [ Matrix.eigenvalues, Matrix.eigenvalues ];
          simp_all +decide [ Matrix.IsHermitian.eigenvalues ];
          exact?
        aesop;
      have h_eigenvalues : ∀ (M : Matrix n n ℝ), Matrix.IsHermitian (U.transpose * M * U) → Matrix.IsHermitian M := by
        simp_all +decide [ Matrix.IsHermitian, ← Matrix.mul_assoc ];
        intro M hM; apply_fun fun x => U * x * U.transpose at hM; simp_all +decide [ Matrix.mul_assoc, isUnit_iff_ne_zero ] ;
        simp_all +decide [ ← Matrix.mul_assoc ];
      by_cases hA : Matrix.IsHermitian A <;> simp_all +decide [ Matrix.spectralRadius ];
      · apply sup'_eq_of_range_eq;
        simp_all +decide [ Set.range_eq_iff ];
        exact ⟨ fun a => by obtain ⟨ y, hy ⟩ := ‹∀ M : Matrix n n ℝ, M.IsHermitian → ( ∀ a : n, ∃ y : n, M.eigenvalues y = ( U.transpose * M * U ).eigenvalues a ) ∧ ∀ a : n, ∃ a_1 : n, ( U.transpose * M * U ).eigenvalues a_1 = M.eigenvalues a› A hA |>.1 a; exact ⟨ y, by rw [ hy ] ⟩, fun a => by obtain ⟨ y, hy ⟩ := ‹∀ M : Matrix n n ℝ, M.IsHermitian → ( ∀ a : n, ∃ y : n, M.eigenvalues y = ( U.transpose * M * U ).eigenvalues a ) ∧ ∀ a : n, ∃ a_1 : n, ( U.transpose * M * U ).eigenvalues a_1 = M.eigenvalues a› A hA |>.2 a; exact ⟨ y, by rw [ hy ] ⟩ ⟩;
      · simp_all +decide [ Matrix.IsHermitian, Matrix.eigenvalues ];
        split_ifs <;> simp_all +decide [ Matrix.mul_assoc ]

/-
Lemma: If A and B are simultaneously diagonalizable by a unitary matrix U, then spectralRadius (A * B) ≤ spectralRadius A * spectralRadius B.
-/
lemma spectralRadius_mul_le_of_SimultDiagOne {n : Type} [Fintype n] [DecidableEq n] [hn : Nonempty n]
    {U A B : Matrix n n ℝ} (hA : SimultDiagOne U A) (hB : SimultDiagOne U B) :
    @Matrix.spectralRadius n _ _ hn (A * B) ≤ @Matrix.spectralRadius n _ _ hn A * @Matrix.spectralRadius n _ _ hn B := by
      have h_diag : ∃ D_A D_B : n → ℝ, U.transpose * A * U = Matrix.diagonal D_A ∧ U.transpose * B * U = Matrix.diagonal D_B := by
        cases hA ; cases hB ; aesop;
      obtain ⟨ D_A, D_B, hA, hB ⟩ := h_diag
      have h_prod : U.transpose * (A * B) * U = Matrix.diagonal (fun i => D_A i * D_B i) := by
        convert congr_arg₂ ( fun x y => x * y ) hA hB using 1 <;> simp +decide [ ← mul_assoc ];
        have := ‹SimultDiagOne U A›.1; simp_all +decide [ ← Matrix.mul_assoc ] ;
        simp +decide [ ← hA, ← hB, mul_assoc, this ]
      have h_spectral_radius : Matrix.spectralRadius (A * B) = Matrix.spectralRadius (U.transpose * (A * B) * U) := by
        apply Eq.symm; exact (by
          have := ‹SimultDiagOne U A›.1;
          exact (by
          exact?));
      have h_spectral_radius : Matrix.spectralRadius (U.transpose * (A * B) * U) = Finset.sup' Finset.univ Finset.univ_nonempty (fun i => |D_A i * D_B i|) := by
        rw [ h_prod, spectralRadius_diagonal ]
      have h_spectral_radius_A : Matrix.spectralRadius A = Finset.sup' Finset.univ Finset.univ_nonempty (fun i => |D_A i|) := by
        have h_spectral_radius_A : Matrix.spectralRadius A = Matrix.spectralRadius (U.transpose * A * U) := by
          apply Eq.symm; exact (by
          apply spectralRadius_eq_of_unitary_similarity;
          cases ‹SimultDiagOne U A› ; aesop)
        rw [h_spectral_radius_A] at *; simp_all +decide [ Matrix.spectralRadius ] ;
        convert spectralRadius_diagonal D_A using 1
      have h_spectral_radius_B : Matrix.spectralRadius B = Finset.sup' Finset.univ Finset.univ_nonempty (fun i => |D_B i|) := by
        convert spectralRadius_diagonal D_B using 1;
        rw [ ← hB ];
        rw [ spectralRadius_eq_of_unitary_similarity ];
        cases ‹SimultDiagOne U B› ; aesop
      simp_all +decide [ Finset.sup'_le_iff ];
      exact fun i => mul_le_mul ( Finset.le_sup' ( fun i => |D_A i| ) ( Finset.mem_univ i ) ) ( Finset.le_sup' ( fun i => |D_B i| ) ( Finset.mem_univ i ) ) ( by positivity ) ( by exact Finset.le_sup' ( fun i => |D_A i| ) ( Finset.mem_univ i ) |> le_trans ( by positivity ) )

/-
Lemma: The greedy step size choice ensures that the maximum weighted product does not increase.
-/
lemma greedy_step_decrease {n : Type} [Fintype n] [DecidableEq n] [Nonempty n]
    (p : n → ℝ) (lam : n → ℝ) (hp : ∀ i, 0 ≤ p i) (hlam : ∀ i, 0 ≤ lam i) :
    let j_opt := Finset.argmax (fun j => p j * lam j) Finset.univ
    let g := match j_opt with | some j => 1 / lam j | none => 0
    let p' := fun i => p i * |1 - g * lam i|
    Finset.univ.sup' Finset.univ_nonempty p' ≤ Finset.univ.sup' Finset.univ_nonempty p := by
      -- Let's simplify the goal using the definition of `j_opt` and `g`.
      simp [Finset.argmax] at *;
      cases h : List.argmax ( fun j => p j * lam j ) Finset.univ.toList <;> simp_all +decide [ ne_of_gt ];
      rw [ List.argmax_eq_some_iff ] at h;
      by_cases h : lam ‹_› = 0 <;> simp_all +decide [ abs_of_nonneg, mul_nonneg, hp, hlam ];
      · exact?;
      · rename_i i hi;
        field_simp;
        -- Let $b$ be the index that maximizes $p_j$.
        obtain ⟨b, hb⟩ : ∃ b, ∀ j, p j ≤ p b := by
          simpa using Finset.exists_max_image Finset.univ p ( Finset.univ_nonempty );
        use b;
        intro j; rw [ abs_div ] ; rw [ abs_of_nonneg ( hlam i ) ] ; rw [ mul_div ] ; rw [ div_le_iff₀ ( lt_of_le_of_ne ( hlam i ) ( Ne.symm h ) ) ] ; cases abs_cases ( lam i - lam j ) <;> nlinarith [ hb j, hb i, hp j, hp i, hlam j, hlam i, hi.1 j, hi.1 i ] ;

/-
Counterexample matrix S.
-/
def S_counter : Fin 1 → Matrix (Fin 2) (Fin 2) ℝ := fun _ => Matrix.diagonal ![1, 2]

/-
Corrected definition of theorem_L_statement.
-/
def theorem_L_statement : Prop :=
  ∀ (K : ℕ) (hK : 1 ≤ K) (S : Fin K → Matrix (Fin 2) (Fin 2) ℝ)
    (hPD : ∀ i, (S i).PosDef) (hSD : SimultDiag K S)
    (hND : ∀ k : Fin K, ∃! j : Fin 2,
      j = (Finset.argmax (fun j =>
        (∏ i ∈ Finset.univ.filter (fun (i : Fin K) => i < k),
          abs (1 - g_opt_fn K S i * (S i).eigenvalues j)) *
               abs ((S k).eigenvalues j)) Finset.univ).getD j),
    let g_opt := g_opt_fn K S
    inNF S g_opt ∧
    ∀ g : Fin K → ℝ, inNF S g →
      (M_cyc S g_opt).spectralRadius ≤
      (M_cyc S g).spectralRadius

/-
Lemma: The range of eigenvalues of the counterexample matrix is {1, 2}.
-/
lemma S_counter_eigenvalues_range : Set.range (S_counter 0).eigenvalues = {1, 2} := by
  convert range_eigenvalues_diagonal _ ; aesop;
  infer_instance

/-
Lemma: The optimal step size for the counterexample is 0.5.
-/
lemma g_opt_counter_val : g_opt_fn 1 S_counter 0 = 1/2 := by
  -- Apply the lemma that states the range of eigenvalues of the counterexample matrix is {1, 2}.
  have h_range : Set.range (S_counter 0).eigenvalues = {1, 2} := by
    exact?;
  rw [ Set.range_eq_iff ] at h_range;
  rcases h_range.2 1 ( by norm_num ) with ⟨ i, hi ⟩ ; rcases h_range.2 2 ( by norm_num ) with ⟨ j, hj ⟩ ; fin_cases i <;> fin_cases j <;> simp_all +decide;
  · convert congr_arg ( fun x : ℝ => 1 / x ) hj using 1;
    · unfold g_opt_fn;
      unfold greedyStepsize; norm_num [ Finset.argmax ] ;
      rw [ WellFounded.fix_eq ] ; norm_num [ Fin.univ_succ ];
      rw [ List.argmax_eq_some_iff.mpr ] ; norm_num [ hi, hj ];
    · norm_num;
  · unfold g_opt_fn;
    unfold greedyStepsize; norm_num [ Fin.univ_succ ] ;
    erw [ WellFounded.fix_eq ] ; norm_num [ Finset.argmax, hi, hj ];
    rcases h : ( { 0, 1 } : Finset ( Fin 2 ) ).toList with _ | ⟨ a, _ | ⟨ b, _ | h ⟩ ⟩ ; aesop;
    · have := congr_arg List.length h; norm_num at this;
    · fin_cases a <;> fin_cases b <;> simp_all +decide [ List.argmax_cons ];
      have := congr_arg List.toFinset h; norm_num [ Finset.ext_iff ] at this;
    · have := congr_arg List.length h; simp +decide at this;