/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 292bc4d5-a79e-42f1-a8a3-765d5e250a6f

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
We have formally disproven all three claims of Conjecture F (Commutative Case).

For Claim 1 (Base case), we constructed a counterexample with d=2, K=1, and Σ₁ = diag(1, 2). The proposed stepsize γ₁ = 1/λ_max(Σ₁) = 1/2 yields a spectral radius of ρ(I - 0.5*Σ₁) = 0.5. However, a stepsize of γ = 0.6 yields ρ(I - 0.6*Σ₁) = 0.4, which is strictly smaller. Thus, the proposed stepsize does not minimise the spectral radius. This is proven in `claim1_disproof_v2`.

For Claim 2 (Recursive formula is well-defined), we constructed two setups with d=2, K=2. Both have Σ₁ = Σ₂ = I, but one has U = I and the other has U = U_rot (rotation by 45 degrees). Since Σ matrices are identity, M₁ = 0 in both cases, so the dominant eigenvector v(M₁) is the same (arbitrary unit vector). However, v cannot be a column of both I and U_rot simultaneously, as their columns are disjoint. Thus, the claim that v is a column of U fails for at least one setup. This is proven in `claim2_disproof`.

For Claim 3 (Recursion minimises spectral radius), since Claim 1 is a special case of Claim 3 (with K=1), the counterexample for Claim 1 also disproves Claim 3. This is proven in `claim3_disproof`.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

/-
Definitions of the problem setup and the algorithm.
-/
open Matrix BigOperators

variable {d K : ℕ}

/-- The spectral radius of a real matrix as a real number. -/
noncomputable def matrixSpectralRadius (A : Matrix (Fin d) (Fin d) ℝ) : ℝ :=
  (spectralRadius ℝ A).toReal

/-- The dominant eigenvector of a matrix A.
    We select a unit eigenvector corresponding to an eigenvalue with modulus equal to the spectral radius. -/
noncomputable def dominantEigenvector (A : Matrix (Fin d) (Fin d) ℝ) : Fin d → ℝ :=
  if h : ∃ v : Fin d → ℝ, ‖v‖ = 1 ∧ ∃ (μ : ℝ), |μ| = matrixSpectralRadius A ∧ A.mulVec v = μ • v
  then Classical.choose h
  else 0

/-- The update operator A_i. -/
def updateOp (S : Matrix (Fin d) (Fin d) ℝ) (γ : ℝ) : Matrix (Fin d) (Fin d) ℝ :=
  1 - γ • S

/-- The setup for the commutative case. -/
structure CommutativeCase (d K : ℕ) where
  Sigmas : Fin K → Matrix (Fin d) (Fin d) ℝ
  U : Matrix (Fin d) (Fin d) ℝ
  Lambdas : Fin K → Fin d → ℝ
  h_orth : U * U.transpose = 1 ∧ U.transpose * U = 1
  h_diag : ∀ i, Sigmas i = U * diagonal (Lambdas i) * U.transpose
  h_pos : ∀ i j, 0 < Lambdas i j

variable (setup : CommutativeCase d K)

/-- The algorithm step. -/
noncomputable def algorithmStep (k : ℕ) (M_prev : Matrix (Fin d) (Fin d) ℝ) : ℝ × Matrix (Fin d) (Fin d) ℝ :=
  if h : k < K then
    let S := setup.Sigmas ⟨k, h⟩
    let γ := if k = 0 then
               1 / matrixSpectralRadius S
             else
               let v := dominantEigenvector M_prev
               1 / (dotProduct v (S.mulVec v))
    let A := updateOp S γ
    (γ, A * M_prev)
  else
    (0, M_prev)

/-- The full run of the algorithm. Returns the sequence of (γ, M). -/
noncomputable def runAlgorithm : ℕ → ℝ × Matrix (Fin d) (Fin d) ℝ
| 0 => (0, 1)
| k + 1 => algorithmStep setup k (runAlgorithm k).2

/-- Helper to access the k-th M (M_k). -/
noncomputable def M (k : ℕ) : Matrix (Fin d) (Fin d) ℝ := (runAlgorithm setup k).2

/-- Helper to access the k-th γ (γ_k). -/
noncomputable def gamma (k : ℕ) : ℝ := (runAlgorithm setup k).1

/-
Lemma: The spectral radius of a diagonal matrix is the supremum of the absolute values of its diagonal entries.
-/
open Matrix BigOperators

lemma matrixSpectralRadius_diagonal {n : Type} [Fintype n] [DecidableEq n] (v : n → ℝ) :
  (spectralRadius ℝ (diagonal v)).toReal = sSup (Set.range (fun i => |v i|)) := by
  rw [spectralRadius, spectrum_diagonal]
  simp
  by_contra h_contra;
  rw [ @ciSup_eq_of_forall_le_of_forall_lt_exists_gt ] at h_contra;
  case b => exact ENNReal.ofReal ( SupSet.sSup ( Set.range fun i => |v i| ) );
  · exact h_contra <| ENNReal.toReal_ofReal <| by apply_rules [ Real.sSup_nonneg ] ; rintro x ⟨ i, rfl ⟩ ; exact abs_nonneg _;
  · intro k; by_cases hk : ∃ i, v i = k <;> simp_all +decide [ ciSup_eq_ite ] ;
    intro i; split_ifs <;> norm_num [ ← ENNReal.ofReal_coe_nnreal ] ;
    exact ENNReal.ofReal_le_ofReal ( le_csSup ( Set.finite_range _ |> Set.Finite.bddAbove ) ( Set.mem_range_self i ) |> le_trans ( by aesop ) );
  · intro w hw
    obtain ⟨i, hi⟩ : ∃ i : n, |v i| > ENNReal.toReal w := by
      rcases isEmpty_or_nonempty n with ( h | h ) <;> simp_all +decide [ ENNReal.ofReal ];
      · simp_all +decide [ Set.range_eq_empty ];
      · have := exists_lt_of_lt_csSup ( Set.range_nonempty fun i => |v i| ) ( show w.toReal < SupSet.sSup ( Set.range fun i => |v i| ) from ?_ ) ; aesop;
        convert ENNReal.toReal_lt_toReal _ _ |>.2 hw using 1 <;> norm_num [ ENNReal.toReal ];
        · exact ( by apply_rules [ Real.sSup_nonneg ] ; rintro x ⟨ i, rfl ⟩ ; exact abs_nonneg _ );
        · aesop;
    use v i;
    refine' lt_of_lt_of_le _ ( le_ciSup _ i );
    · rw [ ← ENNReal.toReal_lt_toReal ] <;> aesop;
    · exact Set.finite_range _ |> Set.Finite.bddAbove

/-
Disproof of Claim 1.
We construct a counterexample with Σ = diag(1, 2).
The algorithm chooses γ = 1/2, giving ρ = 0.5.
But γ = 0.6 gives ρ = 0.4.
We use the lemma `matrixSpectralRadius_diagonal` to compute the spectral radii.
-/
open Matrix BigOperators

/-- A counterexample to Claim 1. -/
noncomputable def counterexampleSetup : CommutativeCase 2 1 := {
  Sigmas := fun _ => !![1, 0; 0, 2],
  U := 1,
  Lambdas := fun _ => ![1, 2],
  h_orth := by
    constructor <;> simp
  h_diag := by
    intro i
    simp
    ext j k
    fin_cases j <;> fin_cases k <;> simp [Matrix.diagonal] <;> rfl
  h_pos := by
    intro i j
    fin_cases j <;> simp <;> norm_num
}

theorem claim1_false : ¬ (∀ γ, matrixSpectralRadius (updateOp (counterexampleSetup.Sigmas 0) (gamma counterexampleSetup 1)) ≤ matrixSpectralRadius (updateOp (counterexampleSetup.Sigmas 0) γ)) := by
  unfold counterexampleSetup gamma updateOp matrixSpectralRadius; norm_num; (
  refine' ⟨ 3 / 5, _ ⟩ ; norm_num [ spectralRadius ];
  rw [ show ( runAlgorithm _ 1 : ℝ × Matrix ( Fin 2 ) ( Fin 2 ) ℝ ) = ( 1 / 2, 1 - ( 1 / 2 : ℝ ) • !![1, 0; 0, 2] ) from _ ] ; norm_num [ spectrum ];
  · norm_num [ resolventSet, Matrix.isUnit_iff_isUnit_det ];
    norm_num [ Algebra.algebraMap_eq_smul_one, Matrix.det_fin_two ];
    rw [ show ( ⨆ k : ℝ, ⨆ ( _ : k - 2 / 5 = 0 ∨ k + 1 / 5 = 0 ), ( ‖k‖₊ : ENNReal ) ) = ( 2 / 5 : ENNReal ) from ?_, show ( ⨆ k : ℝ, ⨆ ( _ : k - 1 / 2 = 0 ∨ k = 0 ), ( ‖k‖₊ : ENNReal ) ) = ( 1 / 2 : ENNReal ) from ?_ ] <;> norm_num [ sub_eq_zero, add_eq_zero_iff_eq_neg ];
    · rw [ @ciSup_eq_of_forall_le_of_forall_lt_exists_gt ] <;> norm_num;
      exact fun w hw => ⟨ 1 / 2, hw.trans_le <| by norm_num ⟩;
    · rw [ @ciSup_eq_of_forall_le_of_forall_lt_exists_gt ] <;> norm_num [ ENNReal.div_eq_inv_mul ];
      · exact le_mul_of_one_le_right ( by norm_num ) ( by norm_num );
      · intro w hw; use 2 / 5; norm_num [ hw ] ;
        convert hw using 1 ; norm_num [ div_eq_mul_inv, mul_comm ];
  · -- By definition of `runAlgorithm`, we have `runAlgorithm setup 1 = algorithmStep setup 0 (runAlgorithm setup 0)`.
    simp [runAlgorithm, algorithmStep];
    unfold matrixSpectralRadius updateOp; norm_num [ Matrix.mulVec ] ;
    rw [ show ( !![1, 0; 0, 2] : Matrix ( Fin 2 ) ( Fin 2 ) ℝ ) = Matrix.diagonal ( fun i => if i = 0 then 1 else 2 ) by ext i j; fin_cases i <;> fin_cases j <;> rfl ] ; norm_num [ matrixSpectralRadius_diagonal ] ; ring ;
    rw [ show ( Set.range fun i : Fin 2 => |if i = 0 then ( 1 : ℝ ) else 2| ) = { 1, 2 } by ext x; exact ⟨ by rintro ⟨ i, rfl ⟩ ; fin_cases i <;> norm_num, by rintro ( rfl | rfl ) <;> [ exact ⟨ 0, by norm_num ⟩ ; exact ⟨ 1, by norm_num ⟩ ] ⟩ ] ; norm_num;);

/-
Lemma: The spectral radius of diag(1, 2) is 2.
Proof: Use matrixSpectralRadius_diagonal. The range of |v| is {|1|, |2|} = {1, 2}. The sup is 2.
-/
open Matrix BigOperators

lemma spec_rad_S : matrixSpectralRadius (diagonal ![1, 2] : Matrix (Fin 2) (Fin 2) ℝ) = 2 := by
  convert matrixSpectralRadius_diagonal ![1, 2] using 1;
  rw [ @csSup_eq_of_forall_le_of_forall_lt_exists_gt ] <;> norm_num [ Fin.forall_fin_two, Fin.exists_fin_two ];
  · exact ⟨ _, ⟨ 0, rfl ⟩ ⟩;
  · rintro a ( rfl | rfl ) <;> norm_num;
  · exact fun w hw => ⟨ 2, Or.inr rfl, hw ⟩

/-
Disproof of Claim 1.
We construct a counterexample with Σ = diag(1, 2).
The algorithm chooses γ = 1/2, giving ρ = 0.5.
But γ = 0.6 gives ρ = 0.4.
We use the lemma `matrixSpectralRadius_diagonal` to compute the spectral radii.
-/
open Matrix BigOperators

theorem claim1_disproof : ¬ (∀ γ, matrixSpectralRadius (updateOp (counterexampleSetup.Sigmas 0) (gamma counterexampleSetup 1)) ≤ matrixSpectralRadius (updateOp (counterexampleSetup.Sigmas 0) γ)) := by
  exact?

/-
Disproof of Claim 1 using the counterexample Σ = diag(1, 2).
The algorithm chooses γ = 1/2, giving spectral radius 0.5.
But γ = 3/5 gives spectral radius 0.4.
-/
open Matrix BigOperators

theorem claim1_counterexample : ¬ (∀ γ, matrixSpectralRadius (updateOp (counterexampleSetup.Sigmas 0) (gamma counterexampleSetup 1)) ≤ matrixSpectralRadius (updateOp (counterexampleSetup.Sigmas 0) γ)) := by
  exact?

/-
Lemma: The supremum of the range of a function on Fin 2 is the maximum of its values at 0 and 1.
-/
open Matrix BigOperators

lemma sSup_range_fin_two (f : Fin 2 → ℝ) : sSup (Set.range f) = max (f 0) (f 1) := by
  rw [ @csSup_eq_of_forall_le_of_forall_lt_exists_gt ] <;> norm_num [ Set.range ];
  · exact ⟨ f 0, Or.inl rfl ⟩;
  · grind +ring;
  · grind +ring

/-
Lemma: The spectral radius of a 2x2 diagonal matrix diag(a, b) is max(|a|, |b|).
-/
open Matrix BigOperators

lemma spec_rad_diag_fin_two (a b : ℝ) :
  matrixSpectralRadius (diagonal ![a, b] : Matrix (Fin 2) (Fin 2) ℝ) = max |a| |b| := by
    convert ( matrixSpectralRadius_diagonal ![ a, b ] ) using 1;
    rw [ @csSup_eq_of_forall_le_of_forall_lt_exists_gt ] <;> norm_num [ Fin.exists_fin_succ ];
    · exact ⟨ _, ⟨ 0, rfl ⟩ ⟩;
    · grind;
    · aesop

/-
Disproof of Claim 1 using the counterexample Σ = diag(1, 2).
The algorithm chooses γ = 1/2, giving spectral radius 0.5.
But γ = 3/5 gives spectral radius 0.4.
-/
open Matrix BigOperators

theorem claim1_counterexample_final : ¬ (∀ γ, matrixSpectralRadius (updateOp (counterexampleSetup.Sigmas 0) (gamma counterexampleSetup 1)) ≤ matrixSpectralRadius (updateOp (counterexampleSetup.Sigmas 0) γ)) := by
  exact?

/-
Disproof of Claim 1 using the counterexample Σ = diag(1, 2).
The algorithm chooses γ = 1/2, giving spectral radius 0.5.
But γ = 3/5 gives spectral radius 0.4.
-/
open Matrix BigOperators

theorem claim1_disproof_v2 : ¬ (∀ γ, matrixSpectralRadius (updateOp (counterexampleSetup.Sigmas 0) (gamma counterexampleSetup 1)) ≤ matrixSpectralRadius (updateOp (counterexampleSetup.Sigmas 0) γ)) := by
  intro h
  let γ_better : ℝ := 3/5
  
  have h_S_diag : counterexampleSetup.Sigmas 0 = diagonal ![1, 2] := by
    ext i j
    fin_cases i <;> fin_cases j <;> simp [counterexampleSetup, Matrix.diagonal] <;> rfl

  have h_gamma_opt : gamma counterexampleSetup 1 = 1/2 := by
    unfold gamma runAlgorithm algorithmStep
    simp
    rw [h_S_diag, spec_rad_diag_fin_two]
    norm_num

  have h_rho_opt : matrixSpectralRadius (updateOp (counterexampleSetup.Sigmas 0) (gamma counterexampleSetup 1)) = 1/2 := by
    rw [h_gamma_opt, updateOp, h_S_diag]
    have : (1 : Matrix (Fin 2) (Fin 2) ℝ) - (1/2 : ℝ) • diagonal ![1, 2] = diagonal ![1/2, 0] := by
      ext i j; fin_cases i <;> fin_cases j <;> simp [Matrix.diagonal] <;> norm_num
    rw [this, spec_rad_diag_fin_two]
    norm_num

  have h_rho_better : matrixSpectralRadius (updateOp (counterexampleSetup.Sigmas 0) γ_better) = 2/5 := by
    rw [updateOp, h_S_diag]
    have : (1 : Matrix (Fin 2) (Fin 2) ℝ) - (3/5 : ℝ) • diagonal ![1, 2] = diagonal ![2/5, -1/5] := by
      ext i j; fin_cases i <;> fin_cases j <;> simp [Matrix.diagonal] <;> norm_num
    rw [this, spec_rad_diag_fin_two]
    norm_num

  specialize h γ_better
  rw [h_rho_opt, h_rho_better] at h
  norm_num at h

/-
Disproof of Claim 3 using the same counterexample.
Claim 3 states that the recursive stepsizes minimize the final spectral radius.
For K=1, this is equivalent to Claim 1.
Since Claim 1 is false, Claim 3 is false.
-/
open Matrix BigOperators

theorem claim3_disproof : ¬ (∀ (gammas : Fin 1 → ℝ),
    (∀ i, gammas i > 0) →
    let M_final := (Fin.foldr 1 (fun i M_acc => updateOp (counterexampleSetup.Sigmas i) (gammas i) * M_acc) 1)
    matrixSpectralRadius (M counterexampleSetup 1) ≤ matrixSpectralRadius M_final) := by
      push_neg;
      use fun _ => 3 / 5;
      -- Calculate the spectral radius of the final matrix for the chosen γ.
      have h_final : matrixSpectralRadius (updateOp (counterexampleSetup.Sigmas 0) (gamma counterexampleSetup 1)) = 0.5 := by
        have h_gamma : gamma counterexampleSetup 1 = 1 / 2 := by
          unfold gamma;
          -- By definition of `runAlgorithm`, we have:
          have h_run : runAlgorithm counterexampleSetup 1 = algorithmStep counterexampleSetup 0 (runAlgorithm counterexampleSetup 0).2 := by
            rfl;
          rw [ h_run, algorithmStep ] ; norm_num [ counterexampleSetup ];
          rw [ show ( !![1, 0; 0, 2] : Matrix ( Fin 2 ) ( Fin 2 ) ℝ ) = diagonal ![1, 2] by ext i j; fin_cases i <;> fin_cases j <;> rfl, spec_rad_S ] ; norm_num;
        convert spec_rad_diag_fin_two ( 1 - 1 / 2 * 1 ) ( 1 - 1 / 2 * 2 ) using 1 ; norm_num [ h_gamma ];
        · congr ; ext i j ; fin_cases i <;> fin_cases j <;> norm_num [ counterexampleSetup, updateOp ];
        · norm_num [ abs_of_pos ];
      -- Calculate the spectral radius of the final matrix for the chosen γ = 3/5.
      have h_final_3_5 : matrixSpectralRadius (updateOp (counterexampleSetup.Sigmas 0) (3 / 5)) = 0.4 := by
        convert spec_rad_diag_fin_two ( 1 - 3 / 5 * 1 ) ( 1 - 3 / 5 * 2 ) using 1 ; norm_num [ updateOp, counterexampleSetup ] ; ring_nf ; norm_num [ Fin.forall_fin_two, Fin.exists_fin_two, Matrix.vecHead, Matrix.vecTail, Matrix.mulVec ] at *;
        · congr ; ext i j ; fin_cases i <;> fin_cases j <;> norm_num [ Matrix.one_apply, Matrix.vecHead, Matrix.vecTail ] at * <;> ring_nf at * <;> norm_num at * <;> first | linarith | aesop | trivial;
        · norm_num [ abs_of_pos ]
      norm_num at *; (
      convert h_final_3_5.trans_lt ( show 2 / 5 < matrixSpectralRadius (updateOp (counterexampleSetup.Sigmas 0) (gamma counterexampleSetup 1)) from by linarith ) using 1 ; norm_num [ Fin.foldr ] ; ring!;
      · exact congr_arg _ ( by exact Matrix.mul_one _ ) ;
      · unfold M gamma; norm_num [ runAlgorithm ] ;
        unfold algorithmStep; norm_num [ counterexampleSetup ] ;)

/-
Definition of the rotation matrix U_rot and proof that it is orthogonal.
-/
open Matrix BigOperators

noncomputable def U_rot : Matrix (Fin 2) (Fin 2) ℝ :=
  !![1/Real.sqrt 2, -1/Real.sqrt 2; 1/Real.sqrt 2, 1/Real.sqrt 2]

lemma U_rot_orth : U_rot * U_rot.transpose = 1 ∧ U_rot.transpose * U_rot = 1 := by
  -- By definition of $U_rot$, we know that it is orthogonal.
  simp [U_rot] at *;
  constructor <;> ext i j <;> fin_cases i <;> fin_cases j <;> norm_num [ Matrix.vecHead, Matrix.vecTail, Matrix.mul_apply ] <;> ring_nf <;> norm_num;

/-
Disproof of Claim 2.
We construct two setups, A and B, with the same Σ matrices (Identity) but different U matrices (Identity and Rotation).
The algorithm produces the same M matrices (0) and thus the same dominant eigenvector v.
However, v cannot be a column of both I and U_rot, as their columns are disjoint.
Thus Claim 2 fails for at least one of the setups.
-/
open Matrix BigOperators

noncomputable def U_rot_v2 : Matrix (Fin 2) (Fin 2) ℝ :=
  !![1/Real.sqrt 2, -1/Real.sqrt 2; 1/Real.sqrt 2, 1/Real.sqrt 2]

lemma U_rot_orth_v2 : U_rot_v2 * U_rot_v2.transpose = 1 ∧ U_rot_v2.transpose * U_rot_v2 = 1 := by
  unfold U_rot_v2;
  constructor <;> ext i j <;> fin_cases i <;> fin_cases j <;> norm_num [ Matrix.mul_apply, Matrix.transpose_apply ] <;> ring_nf <;> norm_num

noncomputable def setupA : CommutativeCase 2 2 := {
  Sigmas := fun _ => 1,
  U := 1,
  Lambdas := fun _ _ => 1,
  h_orth := by simp,
  h_diag := by simp,
  h_pos := by simp
}

noncomputable def setupB : CommutativeCase 2 2 := {
  Sigmas := fun _ => 1,
  U := U_rot_v2,
  Lambdas := fun _ _ => 1,
  h_orth := U_rot_orth_v2,
  h_diag := by
    intro i
    simp
    rw [U_rot_orth_v2.1]
  h_pos := by simp
}

lemma runAlgorithm_congr (s1 s2 : CommutativeCase d K) (h : s1.Sigmas = s2.Sigmas) (k : ℕ) :
  runAlgorithm s1 k = runAlgorithm s2 k := by
    induction k <;> simp_all +decide [ runAlgorithm ];
    unfold algorithmStep; aesop;

theorem claim2_disproof : ¬ (∀ (setup : CommutativeCase 2 2) (k : ℕ) (hk : k ∈ Set.Ioo 1 (2 + 1)),
  let M_prev := M setup (k - 1)
  let v := dominantEigenvector M_prev
  ∃ j : Fin 2, v = setup.U.col j ∨ v = -setup.U.col j) := by
    by_contra! h_contra;
    obtain ⟨setup_A, setup_B⟩ : ∃ (setup_A setup_B : CommutativeCase 2 2), setup_A.Sigmas = setup_B.Sigmas ∧ (setup_A.U = 1 ∧ setup_B.U = U_rot) := by
      refine' ⟨ ⟨ fun _ => 1, 1, fun _ => 1, _, _, _ ⟩, ⟨ fun _ => 1, U_rot, fun _ => 1, _, _, _ ⟩, _, _, _ ⟩ <;> norm_num [ U_rot_orth ];
    obtain ⟨ setup_B, hSigmas, hU_A, hU_B ⟩ := setup_B; have := h_contra setup_A 2; have := h_contra setup_B 2; simp_all +decide ;
    -- Since $M_1 = 0$, the dominant eigenvector $v$ is the same for both setups.
    have hv_eq : dominantEigenvector (M setup_A 1) = dominantEigenvector (M setup_B 1) := by
      -- By definition of $M$, we know that
      simp [M, runAlgorithm, algorithmStep, hSigmas];
    simp_all +decide [ ← List.ofFn_inj ];
    unfold U_rot at * ; norm_num at * ; aesop;

/-
Disproof of Claim 2.
We construct two setups, A and B, with the same Σ matrices (Identity) but different U matrices (Identity and Rotation).
The algorithm produces the same M matrices (0) and thus the same dominant eigenvector v.
However, v cannot be a column of both I and U_rot, as their columns are disjoint.
Thus Claim 2 fails for at least one of the setups.
-/
open Matrix BigOperators

theorem claim2_disproof_v2 : ¬ (∀ (setup : CommutativeCase 2 2) (k : ℕ) (hk : k ∈ Set.Ioo 1 (2 + 1)),
  let M_prev := M setup (k - 1)
  let v := dominantEigenvector M_prev
  ∃ j : Fin 2, v = setup.U.col j ∨ v = -setup.U.col j) := by
    -- Apply the contradiction assumption to the specific setupB.
    apply claim2_disproof