/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 2da9c53d-4b31-48cc-9e39-55204bc79ef8

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
This module defines the symmetric part and `c_total` for 2x2 matrices, and proves three key theorems for the K=3, d=2 continual learning stepsize problem: `variational_trace`, `variational_det`, and `spectral_radius_formula`. It also includes helper lemmas `expansion_identity` and `det_decomposition`.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

/-
Definitions of symmetric part and c_total for 2x2 matrices.
-/
def sym_part (M : Matrix (Fin 2) (Fin 2) ℝ) : Matrix (Fin 2) (Fin 2) ℝ := (M + M.transpose) / 2

def c_total (M : Matrix (Fin 2) (Fin 2) ℝ) : ℝ := (M 0 1 - M 1 0) / 2

/-
Expansion identity for the product of three matrices of the form (1 - g_i S_i).
-/
theorem expansion_identity
  (g1 g2 g3 : ℝ)
  (S1 S2 S3 : Matrix (Fin 2) (Fin 2) ℝ) :
  let A1 := (1 : Matrix (Fin 2) (Fin 2) ℝ) - g1 • S1
  let A2 := (1 : Matrix (Fin 2) (Fin 2) ℝ) - g2 • S2
  let A3 := (1 : Matrix (Fin 2) (Fin 2) ℝ) - g3 • S3
  A3 * A2 * A1 = (1 : Matrix (Fin 2) (Fin 2) ℝ) - (g1 • S1 + g2 • S2 + g3 • S3)
                 + ((g1 * g2) • (S2 * S1) + (g1 * g3) • (S3 * S1) + (g2 * g3) • (S3 * S2))
                 - (g1 * g2 * g3) • (S3 * S2 * S1) := by
                   ext i j; norm_num; ring;
                   fin_cases i <;> fin_cases j <;> simp +decide [ Matrix.mul_apply ] <;> ring!;

/-
Decomposition of determinant into symmetric part determinant and squared skew-symmetric part.
-/
theorem det_decomposition (M : Matrix (Fin 2) (Fin 2) ℝ) :
  M.det = (sym_part M).det + (c_total M)^2 := by
    unfold sym_part c_total; norm_num [ Matrix.det_fin_two ] ; ring;
    norm_num [ div_eq_mul_inv, Matrix.inv_def ] ; ring;
    erw [ Matrix.det_diagonal, Matrix.adjugate_diagonal ] ; norm_num ; ring;

/-
Trace of the expanded matrix M3 (corrected constant term to 2).
-/
theorem variational_trace
  (g1 g2 g3 : ℝ)
  (S1 S2 S3 : Matrix (Fin 2) (Fin 2) ℝ)
  (hS1 : S1.IsSymm) (hS2 : S2.IsSymm) (hS3 : S3.IsSymm) :
  let M3 := (1 : Matrix (Fin 2) (Fin 2) ℝ) - g1 • S1 - g2 • S2 - g3 • S3
             + (g1 * g2) • (S2 * S1) + (g1 * g3) • (S3 * S1) + (g2 * g3) • (S3 * S2)
             - (g1 * g2 * g3) • (S3 * S2 * S1)
  M3.trace = 2 - g1 * S1.trace - g2 * S2.trace - g3 * S3.trace
             + g1 * g2 * (S2 * S1).trace + g1 * g3 * (S3 * S1).trace
             + g2 * g3 * (S3 * S2).trace
             - g1 * g2 * g3 * (S3 * S2 * S1).trace := by
               simp +zetaDelta at *

/-
Determinant of M3 using the decomposition.
-/
theorem variational_det
  (g1 g2 g3 : ℝ)
  (S1 S2 S3 : Matrix (Fin 2) (Fin 2) ℝ)
  (hS1 : S1.IsSymm) (hS2 : S2.IsSymm) (hS3 : S3.IsSymm) :
  let M3 := (1 : Matrix (Fin 2) (Fin 2) ℝ) - g1 • S1 - g2 • S2 - g3 • S3
             + (g1 * g2) • (S2 * S1) + (g1 * g3) • (S3 * S1) + (g2 * g3) • (S3 * S2)
             - (g1 * g2 * g3) • (S3 * S2 * S1)
  M3.det = (sym_part M3).det + (c_total M3)^2 := by
    exact?

/-
Formula for eigenvalues and characteristic polynomial of a 2x2 matrix. Renamed lambda to eig to avoid syntax error.
-/
theorem spectral_radius_formula
  (M : Matrix (Fin 2) (Fin 2) ℝ) :
  let T := M.trace
  let D := M.det
  (T^2 ≥ 4*D) →
  ∃ eig1 eig2 : ℝ,
    eig1 = (T + Real.sqrt (T^2 - 4*D)) / 2 ∧
    eig2 = (T - Real.sqrt (T^2 - 4*D)) / 2 ∧
    M.charpoly = (Polynomial.X - Polynomial.C eig1) *
                 (Polynomial.X - Polynomial.C eig2) := by
                   simp +zetaDelta at *;
                   intro h; exact Polynomial.funext fun x => by simp [ Matrix.charpoly, Matrix.det_fin_two, Matrix.trace_fin_two ] at *; linarith [ Real.mul_self_sqrt ( sub_nonneg.mpr h ) ] ;