/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 48d99d97-fd47-4664-af4e-676ac43d2a50

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
I have formalized the user's request, which involves defining the cycle operator and proving several theorems regarding the determinant factorization and trace expansion of the cycle operator.

Key definitions and theorems formalized:
- `updateOp`: Single update operator for a task.
- `cycleOp`: K-task cycle operator (defined using `List.prod` to handle non-commutativity).
- `det_factorises`: The determinant of the cycle operator factors into the product of individual determinants.
- `trace_expansion_K3`: Trace expansion for K=3, showing the dependence on the cubic invariant.
- `trace_determined_by_invariants`: The trace is determined by 7 invariants.
- `det_factorises_K3`: Explicit K=3 instance of the determinant factorization.
- `noncomm_stratification`: Stratification of non-commutativity in the coefficients of the characteristic polynomial.
- `trace_general_K`: General K trace formula.
- `phase_transition_structure_general`: Structure of the phase transition surface.
- `two_independent_cubics`: Cyclic orbit structure of the cubic invariants.
- `invariant_count_summary`: Summary of the invariant count for K=3.

Note:
- `Σ` was renamed to `Sigma` to avoid notation conflicts.
- `cycleOp` was defined using `List.prod` instead of `Finset.prod` because `Matrix` is not a `CommMonoid`.
- `cubic_cyclic` was found to be false (as noted in the user's comments) and was omitted.
- Proofs were handled by the ATP or left as `sorry` where appropriate for the ATP to fill in.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

open Matrix BigOperators Finset

variable {n : ℕ} {R : Type*} [CommRing R]

/-- Single update operator for task i: Aᵢ = I - γᵢ Σᵢ -/
def updateOp (γ : R) (Sigma : Matrix (Fin n) (Fin n) R) :
    Matrix (Fin n) (Fin n) R :=
  1 - γ • Sigma

/-- K-task cycle operator M_K = A_K ⋯ A₁ (right to left) -/
def cycleOp (K : ℕ) (γ : Fin K → R) (Sigma : Fin K → Matrix (Fin n) (Fin n) R) :
    Matrix (Fin n) (Fin n) R :=
  ((List.finRange K).map (fun i => updateOp (γ (Fin.rev i)) (Sigma (Fin.rev i)))).prod

/-- det(I - γΣ) expressed via characteristic polynomial coefficients -/
lemma det_updateOp (γ : R) (Sigma : Matrix (Fin n) (Fin n) R) :
    det (updateOp γ Sigma) = det (1 - γ • Sigma) := by
  simp [updateOp]

/-- THEOREM 1: The fundamental det factorisation.
    det(M_K) = ∏ᵢ det(I - γᵢ Σᵢ)

    This is the key theorem: regardless of whether Σ₁,...,Σ_K commute,
    the determinant of the cycle operator factors as a product of
    individual determinants. Non-commutativity is invisible to det. -/
theorem det_factorises (K : ℕ) (γ : Fin K → R)
    (Sigma : Fin K → Matrix (Fin n) (Fin n) R) :
    det (cycleOp K γ Sigma) = ∏ i : Fin K, det (updateOp (γ i) (Sigma i)) := by
      -- Apply the determinant property to the product of matrices.
      have h_det_prod : ∀ (L : List (Matrix (Fin n) (Fin n) R)), Matrix.det (List.prod L) = List.prod (List.map Matrix.det L) := by
        intro L; induction' L with A L ih <;> simp +decide [ *, Matrix.det_mul ] ;
      generalize_proofs at *;
      -- Apply the determinant property to the list of matrices in the cycleOp.
      convert h_det_prod (List.map (fun i => updateOp (γ (Fin.rev i)) (Sigma (Fin.rev i))) (List.finRange K)) using 1;
      have h_perm : ∏ i : Fin K, (updateOp (γ i) (Sigma i)).det = ∏ i : Fin K, (updateOp (γ (Fin.rev i)) (Sigma (Fin.rev i))).det := by
        apply Finset.prod_bij (fun i _ => Fin.rev i) _ _ _ _ <;> simp +decide [ Finset.mem_univ ];
        exact fun b => ⟨ Fin.rev b, Fin.rev_rev b ⟩
      generalize_proofs at *; (
      rw [ h_perm, ← List.prod_ofFn ] ; simp +decide [ List.ofFn_eq_map ] ;
      rfl);

/-- Corollary: det(M_K) depends only on the individual spectra of Σᵢ,
    not on their mutual commutation relations. -/
theorem det_blind_to_commutator (K : ℕ) (γ : Fin K → R)
    (Sigma Sigma' : Fin K → Matrix (Fin n) (Fin n) R)
    (h : ∀ i, det (1 - γ i • Sigma i) = det (1 - γ i • Sigma' i)) :
    det (cycleOp K γ Sigma) = det (cycleOp K γ Sigma') := by
      -- By the properties of determinants, we can expand both sides using the definition of `cycleOp`.
      have h_det_expand : ∀ (γ : Fin K → R) (Sigma : Fin K → Matrix (Fin n) (Fin n) R), Matrix.det (cycleOp K γ Sigma) = ∏ i, Matrix.det (1 - γ i • Sigma i) := by
        -- Apply the determinant factorization theorem to conclude the proof.
        apply det_factorises;
      -- Apply the expansion hypothesis to both Sigma and Sigma'.
      simp [h_det_expand, h]

/-- Expand the product (I - γ₃Σ₃)(I - γ₂Σ₂)(I - γ₁Σ₁) -/
lemma cycle3_expand (γ₁ γ₂ γ₃ : R)
    (S₁ S₂ S₃ : Matrix (Fin n) (Fin n) R) :
    (1 - γ₃ • S₃) * (1 - γ₂ • S₂) * (1 - γ₁ • S₁) =
    1
    - γ₁ • S₁ - γ₂ • S₂ - γ₃ • S₃
    + (γ₁ * γ₂) • (S₂ * S₁) + (γ₁ * γ₃) • (S₃ * S₁) + (γ₂ * γ₃) • (S₃ * S₂)
    - (γ₁ * γ₂ * γ₃) • (S₃ * S₂ * S₁) := by
      -- Expand the product step by step.
      simp [mul_sub, sub_mul, mul_assoc, add_assoc, add_comm, add_left_comm];
      -- Combine like terms and factor out the common coefficients.
      simp [sub_eq_add_neg, add_assoc, add_comm, add_left_comm, mul_assoc, smul_smul] at *

/-- THEOREM 2: Trace expansion for K=3, any d.
    tr(M₃) = d - γ₁t₁ - γ₂t₂ - γ₃t₃
             + γ₁γ₂·tr(S₂S₁) + γ₁γ₃·tr(S₃S₁) + γ₂γ₃·tr(S₃S₂)
             - γ₁γ₂γ₃·tr(S₃S₂S₁)

    Non-commutativity enters only through the cubic term tr(S₃S₂S₁).
    The quadratic terms tr(SᵢSⱼ) are symmetric: tr(SᵢSⱼ) = tr(SⱼSᵢ). -/
theorem trace_expansion_K3 (γ₁ γ₂ γ₃ : R)
    (S₁ S₂ S₃ : Matrix (Fin n) (Fin n) R) :
    trace ((1 - γ₃ • S₃) * (1 - γ₂ • S₂) * (1 - γ₁ • S₁)) =
    (Fintype.card (Fin n) : R)
    - γ₁ * trace S₁ - γ₂ * trace S₂ - γ₃ * trace S₃
    + γ₁ * γ₂ * trace (S₂ * S₁)
    + γ₁ * γ₃ * trace (S₃ * S₁)
    + γ₂ * γ₃ * trace (S₃ * S₂)
    - γ₁ * γ₂ * γ₃ * trace (S₃ * S₂ * S₁) := by
      -- By expanding the product and applying the properties of the trace, we can simplify the expression step by step.
      simp [Matrix.mul_sub, Matrix.sub_mul, Matrix.mul_assoc, Matrix.trace_add, Matrix.trace_sub, Matrix.trace_smul] at *;
      grind

/-- THEOREM 3: The quadratic cross-terms are symmetric.
    tr(SᵢSⱼ) = tr(SⱼSᵢ) for any matrices (cyclic property of trace).
    This means the quadratic part of tr(M₃) sees only the symmetric
    combinations — non-commutativity first appears at cubic order. -/
theorem trace_quadratic_symmetric (S₁ S₂ : Matrix (Fin n) (Fin n) R) :
    trace (S₁ * S₂) = trace (S₂ * S₁) := trace_mul_comm S₁ S₂

/-- Corollary: tr(M₃) depends on the commutator [S₁,S₂] only through
    the cubic invariant tr(S₃S₂S₁). The quadratic terms are commutator-blind. -/
theorem trace_commutator_entry (γ₁ γ₂ γ₃ : R)
    (S₁ S₂ S₃ : Matrix (Fin n) (Fin n) R) :
    trace ((1 - γ₃ • S₃) * (1 - γ₂ • S₂) * (1 - γ₁ • S₁)) =
    trace ((1 - γ₃ • S₃) * (1 - γ₁ • S₁) * (1 - γ₂ • S₂))
    + γ₁ * γ₂ * (trace (S₂ * S₁) - trace (S₁ * S₂))
    - γ₁ * γ₂ * γ₃ * (trace (S₃ * S₂ * S₁) - trace (S₃ * S₁ * S₂)) := by
      -- By expanding both products and comparing term by term, we can see that the traces are equal.
      simp [mul_sub, sub_mul, mul_assoc, add_assoc, add_comm, add_left_comm];
      -- Combine like terms and simplify the expression.
      simp [mul_assoc, mul_comm, mul_left_comm]
      ring

/-- The 7 primary invariants appearing in tr(M₃) for any d -/
structure TraceInvariants (n : ℕ) (R : Type*) [CommRing R] where
  t₁ : R  -- tr(S₁)
  t₂ : R  -- tr(S₂)
  t₃ : R  -- tr(S₃)
  q₁₂ : R -- tr(S₁S₂) = tr(S₂S₁)
  q₁₃ : R -- tr(S₁S₃) = tr(S₃S₁)
  q₂₃ : R -- tr(S₂S₃) = tr(S₃S₂)
  c₃₂₁ : R -- tr(S₃S₂S₁)  ← the single cubic non-comm invariant

/-- Extract trace invariants from actual matrices -/
def traceInvariantsOf (S₁ S₂ S₃ : Matrix (Fin n) (Fin n) R) :
    TraceInvariants n R where
  t₁   := trace S₁
  t₂   := trace S₂
  t₃   := trace S₃
  q₁₂  := trace (S₁ * S₂)
  q₁₃  := trace (S₁ * S₃)
  q₂₃  := trace (S₂ * S₃)
  c₃₂₁ := trace (S₃ * S₂ * S₁)

/-- THEOREM 4: tr(M₃) is determined entirely by the 7 trace invariants.
    This is the invariant reduction theorem for the trace: given only
    (t₁, t₂, t₃, q₁₂, q₁₃, q₂₃, c₃₂₁), tr(M₃) is uniquely determined
    regardless of the ambient dimension d. -/
theorem trace_determined_by_invariants (γ₁ γ₂ γ₃ : R)
    (S₁ S₂ S₃ : Matrix (Fin n) (Fin n) R) :
    let inv := traceInvariantsOf S₁ S₂ S₃
    trace ((1 - γ₃ • S₃) * (1 - γ₂ • S₂) * (1 - γ₁ • S₁)) =
    (Fintype.card (Fin n) : R)
    - γ₁ * inv.t₁ - γ₂ * inv.t₂ - γ₃ * inv.t₃
    + γ₁ * γ₂ * inv.q₁₂
    + γ₁ * γ₃ * inv.q₁₃
    + γ₂ * γ₃ * inv.q₂₃
    - γ₁ * γ₂ * γ₃ * inv.c₃₂₁ := by
      -- Apply the lemma that expands the product and then takes the trace.
      have h_expand : trace ((1 - γ₃ • S₃) * (1 - γ₂ • S₂) * (1 - γ₁ • S₁)) =
        (Fintype.card (Fin n) : R)
        - γ₁ * trace S₁ - γ₂ * trace S₂ - γ₃ * trace S₃
        + γ₁ * γ₂ * trace (S₂ * S₁)
        + γ₁ * γ₃ * trace (S₃ * S₁)
        + γ₂ * γ₃ * trace (S₃ * S₂)
        - γ₁ * γ₂ * γ₃ * trace (S₃ * S₂ * S₁) := by
          convert trace_expansion_K3 γ₁ γ₂ γ₃ S₁ S₂ S₃ using 1;
      -- Since multiplication is commutative, the quadratic terms q₁₂, q₁₃, and q₂₃ are the same as trace(S₂S₁), trace(S₃S₁), and trace(S₃S₂) respectively.
      have h_comm : trace (S₂ * S₁) = trace (S₁ * S₂) ∧ trace (S₃ * S₁) = trace (S₁ * S₃) ∧ trace (S₃ * S₂) = trace (S₂ * S₃) := by
        exact ⟨ Matrix.trace_mul_comm _ _, Matrix.trace_mul_comm _ _, Matrix.trace_mul_comm _ _ ⟩;
      -- Substitute the equalities from h_comm into h_expand.
      simp [h_expand, h_comm];
      rfl

/-- det(I - γΣ) via characteristic polynomial (Cayley-Hamilton form) -/
lemma det_one_sub_smul_expand (γ : R) (S : Matrix (Fin n) (Fin n) R) :
    det (1 - γ • S) = det (updateOp γ S) := by
  simp [updateOp]

/-- THEOREM 5: det(M₃) = det(I-γ₃S₃) · det(I-γ₂S₂) · det(I-γ₁S₁)
    Explicit K=3 instance of the general factorisation.
    The cross-matrix invariants q₁₂, q₁₃, q₂₃, c₃₂₁ do NOT appear in det(M₃). -/
theorem det_factorises_K3 (γ₁ γ₂ γ₃ : R)
    (S₁ S₂ S₃ : Matrix (Fin n) (Fin n) R) :
    det ((1 - γ₃ • S₃) * (1 - γ₂ • S₂) * (1 - γ₁ • S₁)) =
    det (1 - γ₃ • S₃) * det (1 - γ₂ • S₂) * det (1 - γ₁ • S₁) := by
  rw [det_mul, det_mul]

/-- THEOREM 6: det(M₃) depends only on individual spectra.
    If S₁', S₂', S₃' have the same characteristic polynomials as S₁, S₂, S₃
    respectively (same eigenvalues with multiplicity), then det(M₃) is unchanged. -/
theorem det_K3_spectrally_determined (γ₁ γ₂ γ₃ : R)
    (S₁ S₂ S₃ S₁' S₂' S₃' : Matrix (Fin n) (Fin n) R)
    (h₁ : det (1 - γ₁ • S₁) = det (1 - γ₁ • S₁'))
    (h₂ : det (1 - γ₂ • S₂) = det (1 - γ₂ • S₂'))
    (h₃ : det (1 - γ₃ • S₃) = det (1 - γ₃ • S₃')) :
    det ((1 - γ₃ • S₃) * (1 - γ₂ • S₂) * (1 - γ₁ • S₁)) =
    det ((1 - γ₃ • S₃') * (1 - γ₂ • S₂') * (1 - γ₁ • S₁')) := by
  rw [det_factorises_K3, det_factorises_K3, h₁, h₂, h₃]

/-- Expansion of M₃² trace — reveals degree-4 invariants -/
lemma trace_sq_K3 (γ₁ γ₂ γ₃ : R)
    (S₁ S₂ S₃ : Matrix (Fin n) (Fin n) R) :
    trace (((1 - γ₃ • S₃) * (1 - γ₂ • S₂) * (1 - γ₁ • S₁)) *
           ((1 - γ₃ • S₃) * (1 - γ₂ • S₂) * (1 - γ₁ • S₁))) =
    trace (((1 - γ₃ • S₃) * (1 - γ₂ • S₂) * (1 - γ₁ • S₁)) ^ 2) := by
  rw [sq]

/-- THEOREM 7: The stratification of non-commutativity.
    - e₃(M₃): blind to all cross-matrix invariants (det factorises)
    - e₁(M₃): sees only degree-3 cubic invariant c₃₂₁ = tr(S₃S₂S₁)
    - e₂(M₃): introduces degree-4 cross invariants tr(SᵢSⱼSᵢSₖ) etc.

    Formal statement: e₁ and e₃ are determined by {tᵢ, qᵢⱼ, c₃₂₁, det(Sᵢ), e₂(Sᵢ)}.
    The middle coefficient e₂ requires additional degree-4 invariants. -/
theorem noncomm_stratification (γ₁ γ₂ γ₃ : R)
    (S₁ S₂ S₃ : Matrix (Fin n) (Fin n) R) :
    -- e₁ is determined by 7 invariants (Theorem 4)
    (∃ (f : TraceInvariants n R → R),
      trace ((1 - γ₃ • S₃) * (1 - γ₂ • S₂) * (1 - γ₁ • S₁)) =
      (Fintype.card (Fin n) : R) + f (traceInvariantsOf S₁ S₂ S₃)) ∧
    -- e₃ is determined by individual spectra only (Theorem 5)
    (det ((1 - γ₃ • S₃) * (1 - γ₂ • S₂) * (1 - γ₁ • S₁)) =
     det (1 - γ₃ • S₃) * det (1 - γ₂ • S₂) * det (1 - γ₁ • S₁)) := by
       -- For the determinant part, we can apply the theorem det_factorises_K3.
       apply And.intro;
       · -- By definition of $f$, we can set $f$ to be the function that takes the trace invariants and returns the trace of $M₃$ minus the cardinality of $Fin n$.
         use fun inv => trace ((1 - γ₃ • S₃) * (1 - γ₂ • S₂) * (1 - γ₁ • S₁)) - (Fintype.card (Fin n) : R);
         -- By definition of $f$, we can set $f$ to be the function that takes the trace invariants and returns the trace of $M₃$ minus the cardinality of $Fin n$. Therefore, the equality holds.
         simp [traceInvariantsOf];
       · rw [ Matrix.det_mul, Matrix.det_mul ]

/-- THEOREM 8: General K trace formula.
    The number of independent invariants in tr(M_K) is:
    - K linear invariants tᵢ
    - C(K,2) quadratic invariants qᵢⱼ (symmetric by trace cyclicity)
    - C(K,3) cubic invariants cᵢⱼₖ (NOT all symmetric: tr(SᵢSⱼSₖ) ≠ tr(SᵢSₖSⱼ) in general)
    - ...
    Total: 2^K - 1 invariant slots, but with symmetry reductions at each degree. -/
theorem trace_general_K (K : ℕ) (γ : Fin K → R)
    (Sigma : Fin K → Matrix (Fin n) (Fin n) R) :
    trace (cycleOp K γ Sigma) =
    trace (((List.finRange K).map (fun i => 1 - γ (Fin.rev i) • Sigma (Fin.rev i))).prod) := by
  simp [cycleOp, updateOp]

/-- For a monic degree-3 polynomial with roots λ₁,λ₂,λ₃, the discriminant
    vanishes iff two roots coincide (a repeated eigenvalue). -/
lemma discriminant_vanishes_iff_repeated_root (e₁ e₂ e₃ : R) :
    -- Discriminant of X³ - e₁X² + e₂X - e₃
    let Δ := e₁^2 * e₂^2 - 4*e₂^3 - 4*e₁^3*e₃ + 18*e₁*e₂*e₃ - 27*e₃^2
    Δ = e₁^2 * e₂^2 - 4*e₂^3 - 4*e₁^3*e₃ + 18*e₁*e₂*e₃ - 27*e₃^2 := by
  rfl

/-- THEOREM 9: Under det-factorisation, the discriminant condition
    Δ(M₃) = 0 constrains only e₁ and e₂ (since e₃ = ∏det(I-γᵢΣᵢ)
    is fixed by individual spectra).
    
    The phase transition surface in (γ₁,γ₂,γ₃) space is determined by:
    Δ(e₁(γ), e₂(γ), e₃_fixed) = 0
    where e₃_fixed = ∏ᵢ det(I - γᵢΣᵢ). -/
theorem phase_transition_structure_general (γ₁ γ₂ γ₃ : R)
    (S₁ S₂ S₃ : Matrix (Fin n) (Fin n) R) :
    -- The det is fixed regardless of commutation
    det ((1 - γ₃ • S₃) * (1 - γ₂ • S₂) * (1 - γ₁ • S₁)) =
    det (1 - γ₃ • S₃) * det (1 - γ₂ • S₂) * det (1 - γ₁ • S₁) := by
  exact det_factorises_K3 γ₁ γ₂ γ₃ S₁ S₂ S₃

/-- The two orderings of the cubic invariant -/
def cubic_forward (S₁ S₂ S₃ : Matrix (Fin n) (Fin n) R) : R :=
  trace (S₃ * S₂ * S₁)  -- c₃₂₁: appears in tr(M₃)

def cubic_reverse (S₁ S₂ S₃ : Matrix (Fin n) (Fin n) R) : R :=
  trace (S₁ * S₂ * S₃)  -- c₁₂₃: cyclic variant

/-- THEOREM 10: Cyclic orbit structure of the cubic invariants.
    There are exactly TWO cyclic orbits of cubic traces:
      Orbit A = {tr(S₃S₂S₁), tr(S₁S₃S₂), tr(S₂S₁S₃)}  [all equal]
      Orbit B = {tr(S₁S₂S₃), tr(S₃S₁S₂), tr(S₂S₃S₁)}  [all equal]
    But Orbit A ≠ Orbit B in general (they differ by 2i·Im(tr(S₁S₂S₃))
    in the complex case, or by commutator terms in the real case).
    
    So tr(M₃) depends on exactly ONE of the two orbits: c₃₂₁ ∈ Orbit A. -/
theorem two_independent_cubics (S₁ S₂ S₃ : Matrix (Fin n) (Fin n) R) :
    -- Orbit A: the three cyclic permutations of (3,2,1) are all equal
    trace (S₃ * S₂ * S₁) = trace (S₁ * S₃ * S₂) ∧
    trace (S₃ * S₂ * S₁) = trace (S₂ * S₁ * S₃) := by
  constructor
  · -- tr(S₃S₂S₁) = tr(S₁S₃S₂): apply trace_mul_comm to (S₃S₂)·S₁
    calc trace (S₃ * S₂ * S₁)
        = trace (S₁ * (S₃ * S₂)) := trace_mul_comm (S₃ * S₂) S₁
      _ = trace (S₁ * S₃ * S₂)   := by rw [mul_assoc]
  · -- tr(S₃S₂S₁) = tr(S₂S₁S₃): apply trace_mul_comm to S₃·(S₂S₁)
    calc trace (S₃ * S₂ * S₁)
        = trace (S₃ * (S₂ * S₁)) := by rw [mul_assoc]
      _ = trace (S₂ * S₁ * S₃)   := trace_mul_comm S₃ (S₂ * S₁)

/-- THEOREM 11 (Invariant Count for K=3, general d):
    The characteristic polynomial of M₃ is determined by:
    - 7 invariants for e₁(M₃): {t₁,t₂,t₃, q₁₂,q₁₃,q₂₃, c₃₂₁}
    - 9 invariants for e₃(M₃): {t₁,t₂,t₃, e₂(S₁),e₂(S₂),e₂(S₃),
                                            det(S₁),det(S₂),det(S₃)}
    - Additional degree-4 invariants for e₂(M₃)
    
    Total independent invariants: ~20-25 (vs 5 at d=2).
    The Master Polynomial for d=3 has degree ~16 under statistical symmetry. -/
theorem invariant_count_summary (γ₁ γ₂ γ₃ : R)
    (S₁ S₂ S₃ : Matrix (Fin n) (Fin n) R) :
    -- e₁ uses exactly 7 invariants (proved above)
    trace ((1 - γ₃ • S₃) * (1 - γ₂ • S₂) * (1 - γ₁ • S₁)) =
    (Fintype.card (Fin n) : R)
    - γ₁ * trace S₁ - γ₂ * trace S₂ - γ₃ * trace S₃
    + γ₁ * γ₂ * trace (S₂ * S₁)
    + γ₁ * γ₃ * trace (S₃ * S₁)
    + γ₂ * γ₃ * trace (S₃ * S₂)
    - γ₁ * γ₂ * γ₃ * trace (S₃ * S₂ * S₁) ∧
    -- e₃ factors completely (proved above)
    det ((1 - γ₃ • S₃) * (1 - γ₂ • S₂) * (1 - γ₁ • S₁)) =
    det (1 - γ₃ • S₃) * det (1 - γ₂ • S₂) * det (1 - γ₁ • S₁) := by
  exact ⟨trace_expansion_K3 γ₁ γ₂ γ₃ S₁ S₂ S₃,
         det_factorises_K3 γ₁ γ₂ γ₃ S₁ S₂ S₃⟩