/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 4c51e673-b820-49a4-8a9b-6a7f9cbee6bc

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
We define the matrices $A_i = I - \gamma_i \Sigma_i$ and their product $M_{10} = A_{10} \dots A_1$. We then define the effective covariances for pairs ($\Sigma_{P_i}^{\text{eff}}$), pairs of pairs ($\Sigma_{Q_i}^{\text{eff}}$), and the residual ($\Sigma_{R}^{\text{eff}}$). Finally, we prove the identity $I - \Sigma_{Q_2}^{\text{eff}} (I - \Sigma_{R}^{\text{eff}}) (I - \Sigma_{Q_1}^{\text{eff}}) = M_{10}$ (with the order of multiplication corrected to match the indices).

```lean
noncomputable def A {d : Type} [Fintype d] [DecidableEq d] (Sigma : Fin 10 → Matrix d d ℝ) (gamma : Fin 10 → ℝ) (i : Fin 10) : Matrix d d ℝ :=
  1 - gamma i • Sigma i

noncomputable def M10 {d : Type} [Fintype d] [DecidableEq d] (Sigma : Fin 10 → Matrix d d ℝ) (gamma : Fin 10 → ℝ) : Matrix d d ℝ :=
  ((List.finRange 10).reverse.map (fun i => A Sigma gamma i)).prod

noncomputable def Sigma_P_eff {d : Type} [Fintype d] [DecidableEq d] (Sigma : Fin 10 → Matrix d d ℝ) (gamma : Fin 10 → ℝ) (i : Fin 5) : Matrix d d ℝ :=
  let i1 : Fin 10 := ⟨2 * i.val, by
    fin_cases i <;> decide⟩
  let i2 : Fin 10 := ⟨2 * i.val + 1, by
    native_decide +revert⟩
  gamma i1 • Sigma i1 + gamma i2 • Sigma i2 - (gamma i1 * gamma i2) • (Sigma i2 * Sigma i1)

noncomputable def Sigma_Q_eff {d : Type} [Fintype d] [DecidableEq d] (Sigma : Fin 10 → Matrix d d ℝ) (gamma : Fin 10 → ℝ) (i : Fin 2) : Matrix d d ℝ :=
  let P1 := Sigma_P_eff Sigma gamma ⟨2 * i.val, by
    fin_cases i <;> decide⟩
  let P2 := Sigma_P_eff Sigma gamma ⟨2 * i.val + 1, by
    fin_cases i <;> decide⟩
  P1 + P2 - P2 * P1

noncomputable def Sigma_R_eff {d : Type} [Fintype d] [DecidableEq d] (Sigma : Fin 10 → Matrix d d ℝ) (gamma : Fin 10 → ℝ) : Matrix d d ℝ :=
  Sigma_P_eff Sigma gamma 4

theorem effective_covariance_identity {d : Type} [Fintype d] [DecidableEq d] (Sigma : Fin 10 → Matrix d d ℝ) (gamma : Fin 10 → ℝ) :
  (1 - Sigma_R_eff Sigma gamma) * (1 - Sigma_Q_eff Sigma gamma 1) * (1 - Sigma_Q_eff Sigma gamma 0) = M10 Sigma gamma := by
  unfold Sigma_R_eff Sigma_Q_eff M10;
  -- Apply the pair identity to each pair effective covariance
  have h_pair : ∀ i : Fin 5, (1 - Sigma_P_eff Sigma gamma i) = (A Sigma gamma (⟨2 * i.val + 1, by
    fin_cases i <;> decide⟩)) * (A Sigma gamma (⟨2 * i.val, by
    decide +revert⟩)) := by
    unfold Sigma_P_eff A; simp +decide [ mul_sub, sub_mul ] ; ring;
    intro i; ext; norm_num; ring;
  generalize_proofs at *;
  -- Apply the nesting identity to each pair-of-pair effective covariance
  have h_nest : ∀ i : Fin 2, (1 - Sigma_Q_eff Sigma gamma i) = (A Sigma gamma (⟨2 * (2 * i.val + 1) + 1, by
    fin_cases i <;> trivial⟩)) * (A Sigma gamma (⟨2 * (2 * i.val + 1), by
    decide +revert⟩)) * (A Sigma gamma (⟨2 * (2 * i.val) + 1, by
    fin_cases i <;> trivial⟩)) * (A Sigma gamma (⟨2 * (2 * i.val), by
    decide +revert⟩)) := by
    intro i
    simp [Sigma_Q_eff, h_pair];
    convert congr_arg₂ ( · * · ) ( h_pair ⟨ 2 * i + 1, by fin_cases i <;> trivial ⟩ ) ( h_pair ⟨ 2 * i, by fin_cases i <;> trivial ⟩ ) using 1 <;> norm_num [ Fin.add_def, Fin.mul_def ] <;> ring!;
    · norm_num [ mul_sub, sub_mul ] ; abel_nf!;
    · rw [ mul_assoc ]
  generalize_proofs at *;
  simp_all +decide [ Fin.forall_fin_succ ];
  simp_all +decide [ Sigma_Q_eff, Sigma_P_eff ];
  simp +decide [ List.finRange, List.map ] ; ac_rfl;
```
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

/-
Define A_i = I - γ_i Σ_i
-/
noncomputable def A {d : Type} [Fintype d] [DecidableEq d] (Sigma : Fin 10 → Matrix d d ℝ) (gamma : Fin 10 → ℝ) (i : Fin 10) : Matrix d d ℝ :=
  1 - gamma i • Sigma i

/-
Define M10 = A_10 ... A_1 (product of A_i for i from 9 down to 0)
-/
noncomputable def M10 {d : Type} [Fintype d] [DecidableEq d] (Sigma : Fin 10 → Matrix d d ℝ) (gamma : Fin 10 → ℝ) : Matrix d d ℝ :=
  ((List.finRange 10).reverse.map (fun i => A Sigma gamma i)).prod

/-
Define pair effective covariances for i=1,...,5:
Σ_{Pᵢ}^{eff} = γ_{2i-1}Σ_{2i-1} + γ_{2i}Σ_{2i} − γ_{2i-1}γ_{2i}Σ_{2i}Σ_{2i-1}
-/
noncomputable def Sigma_P_eff {d : Type} [Fintype d] [DecidableEq d] (Sigma : Fin 10 → Matrix d d ℝ) (gamma : Fin 10 → ℝ) (i : Fin 5) : Matrix d d ℝ :=
  let i1 : Fin 10 := ⟨2 * i.val, by
    fin_cases i <;> decide⟩
  let i2 : Fin 10 := ⟨2 * i.val + 1, by
    native_decide +revert⟩
  gamma i1 • Sigma i1 + gamma i2 • Sigma i2 - (gamma i1 * gamma i2) • (Sigma i2 * Sigma i1)

/-
Define pair-of-pair effective covariances for i=1,2:
Σ_{Qᵢ}^{eff} = Σ_{P_{2i-1}}^{eff} + Σ_{P_{2i}}^{eff} − Σ_{P_{2i}}^{eff}Σ_{P_{2i-1}}^{eff}
-/
noncomputable def Sigma_Q_eff {d : Type} [Fintype d] [DecidableEq d] (Sigma : Fin 10 → Matrix d d ℝ) (gamma : Fin 10 → ℝ) (i : Fin 2) : Matrix d d ℝ :=
  let P1 := Sigma_P_eff Sigma gamma ⟨2 * i.val, by
    fin_cases i <;> decide⟩
  let P2 := Sigma_P_eff Sigma gamma ⟨2 * i.val + 1, by
    fin_cases i <;> decide⟩
  P1 + P2 - P2 * P1

/-
Define the residual effective covariance:
Σ_{R}^{eff} = Σ_{P₅}^{eff}
-/
noncomputable def Sigma_R_eff {d : Type} [Fintype d] [DecidableEq d] (Sigma : Fin 10 → Matrix d d ℝ) (gamma : Fin 10 → ℝ) : Matrix d d ℝ :=
  Sigma_P_eff Sigma gamma 4

/-
Prove that: I − Σ_{Q₂}^{eff} · (I − Σ_{R}^{eff}) · (I − Σ_{Q₁}^{eff}) = M₁₀
(Note: The order of multiplication in the formal statement has been corrected to R, Q2, Q1 to match the indices 10..1 of M10).
-/
theorem effective_covariance_identity {d : Type} [Fintype d] [DecidableEq d] (Sigma : Fin 10 → Matrix d d ℝ) (gamma : Fin 10 → ℝ) :
  (1 - Sigma_R_eff Sigma gamma) * (1 - Sigma_Q_eff Sigma gamma 1) * (1 - Sigma_Q_eff Sigma gamma 0) = M10 Sigma gamma := by
  unfold Sigma_R_eff Sigma_Q_eff M10;
  -- Apply the pair identity to each pair effective covariance
  have h_pair : ∀ i : Fin 5, (1 - Sigma_P_eff Sigma gamma i) = (A Sigma gamma (⟨2 * i.val + 1, by
    fin_cases i <;> decide⟩)) * (A Sigma gamma (⟨2 * i.val, by
    decide +revert⟩)) := by
    unfold Sigma_P_eff A; simp +decide [ mul_sub, sub_mul ] ; ring;
    intro i; ext; norm_num; ring;
  generalize_proofs at *;
  -- Apply the nesting identity to each pair-of-pair effective covariance
  have h_nest : ∀ i : Fin 2, (1 - Sigma_Q_eff Sigma gamma i) = (A Sigma gamma (⟨2 * (2 * i.val + 1) + 1, by
    fin_cases i <;> trivial⟩)) * (A Sigma gamma (⟨2 * (2 * i.val + 1), by
    decide +revert⟩)) * (A Sigma gamma (⟨2 * (2 * i.val) + 1, by
    fin_cases i <;> trivial⟩)) * (A Sigma gamma (⟨2 * (2 * i.val), by
    decide +revert⟩)) := by
    intro i
    simp [Sigma_Q_eff, h_pair];
    convert congr_arg₂ ( · * · ) ( h_pair ⟨ 2 * i + 1, by fin_cases i <;> trivial ⟩ ) ( h_pair ⟨ 2 * i, by fin_cases i <;> trivial ⟩ ) using 1 <;> norm_num [ Fin.add_def, Fin.mul_def ] <;> ring!;
    · norm_num [ mul_sub, sub_mul ] ; abel_nf!;
    · rw [ mul_assoc ]
  generalize_proofs at *;
  simp_all +decide [ Fin.forall_fin_succ ];
  simp_all +decide [ Sigma_Q_eff, Sigma_P_eff ];
  simp +decide [ List.finRange, List.map ] ; ac_rfl;