/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 509556e5-567f-4af2-9823-12dbec131be9

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
I have formalized and proved Theorem 1 (`e2_newton`) and Theorem 3 (`interleaved_quartic_nontrivial`).
Theorem 1 establishes the Newton identity relating the second elementary symmetric polynomial `e2` to the traces of `M` and `M^2`.
Theorem 3 proves the decomposition of the trace of the interleaved product `S₁ S₂ S₁ S₂` into a commutative part and a commutator part.
I did not formalize Theorem 2 or Theorem 4 as their statements were incomplete (missing the RHS polynomial for Theorem 2 and precise definitions for the invariant counting in Theorem 4).
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

/-
Define e2(M) as the coefficient of t^(n-2) in the characteristic polynomial of M.
-/
variable {n : Type*} [DecidableEq n] [Fintype n] {R : Type*} [CommRing R]

noncomputable def e2 (M : Matrix n n R) : R :=
  (M.charpoly).coeff (Fintype.card n - 2)

/-
trace(M)^2 - trace(M^2) equals the sum over i != j of (M_ii M_jj - M_ij M_ji).
-/
theorem trace_sq_sub_trace_sq (M : Matrix n n R) :
    (M.trace)^2 - (M^2).trace = ∑ i : n, ∑ j : n, if i ≠ j then M i i * M j j - M i j * M j i else 0 := by
      simp +decide only [Matrix.trace, sq];
      simp +decide [ Matrix.mul_apply, Finset.sum_ite, Finset.filter_ne ];
      simp +decide only [← Finset.mul_sum _ _ _, ← Finset.sum_mul]

/-
2 * sum_principal_minors_2(M) = trace(M)^2 - trace(M^2).
-/
noncomputable def sum_principal_minors_2 (M : Matrix n n R) : R :=
  ∑ s ∈ Finset.powersetCard 2 (Finset.univ : Finset n), (M.submatrix (Subtype.val : s → n) (Subtype.val : s → n)).det

theorem two_mul_sum_principal_minors_2_eq (M : Matrix n n R) :
    2 * sum_principal_minors_2 M = (M.trace)^2 - (M^2).trace := by
      rw [ trace_sq_sub_trace_sq ];
      unfold sum_principal_minors_2;
      -- Let's simplify the sum on the right-hand side.
      have h_simp_rhs : ∑ i : n, ∑ j : n, (if i ≠ j then M i i * M j j - M i j * M j i else 0) = ∑ s ∈ Finset.powersetCard 2 (Finset.univ : Finset n), (∑ i ∈ s, ∑ j ∈ s, if i ≠ j then M i i * M j j - M i j * M j i else 0) := by
        have h_sum_eq : ∀ i j : n, i ≠ j → (∑ s ∈ Finset.powersetCard 2 (Finset.univ : Finset n), if i ∈ s ∧ j ∈ s then (M i i * M j j - M i j * M j i) else 0) = (M i i * M j j - M i j * M j i) := by
          intro i j hij
          have h_subset : Finset.filter (fun s => i ∈ s ∧ j ∈ s) (Finset.powersetCard 2 (Finset.univ : Finset n)) = { {i, j} } := by
            ext s; simp [hij];
            exact ⟨ fun h => by rw [ Finset.eq_of_subset_of_card_le ( Finset.insert_subset_iff.mpr ⟨ h.2.1, Finset.singleton_subset_iff.mpr h.2.2 ⟩ ) ( by simp +decide [ *, Finset.card_insert_of_notMem ] ) ], fun h => by rw [ h ] ; simp +decide [ hij ] ⟩
          rw [Finset.sum_ite] at *; simp_all +decide [ Finset.sum_singleton, Finset.mem_powersetCard ] ;
        have h_sum_eq : ∑ i : n, ∑ j : n, (if i ≠ j then M i i * M j j - M i j * M j i else 0) = ∑ s ∈ Finset.powersetCard 2 (Finset.univ : Finset n), ∑ i : n, ∑ j : n, (if i ≠ j ∧ i ∈ s ∧ j ∈ s then M i i * M j j - M i j * M j i else 0) := by
          have h_sum_eq : ∑ i : n, ∑ j : n, (if i ≠ j then M i i * M j j - M i j * M j i else 0) = ∑ i : n, ∑ j : n, ∑ s ∈ Finset.powersetCard 2 (Finset.univ : Finset n), (if i ≠ j ∧ i ∈ s ∧ j ∈ s then M i i * M j j - M i j * M j i else 0) := by
            refine' Finset.sum_congr rfl fun i hi => Finset.sum_congr rfl fun j hj => _;
            by_cases hij : i = j <;> simp +decide [ hij, h_sum_eq ];
          rw [ h_sum_eq, Finset.sum_comm ];
          rw [ Finset.sum_comm, Finset.sum_congr rfl ] ; rw [ Finset.sum_comm ] ;
          exact fun i _ => Finset.sum_comm;
        rw [ h_sum_eq ];
        refine' Finset.sum_congr rfl fun s hs => _;
        rw [ ← Finset.sum_subset ( Finset.subset_univ s ) ];
        · refine' Finset.sum_congr rfl fun i hi => _;
          rw [ ← Finset.sum_subset ( Finset.subset_univ s ) ] ; aesop;
          grind;
        · simp +contextual [ Finset.sum_ite ];
      rw [ h_simp_rhs, Finset.mul_sum ];
      refine' Finset.sum_congr rfl fun s hs => _;
      rw [ Finset.mem_powersetCard ] at hs;
      obtain ⟨ i, j, hij ⟩ := Finset.card_eq_two.mp hs.2;
      rw [ Matrix.det_apply' ];
      rw [ show ( Finset.univ : Finset ( Equiv.Perm { x // x ∈ s } ) ) = { Equiv.refl _, Equiv.swap ⟨ i, by aesop ⟩ ⟨ j, by aesop ⟩ } from ?_ ] ; simp +decide [ Finset.sum_pair, hij ] ; ring;
      · rw [ Finset.sum_pair ] <;> simp +decide [ hij, Equiv.swap_apply_def ] ; ring;
        · rw [ show s.attach = { ⟨ i, by aesop ⟩, ⟨ j, by aesop ⟩ } from ?_ ] ; simp +decide [ hij, Finset.prod_pair, hij.1.symm ] ; ring;
          ext ⟨ x, hx ⟩ ; aesop;
        · simp +decide [ Equiv.Perm.ext_iff, hij ];
          exact ⟨ i, Or.inl rfl, by simp +decide [ hij.1, Equiv.swap_apply_def ] ⟩;
      · ext σ; simp [hij];
        rcases σ with ⟨ f, hf ⟩ ; simp_all +decide [ Equiv.Perm.ext_iff ] ;
        simp_all +decide [ Function.LeftInverse, Function.RightInverse, Equiv.swap_apply_def ];
        grind +ring

/-
If a permutation has support size > 2, its contribution to the (n-2)-th coefficient of the characteristic polynomial is 0.
-/
theorem charpoly_term_coeff_eq_zero_of_support_gt_two (M : Matrix n n R) (σ : Equiv.Perm n)
    (h : (Finset.univ.filter (fun i => σ i ≠ i)).card > 2) :
    (∏ i : n, (Polynomial.C (if i = σ i then 1 else 0) * Polynomial.X - Polynomial.C (M i (σ i)))).coeff (Fintype.card n - 2) = 0 := by
      rw [ Finset.prod_congr rfl ];
      rotate_right;
      exact fun i => if i = σ i then Polynomial.X - Polynomial.C ( M i ( σ i ) ) else -Polynomial.C ( M i ( σ i ) );
      · rw [ Finset.prod_ite ];
        rw [ Polynomial.coeff_eq_zero_of_natDegree_lt ];
        refine' lt_of_le_of_lt ( Polynomial.natDegree_mul_le .. ) _;
        refine' lt_of_le_of_lt ( add_le_add ( Polynomial.natDegree_prod_le _ _ ) ( Polynomial.natDegree_prod_le _ _ ) ) _ ; simp_all +decide [ Finset.filter_not, Finset.card_sdiff ];
        simp_all +decide [ eq_comm, Polynomial.X ];
        split_ifs <;> omega;
      · bound

/-
The coefficient of t^(n-2) in the product of (t - M_ii) is the sum of products of pairs of diagonal elements.
-/
theorem charpoly_term_coeff_identity (M : Matrix n n R) (h : Fintype.card n ≥ 2) :
    (∏ i : n, (Polynomial.X - Polynomial.C (M i i))).coeff (Fintype.card n - 2) =
    ∑ s ∈ Finset.powersetCard 2 (Finset.univ : Finset n), ∏ k ∈ s, M k k := by
      -- The coefficient of $t^{n-2}$ in the polynomial $\prod_{i} (t - M_{ii})$ is given by the elementary symmetric polynomial of degree 2.
      have h_coeff : (∏ i : n, (Polynomial.X - Polynomial.C (M i i))).coeff (Fintype.card n - 2) = ∑ s ∈ Finset.powersetCard 2 (Finset.univ : Finset n), ∏ k ∈ s, (-M k k) := by
        rw [ Finset.prod_congr rfl fun _ _ => sub_eq_add_neg _ _ ];
        erw [ Finset.prod_congr rfl fun _ _ => by rw [ ← Polynomial.C_neg ] ];
        erw [ Finset.prod_X_add_C_coeff ];
        · simp +decide [ Nat.sub_sub_self h ];
        · exact?;
      rw [ h_coeff, Finset.sum_congr rfl ] ; intros ; rw [ Finset.prod_congr rfl fun _ _ => neg_eq_neg_one_mul _, Finset.prod_mul_distrib ] ; aesop;

/-
For a transposition (i j), the coefficient of t^(n-2) in the corresponding term of the characteristic polynomial expansion is M_ij * M_ji.
-/
theorem charpoly_term_coeff_transposition (M : Matrix n n R) (i j : n) (h : i ≠ j) :
    let σ := Equiv.swap i j
    (∏ k : n, (Polynomial.C (if k = σ k then 1 else 0) * Polynomial.X - Polynomial.C (M k (σ k)))).coeff (Fintype.card n - 2) =
    M i j * M j i := by
      -- The product simplifies to $(-M_{ij})(-M_{ji}) \prod_{k \ne i,j} (t - M_{kk})$.
      have h_product_simplified : ∏ k : n, ((Polynomial.C : R → Polynomial R) (if k = (Equiv.swap i j) k then 1 else 0) * Polynomial.X - Polynomial.C (M k ((Equiv.swap i j) k))) =
        (-Polynomial.C (M i j)) * (-Polynomial.C (M j i)) * ∏ k ∈ Finset.univ \ {i, j}, (Polynomial.X - Polynomial.C (M k k)) := by
          rw [ ← Finset.prod_sdiff ( Finset.subset_univ { i, j } ) ];
          simp +decide [ Finset.prod_pair h, Equiv.swap_apply_def ];
          rw [ Finset.prod_congr rfl fun x hx => by aesop ] ; simp +decide [ h, eq_comm ] ; ring;
      -- The polynomial $\prod_{k \ne i,j} (t - M_{kk})$ is monic of degree $n-2$.
      have h_monic_deg : (∏ k ∈ Finset.univ \ {i, j}, (Polynomial.X - Polynomial.C (M k k))).coeff (Fintype.card n - 2) = 1 := by
        have h_monic_deg : (∏ k ∈ Finset.univ \ {i, j}, (Polynomial.X - Polynomial.C (M k k))) = Finset.prod (Finset.univ \ {i, j}) (fun k => Polynomial.X - Polynomial.C (M k k)) := by
          rfl;
        rw [ h_monic_deg, Finset.prod_congr rfl fun _ _ => sub_eq_add_neg _ _ ];
        erw [ Finset.prod_congr rfl fun _ _ => by rw [ ← Polynomial.C_neg ] ];
        erw [ Finset.prod_X_add_C_coeff ];
        · simp +decide [ Finset.card_sdiff, * ];
        · simp +decide [ Finset.card_sdiff, * ];
      simp_all +decide [ mul_assoc, Polynomial.coeff_C_mul ]

/-
The set of transpositions in S_n.
-/
def transpositions (n : Type*) [Fintype n] [DecidableEq n] : Finset (Equiv.Perm n) :=
  Finset.univ.filter (fun σ => (Finset.univ.filter (fun i => σ i ≠ i)).card = 2)

/-
The sum of the characteristic polynomial coefficients over all transpositions equals the sum of -M_ij * M_ji over all pairs {i, j}.
-/
theorem sum_transpositions_coeff_eq (M : Matrix n n R) (h : Fintype.card n ≥ 2) :
    ∑ σ ∈ transpositions n, (Equiv.Perm.sign σ : R) *
      (∏ i : n, (Polynomial.C (if i = σ i then 1 else 0) * Polynomial.X - Polynomial.C (M i (σ i)))).coeff (Fintype.card n - 2) =
    ∑ s ∈ Finset.powersetCard 2 (Finset.univ : Finset n),
      -(∏ i ∈ s, ∏ j ∈ s, if i ≠ j then M i j else 1) := by
        refine' Finset.sum_bij ( fun σ _ => Finset.univ.filter fun i => σ i ≠ i ) _ _ _ _;
        · unfold transpositions; aesop;
        · simp +contextual [ Finset.ext_iff, transpositions ];
          intro a₁ ha₁ a₂ ha₂ h_eq
          have h_support : Finset.filter (fun i => a₁ i ≠ i) Finset.univ = Finset.filter (fun i => a₂ i ≠ i) Finset.univ := by
            aesop
          have h_eq_on_support : ∀ i ∈ Finset.filter (fun i => a₁ i ≠ i) Finset.univ, a₁ i = a₂ i := by
            intro i hi; have := Finset.card_eq_two.mp ha₁; obtain ⟨ x, y, hxy ⟩ := this; simp_all +decide [ Finset.ext_iff ] ;
            have := h_eq ( a₁ x ) ; have := h_eq ( a₁ y ) ; have := hxy.2 ( a₂ x ) ; have := hxy.2 ( a₂ y ) ; simp_all +decide [ Equiv.Perm.eq_inv_iff_eq ] ;
            grind +ring
          have h_eq_all : ∀ i, a₁ i = a₂ i := by
            grind +ring
          exact Equiv.Perm.ext h_eq_all;
        · intro s hs; rw [ Finset.mem_powersetCard ] at hs; obtain ⟨ i, j, hij, rfl ⟩ := Finset.card_eq_two.mp hs.2; use Equiv.swap i j; simp_all +decide [ transpositions ] ;
          simp +decide [ Finset.ext_iff, Equiv.swap_apply_def, hij ];
          exact ⟨ by rw [ Finset.card_eq_two ] ; exact ⟨ i, j, by aesop ⟩, fun a => by by_cases ha : a = i <;> by_cases hb : a = j <;> aesop ⟩;
        · intro σ hσ
          obtain ⟨i, j, hij, hσ_eq⟩ : ∃ i j : n, i ≠ j ∧ σ = Equiv.swap i j := by
            have h_support : (Finset.univ.filter (fun i => σ i ≠ i)).card = 2 := by
              exact Finset.mem_filter.mp hσ |>.2;
            obtain ⟨ i, j, hij, h ⟩ := Finset.card_eq_two.mp h_support;
            refine' ⟨ i, j, hij, Equiv.ext fun x => _ ⟩;
            by_cases hx : x = i <;> by_cases hx' : x = j <;> simp_all +decide [ Finset.ext_iff ];
            · have := h ( σ i ) ; specialize h i ; aesop;
            · have := h ( σ j ) ; specialize h j ; aesop;
            · specialize h x; simp_all +decide [ Equiv.swap_apply_def ] ;
          simp_all +decide [ Finset.prod_ite, Finset.filter_ne ];
          convert charpoly_term_coeff_transposition M i j hij using 1;
          · exact congr_arg ( fun f => Polynomial.coeff f ( Fintype.card n - 2 ) ) ( Finset.prod_congr rfl fun x _ => by aesop );
          · rw [ show ( Finset.univ.filter fun x => ¬ ( Equiv.swap i j ) x = x ) = { i, j } from ?_ ];
            · simp +decide [ Finset.prod, hij ];
            · ext x; simp +decide [ Equiv.swap_apply_def, hij ] ; aesop;

/-
e2(M) is the sum of the contribution from the identity permutation and the contributions from all transpositions.
-/
theorem e2_eq_identity_plus_transpositions (M : Matrix n n R) (h : Fintype.card n ≥ 2) :
    e2 M = (∏ i : n, (Polynomial.X - Polynomial.C (M i i))).coeff (Fintype.card n - 2) +
           ∑ σ ∈ transpositions n, (Equiv.Perm.sign σ : R) *
             (∏ i : n, (Polynomial.C (if i = σ i then 1 else 0) * Polynomial.X - Polynomial.C (M i (σ i)))).coeff (Fintype.card n - 2) := by
               -- The coefficient `e2 M` is the sum over all $\sigma \in S_n$ of $\text{sgn}(\sigma)$ times the coefficient of $t^{n-2}$ in the product term.
               have h_coeff : e2 M = ∑ σ : Equiv.Perm n, (Equiv.Perm.sign σ : R) *
                 (∏ i : n, (Polynomial.C (if i = σ i then 1 else 0) * Polynomial.X - Polynomial.C (M i (σ i)))).coeff (Fintype.card n - 2) := by
                   unfold e2 Matrix.charpoly;
                   simp +decide [ Matrix.det_apply', Matrix.charmatrix ];
                   refine' Finset.sum_bij ( fun σ _ => σ⁻¹ ) _ _ _ _ <;> simp +decide;
                   · exact fun b => ⟨ b⁻¹, inv_inv b ⟩;
                   · intro σ; rw [ ← Equiv.prod_comp σ⁻¹ ] ; simp +decide [ Matrix.diagonal ] ;
               rw [ h_coeff, Finset.sum_eq_add_sum_diff_singleton <| Finset.mem_univ 1 ];
               have h_split_sum : ∀ σ : Equiv.Perm n, σ ≠ 1 → (Finset.univ.filter (fun i => σ i ≠ i)).card ≠ 2 →
                 ((Finset.univ.prod (fun i => Polynomial.C (if i = σ i then 1 else 0) * Polynomial.X - Polynomial.C (M i (σ i))))).coeff (Fintype.card n - 2) = 0 := by
                   intro σ hσ hσ';
                   apply charpoly_term_coeff_eq_zero_of_support_gt_two M σ;
                   contrapose! hσ'; interval_cases _ : Finset.card _ <;> simp_all +decide ;
                   · exact hσ ( Equiv.Perm.ext ‹_› );
                   · obtain ⟨ i, hi ⟩ := Finset.card_eq_one.mp ‹_›; simp_all +decide [ Finset.ext_iff ] ;
                     have := hi i; specialize hi ( σ i ) ; simp_all +decide ;
               rw [ ← Finset.sum_subset ( show transpositions n ⊆ Finset.univ \ { 1 } from fun x hx => ?_ ) ];
               · simp +decide;
               · intro σ hσ₁ hσ₂; specialize h_split_sum σ; simp_all +decide [ transpositions ] ;
               · unfold transpositions at hx; aesop;

/-
e2(M) equals sum_principal_minors_2(M).
-/
theorem e2_eq_sum_minors (M : Matrix n n R) (h : Fintype.card n ≥ 2) :
    e2 M = sum_principal_minors_2 M := by
      -- Let's express the sum of the principal minors of size 2 in terms of the characteristic polynomial.
      have h_sum_principal_minors_2 : ∑ s ∈ Finset.powersetCard 2 (Finset.univ : Finset n),
        (Matrix.det (Matrix.submatrix M (Subtype.val : s → n) (Subtype.val : s → n))) =
        ∑ s ∈ Finset.powersetCard 2 (Finset.univ : Finset n),
        (∏ k ∈ s, M k k) +
        ∑ s ∈ Finset.powersetCard 2 (Finset.univ : Finset n),
        -(∏ i ∈ s, ∏ j ∈ s, if i ≠ j then M i j else 1) := by
          rw [ ← Finset.sum_add_distrib ] ; refine' Finset.sum_congr rfl fun s hs => _ ; rw [ Finset.mem_powersetCard ] at hs ; rcases Finset.card_eq_two.mp hs.2 with ⟨ i, j, hij, rfl ⟩ ; simp +decide [ Finset.prod_ite, Finset.filter_ne, Finset.filter_eq, hij ] ; ring;
          erw [ Matrix.det_apply' ] ; simp +decide [ Finset.prod ] ; ring;
          erw [ show ( Finset.univ : Finset ( Equiv.Perm { x : n // x ∈ ( { i, j } : Finset n ) } ) ) = { 1, Equiv.swap ⟨ i, by simp +decide ⟩ ⟨ j, by simp +decide ⟩ } from ?_ ] ; simp +decide [ Finset.sum_pair, hij ] ; ring!;
          · rw [ Finset.sum_pair ] <;> simp +decide [ hij, Equiv.swap_apply_def ] ; ring!;
            · erw [ Multiset.dedup_singleton ] ; aesop;
            · exact Ne.symm ( by simp +decide [ Equiv.swap_apply_def, hij ] );
          · ext σ; simp [Finset.mem_insert, Finset.mem_singleton];
            by_cases hi : σ ⟨ i, by simp +decide ⟩ = ⟨ i, by simp +decide ⟩ <;> by_cases hj : σ ⟨ j, by simp +decide ⟩ = ⟨ j, by simp +decide ⟩ <;> simp_all +decide [ Equiv.Perm.ext_iff ];
            · exact Or.inl fun a ha => by rcases ha with ( rfl | rfl ) <;> assumption;
            · cases' eq_or_ne ( σ ⟨ j, by simp +decide ⟩ ) ⟨ i, by simp +decide ⟩ with h h <;> simp_all +decide [ Equiv.swap_apply_def ];
              · exact absurd ( σ.injective ( h.trans hi.symm ) ) ( by aesop );
              · grind;
            · cases' eq_or_ne ( σ ⟨ i, by simp +decide ⟩ ) ⟨ j, by simp +decide ⟩ with h h <;> simp_all +decide [ Equiv.swap_apply_def ];
              · exact absurd ( σ.injective ( h.trans hj.symm ) ) ( by aesop );
              · grind;
            · refine' Or.inr fun a ha => _;
              cases ha <;> simp_all +decide [ Equiv.swap_apply_def ];
              · grind;
              · grind;
      convert e2_eq_identity_plus_transpositions M h using 1;
      rw [ charpoly_term_coeff_identity, sum_transpositions_coeff_eq ] <;> aesop

/-
The second coefficient of the characteristic polynomial satisfies 2 * e2 = trace(M)^2 - trace(M^2).
-/
theorem e2_newton (M : Matrix n n R) (h : Fintype.card n ≥ 2) :
    2 * e2 M = (M.trace)^2 - (M^2).trace := by
      rw [ e2_eq_sum_minors M h, two_mul_sum_principal_minors_2_eq M ]

/-
trace(S1 * S2 * S1 * S2) = trace(S1^2 * S2^2) + trace(S1 * [S2, S1] * S2).
-/
variable {n : Type*} [DecidableEq n] [Fintype n] {R : Type*} [CommRing R]

theorem interleaved_quartic_nontrivial (S₁ S₂ : Matrix n n R) :
    (S₁ * S₂ * S₁ * S₂).trace =
    (S₁^2 * S₂^2).trace + (S₁ * (S₂ * S₁ - S₁ * S₂) * S₂).trace := by
      simp +decide [ sq, mul_sub, sub_mul, mul_assoc ]