/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 89f3f01e-f67a-405f-944c-5f6fa708b4a6

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
I have successfully loaded the user's code into the workspace.
The following declarations have been added and verified:
- `greedyStep_corrected`: The corrected greedy step definition.
- `corrected_base_equioscillation`: Theorem showing the base case gives equioscillation.
- `corrected_base_optimal`: Theorem showing the base case is optimal.
- `greedy_step_eliminates_bottleneck`: Theorem showing the greedy step eliminates the bottleneck.

All theorems have been proven by the ATP.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

noncomputable def greedyStep_corrected
    {d : Type*} [Fintype d] [DecidableEq d] [Nonempty d]
    {K : ℕ} (lam : Fin K → d → ℝ)
    (g_prev : Fin K → ℝ)
    (k : Fin K)
    (hlam : ∀ j, 0 < lam k j) : ℝ :=
  if k.val = 0 then
    -- Base: Chebyshev optimal for first task
    let lam_min_k := Finset.univ.inf' ⟨Classical.arbitrary d, Finset.mem_univ _⟩ (lam k)
    let lam_max_k := Finset.univ.sup' ⟨Classical.arbitrary d, Finset.mem_univ _⟩ (lam k)
    2 / (lam_min_k + lam_max_k)
  else
    -- Recursive: target bottleneck of prior cycle
    let j_star := (Finset.exists_max_image Finset.univ
      (fun j => ∏ i ∈ Finset.univ.filter (fun i : Fin K => i < k),
        |1 - g_prev i * lam i j|)
      ⟨Classical.arbitrary d, Finset.mem_univ _⟩).choose
    1 / lam k j_star

theorem corrected_base_equioscillation
    (lam_min lam_max : ℝ)
    (hmin : 0 < lam_min) (hle : lam_min ≤ lam_max) :
    let g := 2 / (lam_min + lam_max)
    |1 - g * lam_min| = |1 - g * lam_max| := by
      -- Substitute $g = \frac{2}{\lambda_{\min} + \lambda_{\max}}$ into the expressions.
      field_simp [hmin, hle];
      -- By simplifying, we can see that the absolute values are equal because the numerators are negatives of each other.
      have h_eq : 1 - 2 * lam_min / (lam_min + lam_max) = -(1 - 2 * lam_max / (lam_min + lam_max)) := by
        grind;
      -- Since the absolute value of a negative number is the same as the absolute value of the positive number, we can conclude that the absolute values are equal.
      rw [h_eq]
      simp [abs_neg];
      -- The absolute value of a difference is the same as the absolute value of the negative of that difference.
      rw [abs_sub_comm]

theorem corrected_base_optimal
    (lam_min lam_max gamma : ℝ)
    (hmin : 0 < lam_min) (hle : lam_min ≤ lam_max) (hg : 0 < gamma) :
    let g_star := 2 / (lam_min + lam_max)
    let rho_star := (lam_max - lam_min) / (lam_max + lam_min)
    rho_star ≤ max |1 - gamma * lam_min| |1 - gamma * lam_max| := by
      field_simp;
      rw [ div_le_iff₀ ] <;> cases max_cases |1 - lam_min * gamma| |1 - lam_max * gamma| <;> cases abs_cases ( 1 - lam_min * gamma ) <;> cases abs_cases ( 1 - lam_max * gamma ) <;> push_cast [ * ] at * <;> nlinarith [ mul_pos hg hmin ] ;

theorem greedy_step_eliminates_bottleneck
    {d : Type*} [Fintype d] [DecidableEq d] [Nonempty d]
    {K : ℕ} (lam : Fin K → d → ℝ)
    (g_prev : Fin K → ℝ)
    (k : Fin K)
    (hk : k.val ≠ 0)
    (hlam : ∀ j, 0 < lam k j) :
    let j_star := (Finset.exists_max_image Finset.univ
      (fun j => ∏ i ∈ Finset.univ.filter (fun i : Fin K => i < k),
        |1 - g_prev i * lam i j|)
      ⟨Classical.arbitrary d, Finset.mem_univ _⟩).choose
    1 - greedyStep_corrected lam g_prev k hlam * lam k j_star = 0 := by
      -- By definition of $j_star$, we have $1 - g_k * lam k j_star = 0$ because $g_k = 1 / lam k j_star$.
      simp [greedyStep_corrected, hk];
      grind