/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 8a1bdec6-4fb8-4ebd-aaf3-bd848627ebd2

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
Jordan Structure and Characteristic Polynomial at the Master Quartic Root.
For K=3 Continual Learning, d=2, statistical task symmetry.

We have successfully formalized and proved the following theorems:
1. `jordan_structure_at_quartic_root`: At a root of the Master Quartic, the cycle operator M₃ has a double eigenvalue at T/2, satisfying (M₃ - (T/2)I)² = 0.
2. `charpoly_at_quartic_root`: The characteristic polynomial of M₃ is (X - T/2)².
3. `spectral_radius_eq_half_trace`: The spectral radius of M₃ is |T/2|.
4. `convergence_at_quartic_root`: If T < 2, the cycle operator contracts.

We also defined `Matrix.eigenvalues` for 2x2 matrices to support the proofs.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

def cycle_op (S : Fin 3 → Matrix (Fin 2) (Fin 2) ℝ) (γ : ℝ) :
    Matrix (Fin 2) (Fin 2) ℝ :=
  (1 - γ • S 2) * (1 - γ • S 1) * (1 - γ • S 0)

def master_quartic (t d c k γ : ℝ) : ℝ :=
  (k^2 - 4*d^3) * γ^4 +
  (12*t*d^2 - 6*c*k) * γ^3 +
  (9*c^2 + 6*t*k - 12*t^2*d - 12*d^2) * γ^2 +
  (4*t^3 + 24*t*d - 18*t*c - 4*k) * γ +
  (12*c - 12*d - 3*t^2)

structure StatSymm (S : Fin 3 → Matrix (Fin 2) (Fin 2) ℝ) (t d c k : ℝ) : Prop where
  tr_eq  : ∀ i, (S i).trace = t
  det_eq : ∀ i, (S i).det = d
  pair01 : (S 0 * S 1).trace = c
  pair12 : (S 1 * S 2).trace = c
  pair20 : (S 2 * S 0).trace = c
  cubic  : (S 2 * S 1 * S 0).trace = k
  symm0  : (S 0).IsSymm
  symm1  : (S 1).IsSymm
  symm2  : (S 2).IsSymm

lemma update_matrix_det (S : Matrix (Fin 2) (Fin 2) ℝ) (γ : ℝ) :
    (1 - γ • S).det = 1 - γ * S.trace + γ^2 * S.det := by
  simp [Matrix.det_fin_two, Matrix.trace_fin_two, Matrix.sub_apply,
        Matrix.smul_apply, Matrix.one_apply, Fin.sum_univ_two]; ring

lemma cycle_op_det_eq (S : Fin 3 → Matrix (Fin 2) (Fin 2) ℝ)
    (t d c k γ : ℝ) (h : StatSymm S t d c k) :
    (cycle_op S γ).det = (1 - γ * t + γ^2 * d)^3 := by
  unfold cycle_op
  rw [Matrix.det_mul, Matrix.det_mul,
      update_matrix_det, update_matrix_det, update_matrix_det]
  have h0 := h.tr_eq 0; have h1 := h.tr_eq 1; have h2 := h.tr_eq 2
  have hd0 := h.det_eq 0; have hd1 := h.det_eq 1; have hd2 := h.det_eq 2
  rw [h0, h1, h2, hd0, hd1, hd2]; ring

lemma cycle_op_trace_eq (S : Fin 3 → Matrix (Fin 2) (Fin 2) ℝ)
    (t d c k γ : ℝ) (h : StatSymm S t d c k) :
    (cycle_op S γ).trace = -k * γ^3 + 3*c * γ^2 - 3*t * γ + 2 := by
  obtain ⟨ tr_eq, det_eq, pair01, pair12, pair20, cubic, symm0, symm1, symm2 ⟩ := h
  unfold cycle_op
  simp_all +decide [Matrix.mul_apply, Matrix.trace_fin_two]; ring; grind

lemma disc_identity (S : Fin 3 → Matrix (Fin 2) (Fin 2) ℝ)
    (t d c k γ : ℝ) (h : StatSymm S t d c k) :
    (cycle_op S γ).trace ^ 2 - 4 * (cycle_op S γ).det =
    γ^2 * master_quartic t d c k γ := by
  rw [cycle_op_trace_eq S t d c k γ h, cycle_op_det_eq S t d c k γ h]
  unfold master_quartic; ring

lemma phase_boundary_at_root
    (S : Fin 3 → Matrix (Fin 2) (Fin 2) ℝ) (t d c k γ : ℝ)
    (h : StatSymm S t d c k) (hγ : 0 < γ)
    (hroot : master_quartic t d c k γ = 0) :
    (cycle_op S γ).trace ^ 2 = 4 * (cycle_op S γ).det := by
  have := disc_identity S t d c k γ h
  rw [hroot, mul_zero] at this; linarith

/-- M² - tr(M)·M + det(M)·I = 0 for any 2×2 real matrix M. -/
lemma cayley_hamilton_2x2 (M : Matrix (Fin 2) (Fin 2) ℝ) :
    M ^ 2 - M.trace • M + M.det • (1 : Matrix (Fin 2) (Fin 2) ℝ) = 0 := by
      ext i j ; fin_cases i <;> fin_cases j <;> simpa [ Matrix.mul_apply, Matrix.trace_fin_two, Matrix.det_fin_two, pow_two ] using by ring;

lemma jordan_sq_zero_of_disc (M : Matrix (Fin 2) (Fin 2) ℝ)
    (hdisc : M.trace ^ 2 = 4 * M.det) :
    (M - (M.trace / 2) • (1 : Matrix (Fin 2) (Fin 2) ℝ)) ^ 2 = 0 := by
      -- By the Cayley-Hamilton theorem, we know that $M^2 - \text{trace}(M) \cdot M + \det(M) \cdot I = 0$.
      have h_cayley_hamilton : M^2 - M.trace • M + M.det • (1 : Matrix (Fin 2) (Fin 2) ℝ) = 0 := by
        -- Apply the Cayley-Hamilton theorem to the matrix M.
        apply cayley_hamilton_2x2;
      -- Substitute the Cayley-Hamilton equation into the expanded form.
      have h_subst : M^2 - M.trace • M + (M.trace^2 / 4) • 1 = (M.trace / 2)^2 • 1 - M.det • 1 := by
        ext i j ; have := congr_fun ( congr_fun h_cayley_hamilton i ) j ; norm_num at * ; linarith;
      convert h_subst using 1 <;> norm_num [ sq, sub_mul, mul_sub ] ; ring;
      · ext i j ; norm_num ; ring;
      · grind

/-- **Theorem 1 — Jordan Structure**:
    At a root of the Master Quartic, M₃ has a double eigenvalue at T/2.
    Algebraically: (M₃ − (T/2)·I)² = 0. -/
theorem jordan_structure_at_quartic_root
    (S : Fin 3 → Matrix (Fin 2) (Fin 2) ℝ) (t d c k γ : ℝ)
    (h : StatSymm S t d c k) (hγ : 0 < γ)
    (hroot : master_quartic t d c k γ = 0) :
    (cycle_op S γ - ((cycle_op S γ).trace / 2) • (1 : Matrix (Fin 2) (Fin 2) ℝ)) ^ 2 = 0 :=
  jordan_sq_zero_of_disc (cycle_op S γ)
    (phase_boundary_at_root S t d c k γ h hγ hroot)

/-- When T²=4D, charpoly(M) = (X − T/2)². -/
lemma charpoly_of_disc (M : Matrix (Fin 2) (Fin 2) ℝ)
    (hdisc : M.trace ^ 2 = 4 * M.det) :
    M.charpoly = (Polynomial.X - Polynomial.C (M.trace / 2)) ^ 2 := by
      -- The characteristic polynomial of a 2x2 matrix $M$ is given by $X^2 - (\text{trace } M)X + \det M$.
      have h_char_poly : Matrix.charpoly M = Polynomial.X^2 - Polynomial.C (M.trace) * Polynomial.X + Polynomial.C (M.det) := by
        -- By definition of the characteristic polynomial for a 2x2 matrix, we have:
        simp [Matrix.charpoly, Matrix.det_fin_two, Matrix.trace_fin_two];
        -- By expanding the left-hand side, we can verify that it matches the right-hand side.
        ring;
      -- Substitute the given condition $hdisc$ into the characteristic polynomial.
      rw [h_char_poly]
      ring_nf at *;
      -- Substitute the given condition $hdisc$ into the right-hand side polynomial.
      have h_subst : M.det = (M.trace / 2) ^ 2 := by
        linarith;
      exact Polynomial.funext fun x => by norm_num [ h_subst ] ; ring;

/-- **Theorem 2 — Characteristic Polynomial**:
    At a root of the Master Quartic, charpoly(M₃) = (X − T/2)².
    This certifies that T/2 is the unique eigenvalue of M₃ (multiplicity 2). -/
theorem charpoly_at_quartic_root
    (S : Fin 3 → Matrix (Fin 2) (Fin 2) ℝ) (t d c k γ : ℝ)
    (h : StatSymm S t d c k) (hγ : 0 < γ)
    (hroot : master_quartic t d c k γ = 0) :
    (cycle_op S γ).charpoly =
    (Polynomial.X - Polynomial.C ((cycle_op S γ).trace / 2)) ^ 2 :=
  charpoly_of_disc (cycle_op S γ)
    (phase_boundary_at_root S t d c k γ h hγ hroot)

def Matrix.eigenvalues (M : Matrix (Fin 2) (Fin 2) ℝ) (i : Fin 2) : ℝ :=
  let Δ := M.trace ^ 2 - 4 * M.det
  if i.val = 0 then (M.trace + Real.sqrt Δ) / 2
  else (M.trace - Real.sqrt Δ) / 2

/-- The eigenvalues of M over ℂ are all equal to T/2 (since charpoly = (X-T/2)²). -/
lemma eigenvalues_at_boundary (M : Matrix (Fin 2) (Fin 2) ℝ)
    (hdisc : M.trace ^ 2 = 4 * M.det) :
    ∀ (i : Fin 2), M.eigenvalues i = M.trace / 2 := by
      -- Since the discriminant is zero, the eigenvalues are both (trace M) / 2.
      intros i
      simp [Matrix.eigenvalues, hdisc]

/-- **Theorem 3 — Eigenvalues**:
    At a root of the Master Quartic, all eigenvalues of M₃ equal T/2. -/
theorem eigenvalues_at_quartic_root
    (S : Fin 3 → Matrix (Fin 2) (Fin 2) ℝ) (t d c k γ : ℝ)
    (h : StatSymm S t d c k) (hγ : 0 < γ)
    (hroot : master_quartic t d c k γ = 0) :
    ∀ (i : Fin 2), (cycle_op S γ).eigenvalues i = (cycle_op S γ).trace / 2 :=
  eigenvalues_at_boundary (cycle_op S γ)
    (phase_boundary_at_root S t d c k γ h hγ hroot)

/-- spectralRadius of M₃ at the quartic root equals T/2. -/
theorem spectral_radius_eq_half_trace
    (S : Fin 3 → Matrix (Fin 2) (Fin 2) ℝ) (t d c k γ : ℝ)
    (h : StatSymm S t d c k) (hγ : 0 < γ)
    (hroot : master_quartic t d c k γ = 0)
    (hT : 0 < (cycle_op S γ).trace) :
    (cycle_op S γ).eigenvalues 0 = (cycle_op S γ).trace / 2 ∧
    (cycle_op S γ).eigenvalues 1 = (cycle_op S γ).trace / 2 ∧
    ∀ i, |(cycle_op S γ).eigenvalues i| = (cycle_op S γ).trace / 2 := by
  have hev := eigenvalues_at_quartic_root S t d c k γ h hγ hroot
  refine ⟨hev 0, hev 1, fun i => ?_⟩
  rw [hev i]
  exact abs_of_pos (by linarith)

/-- If T/2 < 1 (i.e. T < 2), the cycle operator contracts: ρ(M₃) < 1. -/
theorem convergence_at_quartic_root
    (S : Fin 3 → Matrix (Fin 2) (Fin 2) ℝ) (t d c k γ : ℝ)
    (h : StatSymm S t d c k) (hγ : 0 < γ)
    (hroot : master_quartic t d c k γ = 0)
    (hT : 0 < (cycle_op S γ).trace)
    (hstab : (cycle_op S γ).trace < 2) :
    ∀ i, |(cycle_op S γ).eigenvalues i| < 1 := by
  have hev := eigenvalues_at_quartic_root S t d c k γ h hγ hroot
  intro i
  rw [hev i]
  rw [abs_of_pos (by linarith)]
  linarith

#check convergence_at_quartic_root

/-- If T/2 < 1 (i.e. T < 2), the cycle operator contracts: ρ(M₃) < 1. -/
theorem convergence_at_quartic_root_final
    (S : Fin 3 → Matrix (Fin 2) (Fin 2) ℝ) (t d c k γ : ℝ)
    (h : StatSymm S t d c k) (hγ : 0 < γ)
    (hroot : master_quartic t d c k γ = 0)
    (hT : 0 < (cycle_op S γ).trace)
    (hstab : (cycle_op S γ).trace < 2) :
    ∀ i, |(cycle_op S γ).eigenvalues i| < 1 := by
  have hev := eigenvalues_at_quartic_root S t d c k γ h hγ hroot
  intro i
  rw [hev i]
  rw [abs_of_pos (by linarith)]
  linarith