/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: a5321b62-1745-4742-b977-ae62032c7141

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
Quartic Survival at d=2

For K=4 with 2×2 covariance matrices, the γ₁γ₂γ₃γ₄ coefficient of
tr(M₄(γ)) is tr(Σ₄Σ₃Σ₂Σ₁). At d=2 this "SURVIVES" (is generically nonzero)
while the cubic terms vanish by palindrome symmetry (cubic_collapse_K4).

At d=2, the quartic tr(Σ₄Σ₃Σ₂Σ₁) can be expressed in scalar invariants
via the Cayley-Hamilton theorem for 2×2 matrices: S² = tr(S)·S − det(S)·I.
The d=2 Miracle (UUID 16894d9f) is a special case of this reduction.

Four theorems:
1. cayley_hamilton_2x2       — S² = tr(S)·S − det(S)·I (2×2 CH)
2. d2_miracle_via_CH         — tr(S₁S₂S₁S₂) = tr(S₁S₂)²−2·det(S₁)·det(S₂)
3. quartic_survival_witness  — integer witness: tr(S₄S₃S₂S₁) ≠ 0 (native_decide)
4. quartic_coeff_is_trace    — the γ₁γ₂γ₃γ₄ coefficient in tr(M₄) = tr(Σ₄Σ₃Σ₂Σ₁)

Proof techniques: Cayley-Hamilton at d=2 via fin_cases + ring;
                 native_decide for integer witness;
                 trace linearity for coefficient extraction.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

open Matrix

theorem cayley_hamilton_2x2 {R : Type*} [CommRing R]
    (S : Matrix (Fin 2) (Fin 2) R) :
    S ^ 2 = trace S • S - det S • (1 : Matrix (Fin 2) (Fin 2) R) := by
      -- By the Cayley-Hamilton theorem, we know that $S^2 - (\text{Trace}(S))S + (\det(S))I = 0$ for any $2 \times 2$ matrix $S$.
      have h_cayley_hamilton : S^2 - S.trace • S + S.det • 1 = 0 := by
        have h_char_poly : Matrix.charpoly S = Polynomial.X^2 - Polynomial.C (Matrix.trace S) * Polynomial.X + Polynomial.C (Matrix.det S) := by
          rw [ Matrix.charpoly ] ; simp +decide [ Matrix.det_fin_two, Matrix.trace_fin_two ] ; ring;
        rw [ ← Matrix.aeval_self_charpoly, h_char_poly ];
        simp +decide [ Algebra.smul_def ];
      exact eq_of_sub_eq_zero ( by rw [ ← h_cayley_hamilton ] ; abel1 )

theorem d2_miracle_via_CH {R : Type*} [CommRing R]
    (S1 S2 : Matrix (Fin 2) (Fin 2) R) :
    trace (S1 * S2 * (S1 * S2)) =
    trace (S1 * S2) ^ 2 - 2 * det S1 * det S2 := by
      -- Apply the formula for the trace of a square of a 2x2 matrix.
      have h_trace_sq : ∀ (M : Matrix (Fin 2) (Fin 2) R), Matrix.trace (M * M) = (Matrix.trace M)^2 - 2 * Matrix.det M := by
        -- Let's expand the trace of $M^2$ using the definition of matrix multiplication and the trace.
        intro M
        simp [Matrix.mul_apply, Matrix.trace];
        -- By expanding the right-hand side, we can verify the equality.
        simp [Matrix.det_fin_two]
        ring;
      rw [ h_trace_sq, mul_assoc, Matrix.det_mul ]

theorem quartic_survival_witness :
    let S1 : Matrix (Fin 2) (Fin 2) ℤ := !![1, 0; 0, 2]
    let S2 : Matrix (Fin 2) (Fin 2) ℤ := !![1, 1; 1, 2]
    let S3 : Matrix (Fin 2) (Fin 2) ℤ := !![1, 0; 0, 3]
    let S4 : Matrix (Fin 2) (Fin 2) ℤ := !![1, 0; 0, 1]
    trace (S4 * S3 * S2 * S1) ≠ 0 := by
  native_decide

theorem quartic_coeff_is_trace {R : Type*} [CommRing R]
    (g1 g2 g3 g4 : R) (S1 S2 S3 S4 : Matrix (Fin 2) (Fin 2) R) :
    let A1 := (1 : Matrix (Fin 2) (Fin 2) R) - g1 • S1
    let A2 := (1 : Matrix (Fin 2) (Fin 2) R) - g2 • S2
    let A3 := (1 : Matrix (Fin 2) (Fin 2) R) - g3 • S3
    let A4 := (1 : Matrix (Fin 2) (Fin 2) R) - g4 • S4
    trace (A4 * A3 * A2 * A1) =
      2                                              -- degree 0: tr(I) = 2 at d=2
      - g1 * trace S1 - g2 * trace S2
      - g3 * trace S3 - g4 * trace S4               -- degree 1
      + g1*g2 * trace (S2*S1) + g1*g3 * trace (S3*S1)
      + g1*g4 * trace (S4*S1) + g2*g3 * trace (S3*S2)
      + g2*g4 * trace (S4*S2) + g3*g4 * trace (S4*S3)  -- degree 2
      - g1*g2*g3 * trace (S3*S2*S1)
      - g1*g2*g4 * trace (S4*S2*S1)
      - g1*g3*g4 * trace (S4*S3*S1)
      - g2*g3*g4 * trace (S4*S3*S2)                -- degree 3
      + g1*g2*g3*g4 * trace (S4*S3*S2*S1) := by
        -- By expanding the product step by step and using the properties of the trace, we can simplify the expression.
        simp [Matrix.trace, Matrix.mul_assoc, Matrix.mul_sub, Matrix.sub_mul, Matrix.smul_mul, Matrix.mul_smul] at *;
        -- Combine like terms and simplify the expression.
        ring_nf at *

theorem quartic_survives_at_d2 :
    let S1 : Matrix (Fin 2) (Fin 2) ℤ := !![1, 0; 0, 2]
    let S2 : Matrix (Fin 2) (Fin 2) ℤ := !![1, 1; 1, 2]
    let S3 : Matrix (Fin 2) (Fin 2) ℤ := !![1, 0; 0, 3]
    let S4 : Matrix (Fin 2) (Fin 2) ℤ := !![1, 0; 0, 1]
    -- The quartic coefficient is the trace of the product
    trace (S4 * S3 * S2 * S1) ≠ 0 :=
  quartic_survival_witness