/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: a786aae7-0cdb-43e4-a645-093a88d0b396

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>

Aristotle's budget for this request has been reached.
If there is partial progress, it will appear in this file.
If you would like to continue working off of this partial progress,
please submit the same prompt, and add this .lean file in "Optional: Attach a Lean file as context" field.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

/-
The Master Quartic Polynomial f(γ) for the K=3 Continual Learning Cycle.
-/
def master_quartic (t d c k γ : ℝ) : ℝ :=
  (k^2 - 4*d^3)*γ^4 +
  (12*t*d^2 - 6*c*k)*γ^3 +
  (9*c^2 + 6*t*k - 12*t^2*d - 12*d^2)*γ^2 +
  (4*t^3 + 24*t*d - 18*t*c - 4*k)*γ +
  (12*c - 12*d - 3*t^2)

/-
The cycle operator for K=3 tasks, defined as the product of the update matrices (I - γ S_i).
-/
def cycle_operator (S : Fin 3 → Matrix (Fin 2) (Fin 2) ℝ) (γ : ℝ) : Matrix (Fin 2) (Fin 2) ℝ :=
  (1 - γ • S 2) * (1 - γ • S 1) * (1 - γ • S 0)

/-
Definitions of the system constants: Trace sum, Determinant sum, Pairwise trace sum, and Cubic Skew (which is 0 for symmetric matrices).
-/
def trace_sum (S : Fin 3 → Matrix (Fin 2) (Fin 2) ℝ) : ℝ :=
  (S 0).trace + (S 1).trace + (S 2).trace

def det_sum (S : Fin 3 → Matrix (Fin 2) (Fin 2) ℝ) : ℝ :=
  (S 0).det + (S 1).det + (S 2).det

def pairwise_sum (S : Fin 3 → Matrix (Fin 2) (Fin 2) ℝ) : ℝ :=
  (S 0 * S 1).trace + (S 1 * S 2).trace + (S 2 * S 0).trace

def cubic_skew (S : Fin 3 → Matrix (Fin 2) (Fin 2) ℝ) : ℝ := 0

/-
The cubic skew parameter, defined as the off-diagonal difference of the product S0 S1 S2.
-/
def system_skew (S : Fin 3 → Matrix (Fin 2) (Fin 2) ℝ) : ℝ :=
  (S 0 * S 1 * S 2) 0 1 - (S 0 * S 1 * S 2) 1 0

/-
The determinant of the cycle operator is the product of the determinants of the individual update matrices.
-/
lemma cycle_det_expansion
  (S : Fin 3 → Matrix (Fin 2) (Fin 2) ℝ)
  (γ : ℝ) :
  (cycle_operator S γ).det = (1 - γ * (S 0).trace + γ^2 * (S 0).det) *
                             (1 - γ * (S 1).trace + γ^2 * (S 1).det) *
                             (1 - γ * (S 2).trace + γ^2 * (S 2).det) := by
                               unfold cycle_operator;
                               norm_num [ Matrix.det_fin_two, Matrix.trace_fin_two ] ; ring;

/-
The trace of the cycle operator expanded in terms of γ, with the correct order of multiplication for the cubic term.
-/
lemma cycle_trace_expansion
  (S : Fin 3 → Matrix (Fin 2) (Fin 2) ℝ)
  (γ : ℝ) :
  (cycle_operator S γ).trace = 2 - γ * (S 0).trace - γ * (S 1).trace - γ * (S 2).trace +
                               γ^2 * ((S 0 * S 1).trace + (S 1 * S 2).trace + (S 2 * S 0).trace) -
                               γ^3 * ((S 2 * S 1 * S 0).trace) := by
                                 unfold cycle_operator; norm_num [ Matrix.trace, Matrix.mul_apply ] ; ring;

/-
The Jury stability criterion for a 2x2 matrix with trace T and determinant D: all eigenvalues are in the unit disk iff |D| < 1 and |T| < 1 + D.
-/
lemma stability_criterion_2x2 (T D : ℝ) :
  (∀ z : ℂ, z^2 - T * z + D = 0 → ‖z‖ < 1) ↔ |D| < 1 ∧ |T| < 1 + D := by
    constructor <;> intro h;
    · constructor;
      · -- By definition of polynomial roots, if $z^2 - Tz + D = 0$, then $z$ is a root of the polynomial.
        obtain ⟨z1, z2, hz⟩ : ∃ z1 z2 : ℂ, z1 + z2 = T ∧ z1 * z2 = D := by
          exact ⟨ ( T + ( T^2 - 4 * D ) ^ ( 1/2 : ℂ ) ) / 2, ( T - ( T^2 - 4 * D ) ^ ( 1/2 : ℂ ) ) / 2, by ring, by ring; rw [ ← Complex.cpow_nat_mul ] ; norm_num; ring ⟩;
        -- Since $|z_1| < 1$ and $|z_2| < 1$, we have $|z_1 z_2| < 1$.
        have h_prod : ‖z1 * z2‖ < 1 := by
          simpa using mul_lt_mul'' ( h z1 ( by linear_combination' hz.1 * z1 - hz.2 ) ) ( h z2 ( by linear_combination' hz.1 * z2 - hz.2 ) ) ( by positivity ) ( by positivity );
        aesop;
      · by_cases h_discriminant : T^2 - 4 * D ≥ 0;
        · have h_real_roots : ∀ z : ℝ, z^2 - T * z + D = 0 → |z| < 1 := by
            exact fun z hz => by simpa [ ← Complex.ofReal_inj ] using h z ( mod_cast hz ) ;
          have h1 := h_real_roots ( ( T + Real.sqrt ( T^2 - 4 * D ) ) / 2 ) ( by linarith [ Real.mul_self_sqrt h_discriminant ] ) ; have h2 := h_real_roots ( ( T - Real.sqrt ( T^2 - 4 * D ) ) / 2 ) ( by linarith [ Real.mul_self_sqrt h_discriminant ] ) ; rw [ abs_lt ] at * ; constructor <;> nlinarith [ Real.sqrt_nonneg ( T^2 - 4 * D ), Real.mul_self_sqrt h_discriminant ] ;
        · have := h ( ( T + Complex.I * Real.sqrt ( 4 * D - T ^ 2 ) ) / 2 ) ?_ <;> norm_num [ Complex.ext_iff, sq ] at *;
          · norm_num [ Complex.normSq, Complex.norm_def ] at this;
            rw [ Real.mul_self_sqrt ( by nlinarith ) ] at this ; rw [ div_lt_iff₀ ( by positivity ) ] at this ; rw [ Real.sqrt_lt' ] at this <;> cases abs_cases T <;> nlinarith [ Real.sqrt_nonneg ( 4 * D - T * T ), Real.mul_self_sqrt ( by nlinarith : 0 ≤ 4 * D - T * T ) ] ;
          · grind;
    · field_simp;
      intro z hz
      by_cases h_real : z.im = 0;
      · simp_all +decide [ Complex.ext_iff ];
        norm_num [ Complex.normSq, Complex.norm_def, h_real ];
        rw [ Real.sqrt_mul_self_eq_abs, abs_lt ] ; constructor <;> nlinarith [ abs_lt.mp h.1, abs_lt.mp h.2 ];
      · norm_num [ Complex.normSq, Complex.norm_def ] at *;
        norm_num [ Complex.ext_iff ] at *;
        rw [ Real.sqrt_lt' ] <;> cases lt_or_gt_of_ne h_real <;> cases abs_cases D <;> cases abs_cases T <;> nlinarith [ sq_nonneg ( z.re - 1 ), sq_nonneg ( z.re + 1 ) ]

/-
For symmetric matrices, tr(S0 S1 S2) = tr(S2 S1 S0).
-/
lemma trace_S0S1S2_eq_trace_S2S1S0
  (S : Fin 3 → Matrix (Fin 2) (Fin 2) ℝ)
  (h_symm : ∀ i, (S i).IsSymm) :
  (S 0 * S 1 * S 2).trace = (S 2 * S 1 * S 0).trace := by
    rw [ ← Matrix.trace_transpose ] ; simp +decide [ Matrix.mul_assoc, Matrix.transpose_mul, h_symm ] ;
    simp +decide only [h_symm _ |> Matrix.IsSymm.eq]

/-
Evaluating the Master Quartic and the discriminant for a test case to check for a relationship.
-/
def test_S : Fin 3 → Matrix (Fin 2) (Fin 2) ℝ :=
  ![ !![2, 0; 0, 1], !![1, 1; 1, 2], !![3, 0; 0, 1] ]

def test_vals : ℝ × ℝ :=
  let S := test_S
  let γ := 0.1
  let t := trace_sum S
  let d := det_sum S
  let c := pairwise_sum S
  let k := system_skew S
  let mq := master_quartic t d c k γ
  let disc := (cycle_operator S γ).trace ^ 2 - 4 * (cycle_operator S γ).det
  (mq, disc)

#eval test_vals

/-
Checking the values of the Master Quartic and the stability conditions for a test case.
-/
def check_vals : List (ℝ × ℝ × ℝ × ℝ) :=
  let S := test_S
  let t := trace_sum S
  let d := det_sum S
  let c := pairwise_sum S
  let k := system_skew S
  [0.1, 0.2, 0.5, 1.0].map fun γ =>
    let mq := master_quartic t d c k γ
    let M := cycle_operator S γ
    let stab1 := 1 + M.det - M.trace
    let stab2 := 1 - M.det
    let stab3 := 1 + M.det + M.trace
    (mq, stab1, stab2, stab3)

#eval check_vals

/-
Evaluating the Master Quartic and Discriminant on rational matrices to find the relationship.
-/
def master_quartic_rat (t d c k γ : ℚ) : ℚ :=
  (k^2 - 4*d^3)*γ^4 +
  (12*t*d^2 - 6*c*k)*γ^3 +
  (9*c^2 + 6*t*k - 12*t^2*d - 12*d^2)*γ^2 +
  (4*t^3 + 24*t*d - 18*t*c - 4*k)*γ +
  (12*c - 12*d - 3*t^2)

def cycle_operator_rat (S : Fin 3 → Matrix (Fin 2) (Fin 2) ℚ) (γ : ℚ) : Matrix (Fin 2) (Fin 2) ℚ :=
  (1 - γ • S 2) * (1 - γ • S 1) * (1 - γ • S 0)

def trace_sum_rat (S : Fin 3 → Matrix (Fin 2) (Fin 2) ℚ) : ℚ :=
  (S 0).trace + (S 1).trace + (S 2).trace

def det_sum_rat (S : Fin 3 → Matrix (Fin 2) (Fin 2) ℚ) : ℚ :=
  (S 0).det + (S 1).det + (S 2).det

def pairwise_sum_rat (S : Fin 3 → Matrix (Fin 2) (Fin 2) ℚ) : ℚ :=
  (S 0 * S 1).trace + (S 1 * S 2).trace + (S 2 * S 0).trace

def system_skew_rat (S : Fin 3 → Matrix (Fin 2) (Fin 2) ℚ) : ℚ :=
  (S 0 * S 1 * S 2) 0 1 - (S 0 * S 1 * S 2) 1 0

def test_S_rat : Fin 3 → Matrix (Fin 2) (Fin 2) ℚ :=
  ![ !![2, 0; 0, 1], !![1, 1; 1, 2], !![3, 0; 0, 1] ]

def check_poly_relation : List (ℚ × ℚ) :=
  let S := test_S_rat
  let t := trace_sum_rat S
  let d := det_sum_rat S
  let c := pairwise_sum_rat S
  let k := system_skew_rat S
  [1, 2, 3, 4, 5].map fun i =>
    let γ : ℚ := i
    let mq := master_quartic_rat t d c k γ
    let M := cycle_operator_rat S γ
    let disc := M.trace ^ 2 - 4 * M.det
    (mq, disc)

#eval check_poly_relation

/-
Checking the stability boundaries against the Master Quartic.
-/
def check_stability_boundaries : List (ℚ × ℚ × ℚ × ℚ) :=
  let S := test_S_rat
  let t := trace_sum_rat S
  let d := det_sum_rat S
  let c := pairwise_sum_rat S
  let k := system_skew_rat S
  [1, 2, 3, 4, 5].map fun i =>
    let γ : ℚ := i
    let mq := master_quartic_rat t d c k γ
    let M := cycle_operator_rat S γ
    let b1 := 1 - M.det
    let b2 := 1 + M.det - M.trace
    let b3 := 1 + M.det + M.trace
    (mq, b1, b2, b3)

#eval check_stability_boundaries

/-
Scanning for the root of the Master Quartic and checking stability boundaries.
-/
def check_root_search : List (ℚ × ℚ × ℚ × ℚ) :=
  let S := test_S_rat
  let t := trace_sum_rat S
  let d := det_sum_rat S
  let c := pairwise_sum_rat S
  let k := system_skew_rat S
  [1, 2, 3, 4, 5, 6, 7, 8, 9].map fun i =>
    let γ : ℚ := mkRat i 10
    let mq := master_quartic_rat t d c k γ
    let M := cycle_operator_rat S γ
    let b1 := 1 - M.det
    let b2 := 1 + M.det - M.trace
    let b3 := 1 + M.det + M.trace
    (mq, b1, b2, b3)

#eval check_root_search

/-
Checking the ratio between the discriminant and the Master Quartic.
-/
def check_ratio : List (ℚ × ℚ × ℚ) :=
  let S := test_S_rat
  let t := trace_sum_rat S
  let d := det_sum_rat S
  let c := pairwise_sum_rat S
  let k := system_skew_rat S
  [1, 2, 3].map fun i =>
    let γ : ℚ := mkRat i 10
    let mq := master_quartic_rat t d c k γ
    let M := cycle_operator_rat S γ
    let disc := M.trace ^ 2 - 4 * M.det
    (mq, disc, disc / mq)

#eval check_ratio

/-
Searching for a root of the Master Quartic between 0 and 0.1.
-/
def find_root_approx : List (ℚ × ℚ) :=
  let S := test_S_rat
  let t := trace_sum_rat S
  let d := det_sum_rat S
  let c := pairwise_sum_rat S
  let k := system_skew_rat S
  List.range 10 |>.map fun i =>
    let γ : ℚ := mkRat i 100
    let mq := master_quartic_rat t d c k γ
    (γ, mq)

#eval find_root_approx

/-
Checking if the Master Quartic is equal to (T^2 - 4D) / γ^2.
-/
def check_hypothesis : List (ℚ × ℚ × ℚ) :=
  let S := test_S_rat
  let t := trace_sum_rat S
  let d := det_sum_rat S
  let c := pairwise_sum_rat S
  let k := system_skew_rat S
  [1, 2, 3].map fun i =>
    let γ : ℚ := mkRat i 10
    let mq := master_quartic_rat t d c k γ
    let M := cycle_operator_rat S γ
    let disc := M.trace ^ 2 - 4 * M.det
    let ratio := disc / (γ^2)
    (mq, ratio, mq - ratio)

#eval check_hypothesis

/-
Refining the search for the root of the Master Quartic between 0.08 and 0.09 and checking the discriminant.
-/
def find_root_refined : List (ℚ × ℚ × ℚ) :=
  let S := test_S_rat
  let t := trace_sum_rat S
  let d := det_sum_rat S
  let c := pairwise_sum_rat S
  let k := system_skew_rat S
  -- Root is between 0.08 and 0.09
  List.range 11 |>.map fun i =>
    let γ : ℚ := mkRat (80 + i) 1000
    let mq := master_quartic_rat t d c k γ
    let M := cycle_operator_rat S γ
    let disc := M.trace ^ 2 - 4 * M.det
    (γ, mq, disc)

#eval find_root_refined

/-
Scanning for roots of the Master Quartic in the range [0, 10].
-/
def scan_roots : List (ℚ × ℚ) :=
  let S := test_S_rat
  let t := trace_sum_rat S
  let d := det_sum_rat S
  let c := pairwise_sum_rat S
  let k := system_skew_rat S
  List.range 20 |>.map fun i =>
    let γ : ℚ := mkRat i 2
    let mq := master_quartic_rat t d c k γ
    (γ, mq)

#eval scan_roots

/-
Checking which stability boundary (det=1, trace=1+det, trace=-(1+det)) is crossed at the root of the Master Quartic.
-/
def check_boundary_crossing : List (ℚ × ℚ × ℚ × ℚ × ℚ) :=
  let S := test_S_rat
  let t := trace_sum_rat S
  let d := det_sum_rat S
  let c := pairwise_sum_rat S
  let k := system_skew_rat S
  -- Root is between 0.08 and 0.09
  List.range 11 |>.map fun i =>
    let γ : ℚ := mkRat (80 + i) 1000
    let mq := master_quartic_rat t d c k γ
    let M := cycle_operator_rat S γ
    let b1 := 1 - M.det
    let b2 := 1 + M.det - M.trace
    let b3 := 1 + M.det + M.trace
    (γ, mq, b1, b2, b3)

#eval check_boundary_crossing