/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: abd10bab-df1e-48b1-a718-2c97460a7ef4

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
This file proves the optimality of the step size gamma* = 2/(lam_min + lam_max) for a single task optimization problem, showing it minimizes the convergence rate rho. It verifies that the optimal rate is rho* = (lam_max - lam_min) / (lam_max + lam_min).
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

open Matrix


variable {d : Type*} [Fintype d] [DecidableEq d]

theorem single_task_rho
    (lam_min lam_max gamma : ℝ)
    (hmin : 0 < lam_min) (hle : lam_min ≤ lam_max) (hg : 0 < gamma) :
    max |1 - gamma * lam_min| |1 - gamma * lam_max| =
    max (|1 - gamma * lam_min|) (|1 - gamma * lam_max|) := rfl

theorem single_task_optimal_gamma
    (lam_min lam_max : ℝ)
    (hmin : 0 < lam_min) (hle : lam_min ≤ lam_max) :
    let gamma_star := 2 / (lam_min + lam_max)
    |1 - gamma_star * lam_min| = |1 - gamma_star * lam_max| := by
      field_simp;
      -- Combine the fractions and simplify the numerators.
      have h_num : 1 - 2 * lam_min / (lam_min + lam_max) = (lam_max - lam_min) / (lam_min + lam_max) ∧ 1 - 2 * lam_max / (lam_min + lam_max) = (lam_min - lam_max) / (lam_min + lam_max) := by
        grind;
      -- Since $|a| = |-a|$ for any real number $a$, we can conclude that $|(lam_max - lam_min) / (lam_min + lam_max)| = |(lam_min - lam_max) / (lam_min + lam_max)|$.
      rw [h_num.left, h_num.right]
      simp [abs_div];
      -- Since $|a - b| = |b - a|$ for any real numbers $a$ and $b$, we can conclude that $|lam_max - lam_min| = |lam_min - lam_max|$.
      rw [abs_sub_comm]

theorem single_task_optimal_rho
    (lam_min lam_max : ℝ)
    (hmin : 0 < lam_min) (hle : lam_min ≤ lam_max) :
    let gamma_star := 2 / (lam_min + lam_max)
    let rho_star := (lam_max - lam_min) / (lam_max + lam_min)
    max |1 - gamma_star * lam_min| |1 - gamma_star * lam_max| = rho_star := by
      -- By simplifying, we can see that both expressions equal $(lam_max - lam_min) / (lam_min + lam_max)$.
      field_simp [hmin, hle]
      ring;
      -- By simplifying, we can see that both expressions inside the absolute values are equal.
      have h_simp : |1 - lam_min * (lam_min + lam_max)⁻¹ * 2| = (lam_max - lam_min) / (lam_min + lam_max) ∧ |1 - lam_max * (lam_min + lam_max)⁻¹ * 2| = (lam_max - lam_min) / (lam_min + lam_max) := by
        -- By simplifying, we can see that both expressions inside the absolute values are equal to $(lam_max - lam_min) / (lam_min + lam_max)$.
        field_simp [hmin, hle];
        -- By simplifying, we can see that both expressions inside the absolute values are equal to $(lam_max - lam_min) / (lam_min + lam_max)$, thus their absolute values are equal.
        apply And.intro;
        · rw [ abs_of_nonneg ] <;> ring_nf <;> nlinarith [ inv_mul_cancel₀ ( by linarith : ( lam_min + lam_max ) ≠ 0 ) ];
        · rw [ abs_of_nonpos ] <;> nlinarith [ mul_div_cancel₀ ( lam_max * 2 ) ( by linarith : ( lam_min + lam_max ) ≠ 0 ), mul_div_cancel₀ ( lam_max - lam_min ) ( by linarith : ( lam_min + lam_max ) ≠ 0 ) ];
      rw [ h_simp.1, h_simp.2, max_self ] ; ring

theorem single_task_optimal_is_minimiser
    (lam_min lam_max gamma : ℝ)
    (hmin : 0 < lam_min) (hle : lam_min ≤ lam_max) (hg : 0 < gamma) :
    let gamma_star := 2 / (lam_min + lam_max)
    let rho_star := (lam_max - lam_min) / (lam_max + lam_min)
    rho_star ≤ max |1 - gamma * lam_min| |1 - gamma * lam_max| := by
      -- By considering the maximum of the two expressions, we can see that it is minimized when they are equal.
      have h_max : ∀ gamma : ℝ, 0 < gamma → max (|1 - gamma * lam_min|) (|1 - gamma * lam_max|) ≥ (lam_max - lam_min) / (lam_max + lam_min) := by
        -- By considering the two cases, we can see that the maximum of the absolute values is always at least (lam_max - lam_min)/(lam_max + lam_min).
        intros gamma hg
        by_cases h_case : |1 - gamma * lam_min| ≥ |1 - gamma * lam_max|;
        · rw [ max_eq_left h_case ] ; exact by rw [ ge_iff_le ] ; rw [ div_le_iff₀ ] <;> cases abs_cases ( 1 - gamma * lam_min ) <;> cases abs_cases ( 1 - gamma * lam_max ) <;> nlinarith;
        · rw [ max_eq_right ( le_of_not_ge h_case ) ];
          cases abs_cases ( 1 - gamma * lam_min ) <;> cases abs_cases ( 1 - gamma * lam_max ) <;> nlinarith [ mul_div_cancel₀ ( lam_max - lam_min ) ( by linarith : ( lam_max + lam_min ) ≠ 0 ) ];
      exact h_max _ hg