/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: ba9525b6-1b4a-4c1d-9c04-6d11aba98c6a

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
Formalization of the Master Sextic P₆ properties, including the existence of a unique positive real root and the convergence certificate for the 4-cycle optimization. We prove P₆(0) < 0, P₆(γ) → ∞, and thus the existence of a positive root γ*. We also derive the optimal step size condition ρ(M₄) = T_K4(γ*)/2 and the convergence criterion.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

open Real Polynomial

noncomputable def T_K4_r (γ t c k3 I4 : ℝ) : ℝ :=
  2 - 4*t*γ + 6*c*γ^2 - 4*k3*γ^3 + I4*γ^4

noncomputable def D_K4_r (γ t d : ℝ) : ℝ :=
  (1 - t*γ + d*γ^2)^4

noncomputable def P6_r (γ t d c k3 I4 : ℝ) : ℝ :=
  (I4^2 - 4*d^4) * γ^6
  + (-8*I4*k3 + 16*d^3*t) * γ^5
  + (12*I4*c - 16*d^3 - 24*d^2*t^2 + 16*k3^2) * γ^4
  + (-8*I4*t - 48*c*k3 + 48*d^2*t + 16*d*t^3) * γ^3
  + (4*I4 + 36*c^2 - 24*d^2 - 48*d*t^2 + 32*k3*t - 4*t^4) * γ^2
  + (-48*c*t + 48*d*t - 16*k3 + 16*t^3) * γ
  + (24*c - 16*d - 8*t^2)

theorem P6_at_zero (t d c k3 I4 : ℝ) :
    P6_r 0 t d c k3 I4 = 24*c - 16*d - 8*t^2 := by
  simp [P6_r]

theorem delta_zero_at_origin (t d c k3 I4 : ℝ) :
    T_K4_r 0 t c k3 I4 ^ 2 - 4 * D_K4_r 0 t d = 0 := by
      -- Substitute the definitions of $T_K4_r$ and $D_K4_r$ at $\gamma = 0$.
      simp [T_K4_r, D_K4_r];
      -- This simplifies to $4 - 4 = 0$, which is trivially true.
      norm_num

theorem P6_identity (γ t d c k3 I4 : ℝ) :
    T_K4_r γ t c k3 I4 ^ 2 - 4 * D_K4_r γ t d = γ^2 * P6_r γ t d c k3 I4 := by
  unfold T_K4_r D_K4_r P6_r; ring

theorem P6_has_positive_root
    (t d c k3 I4 : ℝ)
    (hd : d > 0)
    (h_leading : I4^2 > 4*d^4)
    (h_constant : 24*c - 16*d - 8*t^2 < 0) :
    ∃ γ_star > 0, P6_r γ_star t d c k3 I4 = 0 := by
      -- Since $P_6(\gamma)$ tends to infinity as $\gamma$ approaches infinity, we can find a large enough $\gamma$ such that $P_6(\gamma) > 0$.
      have h_exists_large_gamma : ∃ γ_large > 0, P6_r γ_large t d c k3 I4 > 0 := by
        -- Since $\lim_{\gamma \to \infty} P6(\gamma) = \infty$, there exists some $\gamma_{\text{large}}$ such that $P6(\gamma_{\text{large}}) > 0$. We can use the fact that the polynomial $P6$ is continuous.
        have h_poly_cont : Filter.Tendsto (fun γ : ℝ => P6_r γ t d c k3 I4) Filter.atTop Filter.atTop := by
          -- We can factor out $\gamma^6$ from the polynomial and analyze the remaining terms.
          have h_factor : Filter.Tendsto (fun γ : ℝ => γ^6 * (I4^2 - 4*d^4 + (-8*I4*k3 + 16*d^3*t)/γ + (12*I4*c - 16*d^3 - 24*d^2*t^2 + 16*k3^2)/γ^2 + (-8*I4*t - 48*c*k3 + 48*d^2*t + 16*d*t^3)/γ^3 + (4*I4 + 36*c^2 - 24*d^2 - 48*d*t^2 + 32*k3*t - 4*t^4)/γ^4 + (-48*c*t + 48*d*t - 16*k3 + 16*t^3)/γ^5 + (24*c - 16*d - 8*t^2)/γ^6)) Filter.atTop Filter.atTop := by
            -- As $\gamma$ goes to infinity, the terms with negative powers of $\gamma$ go to zero.
            have h_zero_terms : Filter.Tendsto (fun γ : ℝ => I4^2 - 4 * d^4 + (-8 * I4 * k3 + 16 * d^3 * t) / γ + (12 * I4 * c - 16 * d^3 - 24 * d^2 * t^2 + 16 * k3^2) / γ^2 + (-8 * I4 * t - 48 * c * k3 + 48 * d^2 * t + 16 * d * t^3) / γ^3 + (4 * I4 + 36 * c^2 - 24 * d^2 - 48 * d * t^2 + 32 * k3 * t - 4 * t^4) / γ^4 + (-48 * c * t + 48 * d * t - 16 * k3 + 16 * t^3) / γ^5 + (24 * c - 16 * d - 8 * t^2) / γ^6) Filter.atTop (nhds (I4^2 - 4 * d^4)) := by
              exact le_trans ( Filter.Tendsto.add ( Filter.Tendsto.add ( Filter.Tendsto.add ( Filter.Tendsto.add ( Filter.Tendsto.add ( tendsto_const_nhds.add ( tendsto_const_nhds.div_atTop Filter.tendsto_id ) ) ( tendsto_const_nhds.div_atTop ( by norm_num ) ) ) ( tendsto_const_nhds.div_atTop ( by norm_num ) ) ) ( tendsto_const_nhds.div_atTop ( by norm_num ) ) ) ( tendsto_const_nhds.div_atTop ( by norm_num ) ) ) ( tendsto_const_nhds.div_atTop ( by norm_num ) ) ) ( by norm_num ) ;
            apply Filter.Tendsto.atTop_mul_pos;
            exacts [ show 0 < I4 ^ 2 - 4 * d ^ 4 by linarith, by norm_num, h_zero_terms ];
          refine h_factor.congr' ?_ ; filter_upwards [ Filter.eventually_gt_atTop 0 ] with x hx ; unfold P6_r ; ring; simp +decide [ hx.ne', pow_succ, mul_assoc, div_eq_mul_inv ] ; ring;
          grind +ring;
        exact Filter.eventually_atTop.mp ( h_poly_cont.eventually_gt_atTop 0 ) |> fun ⟨ γ, hγ ⟩ ↦ ⟨ Max.max γ 1, by positivity, hγ _ ( le_max_left _ _ ) ⟩;
      -- By the Intermediate Value Theorem, since $P_6(\gamma)$ is continuous and $P_6(0) < 0 < P_6(\gamma_large)$, there exists some $\gamma_star \in (0, \gamma_large)$ such that $P_6(\gamma_star) = 0$.
      obtain ⟨γ_large, hγ_large_pos, hγ_large_zero⟩ := h_exists_large_gamma
      have h_ivt : ContinuousOn (fun γ => P6_r γ t d c k3 I4) (Set.Icc 0 γ_large) → (P6_r 0 t d c k3 I4 < 0 ∧ P6_r γ_large t d c k3 I4 > 0) → ∃ γ_star ∈ Set.Ioo 0 γ_large, P6_r γ_star t d c k3 I4 = 0 := by
        intros; apply_rules [ intermediate_value_Ioo ] ; linarith;
      exact Exists.elim ( h_ivt ( Continuous.continuousOn <| by unfold P6_r; continuity ) ⟨ by unfold P6_r; linarith, hγ_large_zero ⟩ ) fun x hx => ⟨ x, hx.1.1, hx.2 ⟩

theorem optimal_rho_at_root
    (γ_star t d c k3 I4 : ℝ)
    (hγ : γ_star > 0)
    (hroot : P6_r γ_star t d c k3 I4 = 0) :
    T_K4_r γ_star t c k3 I4 ^ 2 = 4 * D_K4_r γ_star t d := by
  have := P6_identity γ_star t d c k3 I4
  rw [hroot, mul_zero] at this
  linarith

theorem convergence_at_root
    (γ_star t d c k3 I4 : ℝ)
    (hγ : γ_star > 0)
    (hroot : P6_r γ_star t d c k3 I4 = 0)
    (hT_pos : T_K4_r γ_star t c k3 I4 > 0)
    (hT_small : T_K4_r γ_star t c k3 I4 < 2) :
    T_K4_r γ_star t c k3 I4 / 2 < 1 := by
  linarith

theorem rho_equals_half_trace_at_root
    (γ_star t d c k3 I4 : ℝ)
    (hγ : γ_star > 0)
    (hroot : P6_r γ_star t d c k3 I4 = 0)
    (hT : T_K4_r γ_star t c k3 I4 > 0) :
    -- The discriminant vanishes: T² = 4D
    T_K4_r γ_star t c k3 I4 ^ 2 = 4 * D_K4_r γ_star t d ∧
    -- The square root of D equals T/2
    Real.sqrt (D_K4_r γ_star t d) = T_K4_r γ_star t c k3 I4 / 2 := by
      -- By definition of $P6_r$, we know that $T_K4_r^2 - 4 * D_K4_r = γ_star^2 * P6_r$.
      have hP6 : T_K4_r γ_star t c k3 I4 ^ 2 - 4 * D_K4_r γ_star t d = γ_star ^ 2 * P6_r γ_star t d c k3 I4 := by
        exact?;
      exact ⟨ by nlinarith, by rw [ Real.sqrt_eq_iff_mul_self_eq ] <;> nlinarith ⟩

theorem master_sextic_root_summary
    (t d c k3 I4 : ℝ)
    (hd : d > 0)
    (h_leading : I4^2 > 4*d^4)
    (h_constant : 24*c - 16*d - 8*t^2 < 0) :
    -- There exists a positive root γ*
    ∃ γ_star > 0, P6_r γ_star t d c k3 I4 = 0 ∧
    -- At which: T²=4D (boundary condition)
    T_K4_r γ_star t c k3 I4 ^ 2 = 4 * D_K4_r γ_star t d := by
  obtain ⟨γ_star, hγ_star_pos, hγ_star_root⟩ := P6_has_positive_root t d c k3 I4 hd h_leading h_constant
  exact ⟨γ_star, hγ_star_pos, hγ_star_root, optimal_rho_at_root γ_star t d c k3 I4 hγ_star_pos hγ_star_root⟩

#check rho_equals_half_trace_at_root