/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: bebabb9f-3ac3-4014-b101-33816f9c1b4e

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
Formalized the stability margin analysis for K=3 Non-Commutative Continual Learning.
Defined the Master Quartic polynomial `T3` and the stability discriminant `stab_disc`.
Proved that the stability boundary is at `γ_NF` where `T3(γ_NF) = 2`.
Proved the main stability certificate `stability_certificate_K3`, showing that if `γ* < γ_NF` and the quadratic condition holds, then the system is stable (`T3(γ*) < 2`).
Note: The helper lemma `γ_NF_pos` was corrected to include the necessary hypothesis `t > 0`, which was present in the main theorem but missing from the lemma's original statement.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

def T3 (t c k γ : ℝ) : ℝ := 2 - 3*t*γ + 3*c*γ^2 - k*γ^3

theorem T3_at_zero (t c k : ℝ) : T3 t c k 0 = 2 := by unfold T3; ring

theorem T3_minus_2_factors (t c k γ : ℝ) :
    T3 t c k γ - 2 = -γ * (k*γ^2 - 3*c*γ + 3*t) := by unfold T3; ring

theorem T3_below_2 (t c k γ : ℝ) (hγ : 0 < γ) (hq : k*γ^2 - 3*c*γ + 3*t > 0) :
    T3 t c k γ < 2 := by nlinarith [T3_minus_2_factors t c k γ, mul_pos hγ hq]

def stab_disc (t c k : ℝ) : ℝ := 9*c^2 - 12*k*t

def γ_NF (t c k : ℝ) : ℝ := (3*c + Real.sqrt (stab_disc t c k)) / (2*k)

theorem γ_NF_is_root (t c k : ℝ) (hk : k > 0) (hd : stab_disc t c k ≥ 0) :
    k * (γ_NF t c k)^2 - 3*c * (γ_NF t c k) + 3*t = 0 := by
      -- Substitute γ_NF into the quadratic equation and simplify.
      have h_quad : k * ((3 * c + Real.sqrt (9 * c ^ 2 - 12 * k * t)) / (2 * k)) ^ 2 - 3 * c * ((3 * c + Real.sqrt (9 * c ^ 2 - 12 * k * t)) / (2 * k)) + 3 * t = 0 := by
        -- Combine and simplify the terms in the numerator.
        field_simp
        ring;
        -- Since $c^2 * 9 - k * t * 12 \geq 0$, we can apply the property of square roots.
        have h_nonneg : c^2 * 9 - k * t * 12 ≥ 0 := by
          convert hd using 1 ; unfold stab_disc ; ring;
        rw [ Real.sq_sqrt h_nonneg ] ; ring;
      -- Substitute the definition of γ_NF into the goal.
      convert h_quad using 1

theorem T3_at_boundary (t c k : ℝ) (hk : k > 0) (hd : stab_disc t c k ≥ 0) :
    T3 t c k (γ_NF t c k) = 2 := by
      -- Substitute γ_NF into the expression for T3 and simplify.
      have h_T3_gamma_NF : T3 t c k (γ_NF t c k) - 2 = -γ_NF t c k * (k * (γ_NF t c k)^2 - 3 * c * (γ_NF t c k) + 3 * t) := by
        -- Substitute the definition of T3 into the expression.
        rw [T3];
        -- By expanding the right-hand side, we can see that it simplifies to the left-hand side.
        ring;
      -- Substitute γ_NF into the quadratic equation and simplify.
      have h_quad_eq : k * (γ_NF t c k)^2 - 3 * c * (γ_NF t c k) + 3 * t = 0 := by
        -- Apply the theorem that states γ_NF is a root of the quadratic equation.
        apply γ_NF_is_root t c k hk hd;
      -- Substitute h_quad_eq into h_T3_gamma_NF to get T3 t c k (γ_NF t c k) - 2 = 0.
      rw [h_quad_eq] at h_T3_gamma_NF
      simp at h_T3_gamma_NF
      linarith

def stability_margin (γ_star γ_NF : ℝ) : ℝ := γ_NF - γ_star

theorem stability_margin_pos (γ_star γ_NF : ℝ) (h : γ_star < γ_NF) :
    stability_margin γ_star γ_NF > 0 := by unfold stability_margin; linarith

theorem stability_certificate_K3 (t c k γ_star : ℝ)
    (hk : k > 0) (ht : t > 0) (hc : c ≥ 0)
    (hd : stab_disc t c k ≥ 0)
    (hγ_pos : 0 < γ_star)
    (hγ_lt : γ_star < γ_NF t c k)
    (hquad : ∀ x : ℝ, 0 < x → x < γ_NF t c k → k*x^2 - 3*c*x + 3*t > 0) :
    0 < γ_NF t c k ∧
    stability_margin γ_star (γ_NF t c k) > 0 ∧
    T3 t c k γ_star < 2 ∧
    (∀ γ : ℝ, 0 < γ → γ < γ_NF t c k → T3 t c k γ < 2) ∧
    T3 t c k (γ_NF t c k) = 2 := by
      refine' ⟨ _, _, _, _, _ ⟩;
      · linarith;
      · exact sub_pos_of_lt hγ_lt;
      · exact?;
      · exact?;
      · exact?

theorem γ_NF_pos (t c k : ℝ) (hk : k > 0) (ht : t > 0) (hc : c ≥ 0) (hd : stab_disc t c k ≥ 0) :
    0 < γ_NF t c k := by
  unfold γ_NF
  apply div_pos _ (by linarith)
  have h_disc_nonneg : 0 ≤ stab_disc t c k := hd
  have h_sqrt_nonneg : 0 ≤ Real.sqrt (stab_disc t c k) := Real.sqrt_nonneg _
  have h_c_pos : 0 < c := by
    unfold stab_disc at hd
    have : 12 * k * t > 0 := by nlinarith
    have : 9 * c^2 ≥ 12 * k * t := by linarith
    have : c^2 > 0 := by nlinarith
    nlinarith
  nlinarith