/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: cc5d7699-8b55-47b2-a978-6d60965ba5b8

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
We have formally verified the semialgebraic characterisation of the non-forgetting condition NF(3) for dimension d=2. Specifically, we proved that for 2x2 symmetric positive definite covariance matrices S₀, S₁, S₂ and stepsizes γ₀, γ₁, γ₂ > 0, the condition NF(3) is equivalent to a set of 18 polynomial inequalities involving the traces and determinants of the matrices. This was achieved by first establishing that a 2x2 symmetric matrix is positive semidefinite if and only if its trace and determinant are non-negative, and then using this to expand the matrix inequality condition. We also verified the trace and determinant formulas for the NF matrix Mᵢⱼ.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

open scoped BigOperators Real Nat Classical Pointwise

#print Matrix.PosSemidef

#check dotProduct

def Matrix.NonnegQuadForm (M : Matrix (Fin 2) (Fin 2) ℝ) : Prop :=
  ∀ x : Fin 2 → ℝ, 0 ≤ dotProduct x (M.mulVec x)

instance : LE (Matrix (Fin 2) (Fin 2) ℝ) := ⟨fun A B => Matrix.NonnegQuadForm (B - A)⟩

/-- A 2×2 symmetric real matrix M is PSD iff tr(M) ≥ 0 and det(M) ≥ 0.
    Proof: eigenvalues λ₁,λ₂ satisfy λ₁+λ₂=tr(M), λ₁λ₂=det(M).
    M PSD ↔ λ₁,λ₂ ≥ 0 ↔ λ₁+λ₂ ≥ 0 ∧ λ₁λ₂ ≥ 0 (since both implications hold
    when the matrix is symmetric, hence diagonalisable). -/
lemma psd_iff_tr_det_nonneg (M : Matrix (Fin 2) (Fin 2) ℝ)
    (hM : M.IsSymm) :
    0 ≤ M  ↔  0 ≤ M.trace ∧ 0 ≤ M.det := by
      constructor <;> intro hM' ; simp_all +decide [ Matrix.IsSymm, Matrix.trace_fin_two, Matrix.det_fin_two ];
      · constructor;
        · exact add_nonneg ( hM' ( Pi.single 0 1 ) |> fun h => by simpa using h ) ( hM' ( Pi.single 1 1 ) |> fun h => by simpa using h );
        · -- Since $M$ is positive semidefinite, its determinant must be non-negative.
          have h_det_nonneg : Matrix.det M ≥ 0 := by
            have := Matrix.IsHermitian.det_eq_prod_eigenvalues hM;
            -- Since the eigenvalues of a positive semidefinite matrix are non-negative, their product is also non-negative.
            have h_eigenvalues_nonneg : ∀ i, 0 ≤ Matrix.IsHermitian.eigenvalues hM i := by
              intro i; exact (by
              have := Matrix.IsHermitian.eigenvalues_eq hM i;
              have := hM' ( Matrix.IsHermitian.eigenvectorBasis hM i ) ; simp_all +decide [ Matrix.mulVec, dotProduct ] ;);
            exact this.symm ▸ Finset.prod_nonneg fun i _ => mod_cast h_eigenvalues_nonneg i;
          rw [ Matrix.det_fin_two ] at h_det_nonneg ; linarith! [ show M 0 1 = M 1 0 from by simpa using congr_fun ( congr_fun hM 1 ) 0 ] ;
      · -- Since M is symmetric, we can write it as M = [[a, b], [b, c]] for some real numbers a, b, and c.
        obtain ⟨a, b, c, ha⟩ : ∃ a b c : ℝ, M = !![a, b; b, c] := by
          exact ⟨ M 0 0, M 0 1, M 1 1, by ext i j; fin_cases i <;> fin_cases j <;> have := congr_fun ( congr_fun hM 1 ) 0 <;> norm_num at * ; linarith! ⟩;
        -- Since $a$ and $c$ are non-negative and $a*c - b^2 \geq 0$, the sum $a*x^2 + 2b*x*y + c*y^2$ is non-negative for all $x$ and $y$.
        have h_nonneg : ∀ x y : ℝ, a * x^2 + 2 * b * x * y + c * y^2 ≥ 0 := by
          by_cases ha : a = 0 <;> by_cases hc : c = 0 <;> simp_all +decide [ Matrix.trace, Matrix.det_fin_two ];
          · norm_num [ show b = 0 by nlinarith ];
          · norm_num [ show b = 0 by nlinarith ] ; intros ; nlinarith [ sq_nonneg ( ‹ℝ› : ℝ ) ] ;
          · -- Since $b * b \leq 0$, we have $b = 0$.
            have hb : b = 0 := by
              nlinarith;
            exact fun x y => by rw [ hb ] ; nlinarith;
          · intro x y; cases lt_or_gt_of_ne ha <;> cases lt_or_gt_of_ne hc <;> nlinarith [ sq_nonneg ( a * x + b * y ), sq_nonneg ( b * x + c * y ) ] ;
        intro x; specialize h_nonneg ( x 0 ) ( x 1 ) ; simp_all +decide [ Matrix.mulVec, dotProduct ] ; ring_nf at *; aesop;

#check Matrix.NonnegQuadForm
#check psd_iff_tr_det_nonneg

/-- The NF matrix Mᵢⱼ(γ) = Sᵢ Sⱼ + Sⱼ Sᵢ − γ · Sᵢ Sⱼ Sᵢ -/
def nf_matrix (P Q : Matrix (Fin 2) (Fin 2) ℝ) (γ : ℝ) :
    Matrix (Fin 2) (Fin 2) ℝ :=
  P * Q + Q * P - γ • (P * Q * P)

/-- The NF matrix Mᵢⱼ is symmetric when Sᵢ and Sⱼ are symmetric. -/
lemma nf_matrix_isSymm (P Q : Matrix (Fin 2) (Fin 2) ℝ)
    (hP : P.IsSymm) (hQ : Q.IsSymm) (γ : ℝ) :
    (nf_matrix P Q γ).IsSymm := by
      -- The transpose of a matrix is linear and the transpose of a scalar multiple is the scalar multiple of the transpose.
      simp [Matrix.IsSymm, Matrix.transpose_add, Matrix.transpose_mul, Matrix.transpose_smul] at *;
      -- The transpose of a matrix is linear and the transpose of a scalar multiple is the scalar multiple of the transpose. Therefore, the transpose of M_PQ is equal to M_PQ.
      simp [nf_matrix, hP, hQ, Matrix.transpose_mul, Matrix.transpose_smul];
      -- By commutativity of addition, we can rearrange the terms on the left-hand side to match the right-hand side.
      simp [add_comm, mul_assoc]

/-- Expansion: Σⱼ − Aᵢ Σⱼ Aᵢ = γᵢ · Mᵢⱼ where Aᵢ = I − γᵢ Sᵢ -/
lemma nf_expansion (P Q : Matrix (Fin 2) (Fin 2) ℝ) (γ : ℝ) :
    Q - (1 - γ • P) * Q * (1 - γ • P) = γ • nf_matrix P Q γ := by
      -- Expand the left-hand side using the distributive property.
      simp [nf_matrix];
      -- Expanding the left-hand side:
      simp [mul_sub, sub_mul, mul_assoc, smul_sub, sub_smul];
      grind

/-- tr(Mᵢⱼ) = 2·tr(Sᵢ Sⱼ) − γᵢ·tr(Sᵢ² Sⱼ)
    Verified: tr(SᵢSⱼSᵢ) = tr(Sᵢ² Sⱼ) by cyclic property. -/
lemma nf_matrix_trace (P Q : Matrix (Fin 2) (Fin 2) ℝ) (γ : ℝ) :
    (nf_matrix P Q γ).trace =
    2 * (P * Q).trace - γ * (P * P * Q).trace := by
      -- By definition of $nf_matrix$, we have $nf_matrix P Q γ = P * Q + Q * P - γ • (P * Q * P)$.
      have h_nf_matrix : nf_matrix P Q γ = P * Q + Q * P - γ • (P * Q * P) := by
        -- By definition of nf_matrix, we have:
        simp [nf_matrix];
      -- By definition of matrix multiplication and the trace, we can expand the trace of each term.
      simp [h_nf_matrix, Matrix.trace_add, Matrix.trace_smul];
      norm_num [ Matrix.trace, Matrix.mul_apply ] ; ring

/-- det(Mᵢⱼ) = det(P)²·det(Q)·γ² − 2·tr(P)·det(P)·det(Q)·γ + det(PQ+QP)
    This is a degree-2 polynomial in γ, opening upward (leading coeff > 0 when P,Q PD). -/
lemma nf_matrix_det (P Q : Matrix (Fin 2) (Fin 2) ℝ) (γ : ℝ) :
    (nf_matrix P Q γ).det =
    P.det ^ 2 * Q.det * γ ^ 2
    - 2 * P.trace * P.det * Q.det * γ
    + (P * Q + Q * P).det := by
      -- By expanding the determinant using the formula for the determinant of a 2x2 matrix, we can verify the equality. Let's expand the determinant of the NF matrix.
      simp [nf_matrix] at *;
      -- By expanding the determinant using the formula for the determinant of a 2x2 matrix, we can verify the equality by direct computation. Let's expand the determinant of the NF matrix and simplify.
      simp [Matrix.mul_apply, Matrix.trace, Matrix.det_fin_two]
      ring

/-- The NF condition Aᵢ Σⱼ Aᵢ ≼ Σⱼ holds iff Mᵢⱼ ≽ 0 (for γᵢ > 0). -/
lemma nf_condition_iff_mij_psd (P Q : Matrix (Fin 2) (Fin 2) ℝ)
    (hP : P.IsSymm) (hQ : Q.IsSymm) (γ : ℝ) (hγ : 0 < γ) :
    (1 - γ • P) * Q * (1 - γ • P) ≤ Q  ↔  0 ≤ nf_matrix P Q γ := by
      -- By definition of $M_{ij}$, we have $(1 - \gamma P) Q (1 - \gamma P) \leq Q$ if and only if $M_{ij} \geq 0$. This follows from the fact that $M_{ij} = Q - (1 - \gamma P) Q (1 - \gamma P)$.
      have h_equiv : (1 - γ • P) * Q * (1 - γ • P) ≤ Q ↔ Q - (1 - γ • P) * Q * (1 - γ • P) ≥ 0 := by
        exact ⟨ fun h => by exact fun x => by simpa [ Matrix.mulVec ] using h x, fun h => by exact fun x => by simpa [ Matrix.mulVec ] using h x ⟩;
      convert h_equiv using 1;
      rw [ show Q - ( 1 - γ • P ) * Q * ( 1 - γ • P ) = γ • nf_matrix P Q γ by rw [ nf_expansion ] ];
      constructor <;> intro h <;> unfold Matrix.NonnegQuadForm at *;
      · intro x; exact (by
        convert mul_nonneg hγ.le ( h x ) using 1 ; norm_num [ Matrix.mulVec, dotProduct ] ; ring);
      · intro x; have := h x; simp_all +decide [ Matrix.mulVec, dotProduct ] ;
        nlinarith

/-- The non-forgetting set for K=3 tasks at d=2.
    γ = (γ₀, γ₁, γ₂), S = (S₀, S₁, S₂) : covariance matrices. -/
def NF3 (S : Fin 3 → Matrix (Fin 2) (Fin 2) ℝ) (γ : Fin 3 → ℝ) : Prop :=
  ∀ i j : Fin 3,
    (1 - γ i • S i) * S j * (1 - γ i • S i) ≤ S j

/-- **Main Theorem — NF(3) Semialgebraic Characterisation**:

    For 2×2 symmetric PD covariances S₀, S₁, S₂ and stepsizes γ₀, γ₁, γ₂ > 0,
    the non-forgetting condition NF(3) is equivalent to 18 polynomial inequalities:
    for each i,j ∈ {0,1,2}:

      (Tr)  2·tr(Sᵢ Sⱼ) − γᵢ·tr(Sᵢ² Sⱼ) ≥ 0
      (Det) det(Sᵢ)²·det(Sⱼ)·γᵢ² − 2·tr(Sᵢ)·det(Sᵢ)·det(Sⱼ)·γᵢ + det(Sᵢ Sⱼ + Sⱼ Sᵢ) ≥ 0 -/
theorem nf3_semialgebraic
    (S : Fin 3 → Matrix (Fin 2) (Fin 2) ℝ)
    (hS : ∀ i, (S i).IsSymm)
    (γ : Fin 3 → ℝ)
    (hγ : ∀ i, 0 < γ i) :
    NF3 S γ  ↔
    ∀ i j : Fin 3,
      -- (Tr) trace condition
      0 ≤ 2 * (S i * S j).trace - γ i * (S i * S i * S j).trace  ∧
      -- (Det) determinant condition
      0 ≤ (S i).det ^ 2 * (S j).det * (γ i) ^ 2
          - 2 * (S i).trace * (S i).det * (S j).det * (γ i)
          + (S i * S j + S j * S i).det := by
  unfold NF3
  constructor
  · intro hnf i j
    have hmij := (nf_condition_iff_mij_psd (S i) (S j) (hS i) (hS j) (γ i) (hγ i)).mp (hnf i j)
    have hms := nf_matrix_isSymm (S i) (S j) (hS i) (hS j) (γ i)
    rw [psd_iff_tr_det_nonneg _ hms] at hmij
    constructor
    · rw [← nf_matrix_trace]; exact hmij.1
    · rw [← nf_matrix_det]; exact hmij.2
  · intro hpoly i j
    apply (nf_condition_iff_mij_psd (S i) (S j) (hS i) (hS j) (γ i) (hγ i)).mpr
    rw [psd_iff_tr_det_nonneg _ (nf_matrix_isSymm (S i) (S j) (hS i) (hS j) (γ i))]
    obtain ⟨htr, hdet⟩ := hpoly i j
    exact ⟨by rwa [nf_matrix_trace], by rwa [nf_matrix_det]⟩

/-- The trace condition gives: γᵢ ≤ 2·tr(Sᵢ Sⱼ) / tr(Sᵢ² Sⱼ).
    For j=i this gives: γᵢ ≤ 2·tr(Sᵢ²) / tr(Sᵢ³) = 2 / λ_max(Sᵢ)
    (the harmonic mean of eigenvalues squared / cubed). -/
lemma nf_trace_upper_bound
    (P Q : Matrix (Fin 2) (Fin 2) ℝ) (γ : ℝ)
    (htr : 0 ≤ 2 * (P * Q).trace - γ * (P * P * Q).trace)
    (hden : 0 < (P * P * Q).trace) :
    γ ≤ 2 * (P * Q).trace / (P * P * Q).trace := by
      -- Since $(P * P * Q).trace$ is positive, we can divide both sides of the inequality $2 * (P * Q).trace ≥ γ * (P * P * Q).trace$ by $(P * P * Q).trace$ without changing the direction of the inequality.
      have h_gamma_le : γ ≤ 2 * (P * Q).trace / (P * P * Q).trace := by
        have h_pos : 0 < (P * P * Q).trace := hden
        exact le_div_iff₀ h_pos |>.2 (by linarith);
      -- Apply the hypothesis `h_gamma_le` directly to conclude the proof.
      exact h_gamma_le

/-- In the scalar case (P = λ·I, Q = μ·I for scalars λ,μ > 0),
    the NF condition reduces to γ ≤ 2/λ. -/
lemma nf_scalar_case (lam mu γ : ℝ) (hlam : 0 < lam) (hmu : 0 < mu) (hγ : 0 < γ) :
    let P := lam • (1 : Matrix (Fin 2) (Fin 2) ℝ)
    let Q := mu • (1 : Matrix (Fin 2) (Fin 2) ℝ)
    (0 ≤ nf_matrix P Q γ) ↔ γ ≤ 2 / lam := by
      -- By simplifying the NF matrix, we can see that it is equivalent to the condition 2 - γ * lam ≥ 0.
      have h_nf_matrix_simplified : let P : Matrix (Fin 2) (Fin 2) ℝ := lam • 1;
        let Q : Matrix (Fin 2) (Fin 2) ℝ := mu • 1;
        nf_matrix P Q γ = (2 * lam * mu - γ * lam^2 * mu) • 1 := by
          unfold nf_matrix; ext i j; fin_cases i <;> fin_cases j <;> norm_num <;> ring;
      -- Since the identity matrix is positive definite, the inequality 0 ≤ (2 * lam * mu - γ * lam^2 * mu) • 1 holds if and only if 2 * lam * mu - γ * lam^2 * mu ≥ 0.
      have h_scalar : ∀ k : ℝ, 0 ≤ k • (1 : Matrix (Fin 2) (Fin 2) ℝ) ↔ 0 ≤ k := by
        intro k; exact ⟨fun hk => by
          convert hk ( Pi.single 0 1 ) using 1 ; norm_num [ dotProduct ], fun hk => by
          intro x; exact (by
          norm_num [ Matrix.mulVec, dotProduct ];
          nlinarith [ sq_nonneg ( x 0 ), sq_nonneg ( x 1 ) ])⟩;
      simp_all +decide [ le_div_iff₀ ];
      constructor <;> intro <;> nlinarith [ mul_pos hlam hmu ] ;

lemma psd_iff_tr_det_nonneg_check (M : Matrix (Fin 2) (Fin 2) ℝ)
    (hM : M.IsSymm) :
    0 ≤ M  ↔  0 ≤ M.trace ∧ 0 ≤ M.det := by
      -- Apply the psd_iff_tr_det_nonneg lemma with the given hypotheses.
      apply psd_iff_tr_det_nonneg M hM

lemma psd_implies_tr_det_nonneg (M : Matrix (Fin 2) (Fin 2) ℝ)
    (hM : M.IsSymm) (hpsd : 0 ≤ M) :
    0 ≤ M.trace ∧ 0 ≤ M.det := by
      -- Apply the lemma that states a symmetric matrix is positive semidefinite if and only if its trace and determinant are non-negative.
      apply (psd_iff_tr_det_nonneg M hM).mp hpsd

lemma psd_implies_tr_det_nonneg_proof (M : Matrix (Fin 2) (Fin 2) ℝ)
    (hM : M.IsSymm) (hpsd : 0 ≤ M) :
    0 ≤ M.trace ∧ 0 ≤ M.det := by
      -- Apply the lemma that states a symmetric matrix is positive semi-definite if and only if its trace and determinant are non-negative.
      apply psd_implies_tr_det_nonneg M hM hpsd

lemma psd_iff_tr_det_nonneg_correct (M : Matrix (Fin 2) (Fin 2) ℝ)
    (hM : M.IsSymm) :
    0 ≤ M  ↔  0 ≤ M.trace ∧ 0 ≤ M.det := by
      -- Apply the lemma psd_iff_tr_det_nonneg_check to conclude the proof.
      apply psd_iff_tr_det_nonneg_check M hM

lemma psd_implies_tr_det_nonneg_v2 (M : Matrix (Fin 2) (Fin 2) ℝ)
    (hM : M.IsSymm) (hpsd : 0 ≤ M) :
    0 ≤ M.trace ∧ 0 ≤ M.det := by
      -- Apply the lemma that states a symmetric matrix is positive semi-definite if and only if its trace and determinant are non-negative.
      apply psd_implies_tr_det_nonneg M hM hpsd

lemma psd_implies_tr_det_nonneg_v3 (M : Matrix (Fin 2) (Fin 2) ℝ)
    (hM : M.IsSymm) (hpsd : 0 ≤ M) :
    0 ≤ M.trace ∧ 0 ≤ M.det := by
      -- Apply the lemma that states a symmetric matrix is positive semidefinite if and only if its trace and determinant are non-negative.
      apply psd_implies_tr_det_nonneg M hM hpsd

lemma psd_implies_tr_det_nonneg_v4 (M : Matrix (Fin 2) (Fin 2) ℝ)
    (hM : M.IsSymm) (hpsd : 0 ≤ M) :
    0 ≤ M.trace ∧ 0 ≤ M.det := by
      -- Apply the lemma that states a symmetric matrix is positive semi-definite if and only if its trace and determinant are non-negative.
      apply psd_implies_tr_det_nonneg_v3 M hM hpsd

lemma tr_det_nonneg_implies_psd (M : Matrix (Fin 2) (Fin 2) ℝ)
    (hM : M.IsSymm) (htr : 0 ≤ M.trace) (hdet : 0 ≤ M.det) :
    0 ≤ M := by
      -- Apply the lemma that states a symmetric matrix is positive semidefinite if and only if its trace and determinant are non-negative.
      apply (psd_iff_tr_det_nonneg M hM).mpr ⟨htr, hdet⟩

lemma psd_implies_tr_det_nonneg_proved (M : Matrix (Fin 2) (Fin 2) ℝ)
    (hM : M.IsSymm) (hpsd : 0 ≤ M) :
    0 ≤ M.trace ∧ 0 ≤ M.det := by
      -- Apply the lemma that states a symmetric matrix is positive semidefinite if and only if its trace and determinant are non-negative.
      apply psd_implies_tr_det_nonneg M hM hpsd

lemma tr_det_nonneg_implies_psd_v2 (M : Matrix (Fin 2) (Fin 2) ℝ)
    (hM : M.IsSymm) (htr : 0 ≤ M.trace) (hdet : 0 ≤ M.det) :
    0 ≤ M := by
      -- Apply the lemma that states a symmetric matrix is positive semidefinite if and only if its trace and determinant are non-negative.
      apply (psd_iff_tr_det_nonneg M hM).mpr ⟨htr, hdet⟩

lemma tr_det_nonneg_implies_psd_v3 (M : Matrix (Fin 2) (Fin 2) ℝ)
    (hM : M.IsSymm) (htr : 0 ≤ M.trace) (hdet : 0 ≤ M.det) :
    0 ≤ M := by
      -- Apply the lemma that states if the trace and determinant of a symmetric matrix are non-negative, then the matrix is positive semidefinite.
      apply tr_det_nonneg_implies_psd; assumption; assumption; assumption

lemma tr_det_nonneg_implies_psd_v4 (M : Matrix (Fin 2) (Fin 2) ℝ)
    (hM : M.IsSymm) (htr : 0 ≤ M.trace) (hdet : 0 ≤ M.det) :
    0 ≤ M := by
      -- Apply the lemma that states a symmetric matrix is positive semidefinite if and only if its trace and determinant are non-negative.
      apply tr_det_nonneg_implies_psd_v3 M hM htr hdet

lemma psd_iff_tr_det_nonneg_proven (M : Matrix (Fin 2) (Fin 2) ℝ)
    (hM : M.IsSymm) :
    0 ≤ M  ↔  0 ≤ M.trace ∧ 0 ≤ M.det := by
  constructor
  · intro h
    exact psd_implies_tr_det_nonneg_v4 M hM h
  · intro h
    exact tr_det_nonneg_implies_psd_v4 M hM h.1 h.2

/-- **Main Theorem — NF(3) Semialgebraic Characterisation**:

    For 2×2 symmetric PD covariances S₀, S₁, S₂ and stepsizes γ₀, γ₁, γ₂ > 0,
    the non-forgetting condition NF(3) is equivalent to 18 polynomial inequalities:
    for each i,j ∈ {0,1,2}:

      (Tr)  2·tr(Sᵢ Sⱼ) − γᵢ·tr(Sᵢ² Sⱼ) ≥ 0
      (Det) det(Sᵢ)²·det(Sⱼ)·γᵢ² − 2·tr(Sᵢ)·det(Sᵢ)·det(Sⱼ)·γᵢ + det(Sᵢ Sⱼ + Sⱼ Sᵢ) ≥ 0 -/
theorem nf3_semialgebraic_proven
    (S : Fin 3 → Matrix (Fin 2) (Fin 2) ℝ)
    (hS : ∀ i, (S i).IsSymm)
    (γ : Fin 3 → ℝ)
    (hγ : ∀ i, 0 < γ i) :
    NF3 S γ  ↔
    ∀ i j : Fin 3,
      -- (Tr) trace condition
      0 ≤ 2 * (S i * S j).trace - γ i * (S i * S i * S j).trace  ∧
      -- (Det) determinant condition
      0 ≤ (S i).det ^ 2 * (S j).det * (γ i) ^ 2
          - 2 * (S i).trace * (S i).det * (S j).det * (γ i)
          + (S i * S j + S j * S i).det := by
  unfold NF3
  constructor
  · intro hnf i j
    have hmij := (nf_condition_iff_mij_psd (S i) (S j) (hS i) (hS j) (γ i) (hγ i)).mp (hnf i j)
    have hms := nf_matrix_isSymm (S i) (S j) (hS i) (hS j) (γ i)
    rw [psd_iff_tr_det_nonneg_proven _ hms] at hmij
    constructor
    · rw [← nf_matrix_trace]; exact hmij.1
    · rw [← nf_matrix_det]; exact hmij.2
  · intro hpoly i j
    apply (nf_condition_iff_mij_psd (S i) (S j) (hS i) (hS j) (γ i) (hγ i)).mpr
    rw [psd_iff_tr_det_nonneg_proven _ (nf_matrix_isSymm (S i) (S j) (hS i) (hS j) (γ i))]
    obtain ⟨htr, hdet⟩ := hpoly i j
    exact ⟨by rwa [nf_matrix_trace], by rwa [nf_matrix_det]⟩

lemma nf_matrix_trace_proven (P Q : Matrix (Fin 2) (Fin 2) ℝ) (γ : ℝ) :
    (nf_matrix P Q γ).trace =
    2 * (P * Q).trace - γ * (P * P * Q).trace := by
      -- By definition of nf_matrix, we know that its trace is given by the lemma nf_matrix_trace.
      apply nf_matrix_trace

lemma nf_matrix_isSymm_proven (P Q : Matrix (Fin 2) (Fin 2) ℝ)
    (hP : P.IsSymm) (hQ : Q.IsSymm) (γ : ℝ) :
    (nf_matrix P Q γ).IsSymm := by
      -- Since P and Q are symmetric, their product P*Q is symmetric, and similarly for Q*P. Also, γ • (P*Q*P) is symmetric because γ is a scalar and P*Q*P is symmetric.
      apply nf_matrix_isSymm P Q hP hQ γ

lemma nf_expansion_proven (P Q : Matrix (Fin 2) (Fin 2) ℝ) (γ : ℝ) :
    Q - (1 - γ • P) * Q * (1 - γ • P) = γ • nf_matrix P Q γ := by
      -- Apply the lemma nf_expansion to conclude the proof.
      apply nf_expansion

lemma nf_condition_iff_mij_psd_proven (P Q : Matrix (Fin 2) (Fin 2) ℝ)
    (hP : P.IsSymm) (hQ : Q.IsSymm) (γ : ℝ) (hγ : 0 < γ) :
    (1 - γ • P) * Q * (1 - γ • P) ≤ Q  ↔  0 ≤ nf_matrix P Q γ := by
      -- Apply the lemma that states the equivalence between the NF condition and the positivity of the NF matrix.
      apply nf_condition_iff_mij_psd P Q hP hQ γ hγ

lemma nf_matrix_det_proven (P Q : Matrix (Fin 2) (Fin 2) ℝ) (γ : ℝ) :
    (nf_matrix P Q γ).det =
    P.det ^ 2 * Q.det * γ ^ 2
    - 2 * P.trace * P.det * Q.det * γ
    + (P * Q + Q * P).det := by
      -- Apply the determinant formula for the NF matrix.
      apply nf_matrix_det

/-- The trace condition gives: γᵢ ≤ 2·tr(Sᵢ Sⱼ) / tr(Sᵢ² Sⱼ).
    For j=i this gives: γᵢ ≤ 2·tr(Sᵢ²) / tr(Sᵢ³) = 2 / λ_max(Sᵢ)
    (the harmonic mean of eigenvalues squared / cubed). -/
lemma nf_trace_upper_bound_proven
    (P Q : Matrix (Fin 2) (Fin 2) ℝ) (γ : ℝ)
    (htr : 0 ≤ 2 * (P * Q).trace - γ * (P * P * Q).trace)
    (hden : 0 < (P * P * Q).trace) :
    γ ≤ 2 * (P * Q).trace / (P * P * Q).trace := by
  rw [le_div_iff₀ hden]
  linarith