/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: dc62d2aa-50ee-4df2-b689-ad392f8e94aa

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
We define the scalar K-task spectral radius `rho_scalar`, the optimal stepsize `g_opt_scalar`, and the condition number `kappa`.
We prove several properties:
- `rho_scalar_le_exp_neg_one`: The spectral radius is bounded by $1/e$.
- `g_opt_scalar_uniform`: For uniform eigenvalues, the optimal stepsize is $1/(Kc)$.
- `kappa_ge_one`: The condition number is at least 1.
- `rho_scalar_two`: Explicit formula for $K=2$.
- `rho_scalar_two_eq_kappa_div_sq`: Formula for $K=2$ in terms of $\kappa$.
- `rho_scalar_uniform`: Explicit formula for uniform eigenvalues.
- `rho_scalar_uniform_limit`: The spectral radius tends to $1/e$ as $K \to \infty$ for uniform eigenvalues.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

def rho_scalar (K : ℕ) (lam g : Fin K → ℝ) : ℝ :=
  |∏ i : Fin K, (1 - g i * lam i)|

noncomputable def g_opt_scalar (K : ℕ) (lam : Fin K → ℝ) : Fin K → ℝ :=
  fun k => 1 / (∑ i : Fin K, lam i)

noncomputable def kappa (lam_min lam_max : ℝ) : ℝ := lam_max / lam_min

/-
The spectral radius with optimal stepsize is bounded by $1/e$.
-/
theorem rho_scalar_le_exp_neg_one (K : ℕ) (lam : Fin K → ℝ) (hK : K > 0) (hlam : ∀ i, 0 < lam i) :
    rho_scalar K lam (g_opt_scalar K lam) ≤ Real.exp (-1) := by
      unfold rho_scalar g_opt_scalar;
      -- Using the inequality $1 - x \leq e^{-x}$ for each term in the product, we get $\prod_{i=1}^K (1 - \frac{\lambda_i}{\sum_{j=1}^K \lambda_j}) \leq \prod_{i=1}^K e^{-\frac{\lambda_i}{\sum_{j=1}^K \lambda_j}}$.
      have h_prod_le_exp : ∏ i, (1 - (1 / ∑ i, lam i) * lam i) ≤ Real.exp (-∑ i, (1 / ∑ i, lam i) * lam i) := by
        rw [ Real.exp_neg, Real.exp_sum ];
        rw [ ← Finset.prod_inv_distrib ] ; exact Finset.prod_le_prod ( fun _ _ => sub_nonneg.2 <| by rw [ div_mul_eq_mul_div, div_le_iff₀ ] <;> nlinarith [ hlam ‹_›, Finset.single_le_sum ( fun i _ => le_of_lt ( hlam i ) ) ( Finset.mem_univ ‹_› ) ] ) fun _ _ => by rw [ ← Real.exp_neg ] ; exact Real.add_one_le_exp _ |> le_trans ( by linarith ) ;
      by_cases h : ∑ i, lam i = 0 <;> simp_all +decide [ ← Finset.mul_sum _ _ _, ← Finset.sum_mul ];
      · exact absurd h <| ne_of_gt <| Finset.sum_pos ( fun _ _ => hlam _ ) ⟨ ⟨ 0, hK ⟩, Finset.mem_univ _ ⟩;
      · rwa [ abs_of_nonneg ( Finset.prod_nonneg fun i _ => sub_nonneg.2 <| by rw [ inv_mul_le_iff₀ ( lt_of_le_of_ne ( Finset.sum_nonneg fun _ _ => le_of_lt ( hlam _ ) ) ( Ne.symm h ) ) ] ; linarith [ hlam i, Finset.single_le_sum ( fun a _ => le_of_lt ( hlam a ) ) ( Finset.mem_univ i ) ] ) ]

/-
For uniform eigenvalues, the optimal stepsize is $1/(Kc)$.
-/
theorem g_opt_scalar_uniform (K : ℕ) (c : ℝ) :
    g_opt_scalar K (fun _ => c) = fun _ => 1 / (K * c) := by
      unfold g_opt_scalar; aesop;

/-
The condition number is at least 1.
-/
theorem kappa_ge_one (lam_min lam_max : ℝ) (hmin : 0 < lam_min) (hle : lam_min ≤ lam_max) :
    1 ≤ kappa lam_min lam_max := by
      exact le_div_iff₀' hmin |>.2 ( by linarith )

/-
For K=2, the spectral radius is $ab/(a+b)^2$.
-/
theorem rho_scalar_two (a b : ℝ) (ha : 0 < a) (hb : 0 < b) :
    let lam : Fin 2 → ℝ := ![a, b]
    rho_scalar 2 lam (g_opt_scalar 2 lam) = (a * b) / (a + b)^2 := by
      unfold rho_scalar g_opt_scalar; norm_num [ Fin.sum_univ_succ ] ; ring;
      rw [ ← abs_mul ] ; ring_nf ; norm_num [ show a + b ≠ 0 by positivity ] ; ring;
      rw [ abs_of_nonneg ] <;> nlinarith [ mul_pos ha hb, mul_inv_cancel₀ ( by positivity : ( a * b * 2 + a ^ 2 + b ^ 2 ) ≠ 0 ), mul_inv_cancel₀ ( by positivity : ( a + b ) ≠ 0 ) ]

/-
The condition number of uniform eigenvalues is 1.
-/
theorem kappa_eq_one_of_uniform (c : ℝ) (hc : 0 < c) :
    kappa c c = 1 := by
      exact div_self hc.ne'

/-
If the condition number is 1, the extreme eigenvalues are equal.
-/
theorem eq_of_kappa_eq_one (lam_min lam_max : ℝ) (hmin : 0 < lam_min) (hle : lam_min ≤ lam_max) (hkappa : kappa lam_min lam_max = 1) :
    lam_min = lam_max := by
      unfold kappa at hkappa ; rw [ div_eq_iff ] at hkappa <;> linarith;

/-
For K=2, the spectral radius is $\kappa / (1+\kappa)^2$.
-/
theorem rho_scalar_two_eq_kappa_div_sq (a b : ℝ) (ha : 0 < a) (hb : 0 < b) (hab : a ≤ b) :
    let lam : Fin 2 → ℝ := ![a, b]
    rho_scalar 2 lam (g_opt_scalar 2 lam) = (kappa a b) / (1 + kappa a b)^2 := by
      unfold rho_scalar kappa g_opt_scalar; norm_num [ Fin.sum_univ_succ ] ; ring; norm_num [ ha.ne', hb.ne' ] ; ring; (
      -- Simplifying the left-hand side:
      field_simp [ha, hb]
      ring;
      rw [ abs_of_nonneg ( by positivity ), abs_of_nonneg ( by positivity ) ] ; nlinarith [ mul_inv_cancel_left₀ ( by positivity : ( a + b ) ≠ 0 ) a, mul_inv_cancel_left₀ ( by positivity : ( a + b ) ≠ 0 ) b ] ;);

/-
For K=1, the spectral radius is 0.
-/
theorem rho_scalar_one_eq_zero (lam : Fin 1 → ℝ) (h : lam 0 ≠ 0) :
    rho_scalar 1 lam (g_opt_scalar 1 lam) = 0 := by
      unfold rho_scalar g_opt_scalar; norm_num [ Fin.sum_univ_succ ] ; aesop;

/-
The spectral radius is strictly less than 1 (convergence).
-/
theorem rho_scalar_lt_one (K : ℕ) (lam : Fin K → ℝ) (hK : K ≥ 1) (hlam : ∀ i, 0 < lam i) :
    rho_scalar K lam (g_opt_scalar K lam) < 1 := by
      refine' lt_of_le_of_lt ( rho_scalar_le_exp_neg_one K lam hK hlam ) ( Real.exp_neg_one_lt_d9.trans_le ( by norm_num ) )

/-
For uniform eigenvalues, the spectral radius is $|(1 - 1/K)^K|$.
-/
theorem rho_scalar_uniform (K : ℕ) (c : ℝ) (hc : c > 0) (hK : K > 0) :
    rho_scalar K (fun _ => c) (g_opt_scalar K (fun _ => c)) = |(1 - 1 / (K : ℝ)) ^ K| := by
      unfold rho_scalar g_opt_scalar; norm_num [ Finset.card_univ, hK.ne' ] ; ring;
      norm_num [ hc.ne' ]

/-
As K goes to infinity, the spectral radius for uniform eigenvalues tends to 1/e.
-/
theorem rho_scalar_uniform_limit (c : ℝ) (hc : c > 0) :
    Filter.Tendsto (fun K => rho_scalar K (fun _ => c) (g_opt_scalar K (fun _ => c))) Filter.atTop (nhds (Real.exp (-1))) := by
      -- For uniform eigenvalues, the spectral radius is $|(1 - 1/K)^K|$.
      have h_unif : ∀ K : ℕ, K > 0 → rho_scalar K (fun _ => c) (g_opt_scalar K (fun _ => c)) = |(1 - 1 / (K : ℝ)) ^ K| := by
        exact?;
      rw [ Filter.tendsto_congr' ( by filter_upwards [ Filter.eventually_gt_atTop 0 ] with K hK; rw [ h_unif K hK ] ) ] ; norm_num [ Real.exp_neg ] ; (
      rw [ ← Real.exp_neg, Filter.tendsto_congr' ( by filter_upwards [ Filter.eventually_gt_atTop 1 ] with K hK using by rw [ abs_of_nonneg ] ; nlinarith [ inv_mul_cancel₀ ( by positivity : ( K : ℝ ) ≠ 0 ), ( by norm_cast : ( 1 :ℝ ) < K ) ] ) ] ; exact (by
      -- Recognize that $(1 - 1/K)^K$ converges to $e^{-1}$ by the limit definition of the exponential function.
      have h_exp : Filter.Tendsto (fun K : ℕ => (1 + (-1 : ℝ) / K) ^ K) Filter.atTop (nhds (Real.exp (-1))) := by
        exact?;
      exact h_exp.congr fun K => by ring;););