/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: ee5c879b-ab6a-43ab-b9b7-9512bc72c93f

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
We define the 2x2 symplectic matrix J and prove that for A = I - γ₁Σ₁ and B = I - γ₂Σ₂ with symmetric Σ₁, Σ₂, the commutator [A, B] is equal to c • J, where c = γ₁γ₂((Σ₁Σ₂ - Σ₂Σ₁)₀₁). This confirms the commutator is second order in the stepsizes γ₁, γ₂.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

/-
Given A = I − g1*S1 and B = I − g2*S2 where S1, S2 are 2×2 PD symmetric matrices, the commutator [A,B] is c·J where c = g1*g2·(S1*S2 − S2*S1)₀₁ and J is the standard symplectic matrix.
-/
def J : Matrix (Fin 2) (Fin 2) ℝ := !![0, 1; -1, 0]

theorem commutator_formula
  (S1 S2 : Matrix (Fin 2) (Fin 2) ℝ)
  (hS1 : S1.IsSymm) (hS1_pd : S1.PosDef)
  (hS2 : S2.IsSymm) (hS2_pd : S2.PosDef)
  (g1 g2 : ℝ) :
  let A := (1 : Matrix (Fin 2) (Fin 2) ℝ) - g1 • S1
  let B := (1 : Matrix (Fin 2) (Fin 2) ℝ) - g2 • S2
  let c := g1 * g2 * (S1 * S2 - S2 * S1) 0 1
  A * B - B * A = c • J := by
    simp +decide [ Subtype.ext_iff ] at hS1 hS2 ⊢; ext i j; fin_cases i <;> fin_cases j <;> simp +decide [ Matrix.mul_apply ] at * <;> ring;
    · simp +decide [ J, hS1, hS2 ] ; ring;
      rw [ hS1.apply, hS2.apply ] ; ring!;
    · unfold J; norm_num;
    · simp +decide [ J, hS1.apply, hS2.apply ] ; ring;
    · simp +decide [ J, hS1, hS2 ] ; ring;
      rw [ hS1.apply, hS2.apply ] ; ring;