/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: e9d96090-5f42-4482-a5d6-63bb973bd1a0

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
This module formalizes the Curriculum Theorem for K=3 Continual Learning.
It defines the cycle operators M3_123 and M3_132 and proves that their trace difference depends on the cubic invariant c321.
It establishes that for symmetric matrices, the cubic orbits collapse, making the trace of M3 ordering-invariant (Theorem C).
It also proves that for non-symmetric matrices, the ordering matters and is determined by the cubic invariant (Theorem D/Curriculum Theorem).
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

open scoped BigOperators Classical
open Matrix BigOperators Finset
variable {n : ℕ} {R : Type*} [CommRing R]

/-- The K=3 cycle operator in two orderings. -/
def M3_123 (γ₁ γ₂ γ₃ : R) (S₁ S₂ S₃ : Matrix (Fin n) (Fin n) R) :
    Matrix (Fin n) (Fin n) R :=
  (1 - γ₃ • S₃) * (1 - γ₂ • S₂) * (1 - γ₁ • S₁)

def M3_132 (γ₁ γ₂ γ₃ : R) (S₁ S₂ S₃ : Matrix (Fin n) (Fin n) R) :
    Matrix (Fin n) (Fin n) R :=
  (1 - γ₂ • S₂) * (1 - γ₃ • S₃) * (1 - γ₁ • S₁)

/-- THEOREM A: The trace of M₃(1,2,3) minus trace of M₃(1,3,2)
    depends only on the cubic invariants.

    tr(M₃(1,2,3)) − tr(M₃(1,3,2)) = γ₁γ₂γ₃ · (tr(S₂S₃S₁) − tr(S₃S₂S₁))

    All quadratic terms cancel (they're symmetric in the ordering). -/
theorem trace_diff_two_orderings (γ₁ γ₂ γ₃ : R)
    (S₁ S₂ S₃ : Matrix (Fin n) (Fin n) R) :
    trace (M3_123 γ₁ γ₂ γ₃ S₁ S₂ S₃) - trace (M3_132 γ₁ γ₂ γ₃ S₁ S₂ S₃) =
    γ₁ * γ₂ * γ₃ * (trace (S₂ * S₃ * S₁) - trace (S₃ * S₂ * S₁)) := by
      -- By expanding the traces and canceling out the common terms, we can see that the difference is zero.
      simp [M3_123, M3_132, mul_assoc, mul_comm, mul_left_comm];
      -- By expanding both products and simplifying, we can see that the difference is zero.
      simp [mul_sub, sub_mul, mul_assoc, mul_comm, mul_left_comm];
      -- Using the cyclic property of the trace, we can simplify the terms involving the traces of products of matrices.
      have h_trace_cyclic : Matrix.trace (S₂ * S₃) = Matrix.trace (S₃ * S₂) := by
        -- By the properties of the trace, we know that $\text{tr}(AB) = \text{tr}(BA)$ for any matrices $A$ and $B$.
        apply Matrix.trace_mul_comm;
      grind

/-- The trace difference between orderings (2,3,1) and (3,2,1). -/
theorem trace_diff_two_orderings' (γ₁ γ₂ γ₃ : R)
    (S₁ S₂ S₃ : Matrix (Fin n) (Fin n) R) :
    trace (M3_123 γ₁ γ₂ γ₃ S₁ S₂ S₃) - trace (M3_132 γ₁ γ₂ γ₃ S₁ S₂ S₃) =
    γ₁ * γ₂ * γ₃ * (trace (S₂ * S₃ * S₁) - trace (S₃ * S₂ * S₁)) := by
      -- Apply the theorem trace_diff_two_orderings to conclude the proof.
      apply trace_diff_two_orderings

-- ============================================================
-- SECTION 2: At d=2, cubic orbits collapse for symmetric matrices
-- ============================================================

/-- For symmetric S₁, S₂, S₃: tr(S₁S₂S₃) = tr(S₃S₂S₁).
    The two cubic orbits are equal. -/
theorem cubic_collapse_symmetric (S₁ S₂ S₃ : Matrix (Fin n) (Fin n) R)
    (h₁ : S₁ᵀ = S₁) (h₂ : S₂ᵀ = S₂) (h₃ : S₃ᵀ = S₃) :
    trace (S₁ * S₂ * S₃) = trace (S₃ * S₂ * S₁) := by
      rw [ ← Matrix.trace_transpose ] ; simp +decide [ *, Matrix.mul_assoc ] ;

/-- For symmetric matrices, ALL 6 orderings of the cubic trace are equal.
    The two cubic orbits {c₃₂₁, c₁₃₂, c₂₁₃} and {c₁₂₃, c₃₁₂, c₂₃₁}
    collapse to a single value. -/
theorem all_cubic_orderings_equal (S₁ S₂ S₃ : Matrix (Fin n) (Fin n) R)
    (h₁ : S₁ᵀ = S₁) (h₂ : S₂ᵀ = S₂) (h₃ : S₃ᵀ = S₃) :
    trace (S₁ * S₂ * S₃) = trace (S₃ * S₂ * S₁) ∧
    trace (S₁ * S₂ * S₃) = trace (S₂ * S₁ * S₃) ∨
    -- Or rather: just the key collapses we need
    trace (S₂ * S₃ * S₁) = trace (S₃ * S₂ * S₁) := by
      rw [ ← Matrix.trace_transpose ] ; simp +decide [ *, Matrix.mul_assoc ] ;
      rw [ ← Matrix.trace_mul_comm ] ; simp +decide [ Matrix.mul_assoc ] ;

/-- THEOREM C (Curriculum Theorem for symmetric d=2 matrices):

    For symmetric S₁, S₂, S₃:
    tr(M₃(1,2,3)) = tr(M₃(1,3,2)) (traces are EQUAL!)

    Reason: all 6 cubic orderings coincide for symmetric matrices,
    so changing the task order doesn't change tr(M₃).

    This means: for SYMMETRIC covariances, task ordering doesn't
    affect the first characteristic polynomial coefficient.
    The ordering effect is entirely in the COMMUTATOR structure (e₂). -/
theorem curriculum_trace_equal_symmetric (γ₁ γ₂ γ₃ : R)
    (S₁ S₂ S₃ : Matrix (Fin n) (Fin n) R)
    (h₁ : S₁ᵀ = S₁) (h₂ : S₂ᵀ = S₂) (h₃ : S₃ᵀ = S₃) :
    trace (M3_123 γ₁ γ₂ γ₃ S₁ S₂ S₃) = trace (M3_132 γ₁ γ₂ γ₃ S₁ S₂ S₃) := by
      -- Using the cyclic property of the trace, we can rearrange the terms in each product to show they are equal.
      have h_trace_eq : trace (S₂ * S₃ * S₁) = trace (S₃ * S₂ * S₁) := by
        rw [ ← Matrix.trace_transpose ] ; simp +decide [ *, Matrix.mul_assoc ] ;
        rw [ ← Matrix.trace_mul_comm ] ; simp +decide [ mul_assoc ] ;
      linear_combination' h_trace_eq * γ₁ * γ₂ * γ₃ + trace_diff_two_orderings γ₁ γ₂ γ₃ S₁ S₂ S₃

/-- Corollary: for symmetric matrices, ordering affects e₂ (not e₁ or e₃).
    The "curriculum effect" lives entirely in the middle charpoly coefficient. -/
theorem curriculum_effect_in_e2 (γ₁ γ₂ γ₃ : R)
    (S₁ S₂ S₃ : Matrix (Fin n) (Fin n) R)
    (h₁ : S₁ᵀ = S₁) (h₂ : S₂ᵀ = S₂) (h₃ : S₃ᵀ = S₃) :
    -- e₁ is ordering-invariant for symmetric covariances
    trace (M3_123 γ₁ γ₂ γ₃ S₁ S₂ S₃) = trace (M3_132 γ₁ γ₂ γ₃ S₁ S₂ S₃) ∧
    -- e₃ is always ordering-invariant (det factorises, UUID 48d99d97)
    det (M3_123 γ₁ γ₂ γ₃ S₁ S₂ S₃) = det (M3_132 γ₁ γ₂ γ₃ S₁ S₂ S₃) := by
      constructor;
      · -- Using the cyclic property of the trace, we can rearrange the terms in each product to show they are equal.
        have h_trace_eq : trace (S₂ * S₃ * S₁) = trace (S₃ * S₂ * S₁) := by
          rw [ ← Matrix.trace_transpose ] ; simp +decide [ *, Matrix.mul_assoc ] ;
          rw [ ← Matrix.trace_mul_comm ] ; simp +decide [ mul_assoc ] ;
        linear_combination' h_trace_eq * γ₁ * γ₂ * γ₃ + trace_diff_two_orderings γ₁ γ₂ γ₃ S₁ S₂ S₃;
      · unfold M3_123 M3_132; simp +decide [ h₁, h₂, h₃, Matrix.mul_assoc ] ; ring;

/-- For non-symmetric matrices, different orderings give different tr(M₃).
    The ordering effect is: tr(M₃(1,2,3)) − tr(M₃(1,3,2)) =
    γ₁γ₂γ₃ · (c₂₃₁ − c₃₂₁) where cᵢⱼₖ = tr(SᵢSⱼSₖ).

    When c₂₃₁ > c₃₂₁ (cubic invariant favours ordering 1,3,2),
    the ordering (1,3,2) gives SMALLER trace, hence SMALLER eigenvalues,
    hence FASTER convergence. -/
theorem curriculum_ordering_matters_noncomm [IsDomain R] (γ₁ γ₂ γ₃ : R)
    (S₁ S₂ S₃ : Matrix (Fin n) (Fin n) R)
    (hcubic : trace (S₂ * S₃ * S₁) ≠ trace (S₃ * S₂ * S₁))
    (hγ : γ₁ * γ₂ * γ₃ ≠ 0) :
    trace (M3_123 γ₁ γ₂ γ₃ S₁ S₂ S₃) ≠ trace (M3_132 γ₁ γ₂ γ₃ S₁ S₂ S₃) := by
      -- Apply the trace difference theorem to get the difference in traces.
      have h_trace_diff : Matrix.trace (M3_123 γ₁ γ₂ γ₃ S₁ S₂ S₃) - Matrix.trace (M3_132 γ₁ γ₂ γ₃ S₁ S₂ S₃) = γ₁ * γ₂ * γ₃ * (Matrix.trace (S₂ * S₃ * S₁) - Matrix.trace (S₃ * S₂ * S₁)) := by
        -- Apply the trace difference theorem to get the difference in traces using the given parameters.
        apply trace_diff_two_orderings;
      -- Since the difference of the traces is non-zero, the traces themselves must be different.
      have h_traces_ne : Matrix.trace (M3_123 γ₁ γ₂ γ₃ S₁ S₂ S₃) - Matrix.trace (M3_132 γ₁ γ₂ γ₃ S₁ S₂ S₃) ≠ 0 := by
        -- Since the product of two non-zero elements in a domain is non-zero, we can conclude that the difference of the traces is non-zero.
        apply h_trace_diff.symm ▸ mul_ne_zero hγ (sub_ne_zero.mpr hcubic);
      exact sub_ne_zero.mp h_traces_ne

/-- The curriculum order that minimises tr(M₃) for the 1↔2 swap.
    Ordering (1,2,3) is preferred over (1,3,2) when:
    c₂₃₁ < c₃₂₁  i.e.  tr(S₂S₃S₁) < tr(S₃S₂S₁) -/
theorem curriculum_optimal_swap (γ₁ γ₂ γ₃ : ℝ)
    (hγ_pos : 0 < γ₁ * γ₂ * γ₃)
    (S₁ S₂ S₃ : Matrix (Fin n) (Fin n) ℝ) :
    -- Ordering (1,2,3) has smaller trace iff c₂₃₁ < c₃₂₁
    trace (M3_123 γ₁ γ₂ γ₃ S₁ S₂ S₃) < trace (M3_132 γ₁ γ₂ γ₃ S₁ S₂ S₃) ↔
    trace (S₂ * S₃ * S₁) < trace (S₃ * S₂ * S₁) := by
      -- Apply the trace difference theorem to rewrite the goal in terms of the cubic terms.
      have h_trace_diff : trace (M3_123 γ₁ γ₂ γ₃ S₁ S₂ S₃) - trace (M3_132 γ₁ γ₂ γ₃ S₁ S₂ S₃) = γ₁ * γ₂ * γ₃ * (trace (S₂ * S₃ * S₁) - trace (S₃ * S₂ * S₁)) := by
        -- Apply the theorem trace_diff_two_orderings to conclude the proof.
        apply trace_diff_two_orderings;
      constructor <;> intro <;> nlinarith [ h_trace_diff ] ;