/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 30475e78-34e5-47ea-8585-511dd23bc1ab

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
This module proves the "Cubic Collapse" theorem for K=4 symmetric update matrices.
It establishes that for symmetric matrices Σᵢ and update operators Aᵢ = I - γᵢΣᵢ,
the trace of the product A₄A₃A₂A₁ is equal to the trace of the reversed product A₁A₂A₃A₄.
This implies that cubic terms in the expansion which change sign under reversal must vanish.
The result is generalized to K=3 and K=5 as well, demonstrating a general palindrome symmetry for traces of products of symmetric matrices.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

/-
If S is a symmetric matrix, then the update matrix I - gS is also symmetric.
-/
open Matrix

lemma update_op_sym {n : Type*} [Fintype n] [DecidableEq n] {R : Type*} [CommRing R] (g : R) (S : Matrix n n R) (hS : Sᵀ = S) :
    ((1 : Matrix n n R) - g • S)ᵀ = (1 : Matrix n n R) - g • S := by
  simp [transpose_sub, transpose_one, transpose_smul, hS]

/-
The trace of the product of four symmetric update matrices is equal to the trace of the product of the matrices in reverse order.
-/
open Matrix

theorem cubic_collapse_K4
    {n : Type*} [Fintype n] [DecidableEq n] {R : Type*} [CommRing R]
    (g1 g2 g3 g4 : R) (S1 S2 S3 S4 : Matrix n n R)
    (h1 : S1ᵀ = S1) (h2 : S2ᵀ = S2) (h3 : S3ᵀ = S3) (h4 : S4ᵀ = S4) :
    let A1 := (1 : Matrix n n R) - g1 • S1
    let A2 := (1 : Matrix n n R) - g2 • S2
    let A3 := (1 : Matrix n n R) - g3 • S3
    let A4 := (1 : Matrix n n R) - g4 • S4
    trace (A4 * A3 * A2 * A1) = trace (A1 * A2 * A3 * A4) := by
  simp only []
  -- Step 1: each Aᵢ is symmetric
  set A1 := (1 : Matrix n n R) - g1 • S1
  set A2 := (1 : Matrix n n R) - g2 • S2
  set A3 := (1 : Matrix n n R) - g3 • S3
  set A4 := (1 : Matrix n n R) - g4 • S4
  have hA1 : A1ᵀ = A1 := update_op_sym g1 S1 h1
  have hA2 : A2ᵀ = A2 := update_op_sym g2 S2 h2
  have hA3 : A3ᵀ = A3 := update_op_sym g3 S3 h3
  have hA4 : A4ᵀ = A4 := update_op_sym g4 S4 h4
  -- Step 2: (A₄A₃A₂A₁)ᵀ = A₁A₂A₃A₄
  have hrev : (A4 * A3 * A2 * A1)ᵀ = A1 * A2 * A3 * A4 := by
    simp [transpose_mul, hA1, hA2, hA3, hA4, mul_assoc]
  -- Step 3: tr(M) = tr(Mᵀ)
  nth_rw 1 [← hrev]
  exact trace_transpose _

/-
The difference between the trace of the product of four symmetric update matrices and the trace of the product of the matrices in reverse order is zero.
-/
open Matrix

theorem cubic_terms_vanish_K4
    {n : Type*} [Fintype n] [DecidableEq n] {R : Type*} [CommRing R]
    (g1 g2 g3 g4 : R) (S1 S2 S3 S4 : Matrix n n R)
    (h1 : S1ᵀ = S1) (h2 : S2ᵀ = S2) (h3 : S3ᵀ = S3) (h4 : S4ᵀ = S4) :
    let A1 := (1 : Matrix n n R) - g1 • S1
    let A2 := (1 : Matrix n n R) - g2 • S2
    let A3 := (1 : Matrix n n R) - g3 • S3
    let A4 := (1 : Matrix n n R) - g4 • S4
    trace (A4 * A3 * A2 * A1) - trace (A1 * A2 * A3 * A4) = 0 := by
      convert sub_eq_zero_of_eq ( cubic_collapse_K4 g1 g2 g3 g4 S1 S2 S3 S4 h1 h2 h3 h4 ) using 1

/-
The trace of the product of three symmetric update matrices is equal to the trace of the product of the matrices in reverse order.
-/
open Matrix

theorem cubic_collapse_K3_check
    {n : Type*} [Fintype n] [DecidableEq n] {R : Type*} [CommRing R]
    (g1 g2 g3 : R) (S1 S2 S3 : Matrix n n R)
    (h1 : S1ᵀ = S1) (h2 : S2ᵀ = S2) (h3 : S3ᵀ = S3) :
    let A1 := (1 : Matrix n n R) - g1 • S1
    let A2 := (1 : Matrix n n R) - g2 • S2
    let A3 := (1 : Matrix n n R) - g3 • S3
    trace (A3 * A2 * A1) = trace (A1 * A2 * A3) := by
  simp only []
  set A1 := (1 : Matrix n n R) - g1 • S1
  set A2 := (1 : Matrix n n R) - g2 • S2
  set A3 := (1 : Matrix n n R) - g3 • S3
  have hA1 : A1ᵀ = A1 := update_op_sym g1 S1 h1
  have hA2 : A2ᵀ = A2 := update_op_sym g2 S2 h2
  have hA3 : A3ᵀ = A3 := update_op_sym g3 S3 h3
  have hrev : (A3 * A2 * A1)ᵀ = A1 * A2 * A3 := by
    simp [transpose_mul, hA1, hA2, hA3, mul_assoc]
  nth_rw 1 [← hrev]
  exact trace_transpose _

/-
The trace of the product of five symmetric update matrices is equal to the trace of the product of the matrices in reverse order.
-/
open Matrix

theorem cubic_collapse_K5
    {n : Type*} [Fintype n] [DecidableEq n] {R : Type*} [CommRing R]
    (g1 g2 g3 g4 g5 : R) (S1 S2 S3 S4 S5 : Matrix n n R)
    (h1 : S1ᵀ = S1) (h2 : S2ᵀ = S2) (h3 : S3ᵀ = S3)
    (h4 : S4ᵀ = S4) (h5 : S5ᵀ = S5) :
    let A1 := (1 : Matrix n n R) - g1 • S1
    let A2 := (1 : Matrix n n R) - g2 • S2
    let A3 := (1 : Matrix n n R) - g3 • S3
    let A4 := (1 : Matrix n n R) - g4 • S4
    let A5 := (1 : Matrix n n R) - g5 • S5
    trace (A5 * A4 * A3 * A2 * A1) = trace (A1 * A2 * A3 * A4 * A5) := by
  simp only []
  set A1 := (1 : Matrix n n R) - g1 • S1
  set A2 := (1 : Matrix n n R) - g2 • S2
  set A3 := (1 : Matrix n n R) - g3 • S3
  set A4 := (1 : Matrix n n R) - g4 • S4
  set A5 := (1 : Matrix n n R) - g5 • S5
  have hA1 : A1ᵀ = A1 := update_op_sym g1 S1 h1
  have hA2 : A2ᵀ = A2 := update_op_sym g2 S2 h2
  have hA3 : A3ᵀ = A3 := update_op_sym g3 S3 h3
  have hA4 : A4ᵀ = A4 := update_op_sym g4 S4 h4
  have hA5 : A5ᵀ = A5 := update_op_sym g5 S5 h5
  have hrev : (A5 * A4 * A3 * A2 * A1)ᵀ = A1 * A2 * A3 * A4 * A5 := by
    simp [transpose_mul, hA1, hA2, hA3, hA4, hA5, mul_assoc]
  nth_rw 1 [← hrev]
  exact trace_transpose _