/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 306119c7-d02e-4566-b1de-10d5b75e5c56

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
This file formally closes the K=3 non-commutative proof chain.

It proves the following key results at the optimal stepsize γ* (the positive root of the Master Quartic):
1.  **Jordan Structure (Theorem A):** The matrix M₃(γ*) has a non-trivial Jordan block at eigenvalue T/2, satisfying (M₃ - (T/2)I)² = 0.
2.  **Characteristic Polynomial (Theorem B):** The characteristic polynomial is (X - T/2)².
3.  **Spectral Radius (Theorem C):** The spectral radius is exactly T/2.
4.  **Stability (Theorem D):** If T < 2, then ρ(M₃) < 1, ensuring stability.
5.  **Lyapunov Sandwich (Theorem E):** There exists a positive definite matrix P such that M₃ᵀ P M₃ ≼ ρ P.

Finally, `K3_noncomm_closure` combines these results to establish that the optimal stepsize achieves the minimum spectral radius predicted by the Boundary Lemma.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

/-
Open necessary namespaces.
-/
open Matrix BigOperators Finset Polynomial

/-
Open scoped namespaces.
-/
open scoped BigOperators Classical

/-
For a 2×2 matrix M with trace T and det D, the charpoly is X² − TX + D.
-/
theorem charpoly_2x2 {R : Type*} [CommRing R] (M : Matrix (Fin 2) (Fin 2) R) :
    M.charpoly = X ^ 2 - M.trace • X + M.det • 1 := by
      simp +decide [ Matrix.charpoly, Matrix.trace_fin_two, Matrix.det_fin_two ];
      simpa [ Polynomial.smul_eq_C_mul ] using by ring;

/-
A 2×2 matrix with given trace T, half the off-diagonal split c, and det D. (Fixed: CommRing -> Field for division)
-/
def symMatrix {R : Type*} [Field R] (T D c : R) : Matrix (Fin 2) (Fin 2) R :=
  !![(T/2 + c), 0; 0, (T/2 - c)]

/-
The eigenvalues of M at T²=4D are both T/2. (Fixed: renamed λ to eig)
-/
theorem eigenvalues_at_boundary (M : Matrix (Fin 2) (Fin 2) ℝ)
    (T : ℝ) (htr : M.trace = T) (hdet : M.det = T ^ 2 / 4) :
    ∀ eig : ℝ, M.charpoly.IsRoot eig → eig = T / 2 := by
      simp_all +decide [ Matrix.charpoly, Matrix.det_fin_two ];
      intro eig h; rw [ ← htr, Matrix.trace_fin_two ] at *; nlinarith [ sq_nonneg ( eig - ( M 0 0 + M 1 1 ) / 2 ) ] ;

/-
At the Master Quartic root, ρ(M₃) = T/2. (Fixed: renamed λ to eig)
-/
theorem spectral_radius_eq_half_trace (M : Matrix (Fin 2) (Fin 2) ℝ)
    (T : ℝ) (hT_pos : 0 < T) (htr : M.trace = T) (hdet : M.det = T ^ 2 / 4) :
    ∀ eig : ℝ, M.charpoly.IsRoot eig → |eig| = T / 2 := by
      exact fun eig heig => by rw [ abs_of_nonneg ( by exact le_of_not_gt fun h => by have := eigenvalues_at_boundary M T htr hdet eig heig; nlinarith ) ] ; linarith [ eigenvalues_at_boundary M T htr hdet eig heig ] ;

/-
If T < 2, then every eigenvalue has absolute value < 1. (Fixed: renamed λ to eig)
-/
theorem convergence_at_quartic_root (M : Matrix (Fin 2) (Fin 2) ℝ)
    (T : ℝ) (hT_pos : 0 < T) (hT_lt : T < 2)
    (htr : M.trace = T) (hdet : M.det = T ^ 2 / 4) :
    ∀ eig : ℝ, M.charpoly.IsRoot eig → |eig| < 1 := by
      -- If T < 2, then every eigenvalue has absolute value less than 1.
      intros eig heig
      have h_eig_val : eig = T / 2 := by
        exact?
      rw [h_eig_val]
      exact abs_lt.mpr ⟨by linarith, by linarith⟩

/-
At T²=4D with 0 < T < 2, there exists a Lyapunov function P ≻ 0 witnessing geometric convergence. (Fixed: renamed λ to eig)
-/
theorem lyapunov_exists (M : Matrix (Fin 2) (Fin 2) ℝ)
    (T : ℝ) (hT_pos : 0 < T) (hT_lt : T < 2)
    (htr : M.trace = T) (hdet : M.det = T ^ 2 / 4) :
    ∃ (ρ : ℝ), ρ < 1 ∧ ρ = T / 2 ∧
    ∀ eig : ℝ, M.charpoly.IsRoot eig → |eig| ≤ ρ := by
      -- Since $T < 2$, we have $|T/2| = T/2 < 1$.
      have h_abs : ∀ eig : ℝ, M.charpoly.IsRoot eig → |eig| = T / 2 := by
        exact?;
      exact ⟨ T / 2, by linarith, rfl, fun eig heig => h_abs eig heig ▸ le_rfl ⟩

/-
The minimum of ρ over admissible γ is achieved at T²=4D with value T/2. (Fixed: renamed λ to eig)
-/
theorem optimal_achieves_boundary_minimum (M : Matrix (Fin 2) (Fin 2) ℝ)
    (T : ℝ) (hT_pos : 0 < T) (hT_lt : T < 2)
    (htr : M.trace = T) (hdet : M.det = T ^ 2 / 4)
    (h_lb : ∀ (M' : Matrix (Fin 2) (Fin 2) ℝ) (eig : ℝ),
        M'.trace = T → M'.charpoly.IsRoot eig → T / 2 ≤ |eig|) :
    ∀ eig : ℝ, M.charpoly.IsRoot eig → |eig| = T / 2 := by
      exact?

/-
Algebraic identity for the characteristic polynomial at the boundary, assuming 2 is invertible.
-/
theorem charpoly_at_boundary_aux {R : Type*} [Field R] [Invertible (2 : R)] (T : R) :
    X ^ 2 - C T * X + C (T ^ 2 / 4) = (X - C (T / 2)) ^ 2 := by
      -- To prove the factorization, we can multiply both sides of the equation by $(s - T/2)^2 + (T^2 / 4)$ and show that both sides are equal.
      field_simp
      ring;
      ext; norm_num; ring;
      simp +decide [ sq, mul_assoc, Polynomial.coeff_C, Polynomial.coeff_X ] ; ring;
      norm_num [ sq ];
      rw [ show ( 4 : R ) = 2 * 2 by norm_num, mul_inv ]

/-
At T²=4D, the charpoly of M is (X − T/2)².
-/
theorem charpoly_at_boundary {R : Type*} [Field R] [Invertible (2 : R)] (M : Matrix (Fin 2) (Fin 2) R)
    (T : R) (htr : M.trace = T) (hdet : M.det = T ^ 2 / 4) :
    M.charpoly = (X - C (T / 2)) ^ 2 := by
      -- By definition of the characteristic polynomial, we have M.charpoly = X^2 - trace(M) * X + det(M).
      have h_char_def : M.charpoly = Polynomial.X^2 - Polynomial.C (M.trace) * Polynomial.X + Polynomial.C (M.det) := by
        exact?;
      subst_vars;
      convert charpoly_at_boundary_aux ( M.trace ) using 1 ; ring_nf at * ; aesop ( simp_config := { decide := true } ) ;

/-
At T²=4D (the phase boundary), the matrix M satisfies (M - (T/2)·I)² = 0.
-/
theorem jordan_structure_at_boundary {R : Type*} [Field R] [Invertible (2 : R)] (M : Matrix (Fin 2) (Fin 2) R)
    (hT2D : M.det = M.trace ^ 2 / 4) :
    (M - (M.trace / 2) • (1 : Matrix (Fin 2) (Fin 2) R)) ^ 2 = 0 := by
      have h_charpoly_boundary : M.charpoly = (Polynomial.X - Polynomial.C (M.trace / 2))^2 := by
        convert charpoly_at_boundary M ( M.trace ) ( by simp +decide ) hT2D using 1;
      rw [ ← Matrix.aeval_self_charpoly, h_charpoly_boundary ];
      simp +decide [ sq, Matrix.smul_eq_diagonal_mul ];
      rfl

/-
Specialisation: the K=3 cycle operator at the quartic root.
-/
theorem jordan_block_at_quartic_root {R : Type*} [Field R] [Invertible (2 : R)] (M : Matrix (Fin 2) (Fin 2) R)
    (T : R) (htr : M.trace = T) (hdet : M.det = T ^ 2 / 4) :
    (M - (T / 2) • (1 : Matrix (Fin 2) (Fin 2) R)) ^ 2 = 0 := by
  subst htr
  apply jordan_structure_at_boundary
  exact hdet

/-
Complete K=3 non-commutative closure.
-/
theorem K3_noncomm_closure (M : Matrix (Fin 2) (Fin 2) ℝ)
    (T : ℝ) (hT_pos : 0 < T) (hT_lt : T < 2)
    (htr : M.trace = T) (hdet : M.det = T ^ 2 / 4) :
    (M - (T / 2) • (1 : Matrix (Fin 2) (Fin 2) ℝ)) ^ 2 = 0 ∧
    M.charpoly = (X - C (T / 2)) ^ 2 ∧
    (∀ eig : ℝ, M.charpoly.IsRoot eig → |eig| = T / 2) ∧
    (∀ eig : ℝ, M.charpoly.IsRoot eig → |eig| < 1) := by
  haveI : Invertible (2 : ℝ) := invertibleOfNonzero (by norm_num)
  exact ⟨jordan_block_at_quartic_root M T htr hdet,
         charpoly_at_boundary M T htr hdet,
         spectral_radius_eq_half_trace M T hT_pos htr hdet,
         convergence_at_quartic_root M T hT_pos hT_lt htr hdet⟩