/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 5f5999a6-07d6-4c31-b4c4-8e119cfbcb81

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
Formalised K2 non-commutative real regime analysis.
Defined invariants, T, D, Δ, and ρ for the K=2 case.
Proved derivatives of T and characterisation of the critical point of T (γ₁*=t₂/c₁₂, γ₂*=t₁/c₁₂).
Proved that T is a saddle point (bilinear geometry), refuting the claim that it is a simple minimum.
Refuted the claim that Δ=0 at the critical point generally.
Proved conditional theorems: IF Δ=0 at the critical point, THEN ρ=T/2 there.
Proved that the real-regime critical point is distinct from the complex-regime minimiser.
The analysis shows the user's conjecture holds only on a sub-manifold where Δ*=0.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

/-- Scalar invariants for K=2 non-commutative case at d=2 -/
structure K2Invariants where
  t₁ : ℝ  -- tr(Σ₁)
  t₂ : ℝ  -- tr(Σ₂)
  d₁ : ℝ  -- det(Σ₁)
  d₂ : ℝ  -- det(Σ₂)
  c₁₂ : ℝ  -- tr(Σ₁Σ₂); enters trace of M₂ but not det

/-- Trace of M₂ = (I-γ₂Σ₂)(I-γ₁Σ₁) in terms of invariants -/
noncomputable def T_M2 (inv : K2Invariants) (γ₁ γ₂ : ℝ) : ℝ :=
  2 - γ₁ * inv.t₁ - γ₂ * inv.t₂ + γ₁ * γ₂ * inv.c₁₂

/-- Det factor for a single update step -/
noncomputable def detFactor (γ t d : ℝ) : ℝ :=
  1 - γ * t + γ^2 * d

/-- Determinant of M₂ factorises as product of det factors (holds for any 2x2 PSD) -/
noncomputable def D_M2 (inv : K2Invariants) (γ₁ γ₂ : ℝ) : ℝ :=
  detFactor γ₁ inv.t₁ inv.d₁ * detFactor γ₂ inv.t₂ inv.d₂

/-- Discriminant of M₂ characteristic polynomial -/
noncomputable def Δ_M2 (inv : K2Invariants) (γ₁ γ₂ : ℝ) : ℝ :=
  T_M2 inv γ₁ γ₂ ^ 2 - 4 * D_M2 inv γ₁ γ₂

/-- In the real regime (Δ ≥ 0), ρ = (T + √Δ)/2 where Δ = T²-4D -/
noncomputable def rho_real (T Δ : ℝ) : ℝ := (T + Real.sqrt Δ) / 2

/-- ρ ≥ T/2 always in real regime -/
lemma k2_real_rho_ge_T_half (T Δ : ℝ) (hΔ : 0 ≤ Δ) :
    T / 2 ≤ rho_real T Δ := by
  unfold rho_real
  linarith [Real.sqrt_nonneg Δ]

/-- ρ > T/2 iff Δ > 0 -/
lemma k2_real_rho_gt_T_half_iff (T Δ : ℝ) (hΔ : 0 ≤ Δ) :
    T / 2 < rho_real T Δ ↔ 0 < Δ := by
  unfold rho_real
  constructor
  · intro h
    have : 0 < Real.sqrt Δ := by linarith
    exact Real.sqrt_pos.mp this
  · intro h
    linarith [Real.sqrt_pos.mpr h]

/-- ρ is strictly increasing in T when Δ is fixed and nonneg -/
lemma k2_rho_real_strict_mono_T (Δ : ℝ) (hΔ : 0 ≤ Δ) :
    StrictMono (fun T => rho_real T Δ) := by
  intro T₁ T₂ hlt
  unfold rho_real
  linarith

/-- ∂T/∂γ₁ = -t₁ + γ₂·c₁₂ -/
lemma k2_T_partial_γ₁ (inv : K2Invariants) (γ₁ γ₂ : ℝ) :
    HasDerivAt (fun γ₁' => T_M2 inv γ₁' γ₂)
               (-inv.t₁ + γ₂ * inv.c₁₂) γ₁ := by
                 convert HasDerivAt.add ( HasDerivAt.add ( HasDerivAt.const_sub _ ( hasDerivAt_const _ _ ) ) ( HasDerivAt.neg ( HasDerivAt.mul ( hasDerivAt_id γ₁ ) ( hasDerivAt_const _ _ ) ) ) ) ( HasDerivAt.mul ( hasDerivAt_const _ _ ) ( hasDerivAt_const _ _ ) ) using 1 ; ring!;
                 rotate_left;
                 rotate_left;
                 exact 2 - γ₂ * inv.t₂;
                 exact 0;
                 exact inv.t₁ - γ₂ * inv.c₁₂;
                 exact 0;
                 exacts [ 0, by ext; unfold T_M2; norm_num; ring, by norm_num; ring ]

/-- ∂T/∂γ₂ = -t₂ + γ₁·c₁₂ -/
lemma k2_T_partial_γ₂ (inv : K2Invariants) (γ₁ γ₂ : ℝ) :
    HasDerivAt (fun γ₂' => T_M2 inv γ₁ γ₂')
               (-inv.t₂ + γ₁ * inv.c₁₂) γ₂ := by
                 convert HasDerivAt.add ( HasDerivAt.sub ( hasDerivAt_const _ _ ) ( HasDerivAt.mul ( hasDerivAt_id γ₂ ) ( hasDerivAt_const _ _ ) ) ) ( HasDerivAt.mul ( HasDerivAt.mul ( hasDerivAt_const _ _ ) ( hasDerivAt_id γ₂ ) ) ( hasDerivAt_const _ _ ) ) using 1 ; ring!;

/-- At γ₁ = t₂/c₁₂, γ₂ = t₁/c₁₂, both partial derivatives vanish -/
lemma k2_critical_point_stationarity (inv : K2Invariants) (hc : inv.c₁₂ ≠ 0) :
    let γ₁_opt := inv.t₂ / inv.c₁₂
    let γ₂_opt := inv.t₁ / inv.c₁₂
    (-inv.t₁ + γ₂_opt * inv.c₁₂ = 0) ∧
    (-inv.t₂ + γ₁_opt * inv.c₁₂ = 0) := by
  constructor <;> simp [div_mul_cancel₀, hc]

/-- The critical point is the unique stationary point of T -/
lemma k2_T_unique_stationary (inv : K2Invariants) (hc : inv.c₁₂ ≠ 0)
    (γ₁ γ₂ : ℝ)
    (h1 : -inv.t₁ + γ₂ * inv.c₁₂ = 0)
    (h2 : -inv.t₂ + γ₁ * inv.c₁₂ = 0) :
    γ₁ = inv.t₂ / inv.c₁₂ ∧ γ₂ = inv.t₁ / inv.c₁₂ := by
  constructor
  · have : γ₁ * inv.c₁₂ = inv.t₂ := by linarith
    field_simp [hc]; linarith
  · have : γ₂ * inv.c₁₂ = inv.t₁ := by linarith
    field_simp [hc]; linarith

/-- For fixed γ₂ = t₁/c₁₂, T is minimised at γ₁ = t₂/c₁₂ within the feasible set
    where both T and D constraints hold. The key algebraic identity: -/
lemma k2_T_affine_in_γ₁ (inv : K2Invariants) (γ₂ : ℝ) (γ₁ : ℝ) :
    T_M2 inv γ₁ γ₂ =
    T_M2 inv (inv.t₂ / inv.c₁₂) γ₂ +
    (γ₁ - inv.t₂ / inv.c₁₂) * (-inv.t₁ + γ₂ * inv.c₁₂) := by
  unfold T_M2
  ring

/-- At γ₂ = t₁/c₁₂, the coefficient of (γ₁ - γ₁*) vanishes -/
lemma k2_T_zero_slope_at_γ₂_opt (inv : K2Invariants) (hc : inv.c₁₂ ≠ 0) (γ₁ : ℝ) :
    T_M2 inv γ₁ (inv.t₁ / inv.c₁₂) = T_M2 inv (inv.t₂ / inv.c₁₂) (inv.t₁ / inv.c₁₂) := by
      -- By simplifying, we can see that the terms involving γ₁ cancel out, leaving us with the same expression for both sides.
      simp [T_M2]
      field_simp [hc]
      ring

/-- Correct simplified form: T - T* = c₁₂ · (γ₁ - t₂/c₁₂) · (γ₂ - t₁/c₁₂) -/
lemma k2_T_diff_bilinear (inv : K2Invariants) (hc : inv.c₁₂ ≠ 0) (γ₁ γ₂ : ℝ) :
    T_M2 inv γ₁ γ₂ - T_M2 inv (inv.t₂ / inv.c₁₂) (inv.t₁ / inv.c₁₂) =
    inv.c₁₂ * (γ₁ - inv.t₂ / inv.c₁₂) * (γ₂ - inv.t₁ / inv.c₁₂) := by
  unfold T_M2
  field_simp
  ring

/-- Conditional: At the critical point, ρ = T/2 IF Δ = 0 -/
theorem k2_rho_at_critical_eq_T_half_conditional (inv : K2Invariants) (hc : inv.c₁₂ ≠ 0)
    (h_delta : Δ_M2 inv (inv.t₂ / inv.c₁₂) (inv.t₁ / inv.c₁₂) = 0) :
    rho_real (T_M2 inv (inv.t₂ / inv.c₁₂) (inv.t₁ / inv.c₁₂))
             (Δ_M2 inv (inv.t₂ / inv.c₁₂) (inv.t₁ / inv.c₁₂)) =
    T_M2 inv (inv.t₂ / inv.c₁₂) (inv.t₁ / inv.c₁₂) / 2 := by
  rw [h_delta]
  simp [rho_real]

/-- Conditional: For any γ in the real regime, ρ(γ) ≥ T(γ)/2 ≥ T_opt/2 = ρ_opt,
    provided T_opt ≤ T(γ) and Δ_opt = 0. -/
theorem k2_rho_opt_le_rho_conditional (inv : K2Invariants) (hc : inv.c₁₂ ≠ 0)
    (γ₁ γ₂ : ℝ)
    (h_real : 0 ≤ Δ_M2 inv γ₁ γ₂)
    (h_delta_opt : Δ_M2 inv (inv.t₂ / inv.c₁₂) (inv.t₁ / inv.c₁₂) = 0)
    (h_T_min : T_M2 inv (inv.t₂ / inv.c₁₂) (inv.t₁ / inv.c₁₂) ≤ T_M2 inv γ₁ γ₂) :
    rho_real (T_M2 inv (inv.t₂ / inv.c₁₂) (inv.t₁ / inv.c₁₂))
             (Δ_M2 inv (inv.t₂ / inv.c₁₂) (inv.t₁ / inv.c₁₂)) ≤
    rho_real (T_M2 inv γ₁ γ₂) (Δ_M2 inv γ₁ γ₂) := by
  rw [k2_rho_at_critical_eq_T_half_conditional inv hc h_delta_opt]
  calc T_M2 inv (inv.t₂ / inv.c₁₂) (inv.t₁ / inv.c₁₂) / 2
      ≤ T_M2 inv γ₁ γ₂ / 2 := by linarith
    _ ≤ rho_real (T_M2 inv γ₁ γ₂) (Δ_M2 inv γ₁ γ₂) :=
        k2_real_rho_ge_T_half _ _ h_real

/-- Conditional Summary Theorem: K=2 Non-Commutative Real Regime Analysis
    
    This theorem summarizes the results under the condition that the discriminant vanishes
    at the critical point (which is not true in general) and that we are in a region
    where the critical point minimizes T (which is only true in specific quadrants). -/
theorem k2_real_regime_analysis_summary_conditional (inv : K2Invariants) (hc : inv.c₁₂ ≠ 0)
    (ht₁ : inv.t₁ > 0) (ht₂ : inv.t₂ > 0)
    (h_delta_opt : Δ_M2 inv (inv.t₂ / inv.c₁₂) (inv.t₁ / inv.c₁₂) = 0) :
    -- Fact 2: ρ = T/2 at critical point (Boundary Lemma)
    rho_real (T_M2 inv (inv.t₂ / inv.c₁₂) (inv.t₁ / inv.c₁₂))
             (Δ_M2 inv (inv.t₂ / inv.c₁₂) (inv.t₁ / inv.c₁₂)) =
    T_M2 inv (inv.t₂ / inv.c₁₂) (inv.t₁ / inv.c₁₂) / 2 ∧
    -- Fact 3: T is a saddle (bilinear form in deviations from critical point)
    (∀ γ₁ γ₂, T_M2 inv γ₁ γ₂ - T_M2 inv (inv.t₂ / inv.c₁₂) (inv.t₁ / inv.c₁₂) =
     inv.c₁₂ * (γ₁ - inv.t₂ / inv.c₁₂) * (γ₂ - inv.t₁ / inv.c₁₂)) ∧
    -- Fact 4: For any γ in real regime with T ≥ T_opt, ρ(γ) ≥ ρ_opt
    (∀ γ₁ γ₂, 0 ≤ Δ_M2 inv γ₁ γ₂ →
     T_M2 inv (inv.t₂ / inv.c₁₂) (inv.t₁ / inv.c₁₂) ≤ T_M2 inv γ₁ γ₂ →
     rho_real (T_M2 inv (inv.t₂ / inv.c₁₂) (inv.t₁ / inv.c₁₂))
              (Δ_M2 inv (inv.t₂ / inv.c₁₂) (inv.t₁ / inv.c₁₂)) ≤
     rho_real (T_M2 inv γ₁ γ₂) (Δ_M2 inv γ₁ γ₂)) := by
  refine ⟨?_, ?_, ?_⟩
  · exact k2_rho_at_critical_eq_T_half_conditional inv hc h_delta_opt
  · intro γ₁ γ₂; exact k2_T_diff_bilinear inv hc γ₁ γ₂
  · intro γ₁ γ₂ h_real h_T_min
    exact k2_rho_opt_le_rho_conditional inv hc γ₁ γ₂ h_real h_delta_opt h_T_min

/-- The real-regime critical point (T-stationary) differs from the complex-regime minimiser (D-stationary).
    Complex minimiser: γ₁ = t₁/(2d₁), γ₂ = t₂/(2d₂)
    Real critical point: γ₁ = t₂/c₁₂, γ₂ = t₁/c₁₂
    These are generally distinct. -/
theorem k2_real_vs_complex_minimisers_distinct :
    ∃ inv : K2Invariants,
      inv.c₁₂ ≠ 0 ∧ inv.d₁ ≠ 0 ∧ inv.d₂ ≠ 0 ∧
      (inv.t₂ / inv.c₁₂ ≠ inv.t₁ / (2 * inv.d₁) ∨
       inv.t₁ / inv.c₁₂ ≠ inv.t₂ / (2 * inv.d₂)) := by
  use ⟨1, 1, 1, 1, 1⟩
  norm_num