/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 6ae7365f-182f-47d1-969d-ef9b65a36fb7

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
We define the 2x2 symplectic matrix `J2` and the scalar commutator `eps`.
We prove `commutator_structure` showing that the commutator of two symmetric matrices is proportional to `J2`.
We prove `expansion_identity` which expands the product $A_3 A_2 A_1$.
We prove `product_antisymmetric_part` which shows that the antisymmetric part of the product is proportional to `J2` with a coefficient that is a linear combination of the epsilons (weighted by traces and gammas).
This confirms that the commutator structure is captured by the three scalars.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

/-
Definition of the 2x2 symplectic matrix J.
-/
open Matrix

def J2 : Matrix (Fin 2) (Fin 2) ℝ := !![0, 1; -1, 0]

/-
Definition of the scalar epsilon derived from the commutator of two matrices.
-/
open Matrix

def eps (A B : Matrix (Fin 2) (Fin 2) ℝ) : ℝ := (A * B - B * A) 0 1

/-
The commutator of two 2x2 symmetric matrices is proportional to J2.
-/
open Matrix

theorem commutator_structure
  (S1 S2 : Matrix (Fin 2) (Fin 2) ℝ)
  (hS1 : S1.IsSymm) (hS2 : S2.IsSymm) :
  S1 * S2 - S2 * S1 = (eps S1 S2) • J2 := by
  unfold eps J2;
  have hS : S1 1 0 = S1 0 1 ∧ S2 1 0 = S2 0 1 := by
    exact ⟨ by simpa using congr_fun ( congr_fun hS1 0 ) 1, by simpa using congr_fun ( congr_fun hS2 0 ) 1 ⟩;
  ext i j ; fin_cases i <;> fin_cases j <;> norm_num [ hS, Matrix.mul_apply ] <;> ring!;

/-
The product of three matrices A3 A2 A1 expands to a specific polynomial in g and S.
-/
open Matrix

theorem expansion_identity
  (g1 g2 g3 : ℝ)
  (S1 S2 S3 : Matrix (Fin 2) (Fin 2) ℝ)
  (A1 : Matrix (Fin 2) (Fin 2) ℝ) (hA1 : A1 = 1 - g1 • S1)
  (A2 : Matrix (Fin 2) (Fin 2) ℝ) (hA2 : A2 = 1 - g2 • S2)
  (A3 : Matrix (Fin 2) (Fin 2) ℝ) (hA3 : A3 = 1 - g3 • S3) :
  A3 * A2 * A1 = 1 - (g1 • S1 + g2 • S2 + g3 • S3) +
    ((g1 * g2) • (S2 * S1) + (g1 * g3) • (S3 * S1) + (g2 * g3) • (S3 * S2)) -
    (g1 * g2 * g3) • (S3 * S2 * S1) := by
  norm_num [ hA1, hA2, hA3, mul_sub, sub_mul, mul_assoc ] ; ring;
  ext i j ; norm_num ; ring;

/-
The commutator of A1 and A2 is proportional to J2, scaled by the product of gammas and epsilon.
-/
open Matrix

theorem commutator_of_A
  (g1 g2 : ℝ)
  (S1 S2 : Matrix (Fin 2) (Fin 2) ℝ)
  (hS1 : S1.IsSymm) (hS2 : S2.IsSymm)
  (A1 : Matrix (Fin 2) (Fin 2) ℝ) (hA1 : A1 = 1 - g1 • S1)
  (A2 : Matrix (Fin 2) (Fin 2) ℝ) (hA2 : A2 = 1 - g2 • S2) :
  A1 * A2 - A2 * A1 = (g1 * g2 * eps S1 S2) • J2 := by
  unfold eps;
  -- Substitute the definition of the commutator and simplify.
  have h_comm : A1 * A2 - A2 * A1 = (g1 * g2) • (S1 * S2 - S2 * S1) := by
    ext i j; simp +decide [ *, mul_sub, sub_mul ] ; ring;
  rw [ h_comm, show ( S1 * S2 - S2 * S1 ) = ( S1 * S2 - S2 * S1 ) 0 1 • J2 from ?_ ];
  · norm_num [ ← smul_assoc ];
    norm_num [ J2 ];
  · convert commutator_structure S1 S2 hS1 hS2 using 1

/-
The antisymmetric part of the product is proportional to J2, with a coefficient depending on the epsilons and traces.
-/
open Matrix

def cubic_coeff (S1 S2 S3 : Matrix (Fin 2) (Fin 2) ℝ) : ℝ :=
  (eps S1 S2 * S3.trace + eps S1 S3 * S2.trace + eps S2 S3 * S1.trace) / 2

theorem product_antisymmetric_part
  (g1 g2 g3 : ℝ)
  (S1 S2 S3 : Matrix (Fin 2) (Fin 2) ℝ)
  (hS1 : S1.IsSymm) (hS2 : S2.IsSymm) (hS3 : S3.IsSymm)
  (A1 : Matrix (Fin 2) (Fin 2) ℝ) (hA1 : A1 = 1 - g1 • S1)
  (A2 : Matrix (Fin 2) (Fin 2) ℝ) (hA2 : A2 = 1 - g2 • S2)
  (A3 : Matrix (Fin 2) (Fin 2) ℝ) (hA3 : A3 = 1 - g3 • S3) :
  let P := A3 * A2 * A1
  P - P.transpose =
    ( - g1 * g2 * eps S1 S2
      - g1 * g3 * eps S1 S3
      - g2 * g3 * eps S2 S3
      + g1 * g2 * g3 * cubic_coeff S1 S2 S3
    ) • J2 := by
  unfold cubic_coeff;
  ext i j; fin_cases i <;> fin_cases j <;> norm_num [ hA1, hA2, hA3, Matrix.mul_apply ] ; ring; (
  unfold J2; norm_num;);
  · unfold eps; norm_num [ Matrix.mul_apply, Matrix.trace ] ; ring; (
    unfold J2; norm_num ; ring;
    rw [ show S1 0 1 = S1 1 0 by simpa [ eq_comm ] using congr_fun ( congr_fun hS1 1 ) 0, show S2 0 1 = S2 1 0 by simpa [ eq_comm ] using congr_fun ( congr_fun hS2 1 ) 0, show S3 0 1 = S3 1 0 by simpa [ eq_comm ] using congr_fun ( congr_fun hS3 1 ) 0 ] ; ring;);
  · unfold eps; norm_num [ J2, Matrix.trace ] ; ring; (
    norm_num [ Matrix.mul_apply, hS1.apply, hS2.apply, hS3.apply ] ; ring;);
  · unfold eps J2; norm_num [ Matrix.trace ] ; ring;