/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 719c8d4f-2414-4128-a36d-49b996171f34

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
Formalized the Master Sextic discriminant identity for K=4 non-commutative tasks under statistical symmetry. Defined the trace T_K4, determinant D_K4, discriminant Delta_K4, and the Master Sextic polynomial P6. Proved the identity Delta_K4 = γ² * P6, and derived corollaries regarding the factorization, boundary conditions, and degree structure.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

/-
Trace of M₄ under statistical task symmetry with uniform stepsize γ.
-/
noncomputable def T_K4 (γ t c k3 I4 : ℝ) : ℝ :=
  2 - 4*t*γ + 6*c*γ^2 - 4*k3*γ^3 + I4*γ^4

/-
Determinant of M₄ under statistical task symmetry.
-/
noncomputable def D_K4 (γ t d : ℝ) : ℝ :=
  (1 - t*γ + d*γ^2)^4

/-
The discriminant Δ₄ = T² − 4D
-/
noncomputable def Delta_K4 (γ t d c k3 I4 : ℝ) : ℝ :=
  T_K4 γ t c k3 I4 ^ 2 - 4 * D_K4 γ t d

/-
The Master Sextic P₆
-/
noncomputable def P6 (γ t d c k3 I4 : ℝ) : ℝ :=
  (I4^2 - 4*d^4) * γ^6
  + (-8*I4*k3 + 16*d^3*t) * γ^5
  + (12*I4*c - 16*d^3 - 24*d^2*t^2 + 16*k3^2) * γ^4
  + (-8*I4*t - 48*c*k3 + 48*d^2*t + 16*d*t^3) * γ^3
  + (4*I4 + 36*c^2 - 24*d^2 - 48*d*t^2 + 32*k3*t - 4*t^4) * γ^2
  + (-48*c*t + 48*d*t - 16*k3 + 16*t^3) * γ
  + (24*c - 16*d - 8*t^2)

/-
Main theorem: The Master Sextic discriminant identity.
-/
theorem master_sextic_identity (γ t d c k3 I4 : ℝ) :
    Delta_K4 γ t d c k3 I4 = γ^2 * P6 γ t d c k3 I4 := by
  unfold Delta_K4 T_K4 D_K4 P6
  ring

/-
Corollary: The discriminant vanishes at γ=0 (double root).
-/
theorem delta_K4_zero_at_zero (t d c k3 I4 : ℝ) :
    Delta_K4 0 t d c k3 I4 = 0 := by
      unfold Delta_K4 T_K4 D_K4; norm_num;

/-
Corollary: The Master Sextic is the unique polynomial P such that Δ₄ = γ²·P.
-/
theorem delta_K4_factorisation (γ t d c k3 I4 : ℝ) :
    T_K4 γ t c k3 I4 ^ 2 - 4 * D_K4 γ t d = γ^2 * P6 γ t d c k3 I4 := by
  exact master_sextic_identity γ t d c k3 I4

/-
The optimal stepsize γ* is characterised as the positive real root of P₆.
-/
theorem boundary_iff_sextic (γ t d c k3 I4 : ℝ) (hγ : γ ≠ 0) :
    T_K4 γ t c k3 I4 ^ 2 = 4 * D_K4 γ t d ↔ P6 γ t d c k3 I4 = 0 := by
  rw [← sub_eq_zero]
  rw [show T_K4 γ t c k3 I4 ^ 2 - 4 * D_K4 γ t d = γ^2 * P6 γ t d c k3 I4
      from master_sextic_identity γ t d c k3 I4]
  constructor
  · intro h
    exact (mul_eq_zero.mp h).resolve_left (pow_ne_zero 2 hγ)
  · intro h
    simp [h]

/-
The degree structure: P₆ has degree 6 in γ with leading coefficient I4²−4d⁴.
-/
theorem P6_leading_term (t d c k3 I4 : ℝ) :
    P6 1 t d c k3 I4 =
    (I4^2 - 4*d^4)
    + (-8*I4*k3 + 16*d^3*t)
    + (12*I4*c - 16*d^3 - 24*d^2*t^2 + 16*k3^2)
    + (-8*I4*t - 48*c*k3 + 48*d^2*t + 16*d*t^3)
    + (4*I4 + 36*c^2 - 24*d^2 - 48*d*t^2 + 32*k3*t - 4*t^4)
    + (-48*c*t + 48*d*t - 16*k3 + 16*t^3)
    + (24*c - 16*d - 8*t^2) := by
  unfold P6; ring

/-
Comparison with K=3 Master Quartic: the structure is identical with K replaced by K+1.
-/
theorem sextic_vs_quartic_degree : (6 : ℕ) = 2 * (4 - 1) := by norm_num

/-
Summary theorem combining all results.
-/
theorem master_sextic_summary :
    -- 1. The identity holds
    (∀ γ t d c k3 I4 : ℝ,
      T_K4 γ t c k3 I4 ^ 2 - 4 * D_K4 γ t d = γ^2 * P6 γ t d c k3 I4) ∧
    -- 2. At γ=0: discriminant vanishes
    (∀ t d c k3 I4 : ℝ, Delta_K4 0 t d c k3 I4 = 0) ∧
    -- 3. Boundary T²=4D ↔ P₆=0 for γ≠0
    (∀ γ t d c k3 I4 : ℝ, γ ≠ 0 →
      (T_K4 γ t c k3 I4 ^ 2 = 4 * D_K4 γ t d ↔ P6 γ t d c k3 I4 = 0)) :=
  ⟨master_sextic_identity, delta_K4_zero_at_zero, boundary_iff_sextic⟩