/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 809a46bf-0c82-4bb8-b9da-91ad6191ef51

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
Verified the CL Stability Certificate for K=3 Non-Commutative case.
The file defines the Task Compatibility Index (κ), Stability Margin (δ), and proves the stability certificate theorem `CL_stability_certificate_K3`.
Key results include:
- `task_compat`: Definition of κ = T₃(γ*)/2.
- `stab_margin`: Definition of δ = γ_NF - γ*.
- `T3_stable`: Proof that T₃(γ) < 2 for stable γ.
- `bwt_decay`: Proof of forgetting decay rate ~ κ².
- `CL_stability_certificate_K3`: Main theorem combining stability conditions and decay rate.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

open Real

def T3 (t c k γ : ℝ) : ℝ := 2 - 3*t*γ + 3*c*γ^2 - k*γ^3

def task_compat (t c k γ_star : ℝ) : ℝ := T3 t c k γ_star / 2

theorem compat_lt_one_iff (t c k γ_star : ℝ) (hT : T3 t c k γ_star > 0) :
    task_compat t c k γ_star < 1 ↔ T3 t c k γ_star < 2 := by
  unfold task_compat; constructor <;> intro h <;> linarith

theorem compat_pos (t c k γ_star : ℝ) (hT : T3 t c k γ_star > 0) :
    task_compat t c k γ_star > 0 := by unfold task_compat; linarith

def γ_NF (t c k : ℝ) : ℝ := (3*c + Real.sqrt (9*c^2 - 12*k*t)) / (2*k)

def stab_margin (γ_star t c k : ℝ) : ℝ := γ_NF t c k - γ_star

theorem T3_factor (t c k γ : ℝ) :
    T3 t c k γ - 2 = -γ * (k*γ^2 - 3*c*γ + 3*t) := by unfold T3; ring

theorem T3_stable (t c k γ : ℝ) (hγ : 0 < γ) (hq : k*γ^2 - 3*c*γ + 3*t > 0) :
    T3 t c k γ < 2 := by nlinarith [T3_factor t c k γ, mul_pos hγ hq]

theorem γ_NF_root (t c k : ℝ) (hk : k > 0) (hd : 9*c^2 - 12*k*t ≥ 0) :
    k * (γ_NF t c k)^2 - 3*c * (γ_NF t c k) + 3*t = 0 := by
      -- Substitute γ_NF into the quadratic equation and simplify to verify that it equals zero.
      simp [γ_NF]
      field_simp
      ring;
      -- By simplifying, we can see that the expression indeed equals zero.
      rw [Real.sq_sqrt (by linarith)]
      ring

theorem T3_at_NF (t c k : ℝ) (hk : k > 0) (hd : 9*c^2 - 12*k*t ≥ 0) :
    T3 t c k (γ_NF t c k) = 2 := by
      -- By definition of $γ_NF$, we know that $k * (γ_NF t c k)^2 - 3 * c * (γ_NF t c k) + 3 * t = 0$.
      have h_gamma_NF : k * (γ_NF t c k)^2 - 3 * c * (γ_NF t c k) + 3 * t = 0 := by
        -- By definition of $γ_NF$, we know that $k * γ_NF^2 - 3 * c * γ_NF + 3 * t = 0$ follows directly from the quadratic formula.
        apply γ_NF_root t c k hk hd;
      -- Substitute γ = γ_NF into the expression for T3 and simplify.
      have h_T3_gamma_NF : T3 t c k (γ_NF t c k) = 2 - 3 * t * γ_NF t c k + 3 * c * (γ_NF t c k)^2 - k * (γ_NF t c k)^3 := by
        rfl;
      grind

theorem bwt_decay (κ ff : ℝ) (hκ : |κ| < 1) :
    Filter.Tendsto (fun n : ℕ => ff^2 * κ^(2*n) - 1) Filter.atTop (nhds (-1)) := by
      -- Since $|κ| < 1$, we have $\lim_{n \to \infty} κ^{2n} = 0$.
      have h_pow_zero : Filter.Tendsto (fun n => κ^(2*n)) Filter.atTop (nhds 0) := by
        -- Since $|κ| < 1$, we can apply the fact that $κ^n$ tends to $0$ as $n$ approaches infinity.
        have h_pow_zero : Filter.Tendsto (fun n => κ ^ n) Filter.atTop (nhds 0) := by
          -- Apply the fact that if the absolute value of a number is less than 1, then raising it to an increasingly large power will make it approach 0.
          apply tendsto_pow_atTop_nhds_zero_of_abs_lt_one; assumption;
        -- Since $κ^n$ tends to $0$ as $n$ approaches infinity, squaring it will also tend to $0$.
        have h_pow_zero_sq : Filter.Tendsto (fun n => (κ ^ n) ^ 2) Filter.atTop (nhds 0) := by
          simpa using h_pow_zero.pow 2;
        simpa only [ pow_mul' ] using h_pow_zero_sq;
      simpa using Filter.Tendsto.sub ( h_pow_zero.const_mul ( ff ^ 2 ) ) tendsto_const_nhds

theorem bwt_bounded (ff κ : ℝ) (n : ℕ)
    (hff0 : 0 ≤ ff) (hff1 : ff ≤ 1) (hκ0 : 0 ≤ κ) (hκ1 : κ ≤ 1) :
    -1 ≤ ff^2 * κ^(2*n) - 1 ∧ ff^2 * κ^(2*n) - 1 ≤ 0 := by
  have hκn : κ^(2*n) ≤ 1 := pow_le_one₀ hκ0 hκ1
  constructor
  · linarith [mul_nonneg (sq_nonneg ff) (pow_nonneg hκ0 (2*n))]
  · nlinarith [mul_le_one₀ (by nlinarith : ff^2 ≤ 1) (pow_nonneg hκ0 _) hκn]

theorem CL_stability_certificate_K3
    (t c k γ_star : ℝ)
    (hk : k > 0) (ht : t > 0) (hc : c ≥ 0)
    (hd : 9*c^2 - 12*k*t ≥ 0)
    (hγ_pos : 0 < γ_star)
    (hγ_lt : γ_star < γ_NF t c k)
    (hT_pos : T3 t c k γ_star > 0)
    (hquad : ∀ x : ℝ, 0 < x → x < γ_NF t c k → k*x^2 - 3*c*x + 3*t > 0) :
    -- κ = task compatibility index
    let κ := task_compat t c k γ_star
    -- (1) κ ∈ (0, 1): training is stable at γ*
    0 < κ ∧ κ < 1 ∧
    -- (2) Stability margin δ > 0
    stab_margin γ_star t c k > 0 ∧
    -- (3) The entire interval (0, γ_NF) is stable
    (∀ γ : ℝ, 0 < γ → γ < γ_NF t c k → T3 t c k γ < 2) ∧
    -- (4) Boundary is tight: T₃(γ_NF) = 2
    T3 t c k (γ_NF t c k) = 2 ∧
    -- (5) BWT decays to -1 at rate κ² per cycle
    Filter.Tendsto (fun n : ℕ => (1:ℝ) * κ^(2*n) - 1) Filter.atTop (nhds (-1)) := by
      -- Now let's verify that the compatibility index is less than 1.
      have hκ_lt_1 : task_compat t c k γ_star < 1 := by
        -- Substitute the expression for T3 t c k γ_star into the compatibility index.
        have h_task_compat : task_compat t c k γ_star = T3 t c k γ_star / 2 := by
          rfl;
        linarith [ T3_stable t c k γ_star hγ_pos ( hquad γ_star hγ_pos hγ_lt ) ];
      refine' ⟨ _, hκ_lt_1, _, _, _, _ ⟩;
      · exact div_pos hT_pos zero_lt_two;
      · exact sub_pos_of_lt hγ_lt;
      · exact fun γ hγ_pos hγ_lt => T3_stable t c k γ hγ_pos ( hquad γ hγ_pos hγ_lt );
      · exact T3_at_NF t c k hk hd;
      · norm_num [ pow_mul ];
        exact le_trans ( Filter.Tendsto.sub ( tendsto_pow_atTop_nhds_zero_of_lt_one ( sq_nonneg _ ) ( by nlinarith [ show 0 ≤ task_compat t c k γ_star from div_nonneg hT_pos.le zero_le_two ] ) ) tendsto_const_nhds ) ( by norm_num )