/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 94078188-03f5-4ed3-9179-149cf17749a4

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
I have successfully loaded and verified the user's definitions and theorems regarding the NF condition for matrices.
Specifically, I have formalized:
- `A2`: The matrix function $A_2(\gamma, S) = I - \gamma S$.
- `NF3_condition`: The condition involving three matrices and three scalars.
- `NF3_diagonal_iff`: The reduction of the matrix condition to scalar inequalities for diagonal matrices.
- `NF_scalar_iff`: Simplification of the scalar condition.
- `NF_scalar_range`: The range of $\gamma$ satisfying the scalar condition.

Note: The proof of `NF_scalar_range` provided in the input relied on `sq_le_one_iff_of_nonneg`, which was not found; the ATP successfully synthesized an alternative proof.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

def A2 (g : ℝ) (S : Matrix (Fin 2) (Fin 2) ℝ) : Matrix (Fin 2) (Fin 2) ℝ :=
  (1 : Matrix (Fin 2) (Fin 2) ℝ) - g • S

open scoped MatrixOrder in
def NF3_condition (S1 S2 S3 : Matrix (Fin 2) (Fin 2) ℝ)
    (g1 g2 g3 : ℝ) : Prop :=
  (A2 g1 S1).transpose * S2 * A2 g1 S1 ≤ S2 ∧
  (A2 g1 S1).transpose * S3 * A2 g1 S1 ≤ S3 ∧
  (A2 g2 S2).transpose * S1 * A2 g2 S2 ≤ S1 ∧
  (A2 g2 S2).transpose * S3 * A2 g2 S2 ≤ S3 ∧
  (A2 g3 S3).transpose * S1 * A2 g3 S3 ≤ S1 ∧
  (A2 g3 S3).transpose * S2 * A2 g3 S3 ≤ S2

theorem NF3_diagonal_iff
    (a1 a2 b1 b2 c1 c2 : ℝ)
    (ha : 0 < a1) (ha2 : 0 < a2)
    (hb : 0 < b1) (hb2 : 0 < b2)
    (hc : 0 < c1) (hc2 : 0 < c2)
    (g1 g2 g3 : ℝ) :
    let S1 := Matrix.diagonal ![(a1 : ℝ), a2]
    let S2 := Matrix.diagonal ![(b1 : ℝ), b2]
    let S3 := Matrix.diagonal ![(c1 : ℝ), c2]
    open scoped MatrixOrder in
    NF3_condition S1 S2 S3 g1 g2 g3 ↔
    (∀ j : Fin 2, (1 - g1 * ![a1, a2] j) ^ 2 * ![b1, b2] j ≤ ![b1, b2] j) ∧
    (∀ j : Fin 2, (1 - g1 * ![a1, a2] j) ^ 2 * ![c1, c2] j ≤ ![c1, c2] j) ∧
    (∀ j : Fin 2, (1 - g2 * ![b1, b2] j) ^ 2 * ![a1, a2] j ≤ ![a1, a2] j) ∧
    (∀ j : Fin 2, (1 - g2 * ![b1, b2] j) ^ 2 * ![c1, c2] j ≤ ![c1, c2] j) ∧
    (∀ j : Fin 2, (1 - g3 * ![c1, c2] j) ^ 2 * ![a1, a2] j ≤ ![a1, a2] j) ∧
    (∀ j : Fin 2, (1 - g3 * ![c1, c2] j) ^ 2 * ![b1, b2] j ≤ ![b1, b2] j) := by
      refine' ⟨ fun h => _, fun h => _ ⟩;
      · -- By definition of NF3_condition, we know that the matrix inequalities hold.
        obtain ⟨h1, h2, h3, h4, h5, h6⟩ := h;
        unfold A2 at *; simp_all +decide [ Fin.forall_fin_two, Matrix.mul_apply, pow_two ] ;
        have := h1.2 ( Pi.single 0 1 ) ; have := h1.2 ( Pi.single 1 1 ) ; have := h2.2 ( Pi.single 0 1 ) ; have := h2.2 ( Pi.single 1 1 ) ; have := h3.2 ( Pi.single 0 1 ) ; have := h3.2 ( Pi.single 1 1 ) ; have := h4.2 ( Pi.single 0 1 ) ; have := h4.2 ( Pi.single 1 1 ) ; have := h5.2 ( Pi.single 0 1 ) ; have := h5.2 ( Pi.single 1 1 ) ; have := h6.2 ( Pi.single 0 1 ) ; have := h6.2 ( Pi.single 1 1 ) ; norm_num [ Matrix.mul_apply, Matrix.PosSemidef ] at * ;
        exact ⟨ ⟨ by nlinarith, by nlinarith ⟩, ⟨ by nlinarith, by nlinarith ⟩, by nlinarith, by nlinarith ⟩;
      · unfold NF3_condition;
        unfold A2; simp_all +decide [ Fin.forall_fin_two, Matrix.mul_apply, Matrix.diagonal ] ;
        norm_num [ Matrix.mul_apply, Matrix.le_iff ] at *;
        refine' ⟨ _, _, _, _, _ ⟩;
        · constructor <;> norm_num [ ← Matrix.ext_iff, Fin.forall_fin_two, Matrix.mul_apply ];
          · ext i j; fin_cases i <;> fin_cases j <;> norm_num [ Matrix.mul_apply ] ;
          · norm_num [ Matrix.mulVec, Matrix.mul_apply ];
            intro x; nlinarith [ sq_nonneg ( x 0 ), sq_nonneg ( x 1 ), abs_le.mp h.1.1, abs_le.mp h.1.2, mul_le_mul_of_nonneg_left ( show ( 1 - g1 * a1 ) ^ 2 ≤ 1 by nlinarith [ abs_le.mp h.1.1 ] ) hb.le, mul_le_mul_of_nonneg_left ( show ( 1 - g1 * a2 ) ^ 2 ≤ 1 by nlinarith [ abs_le.mp h.1.2 ] ) hb2.le ] ;
        · constructor;
          · ext i j; fin_cases i <;> fin_cases j <;> norm_num [ Matrix.mul_apply, Matrix.IsHermitian ] ;
          · norm_num [ Fin.sum_univ_succ, Matrix.mulVec, dotProduct ];
            norm_num [ Matrix.mul_apply, Matrix.transpose_apply ];
            intro x; nlinarith [ sq_nonneg ( x 0 ), sq_nonneg ( x 1 ), mul_le_mul_of_nonneg_left ( show ( 1 - g1 * a1 ) ^ 2 ≤ 1 by nlinarith [ abs_le.mp h.1.1 ] ) ( show 0 ≤ c1 by positivity ), mul_le_mul_of_nonneg_left ( show ( 1 - g1 * a2 ) ^ 2 ≤ 1 by nlinarith [ abs_le.mp h.1.2 ] ) ( show 0 ≤ c2 by positivity ) ] ;
        · constructor <;> norm_num [ ← Matrix.ext_iff, Fin.forall_fin_two, Matrix.mul_apply ];
          · ext i j; fin_cases i <;> fin_cases j <;> norm_num [ Matrix.mul_apply, Matrix.IsHermitian ] ;
          · norm_num [ Matrix.mulVec, Matrix.mul_apply ];
            field_simp;
            exact fun x => add_nonneg ( mul_nonneg ( mul_nonneg ( sq_nonneg _ ) ha.le ) ( by nlinarith only [ abs_le.mp h.2.1.1 ] ) ) ( mul_nonneg ( mul_nonneg ( sq_nonneg _ ) ha2.le ) ( by nlinarith only [ abs_le.mp h.2.1.2 ] ) );
        · constructor <;> norm_num [ ← Matrix.ext_iff, Fin.forall_fin_two, Matrix.mul_apply ];
          · ext i j; fin_cases i <;> fin_cases j <;> norm_num [ Matrix.mul_apply, Matrix.transpose_apply ] ;
          · norm_num [ Matrix.mulVec, Matrix.mul_apply ];
            field_simp;
            exact fun x => add_nonneg ( mul_nonneg ( mul_nonneg ( sq_nonneg _ ) hc.le ) ( by nlinarith only [ abs_le.mp h.2.1.1 ] ) ) ( mul_nonneg ( mul_nonneg ( sq_nonneg _ ) hc2.le ) ( by nlinarith only [ abs_le.mp h.2.1.2 ] ) );
        · constructor <;> rw [ Matrix.PosSemidef ] <;> norm_num [ Fin.forall_fin_two, Matrix.mul_apply ] at *;
          · norm_num [ Matrix.mulVec, Matrix.mul_apply, Matrix.IsHermitian ] at *;
            norm_num [ ← Matrix.ext_iff, Fin.forall_fin_two, Matrix.mul_apply ] at *;
            exact ⟨ ⟨ by ring, by ring ⟩, fun x => by nlinarith [ sq_nonneg ( x 0 ), sq_nonneg ( x 1 ), mul_le_mul_of_nonneg_left ( show ( 1 - g3 * c1 ) * ( 1 - g3 * c1 ) ≤ 1 by nlinarith [ abs_le.mp h.2.2.1 ] ) ha.le, mul_le_mul_of_nonneg_left ( show ( 1 - g3 * c2 ) * ( 1 - g3 * c2 ) ≤ 1 by nlinarith [ abs_le.mp h.2.2.2 ] ) ha2.le ] ⟩;
          · constructor <;> norm_num [ Matrix.mulVec, Matrix.mul_apply ] at *;
            · ext i j ; fin_cases i <;> fin_cases j <;> norm_num [ Matrix.mul_apply, Matrix.transpose_apply ];
            · intro x; ring_nf; norm_num [ abs_le ] at *;
              nlinarith [ show 0 ≤ x 0 ^ 2 * b1 * c1 by positivity, show 0 ≤ x 1 ^ 2 * b2 * c2 by positivity, mul_le_mul_of_nonneg_left h.2.2.1.1 ( show 0 ≤ x 0 ^ 2 * b1 * c1 by positivity ), mul_le_mul_of_nonneg_left h.2.2.2.1 ( show 0 ≤ x 1 ^ 2 * b2 * c2 by positivity ) ]

theorem NF_scalar_iff (g lam_ij : ℝ) (hlam : 0 < lam_ij) :
    (1 - g * lam_ij) ^ 2 * lam_ij ≤ lam_ij ↔
    g * (g * lam_ij - 2) * lam_ij ≤ 0 := by
  constructor <;> intro h <;> nlinarith [sq_nonneg (1 - g * lam_ij),
    mul_pos hlam hlam]

theorem NF_scalar_range (g lam_ij : ℝ) (hlam : 0 < lam_ij) :
    (1 - g * lam_ij) ^ 2 ≤ 1 ↔ 0 ≤ g ∧ g ≤ 2 / lam_ij := by
      -- By taking the square root of both sides of the inequality $(1 - g * lam_ij)^2 \leq 1$, we get $-1 \leq 1 - g * lam_ij \leq 1$.
      have h_sqrt : (1 - g * lam_ij)^2 ≤ 1 ↔ -1 ≤ 1 - g * lam_ij ∧ 1 - g * lam_ij ≤ 1 := by
        -- The square of a real number is less than or equal to 1 if and only if the number itself is between -1 and 1.
        apply Iff.intro (fun h => ⟨by nlinarith, by nlinarith⟩) (fun h => by nlinarith);
      -- By simplifying the inequalities from h_sqrt, we can derive the required bounds for g.
      simp [h_sqrt] at *; exact ⟨fun h => ⟨by nlinarith [mul_div_cancel₀ 2 hlam.ne'], by nlinarith [mul_div_cancel₀ 2 hlam.ne']⟩, fun h => ⟨by nlinarith [mul_div_cancel₀ 2 hlam.ne'], by nlinarith [mul_div_cancel₀ 2 hlam.ne']⟩⟩;