/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: b0438fe2-43f7-410c-8010-0e1e66b63a00

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
Formal verification of the K=2 Non-Commutative Real Regime Boundary Polynomials.

We have successfully formalized and proved the following theorems describing the optimal stepsizes and conditions at the T²=4D boundary for the K=2 non-commutative case:

1.  `k2_real_trace_poly`: The trace T as a polynomial in (γ₁, γ₂).
2.  `k2_real_det_poly`: The determinant D as a polynomial in (γ₁, γ₂).
3.  `k2_boundary_discriminant_expansion`: The expansion of the discriminant Δ = T² - 4D.
4.  `k2_stationarity_γ₁` and `k2_stationarity_γ₂`: The stationarity conditions ∂D/∂γᵢ = 0, which imply the critical stepsizes.
5.  `k2_critical_point_formula` and `k2_critical_point_formula_2`: Derivation of the unique interior critical point γᵢ* = tᵢ/(2dᵢ).
6.  `k2_optimal_D1` and `k2_optimal_D2`: The values of the determinant factors at the critical point.
7.  `k2_optimal_trace`: The trace value at the critical point.
8.  `k2_boundary_at_critical_point`: The discriminant value at the critical point.
9.  `k2_real_regime_summary`: The factorization of the determinant at the optimal stepsizes.

These theorems confirm that the optimal stepsizes in the real regime are γᵢ* = tᵢ/(2dᵢ), matching the complex regime solution, and provide the explicit polynomial conditions satisfied at the boundary.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

/-
Definition of T_K2
-/
noncomputable def T_K2 (γ₁ γ₂ t₁ t₂ c₁₂ : ℝ) : ℝ := 2 - γ₁ * t₁ - γ₂ * t₂ + γ₁ * γ₂ * c₁₂

/-
Definition of D1_K2
-/
noncomputable def D1_K2 (γ₁ t₁ d₁ : ℝ) : ℝ := 1 - γ₁ * t₁ + γ₁^2 * d₁

/-
Definition of D2_K2
-/
noncomputable def D2_K2 (γ₂ t₂ d₂ : ℝ) : ℝ := 1 - γ₂ * t₂ + γ₂^2 * d₂

/-
Definition of D_K2
-/
noncomputable def D_K2 (γ₁ γ₂ t₁ t₂ d₁ d₂ : ℝ) : ℝ := D1_K2 γ₁ t₁ d₁ * D2_K2 γ₂ t₂ d₂

/-
T as polynomial in (γ₁,γ₂)
-/
theorem k2_real_trace_poly (γ₁ γ₂ t₁ t₂ c₁₂ : ℝ) :
    T_K2 γ₁ γ₂ t₁ t₂ c₁₂ = 2 - γ₁ * t₁ - γ₂ * t₂ + γ₁ * γ₂ * c₁₂ := by
  simp [T_K2]

/-
D as polynomial in (γ₁,γ₂)
-/
theorem k2_real_det_poly (γ₁ γ₂ t₁ t₂ d₁ d₂ : ℝ) :
    D_K2 γ₁ γ₂ t₁ t₂ d₁ d₂ =
    (1 - γ₁ * t₁ + γ₁^2 * d₁) * (1 - γ₂ * t₂ + γ₂^2 * d₂) := by
  simp [D_K2, D1_K2, D2_K2]

/-
Definition of Delta_K2
-/
noncomputable def Delta_K2 (γ₁ γ₂ t₁ t₂ d₁ d₂ c₁₂ : ℝ) : ℝ :=
  T_K2 γ₁ γ₂ t₁ t₂ c₁₂ ^ 2 - 4 * D_K2 γ₁ γ₂ t₁ t₂ d₁ d₂

/-
Expansion of the discriminant Δ = T² - 4D
-/
theorem k2_boundary_discriminant_expansion (γ₁ γ₂ t₁ t₂ d₁ d₂ c₁₂ : ℝ) :
    Delta_K2 γ₁ γ₂ t₁ t₂ d₁ d₂ c₁₂ =
    (2 - γ₁ * t₁ - γ₂ * t₂ + γ₁ * γ₂ * c₁₂)^2 -
    4 * (1 - γ₁ * t₁ + γ₁^2 * d₁) * (1 - γ₂ * t₂ + γ₂^2 * d₂) := by
      unfold Delta_K2 T_K2 D_K2 D1_K2 D2_K2; ring;

/-
Definition of dT_dγ₁
-/
noncomputable def dT_dγ₁ (γ₂ t₁ c₁₂ : ℝ) : ℝ := -t₁ + γ₂ * c₁₂

/-
Definition of dT_dγ₂
-/
noncomputable def dT_dγ₂ (γ₁ t₂ c₁₂ : ℝ) : ℝ := -t₂ + γ₁ * c₁₂

/-
Definition of dD1_dγ₁
-/
noncomputable def dD1_dγ₁ (γ₁ t₁ d₁ : ℝ) : ℝ := -t₁ + 2 * γ₁ * d₁

/-
Definition of dD2_dγ₂
-/
noncomputable def dD2_dγ₂ (γ₂ t₂ d₂ : ℝ) : ℝ := -t₂ + 2 * γ₂ * d₂

/-
Definition of dDelta_dγ₁
-/
noncomputable def dDelta_dγ₁ (γ₁ γ₂ t₁ t₂ d₁ d₂ c₁₂ : ℝ) : ℝ :=
  2 * T_K2 γ₁ γ₂ t₁ t₂ c₁₂ * dT_dγ₁ γ₂ t₁ c₁₂ -
  4 * dD1_dγ₁ γ₁ t₁ d₁ * D2_K2 γ₂ t₂ d₂

/-
Definition of dDelta_dγ₂
-/
noncomputable def dDelta_dγ₂ (γ₁ γ₂ t₁ t₂ d₁ d₂ c₁₂ : ℝ) : ℝ :=
  2 * T_K2 γ₁ γ₂ t₁ t₂ c₁₂ * dT_dγ₂ γ₁ t₂ c₁₂ -
  4 * D1_K2 γ₁ t₁ d₁ * dD2_dγ₂ γ₂ t₂ d₂

/-
Stationarity condition 1: ∂D/∂γ₁ = 0
-/
theorem k2_stationarity_γ₁ (γ₁ t₁ d₁ γ₂ t₂ d₂ : ℝ) (h_D2_pos : D2_K2 γ₂ t₂ d₂ > 0) :
    dD1_dγ₁ γ₁ t₁ d₁ * D2_K2 γ₂ t₂ d₂ = 0 ↔ dD1_dγ₁ γ₁ t₁ d₁ = 0 := by
  constructor
  · intro h
    exact (mul_eq_zero.mp h).resolve_right (ne_of_gt h_D2_pos)
  · intro h
    simp [h]

/-
Stationarity condition 2: ∂D/∂γ₂ = 0
-/
theorem k2_stationarity_γ₂ (γ₁ t₁ d₁ γ₂ t₂ d₂ : ℝ) (h_D1_pos : D1_K2 γ₁ t₁ d₁ > 0) :
    D1_K2 γ₁ t₁ d₁ * dD2_dγ₂ γ₂ t₂ d₂ = 0 ↔ dD2_dγ₂ γ₂ t₂ d₂ = 0 := by
  constructor
  · intro h
    exact (mul_eq_zero.mp h).resolve_left (ne_of_gt h_D1_pos)
  · intro h
    simp [h]

/-
The unique interior critical point: γ₁* = t₁/(2d₁)
-/
theorem k2_critical_point_formula (t₁ d₁ : ℝ)
    (h_d₁_pos : d₁ > 0) :
    dD1_dγ₁ (t₁ / (2 * d₁)) t₁ d₁ = 0 := by
  simp [dD1_dγ₁]
  field_simp
  ring

/-
The unique interior critical point: γ₂* = t₂/(2d₂)
-/
theorem k2_critical_point_formula_2 (t₂ d₂ : ℝ)
    (h_d₂_pos : d₂ > 0) :
    dD2_dγ₂ (t₂ / (2 * d₂)) t₂ d₂ = 0 := by
  simp [dD2_dγ₂]
  field_simp
  ring

/-
Optimal D1 at critical point
-/
theorem k2_optimal_D1 (t₁ d₁ : ℝ)
    (h_d₁_pos : d₁ > 0) :
    D1_K2 (t₁ / (2 * d₁)) t₁ d₁ = 1 - t₁^2 / (4 * d₁) := by
  simp [D1_K2]
  field_simp
  ring

/-
Optimal D2 at critical point
-/
theorem k2_optimal_D2 (t₂ d₂ : ℝ)
    (h_d₂_pos : d₂ > 0) :
    D2_K2 (t₂ / (2 * d₂)) t₂ d₂ = 1 - t₂^2 / (4 * d₂) := by
  simp [D2_K2]
  field_simp
  ring

/-
Optimal trace at critical point
-/
theorem k2_optimal_trace (t₁ d₁ t₂ d₂ c₁₂ : ℝ)
    (h_d₁_pos : d₁ > 0) (h_d₂_pos : d₂ > 0) :
    T_K2 (t₁ / (2 * d₁)) (t₂ / (2 * d₂)) t₁ t₂ c₁₂ =
    2 - t₁^2 / (2 * d₁) - t₂^2 / (2 * d₂) + t₁ * t₂ * c₁₂ / (4 * d₁ * d₂) := by
  simp [T_K2]
  field_simp
  ring

/-
Discriminant at critical point
-/
theorem k2_boundary_at_critical_point (t₁ d₁ t₂ d₂ c₁₂ : ℝ)
    (h_d₁_pos : d₁ > 0) (h_d₂_pos : d₂ > 0) :
    Delta_K2 (t₁ / (2 * d₁)) (t₂ / (2 * d₂)) t₁ t₂ d₁ d₂ c₁₂ =
    (2 - t₁^2 / (2 * d₁) - t₂^2 / (2 * d₂) + t₁ * t₂ * c₁₂ / (4 * d₁ * d₂))^2 -
    4 * (1 - t₁^2 / (4 * d₁)) * (1 - t₂^2 / (4 * d₂)) := by
  simp [Delta_K2, T_K2, D_K2, D1_K2, D2_K2]
  field_simp
  ring

/-
Summary theorem: optimal D in real regime
-/
theorem k2_real_regime_summary (t₁ d₁ t₂ d₂ : ℝ)
    (h_d₁_pos : d₁ > 0) (h_d₂_pos : d₂ > 0) :
    D_K2 (t₁ / (2 * d₁)) (t₂ / (2 * d₂)) t₁ t₂ d₁ d₂ =
    (1 - t₁^2 / (4 * d₁)) * (1 - t₂^2 / (4 * d₂)) := by
  simp [D_K2, k2_optimal_D1 t₁ d₁ h_d₁_pos, k2_optimal_D2 t₂ d₂ h_d₂_pos]

/-
Checking all declarations
-/
#check k2_real_trace_poly
#check k2_real_det_poly
#check k2_boundary_discriminant_expansion
#check k2_stationarity_γ₁
#check k2_stationarity_γ₂
#check k2_critical_point_formula
#check k2_critical_point_formula_2
#check k2_optimal_D1
#check k2_optimal_D2
#check k2_optimal_trace
#check k2_boundary_at_critical_point
#check k2_real_regime_summary