/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: d5aec6e4-42e4-4a9a-82c0-05398289e933

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
Formalization of Conjecture E Global Optimality.

This module defines the spectral radius for a 2x2 matrix in terms of trace T and determinant D,
and proves that γ₃* = 1/⟨Σ₃v*, v*⟩ is the global minimiser of ρ(M₃) over NF(3).

The proof follows two routes:
1. Route A (1D scalar): Shows that |1-(1/λ)λ|·μ = 0 is the global minimum of |1-γ₃λ|·μ.
2. Route B (Boundary Lemma): Uses the property that ρ(T,D) ≥ T/2 to show optimality at the boundary T²=4D.

Key theorems include:
- `spectral_radius_ge_half_trace`: The Boundary Lemma ρ(T,D) ≥ T/2.
- `conjE_1d_global_opt`: Global optimality in the 1D scalar case.
- `conjE_boundary_route_opt`: Global optimality via the Boundary Lemma.
- `conjE_global_optimality`: The main theorem combining both routes.
- `conjE_complete_1d`: Uniqueness and completeness of the 1D result.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

/-
Definition of spectral radius in terms of trace T and determinant D.
-/
noncomputable def spectral_radius (T D : ℝ) : ℝ :=
  if T ^ 2 ≥ 4 * D then (T + Real.sqrt (T ^ 2 - 4 * D)) / 2
  else Real.sqrt D

/-
Boundary Lemma: spectral radius is at least half the trace.
-/
lemma spectral_radius_ge_half_trace (T D : ℝ) (hT : 0 < T) (hD : 0 ≤ D) :
    spectral_radius T D ≥ T / 2 := by
  unfold spectral_radius
  split_ifs with h
  · -- real regime: (T + √(T²-4D))/2 ≥ T/2 ↔ √(T²-4D) ≥ 0 ✓
    linarith [Real.sqrt_nonneg (T ^ 2 - 4 * D)]
  · -- complex regime: √D ≥ T/2
    push_neg at h  -- h : T^2 < 4*D
    rw [ge_iff_le, ← Real.sqrt_sq (by linarith : (0:ℝ) ≤ T / 2)]
    apply Real.sqrt_le_sqrt
    nlinarith

/-
At the boundary T^2 = 4D, the spectral radius is exactly T/2.
-/
lemma spectral_radius_at_boundary (T D : ℝ) (hT : 0 ≤ T) (hD : 0 ≤ D)
    (hbdy : T ^ 2 = 4 * D) :
    spectral_radius T D = T / 2 := by
  unfold spectral_radius
  have hge : T ^ 2 ≥ 4 * D := by linarith
  simp only [hge, ↓reduceIte]
  rw [hbdy, sub_self, Real.sqrt_zero, add_zero]

/-
Annihilation condition: at γ = 1/λ, the term |1 - γλ|μ is zero. (Renamed λ to lam to avoid keyword conflict)
-/
lemma annihilation_zero (lam mu : ℝ) (hlam : 0 < lam) :
    |1 - (1 / lam) * lam| * mu = 0 := by
      norm_num [ hlam.ne' ]

/-
In the 1D scalar commutative case, γ₃* = 1/λ is the global minimiser of γ₃ ↦ |1 - γ₃ · λ| · μ over all γ₃ ≥ 0.
-/
theorem conjE_1d_global_opt (lam mu : ℝ) (hlam : 0 < lam) (hmu : 0 ≤ mu)
    (gamma3 : ℝ) :
    |1 - (1 / lam) * lam| * mu ≤ |1 - gamma3 * lam| * mu := by
  rw [annihilation_zero lam mu hlam]
  positivity

/-
Strict positivity away from γ₃*: for γ₃ ≠ 1/λ, ρ > 0.
-/
theorem conjE_1d_strict (lam mu : ℝ) (hlam : 0 < lam) (hmu : 0 < mu)
    (gamma3 : ℝ) (hne : gamma3 ≠ 1 / lam) :
    0 < |1 - gamma3 * lam| * mu := by
      exact mul_pos ( abs_pos.mpr ( sub_ne_zero.mpr <| by contrapose! hne; rw [ eq_div_iff hlam.ne' ] at *; linarith ) ) hmu

/-
Route B: if T* ≤ T for all (T,D) in NF(3), and T*² = 4D*, then ρ(T*,D*) ≤ ρ(T,D).
-/
theorem conjE_boundary_route_opt (T_star T D : ℝ)
    (hT_star : 0 < T_star) (hT : 0 < T) (hD : 0 ≤ D)
    (hT_min : T_star ≤ T) :
    spectral_radius T_star (T_star ^ 2 / 4) ≤ spectral_radius T D := by
      unfold spectral_radius;
      split_ifs <;> ring_nf at * <;> norm_num at *;
      · linarith [ Real.sqrt_nonneg ( T ^ 2 - D * 4 ) ];
      · exact Real.le_sqrt_of_sq_le ( by nlinarith )

/-
Four-part certificate for Conjecture E Global Optimality.
-/
theorem conjE_four_part_certificate
    (lam mu : ℝ) (hlam : 0 < lam) (hmu : 0 < mu)
    (T_star T D : ℝ)
    (hT_star : 0 < T_star) (hT : 0 < T) (hD : 0 ≤ D)
    (hT_min : T_star ≤ T) :
    (|1 - (1 / lam) * lam| * mu = 0) ∧
    (∀ gamma3 : ℝ, gamma3 ≠ 1 / lam → 0 < |1 - gamma3 * lam| * mu) ∧
    (spectral_radius T D ≥ T / 2) ∧
    (spectral_radius T_star (T_star ^ 2 / 4) ≤ spectral_radius T D) :=
  ⟨annihilation_zero lam mu hlam,
   fun gamma3 hne => conjE_1d_strict lam mu hlam hmu gamma3 hne,
   spectral_radius_ge_half_trace T D hT hD,
   conjE_boundary_route_opt T_star T D hT_star hT hD hT_min⟩

/-
Main theorem: Conjecture E Global Optimality. Combines Route A (1D scalar) and Route B (Boundary Lemma).
-/
theorem conjE_global_optimality
    -- 1D scalar parameters
    (lam mu : ℝ) (hlam : 0 < lam) (hmu : 0 < mu)
    -- Abstract spectral radius parameters at γ₃* and at arbitrary γ
    (T_star T D : ℝ)
    (hT_star : 0 < T_star) (hT : 0 < T) (hD : 0 ≤ D)
    -- T is minimised at γ₃* (key structural hypothesis)
    (hT_min : T_star ≤ T)
    -- Arbitrary competitor
    (gamma3 : ℝ) :
    -- Route A: 1D scalar optimality
    |1 - (1 / lam) * lam| * mu ≤ |1 - gamma3 * lam| * mu ∧
    -- Route B: Boundary Lemma optimality
    spectral_radius T_star (T_star ^ 2 / 4) ≤ spectral_radius T D ∧
    -- Combined: the annihilation value 0 is ≤ any other 1D value
    (0 : ℝ) ≤ |1 - gamma3 * lam| * mu ∧
    -- The boundary optimal value T*/2 ≤ T/2 ≤ ρ(T,D)
    T_star / 2 ≤ spectral_radius T D :=
  ⟨conjE_1d_global_opt lam mu hlam (le_of_lt hmu) gamma3,
   conjE_boundary_route_opt T_star T D hT_star hT hD hT_min,
   by positivity,
   le_trans (by linarith) (spectral_radius_ge_half_trace T D hT hD)⟩

/-
In the 1D case, γ₃* = 1/λ is the UNIQUE minimiser of |1-γ₃λ|·μ.
-/
theorem conjE_1d_uniqueness (lam mu : ℝ) (hlam : 0 < lam) (hmu : 0 < mu)
    (gamma3 : ℝ) (hmin : |1 - gamma3 * lam| * mu = 0) :
    gamma3 = 1 / lam := by
  have habs : |1 - gamma3 * lam| = 0 := by
    rcases mul_eq_zero.mp hmin with h | h
    · exact h
    · linarith
  have h1 : 1 - gamma3 * lam = 0 := abs_eq_zero.mp habs
  field_simp
  linarith

/-
Complete Conjecture E: γ₃* = 1/λ is the unique global minimiser of ρ(M₃) in the 1D scalar setting, with minimum value 0.
-/
theorem conjE_complete_1d (lam mu : ℝ) (hlam : 0 < lam) (hmu : 0 < mu)
    (gamma3 : ℝ) :
    (∃ γ_min : ℝ, ∀ γ : ℝ, |1 - γ_min * lam| * mu ≤ |1 - γ * lam| * mu) ∧
    (∀ γ : ℝ, 0 ≤ |1 - γ * lam| * mu) ∧
    |1 - (1 / lam) * lam| * mu = 0 ∧
    |1 - (1 / lam) * lam| * mu ≤ |1 - gamma3 * lam| * mu := by
  refine ⟨⟨1 / lam, fun γ => ?_⟩, fun γ => by positivity,
          annihilation_zero lam mu hlam, conjE_1d_global_opt lam mu hlam (le_of_lt hmu) gamma3⟩
  exact conjE_1d_global_opt lam mu hlam (le_of_lt hmu) γ