/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: e15ee141-251a-42aa-b8c0-03d000d58c09

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
K=2 Non-Commutative Spectral Radius: Complete Formula at d=2.

We prove that for the K=2 cycle operator M₂ = (I - γ₂ S₂)(I - γ₁ S₁) with 2x2 matrices,
the spectral radius depends on exactly five invariants:
t₁ = tr(S₁), t₂ = tr(S₂), d₁ = det(S₁), d₂ = det(S₂), and c₁₂ = tr(S₁ S₂).

Key theorems:
- k2_det_formula: det(M₂) factors into quadratic polynomials in γ₁, γ₂.
- k2_trace_formula: tr(M₂) depends on the non-commutative coupling only via c₁₂.
- k2_invariant_reduction: The spectral radius is determined by (t₁, t₂, d₁, d₂, c₁₂).
- k2_complex_regime_rho: In the complex regime, ρ(M₂) = √det(M₂).

-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

def cycle_op_k2 (S : Fin 2 → Matrix (Fin 2) (Fin 2) ℝ) (γ : Fin 2 → ℝ) :
    Matrix (Fin 2) (Fin 2) ℝ :=
  (1 - γ 1 • S 1) * (1 - γ 0 • S 0)

lemma k2_single_factor_det (S : Matrix (Fin 2) (Fin 2) ℝ) (γ : ℝ) :
    (1 - γ • S).det = 1 - γ * S.trace + γ ^ 2 * S.det := by
  simp [Matrix.det_fin_two, Matrix.trace_fin_two,
        Matrix.sub_apply, Matrix.smul_apply, Matrix.one_apply,
        Fin.sum_univ_two]
  ring

lemma k2_det_factorisation
    (S : Fin 2 → Matrix (Fin 2) (Fin 2) ℝ) (γ : Fin 2 → ℝ) :
    (cycle_op_k2 S γ).det =
    (1 - γ 1 • S 1).det * (1 - γ 0 • S 0).det := by
  unfold cycle_op_k2
  exact Matrix.det_mul _ _

theorem k2_det_formula
    (S : Fin 2 → Matrix (Fin 2) (Fin 2) ℝ) (γ : Fin 2 → ℝ) :
    (cycle_op_k2 S γ).det =
    (1 - γ 0 * (S 0).trace + (γ 0) ^ 2 * (S 0).det) *
    (1 - γ 1 * (S 1).trace + (γ 1) ^ 2 * (S 1).det) := by
  rw [k2_det_factorisation, k2_single_factor_det, k2_single_factor_det]
  ring

lemma k2_trace_cyclic (S₁ S₂ : Matrix (Fin 2) (Fin 2) ℝ) :
    (S₁ * S₂).trace = (S₂ * S₁).trace := by
      -- The trace of a product of matrices is invariant under cyclic permutations.
      apply Matrix.trace_mul_comm

theorem k2_trace_formula
    (S : Fin 2 → Matrix (Fin 2) (Fin 2) ℝ) (γ : Fin 2 → ℝ) :
    (cycle_op_k2 S γ).trace =
    2 - γ 0 * (S 0).trace - γ 1 * (S 1).trace +
    γ 0 * γ 1 * (S 1 * S 0).trace := by
  unfold cycle_op_k2
  simp [Matrix.trace_fin_two, Matrix.mul_apply, Fin.sum_univ_two,
        Matrix.sub_apply, Matrix.smul_apply, Matrix.one_apply,
        Matrix.add_apply, Matrix.mul_apply]
  ring

theorem k2_invariant_reduction
    (S : Fin 2 → Matrix (Fin 2) (Fin 2) ℝ) (γ : Fin 2 → ℝ)
    (t₁ t₂ d₁ d₂ c₁₂ : ℝ)
    (ht₁ : (S 0).trace = t₁) (ht₂ : (S 1).trace = t₂)
    (hd₁ : (S 0).det = d₁) (hd₂ : (S 1).det = d₂)
    (hc  : (S 1 * S 0).trace = c₁₂) :
    (cycle_op_k2 S γ).trace = 2 - γ 0 * t₁ - γ 1 * t₂ + γ 0 * γ 1 * c₁₂  ∧
    (cycle_op_k2 S γ).det =
      (1 - γ 0 * t₁ + (γ 0)^2 * d₁) * (1 - γ 1 * t₂ + (γ 1)^2 * d₂) := by
  constructor
  · rw [k2_trace_formula, ht₁, ht₂, hc]
  · rw [k2_det_formula, ht₁, ht₂, hd₁, hd₂]

def k2_eigenvalues_complex (M : Matrix (Fin 2) (Fin 2) ℝ)
    (hdisc : M.trace ^ 2 < 4 * M.det) (i : Fin 2) : ℝ :=
  Real.sqrt M.det

theorem k2_complex_regime_rho
    (S : Fin 2 → Matrix (Fin 2) (Fin 2) ℝ) (γ : Fin 2 → ℝ)
    (hdisc : (cycle_op_k2 S γ).trace ^ 2 < 4 * (cycle_op_k2 S γ).det) :
    Real.sqrt (cycle_op_k2 S γ).det =
    Real.sqrt ((1 - γ 0 * (S 0).trace + (γ 0)^2 * (S 0).det) *
               (1 - γ 1 * (S 1).trace + (γ 1)^2 * (S 1).det)) := by
  congr 1
  exact k2_det_formula S γ

lemma k2_det_pos
    (S : Fin 2 → Matrix (Fin 2) (Fin 2) ℝ) (γ : Fin 2 → ℝ)
    (h₀ : 0 < 1 - γ 0 * (S 0).trace + (γ 0)^2 * (S 0).det)
    (h₁ : 0 < 1 - γ 1 * (S 1).trace + (γ 1)^2 * (S 1).det) :
    0 < (cycle_op_k2 S γ).det := by
  rw [k2_det_formula]
  exact mul_pos h₀ h₁

lemma k2_single_factor_min
    (t d γ : ℝ) (ht : 0 < t) (hd : 0 < d) (htd : t^2 > 4*d)
    (hγ : γ = t / (2 * d)) :
    1 - γ * t + γ^2 * d = 1 - t^2 / (4 * d) := by
  rw [hγ]; field_simp; ring

theorem k2_commutative_same_formula
    (S : Fin 2 → Matrix (Fin 2) (Fin 2) ℝ) (γ : Fin 2 → ℝ)
    (hcomm : S 0 * S 1 = S 1 * S 0) :
    (cycle_op_k2 S γ).trace =
    2 - γ 0 * (S 0).trace - γ 1 * (S 1).trace +
    γ 0 * γ 1 * (S 0 * S 1).trace ∧
    (cycle_op_k2 S γ).det =
    (1 - γ 0 * (S 0).trace + (γ 0)^2 * (S 0).det) *
    (1 - γ 1 * (S 1).trace + (γ 1)^2 * (S 1).det) := by
  constructor
  · rw [k2_trace_formula]
    congr 1
    rw [k2_trace_cyclic, hcomm]
  · exact k2_det_formula S γ

theorem k2_disc_formula
    (S : Fin 2 → Matrix (Fin 2) (Fin 2) ℝ) (γ : Fin 2 → ℝ) :
    (cycle_op_k2 S γ).trace ^ 2 - 4 * (cycle_op_k2 S γ).det =
    (S 1 * S 0).trace ^ 2 * (γ 0) ^ 2 * (γ 1) ^ 2
    - 2 * (S 1 * S 0).trace * (γ 0) ^ 2 * (γ 1) * (S 0).trace
    - 2 * (S 1 * S 0).trace * (γ 0) * (γ 1) ^ 2 * (S 1).trace
    + 4 * (S 1 * S 0).trace * (γ 0) * (γ 1)
    - 4 * (S 0).det * (S 1).det * (γ 0) ^ 2 * (γ 1) ^ 2
    + 4 * (S 0).det * (γ 0) ^ 2 * (γ 1) * (S 1).trace - 4 * (S 0).det * (γ 0) ^ 2
    + 4 * (S 1).det * (γ 0) * (γ 1) ^ 2 * (S 0).trace - 4 * (S 1).det * (γ 1) ^ 2
    + (γ 0) ^ 2 * (S 0).trace ^ 2 - 2 * (γ 0) * (γ 1) * (S 0).trace * (S 1).trace
    + (γ 1) ^ 2 * (S 1).trace ^ 2 := by
  rw [k2_trace_formula, k2_det_formula]
  ring