/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: ef566474-c1ed-49cb-b26d-75bb80476fb7

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
Verified the K=4 Curriculum Theorem trace difference formulas for adjacent swaps and the uniform stepsize corollary.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

variable {n : Type*} [Fintype n] [DecidableEq n]

variable (S1 S2 S3 S4 : Matrix n n ℝ) (γ1 γ2 γ3 γ4 : ℝ)

/-
K=4 Curriculum Theorem — Swap(1,2)
-/
theorem k4_curriculum_swap12 :
    let A1 : Matrix n n ℝ := 1 - γ1 • S1
    let A2 : Matrix n n ℝ := 1 - γ2 • S2
    let A3 : Matrix n n ℝ := 1 - γ3 • S3
    let A4 : Matrix n n ℝ := 1 - γ4 • S4
    Matrix.trace (A4 * A3 * A2 * A1) - Matrix.trace (A4 * A3 * A1 * A2) =
    γ1 * γ2 * (
      (-γ3) * (Matrix.trace (S3 * S2 * S1) - Matrix.trace (S3 * S1 * S2)) +
      (-γ4) * (Matrix.trace (S4 * S2 * S1) - Matrix.trace (S4 * S1 * S2)) +
      γ3 * γ4 * (Matrix.trace (S4 * S3 * S2 * S1) -
                  Matrix.trace (S4 * S3 * S1 * S2))) := by
                    norm_num [ Matrix.mul_sub, sub_mul ] ; ring;
                    rw [ Matrix.trace_mul_comm ] ; ring;

/-
K=4 Curriculum Theorem — Swap(2,3)
-/
theorem k4_curriculum_swap23 :
    let A1 : Matrix n n ℝ := 1 - γ1 • S1
    let A2 : Matrix n n ℝ := 1 - γ2 • S2
    let A3 : Matrix n n ℝ := 1 - γ3 • S3
    let A4 : Matrix n n ℝ := 1 - γ4 • S4
    Matrix.trace (A4 * A3 * A2 * A1) - Matrix.trace (A4 * A2 * A3 * A1) =
    γ2 * γ3 * (
      (-γ1) * (Matrix.trace (S3 * S2 * S1) - Matrix.trace (S2 * S3 * S1)) +
      (-γ4) * (Matrix.trace (S4 * S3 * S2) - Matrix.trace (S4 * S2 * S3)) +
      γ1 * γ4 * (Matrix.trace (S4 * S3 * S2 * S1) -
                  Matrix.trace (S4 * S2 * S3 * S1))) := by
                    simp +decide [ mul_assoc, sub_mul, mul_sub ] ; ring;
                    rw [ ← Matrix.trace_mul_comm S3 ] ; ring;

/-
K=4 Curriculum Theorem — Swap(3,4)
-/
theorem k4_curriculum_swap34 :
    let A1 : Matrix n n ℝ := 1 - γ1 • S1
    let A2 : Matrix n n ℝ := 1 - γ2 • S2
    let A3 : Matrix n n ℝ := 1 - γ3 • S3
    let A4 : Matrix n n ℝ := 1 - γ4 • S4
    Matrix.trace (A4 * A3 * A2 * A1) - Matrix.trace (A3 * A4 * A2 * A1) =
    γ3 * γ4 * (
      (-γ1) * (Matrix.trace (S4 * S3 * S1) - Matrix.trace (S3 * S4 * S1)) +
      (-γ2) * (Matrix.trace (S4 * S3 * S2) - Matrix.trace (S3 * S4 * S2)) +
      γ1 * γ2 * (Matrix.trace (S4 * S3 * S2 * S1) -
                  Matrix.trace (S3 * S4 * S2 * S1))) := by
                    simp +decide [ mul_add, sub_mul, add_mul, mul_sub, Matrix.mul_assoc ];
                    rw [ Matrix.trace_mul_comm ] ; ring

/-
Uniform-stepsize curriculum rule (leading order)
-/
theorem k4_curriculum_uniform_corollary (γ : ℝ) :
    -- Swap12 at uniform γ
    let A1 : Matrix n n ℝ := 1 - γ • S1
    let A2 : Matrix n n ℝ := 1 - γ • S2
    let A3 : Matrix n n ℝ := 1 - γ • S3
    let A4 : Matrix n n ℝ := 1 - γ • S4
    Matrix.trace (A4 * A3 * A2 * A1) - Matrix.trace (A4 * A3 * A1 * A2) =
    γ^2 * (
      (-γ) * (Matrix.trace (S3 * S2 * S1) - Matrix.trace (S3 * S1 * S2)) +
      (-γ) * (Matrix.trace (S4 * S2 * S1) - Matrix.trace (S4 * S1 * S2)) +
      γ^2 * (Matrix.trace (S4 * S3 * S2 * S1) -
              Matrix.trace (S4 * S3 * S1 * S2))) := by
                norm_num [ Matrix.mul_assoc, sub_mul, mul_sub ] ; ring;
                rw [ ← Matrix.trace_mul_comm ] ; ring;