/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: f04a3e22-1ef0-470c-b533-dd1f36893059

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
This module proves the Commutator Sandwich Formula for Continual Learning Cycle Operators for K=4 and K=3.
It defines the update operators A_i = I - γ_i Σ_i and proves the trace difference formulas for adjacent swaps.
Note: The signs in the user's original statements were incorrect (off by a factor of -1).
The proved theorems use the correct commutator direction (e.g., S2*S1 - S1*S2 instead of S1*S2 - S2*S1 for the A2 A1 - A1 A2 difference).
The theorems are:
1. commutator_sandwich_K4_adj12
2. commutator_sandwich_K4_adj23
3. commutator_sandwich_K4_adj34
4. commutator_sandwich_K3_corollary
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

open Matrix
variable {n : Type*} [Fintype n] [DecidableEq n]
variable {R : Type*} [CommRing R]

#check (1 : Matrix n n R)
#check (trace : Matrix n n R → R)
#synth Mul (Matrix n n R)
#synth HMul (Matrix n n R) (Matrix n n R) (Matrix n n R)
#synth SMul R (Matrix n n R)

/-
Helper: trace is linear (used as sub → sub of traces)
-/
lemma trace_sub_eq {n : Type*} [Fintype n] [DecidableEq n] {R : Type*} [CommRing R] {M₁ M₂ : Matrix n n R} :
    trace M₁ - trace M₂ = trace (M₁ - M₂) := by
  simp [map_sub]

#synth IsScalarTower R (Matrix n n R) (Matrix n n R)
#synth SMulCommClass R (Matrix n n R) (Matrix n n R)

/-
Helper: the commutator of two update operators is a scalar multiple of the matrix commutator of the covariances.
-/
lemma update_commutator (gi gj : R) (Si Sj : Matrix n n R) :
    ((1 : Matrix n n R) - gi • Si) * (1 - gj • Sj) -
    (1 - gj • Sj) * (1 - gi • Si) =
    (gi * gj) • (Si * Sj - Sj * Si) := by
      ext i j; simp +decide [ mul_sub, sub_mul, Matrix.mul_apply, smul_neg, smul_assoc ] ; ring;

/-
THEOREM 1: Commutator Sandwich K=4, adjacent swap (1,2) (Corrected Sign)
-/
theorem commutator_sandwich_K4_adj12
    (g1 g2 g3 g4 : R) (S1 S2 S3 S4 : Matrix n n R) :
    let A1 := (1 : Matrix n n R) - g1 • S1
    let A2 := (1 : Matrix n n R) - g2 • S2
    let A3 := (1 : Matrix n n R) - g3 • S3
    let A4 := (1 : Matrix n n R) - g4 • S4
    trace (A4 * A3 * A2 * A1) - trace (A4 * A3 * A1 * A2) =
    g1 * g2 * trace (A4 * A3 * (S2 * S1 - S1 * S2)) := by
      simp +decide [ Matrix.trace_mul_comm ( 1 - g4 • S4 - g3 • ( ( 1 - g4 • S4 ) * S3 ) ), mul_assoc, mul_sub, sub_mul ] ; ring

/-
THEOREM 2: Commutator Sandwich K=4, adjacent swap (2,3) (Corrected Sign)
-/
theorem commutator_sandwich_K4_adj23
    (g1 g2 g3 g4 : R) (S1 S2 S3 S4 : Matrix n n R) :
    let A1 := (1 : Matrix n n R) - g1 • S1
    let A2 := (1 : Matrix n n R) - g2 • S2
    let A3 := (1 : Matrix n n R) - g3 • S3
    let A4 := (1 : Matrix n n R) - g4 • S4
    trace (A4 * A3 * A2 * A1) - trace (A4 * A2 * A3 * A1) =
    g2 * g3 * trace (A4 * (S3 * S2 - S2 * S3) * A1) := by
      simp +decide [ mul_sub, sub_mul, mul_assoc ];
      grind +ring

/-
THEOREM 3: Commutator Sandwich K=4, adjacent swap (3,4) (Corrected Sign)
-/
theorem commutator_sandwich_K4_adj34
    (g1 g2 g3 g4 : R) (S1 S2 S3 S4 : Matrix n n R) :
    let A1 := (1 : Matrix n n R) - g1 • S1
    let A2 := (1 : Matrix n n R) - g2 • S2
    let A3 := (1 : Matrix n n R) - g3 • S3
    let A4 := (1 : Matrix n n R) - g4 • S4
    trace (A4 * A3 * A2 * A1) - trace (A3 * A4 * A2 * A1) =
    g3 * g4 * trace ((S4 * S3 - S3 * S4) * (A2 * A1)) := by
      simp +decide [ sub_mul, mul_sub, mul_assoc ];
      ring

/-
THEOREM 4: K=3 Curriculum Theorem as corollary (Corrected Sign)
-/
theorem commutator_sandwich_K3_corollary
    (g1 g2 g3 : R) (S1 S2 S3 : Matrix n n R) :
    let A1 := (1 : Matrix n n R) - g1 • S1
    let A2 := (1 : Matrix n n R) - g2 • S2
    let A3 := (1 : Matrix n n R) - g3 • S3
    trace (A3 * A2 * A1) - trace (A3 * A1 * A2) =
    g1 * g2 * trace (A3 * (S2 * S1 - S1 * S2)) := by
      simp +decide [ mul_sub, sub_mul ] ; ring;
      rw [ ← Matrix.mul_assoc, ← Matrix.mul_assoc ]